create view [covid].[COVID_CONTACT_VIEW]
as
SELECT * FROM AtlasPublic.VIEW_UODS_VIEWSYSTEMCONTACTDATA WHERE DIID IN (SELECT PR_ROWID FROM AtlasPublic.VIEW_UODS_PERSONALRECORD WHERE PR_DISEASECODE_DR = 543030)