






CREATE view [covid].[SARS2_PERSON_VIEW_ADDL1]
as


SELECT
    PER.DVPER_ROWID AS PER_ROWID,
    ENTADDRCOUNTRY.PARTCOUNTRY AS PER_COUNTRYOFBIRTHDR,
--    [dbo].[MDF_ATTR_GETDATETIMEVALUE_ENTATTR_BYENTITYID](PER.DVPER_ROWID,'VALUETS', 'PER_DATEOFUSARRIVAL') AS PER_DATEOFARRIVAL,
--    [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](PER.DVPER_ROWID,'VALUESTRING_TXT','PER_OCCUPATIONLOCATION') AS PER_OCCUPATIONLOCATION,
--    [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](PER.DVPER_ROWID,'VALUECODE_ORTX','PER_OCCUPATIONDR') AS PER_OCCUPATIONSPECIFY,
--    ATTOCCSETTING.VALUECODE_ID AS PER_OCCUPATIONSETTINGTYPEDR,
--    ATTOCCSETTING.VALUECODE_ORTX AS PER_OCCUPATIONSETTINGTYPESPECIFY,
    ENTNAME.PARTMID AS PER_MIDDLENAME,
--    [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](PER.DVPER_RootID,'VALUESTRING_TXT','PER_StateNumber') AS PER_STATENUMBER,
--    [dbo].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](PER.DVPER_ROWID,'VALUECODE_ID','PER_RESIDENCECOUNTYDR') AS PER_COUNTYOFRESIDENCE,
    ENTADDR.PARTCEN AS PER_CENSUSTRACT,
    ENTADDR.PARTGEOLAT AS PER_LATITUDE,
    ENTADDR.PARTGEOLONG AS PER_LONGITUDE,
    ENTADDR.USECODE_ORTX AS PER_ADDRESSSTANDARDIZED,
    ENTADDR.PARTCOUNTYFIPS AS PER_COUNTYFIPS,
    ENTADDR.PARTCOUNTY AS PER_COUNTY,
    ENTADDR.PARTCENBLOCK AS PER_CENSUSBLOCK,
    ENTADDR.PARTZIPPLUS4 AS PER_ZIPPLUS4,
    ENTADDR.PARTCOUNTRY AS PER_COUNTRY,
    UCSCOUNTRY.FULLNAME as PER_COUNTRY_NAME,
--    [dbo].[MDF_UCS_FULLNAME_UCS_BYUCSID](PER.DVPER_SEXCODE_ID) AS PER_SEX,
--    [dbo].[MDF_UCS_FULLNAME_UCS_BYUCSID](PER.DVPER_RACECODE_ID) AS PER_RACE,
--    [dbo].[MDF_UCS_FULLNAME_UCS_BYUCSID](PER.DVPER_ETHNICITYCODE_ID) AS PER_ETHNICITY,
--    [dbo].[MDF_UCS_FULLNAME_UCS_BYUCSID](PER.DVPER_OCCUPATIONCODE_ID) AS PER_OCCUPATION,
    ENTNAME.PARTSFX AS PER_NAMESUFFIX,
--    [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](ENTPER.ID,'VALUESTRING','PER_WorkSchoolContact') AS PER_WORKSCHOOLCONTACT,
    TLANG.LANGUAGECODE_ID AS PER_PRIMARYLANGUAGE_DR,
    [dbo].[MDF_UCS_FULLNAME_UCS_BYUCSID](TLANG.LANGUAGECODE_ID) AS PER_PRIMARYLANGUAGE,
    [LAC].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID]((CASE WHEN  S_Link.ID IS NOT NULL THEN S_Link.Entity2_ID ELSE PER.DVPER_RowID END),'VALUESTRING','PSNID_EMAILID') AS PER_EMAIL,
    [LAC].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID]((CASE WHEN  S_Link.ID IS NOT NULL THEN S_Link.Entity2_ID ELSE PER.DVPER_RowID END),'VALUESTRING','PSNID_ELECTRONICCONTACT') AS PER_ELECTRONICCONTACT
FROM DBO.DV_PERSON(NOLOCK) AS PER
    INNER JOIN DBO.E_ENTITY ENTPER (NOLOCK) ON PER.DVPER_ROWID = ENTPER.[ID]
    LEFT OUTER JOIN R_ROLE(NOLOCK) R_LOCE ON R_LOCE.player_id=ENTPER.[ID] AND R_LOCE.classCode='LOCE' AND R_LOCE.metaCode='PER_WorkSchoolLocationDR'
    LEFT OUTER JOIN T_ENTITYNAME(NOLOCK) SCHOOL_LOC_NAME ON R_LOCE.Scoper_ID=SCHOOL_LOC_NAME.Entity_ID AND SCHOOL_LOC_NAME.metaCode='LOC_Name' AND SCHOOL_LOC_NAME.useCode='SRCH'
    LEFT JOIN DBO.V_UNIFIEDCODESET UCSNAME (NOLOCK) ON  PER.DVPER_NAMESPACECODE_ID = UCSNAME.ID
    LEFT JOIN DBO.V_UNIFIEDCODESET UCSOP (NOLOCK) ON  PER.DVPER_IMPORTOPTIONSCODE_ID = UCSOP.ID
    LEFT OUTER JOIN dbo.S_Link (NOLOCK) ON S_Link.Name = 'Person-Primary'
        AND S_Link.Entity1_ID = PER.DVPER_ROWID
    LEFT OUTER JOIN dbo.T_EntityAddress ENTADDR (NOLOCK)  ON ENTADDR.Entity_ID=PER.DVPER_ROWID AND ENTADDR.useCode='H'
        AND ENTADDR.ID = (CASE WHEN S_Link.ID IS NOT NULL THEN S_Link.tAddress1_ID ELSE ENTADDR.ID END)
    LEFT OUTER JOIN DBO.T_ENTITYNAME ENTNAME (NOLOCK) ON  ENTNAME.ENTITY_ID = (CASE WHEN  S_Link.ID IS NOT NULL THEN S_Link.Entity2_ID ELSE PER.DVPER_RowID END)
    LEFT JOIN V_UNIFIEDCODESET UCSCOUNTRY (NOLOCK) on ENTADDR.partCountry = UCSCOUNTRY.ID
    LEFT OUTER JOIN DBO.T_ENTITYADDRESS ENTADDRCOUNTRY (NOLOCK) ON  ENTADDRCOUNTRY.ENTITY_ID = PER.DVPER_ROWID AND ENTADDRCOUNTRY.USECODE = 'BIR'
--    LEFT OUTER JOIN DBO.T_ATTRIBUTE ATTOCCSETTING (NOLOCK) ON  ATTOCCSETTING.ENTITY_ID = PER.DVPER_ROWID AND ATTOCCSETTING.NAME = 'PER_OCCUPATIONSETTINGTYPEDR' AND ATTOCCSETTING.TYPE = 'CV'
    LEFT OUTER JOIN DBO.T_LANGUAGECOMMUNICATION TLANG (NOLOCK) ON  PER.DVPER_ROWID = TLANG.ENTITY_ID AND TLANG.METACODE = 'PER_PRIMARYLANGUAGE_FK'
    WHERE ((ISNULL(UCSNAME.CONCEPTCODE,'') = ''
        OR (
            ISNULL(UCSNAME.CONCEPTCODE,'') <> ''
            AND (UCSNAME.CONCEPTCODE <> 'WEB')
            AND ISNULL(UCSOP.CONCEPTCODE,'') <> ''
            AND (UCSOP.CONCEPTCODE NOT IN ('ALR', 'UDL'))
        ))
        AND PER.DVPER_RowID IN (SELECT PR.DVPR_PERSONDR
    FROM [dbo].DV_PHPERSONALRECORD PR (NOLOCK)
    INNER JOIN dbo.DV_Person PER (NOLOCK) ON PER.DVPER_RowID=PR.DVPR_PersonDR
    WHERE PR.DVPR_DiseaseCode_ID = 544041))

