create table dbo.All_Contact
(
	Disease int not null,
	DIID int not null,
	CONTACTID int not null,
	INSTANCEID int null,
	RECORDTYPE varchar(2) null,
	RLENT_FIRSTNAME varchar(100) null,
	RLENT_LASTNAME varchar(100) null,
	RLENT_MIDDLEINITIAL varchar(100) null,
	RLENT_NAMESUFFIX varchar(50) null,
	RLENT_AGE int null,
	RLENT_DOB datetime null,
	RLENT_SEX varchar(255) null,
	RLENT_CONTACTTYPE varchar(255) null,
	RLENT_DATESOFCONTACT datetime null,
	RLENT_STREETADDRESS varchar(100) null,
	RLENT_APARTMENT varchar(100) null,
	RLENT_CITY varchar(100) null,
	RLENT_ZIP varchar(100) null,
	RLENT_PHONE varchar(100) null,
	RLENT_DISTRICT varchar(255) null,
	RLENT_PROPHYLAXISMEDICATION varchar(max) null,
	RLENT_INVESTIGATORDR varchar(202) null,
	RLENT_EXPEVENTDR int null,
	RLENT_EXPEVENT varchar(250) null,
	RLENT_PRIORITYDR varchar(255) null,
	RLENT_CLUSTERID varchar(max) null,
	RLENT_STATUSDR varchar(255) null,
	FOLDERID int null,
	RLENT_ELECTRONICCONTACT varchar(max) null,
	RLENT_EMAIL varchar(max) null,
	RLENT_STATE varchar(100) null,
	RLENT_RACE varchar(255) null,
	RLENT_PERSONALRECORDDR int null,
	RLENT_PERSONALRECORDID varchar(50) null,
	RLENT_PERSONALRECORDTYPE varchar(100) null,
	RLENT_CONTACTINVESTIGATIONLINKEDINCIDENTDR int null,
	RLENT_CONTACTINVESTIGATIONLINKEDINCIDENTID varchar(50) null
)
go
create clustered index [All_Contact.Fake.PrimaryKey] on dbo.All_Contact( DIID, CONTACTID, Disease )
