CREATE TABLE [internals].[allincidentpersonalrecord](
	[PR_INCIDENTID] [int] NOT NULL,
	[PR_CMRID] [varchar](50) NOT NULL,
	[PR_MRN] [varchar](50) NULL,
	[PR_CREATEDATE] [datetime] NOT NULL,
	[PR_ONSETDATE] [datetime] NULL,
	[PR_EPISODEDATE] [datetime] NULL,
	[PR_CLOSEDDATE] [datetime] NULL,
	[PR_DATEREPORTEDBY] [datetime] NULL,
	[PR_STANDARDAGE] [real] NULL,
	[PR_DATESUBMITTED] [datetime] NULL,
	[PR_ISINDEXCASE] [bit] NULL,
	[PR_CLUSTERID] [varchar](8000) NULL,
	[PR_DATEOFDIAGNOSIS] [datetime] NULL,
	[PR_DISEASECODE_DR] [int] NULL,
	[PR_DISTRICTCODE_DR] [int] NULL,
	[PR_PROCESSSTATUSCODE_DR] [int] NULL,
	[PR_RESOLUTIONSTATUSCODE_DR] [int] NULL,
	[Secondary_District] [varchar](255) NULL,
	[PR_NURSEINVESTIGATORDR] [int] NULL,
	[PR_PERSONDR] [int] NULL,
	[PR_REPORTSOURCEDR] [int] NULL,
	[PR_ROWID] [int] NOT NULL,
	[PR_USERDR] [int] NULL,
	[PR_TYPEDR] [int] NULL,
	[PR_OUTBREAKDRSTEXT] [varchar](max) NULL, 
	[PR_OUTBREAKNUMBERS] [varchar](max) NULL,
	[PR_OUTBREAKTYPES] [varchar](max) NULL,
	[PR_RECEIVEDDATE] [datetime] NULL,
	[PR_IMPORTEDSTATUS] [int] NULL,
	[Final_Disposition] [varchar](255) NULL,
	[PR_LIPRESULTVALUE] [varchar](8000) NULL,                     
	[Lab_Report_Test_Name] [varchar](255) NULL,
	[PR_PROVIDERNAME] [varchar](255) NULL,
	[PR_REPORTEDBYLAB] [bit] NULL,
	[PR_LIPRESULTNOTES] [varchar](8000) NULL,
	[PR_HEALTHCAREPROVIDERLOCATIONDR] [int] NULL,
	[PR_DATESENT] [datetime] NULL,
	[PR_LASTCDCUPDATE] [datetime] NULL,
	[PR_LIPRESULTNAME] [varchar](255) NULL,
	[PR_DATELASTEDITED] [datetime] NULL,
	[PR_DISEASE] [varchar](255) NULL,
	[PR_DISEASESHORTNAME] [varchar](100) NULL,
	[PR_DISTRICT] [varchar](255) NULL,
	[PR_PROCESSSTATUS] [varchar](255) NULL,
	[PR_RESOLUTIONSTATUS] [varchar](255) NULL,
	[PR_PHTYPE] [varchar](255) NULL,
	[PR_SPA] [varchar](255) NULL,
	[PR_SPACODE_DR] [int] NULL,
	[Health_District_Number] [varchar](255) NULL,
	[PR_SPECIMENTYPE] [nvarchar](max) NULL,
	[PR_SPECIMENDATECOLLECTED] [nvarchar](max) NULL,
	[PR_SPECIMENDATERECEIVED] [nvarchar](max) NULL,
	[PR_SPECIMENRESULT] [nvarchar](max) NULL,
	[PR_SPECIMENNOTE] [nvarchar](max) NULL,
	[PR_LABORATORY] [varchar](250) NULL,
	[PR_NURSEINVESTIGATOR] [varchar](202) NOT NULL,
	[Additional_Provider] [varchar](250) NULL,
	[Additional_Laboratory] [varchar](250) NULL,
	[Created_By] [varchar](14) NOT NULL,
	[ImportedBy] [varchar](202) NULL,
	[Priority] [varchar](255) NULL,
	[Report_Source] [varchar](250) NULL,
	[Suspected_Exposure_Types] [nvarchar](max) NULL,
	[Type_of_Contact] [varchar](255) NULL
)

go
create clustered index [allincidentpersonalrecord.PR_ROWID.FakePrimaryKey] 
on internals.allincidentpersonalrecord( PR_ROWID )
