CREATE TABLE [dbo].[Ax_FBIFood] (
    [FBIF_RowID]  INT NOT NULL,
    [FBIF_FoodDR] INT NULL,
    CONSTRAINT [PK_Ax_FBIFood] PRIMARY KEY CLUSTERED ([FBIF_RowID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_Ax_FBIFood_A_Act] FOREIGN KEY ([FBIF_RowID]) REFERENCES [dbo].[A_Act] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Ax_FBIFood_V_UnifiedCodeSet] FOREIGN KEY ([FBIF_FoodDR]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[Ax_FBIFood] NOCHECK CONSTRAINT [FK_Ax_FBIFood_A_Act];


GO
ALTER TABLE [dbo].[Ax_FBIFood] NOCHECK CONSTRAINT [FK_Ax_FBIFood_V_UnifiedCodeSet];

