CREATE TABLE [dbo].[Ax_UDFValues] (
    [ServerId]         INT           NULL,
    [ID]               INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Act_Parent_ID]    INT           NULL,
    [METACODE_UCSID]   INT           NULL,
    [CREATEDATETIME]   DATETIME      NULL,
    [LASTEDITDATETIME] DATETIME      NULL,
    [VALUESTRING]      VARCHAR (MAX) NULL,
    [VALUEDATETIME]    DATETIME      NULL,
    [VALUE_ENTITYID]   INT           NULL,
    [VALUE_UCSID]      INT           NULL,
    [FRM_DefinitionID] INT           NULL,
    [SEC_DefinitionID] INT           NULL,
    [UDF_InstanceID]   INT           NULL,
    CONSTRAINT [S_UDFValues_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [A_Act_S_UDFValues_FK2] FOREIGN KEY ([Act_Parent_ID]) REFERENCES [dbo].[A_Act] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_Code_ID_V_UNIFIEDCODESET] FOREIGN KEY ([METACODE_UCSID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_FRM_Definition_ID_V_UNIFIEDCODESET] FOREIGN KEY ([FRM_DefinitionID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_SEC_Definition_ID_V_UNIFIEDCODESET] FOREIGN KEY ([SEC_DefinitionID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_UDF_Instance_ID_A_ACT] FOREIGN KEY ([UDF_InstanceID]) REFERENCES [dbo].[A_Act] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_valueCode_ID_V_UNIFIEDCODESET] FOREIGN KEY ([VALUE_UCSID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_A_Ax_UDFValues_valueEntity_ID_E_ENTITY] FOREIGN KEY ([VALUE_ENTITYID]) REFERENCES [dbo].[E_Entity] ([ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [A_Act_S_UDFValues_FK2];


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [FK_A_Ax_UDFValues_Code_ID_V_UNIFIEDCODESET];


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [FK_A_Ax_UDFValues_FRM_Definition_ID_V_UNIFIEDCODESET];


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [FK_A_Ax_UDFValues_SEC_Definition_ID_V_UNIFIEDCODESET];


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [FK_A_Ax_UDFValues_UDF_Instance_ID_A_ACT];


GO
ALTER TABLE [dbo].[Ax_UDFValues] NOCHECK CONSTRAINT [FK_A_Ax_UDFValues_valueCode_ID_V_UNIFIEDCODESET];


GO
ALTER TABLE [dbo].[Ax_UDFValues] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);


GO
CREATE NONCLUSTERED INDEX [IX_S_UDFValues_Act_Parent_ID]
    ON [dbo].[Ax_UDFValues]([Act_Parent_ID] ASC) WITH (FILLFACTOR = 70)
    ON [PRIMARY_IDX];


GO
CREATE NONCLUSTERED INDEX [IX_S_UDFVALUES_VALUE]
    ON [dbo].[Ax_UDFValues]([VALUE_UCSID] ASC) WITH (FILLFACTOR = 70);


GO
ALTER INDEX [IX_S_UDFVALUES_VALUE]
    ON [dbo].[Ax_UDFValues] DISABLE;


GO
CREATE NONCLUSTERED INDEX [IX_AX_UDFVALUES_FRM_SEC_METACODE_INSTANCE_ID]
    ON [dbo].[Ax_UDFValues]([FRM_DefinitionID] ASC, [SEC_DefinitionID] ASC, [METACODE_UCSID] ASC, [UDF_InstanceID] ASC)
    INCLUDE([VALUEDATETIME], [VALUE_UCSID], [ID]) WITH (FILLFACTOR = 70)
    ON [PRIMARY_IDX];


GO
ALTER INDEX [IX_AX_UDFVALUES_FRM_SEC_METACODE_INSTANCE_ID]
    ON [dbo].[Ax_UDFValues] DISABLE;


GO
CREATE NONCLUSTERED INDEX [IX_Ax_UDF_InstanceID]
    ON [dbo].[Ax_UDFValues]([UDF_InstanceID] ASC)
    INCLUDE([ID]) WITH (FILLFACTOR = 70)
    ON [PRIMARY_IDX];


GO
ALTER INDEX [IX_Ax_UDF_InstanceID]
    ON [dbo].[Ax_UDFValues] DISABLE;


GO
CREATE NONCLUSTERED INDEX [IX_AX_UDFVALUES_SEC_METACODE_INSTANCE_ID]
    ON [dbo].[Ax_UDFValues]([SEC_DefinitionID] ASC, [METACODE_UCSID] ASC, [UDF_InstanceID] ASC) WITH (FILLFACTOR = 70)
    ON [PRIMARY_IDX];


GO
ALTER INDEX [IX_AX_UDFVALUES_SEC_METACODE_INSTANCE_ID]
    ON [dbo].[Ax_UDFValues] DISABLE;


GO
CREATE NONCLUSTERED INDEX [IX_S_UDFVALUES_VALUE_2]
    ON [dbo].[Ax_UDFValues]([METACODE_UCSID] ASC)
    INCLUDE([Act_Parent_ID], [VALUESTRING], [VALUEDATETIME], [VALUE_ENTITYID], [VALUE_UCSID]);

