CREATE TABLE [dbo].[S_Form] (
    [FORM_ID]   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FORM_Text] NVARCHAR (50) NULL,
    CONSTRAINT [S_Form_PK] PRIMARY KEY CLUSTERED ([FORM_ID] ASC) WITH (FILLFACTOR = 95) ON [PRIMARY_IDX]
) ON [PRIMARY_IDX];


GO
CREATE STATISTICS [IX_WA_FORM_ID]
    ON [dbo].[S_Form]([FORM_ID]);


GO
CREATE STATISTICS [IX_WA_FORM_Text]
    ON [dbo].[S_Form]([FORM_Text]);

