CREATE TABLE [dbo].[SARS2_PERSON] (
    [PER_ROWID]                        INT              NOT NULL,
    [PER_LEGACY_ROWID]                 VARCHAR (50)     NULL,
    [PER_COUNTRYOFBIRTHDR]             VARCHAR (100)    NULL,
    [PER_CELLPHONE]                    VARCHAR (100)    NULL,
    [PER_DATEOFUSARRIVAL]              DATETIME2 (3)    NULL,
    [PER_OCCUPATIONLOCATION]           TEXT             NULL,
    [PER_OCCUPATIONSPECIFY]            TEXT             NULL,
    [PER_OCCUPATIONSETTINGTYPEDR]      INT              NULL,
    [PER_OCCUPATIONSETTINGTYPESPECIFY] VARCHAR (50)     NULL,
    [PER_ROOTID]                       INT              NULL,
    [PER_LASTNAME]                     VARCHAR (100)    NULL,
    [PER_FIRSTNAME]                    VARCHAR (100)    NULL,
    [PER_MIDDLENAME]                   VARCHAR (100)    NULL,
    [PER_SSN]                          VARCHAR (50)     NULL,
    [PER_HOMEPHONE]                    VARCHAR (100)    NULL,
    [PER_WORKPHONE]                    VARCHAR (100)    NULL,
    [PER_STREETADDRESS]                VARCHAR (100)    NULL,
    [PER_APARTMENT]                    VARCHAR (100)    NULL,
    [PER_CITY]                         VARCHAR (100)    NULL,
    [PER_STATE]                        VARCHAR (100)    NULL,
    [PER_STATENUMBER]                  TEXT             NULL,
    [PER_ZIP]                          VARCHAR (100)    NULL,
    [PER_ClientID]                     INT              NULL,
    [PER_COUNTYOFRESIDENCE]            VARCHAR (255)    NULL,
    [PER_CENSUSTRACT]                  VARCHAR (100)    NULL,
    [PER_LATITUDE]                     VARCHAR (100)    NULL,
    [PER_LONGITUDE]                    VARCHAR (100)    NULL,
    [PER_ADDRESSSTANDARDIZED]          VARCHAR (50)     NULL,
    [PER_COUNTYFIPS]                   VARCHAR (100)    NULL,
    [PER_COUNTY]                       VARCHAR (100)    NULL,
    [PER_CENSUSBLOCK]                  VARCHAR (100)    NULL,
    [PER_ZIPPLUS4]                     VARCHAR (100)    NULL,
    [PER_COUNTRY]                      VARCHAR (100)    NULL,
    [PER_COUNTRY_NAME]                 VARCHAR (255)    NULL,
    [PER_DOB]                          DATETIME2 (3)    NULL,
    [PER_SEX]                          VARCHAR (255)    NULL,
    [PER_RACE]                         VARCHAR (255)    NULL,
    [PER_ETHNICITY]                    VARCHAR (255)    NULL,
    [PER_OCCUPATION]                   VARCHAR (255)    NULL,
    [PER_SEXCODE_DR]                   INT              NULL,
    [PER_RACECODE_DR]                  INT              NULL,
    [PER_ETHNICITYCODE_DR]             INT              NULL,
    [PER_OCCUPATIONCODE_DR]            INT              NULL,
    [PER_NAMESUFFIX]                   VARCHAR (50)     NULL,
    [PER_RECORDCREATEDBY]              VARCHAR (14)     NOT NULL,
    [PER_WORKSCHOOLLOCATION]           VARCHAR (250)    NULL,
    [PER_WORKSCHOOLCONTACT]            TEXT             NULL,
    [PER_PRIMARYLANGUAGE_DR]           INT              NULL,
    [PER_PRIMARYLANGUAGE]              VARCHAR (255)    NULL,
    [PER_EMAIL]                        TEXT             NULL,
    [PER_ELECTRONICCONTACT]            TEXT             NULL,
    [PER_CURRENTVERSION]               VARCHAR (1)      NOT NULL,
    [HashCode]                         VARBINARY (8000) NULL,
    [SynchronizationType]              TINYINT          NOT NULL,
    [SynchronizationDateTime]          DATETIME         NOT NULL,
    CONSTRAINT [PK_SARS2_PERSON] PRIMARY KEY CLUSTERED ([PER_ROWID] ASC) ON [WCExtracted_Data]
) ON [WCExtracted_Data] TEXTIMAGE_ON [WCExtracted_Data];

