CREATE TABLE [dbo].[VCP_SNOMED] (
    [SNMD_ConditionID]   VARCHAR (255) NULL,
    [SNMD_ConditionName] VARCHAR (255) NULL,
    [SNMD_Status]        VARCHAR (255) NULL,
    [SNMD_LegacyCode]    VARCHAR (255) NULL,
    [SubjCode_ID]        INT           NOT NULL,
    [ID]                 INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    CONSTRAINT [VCP_SNOMED_PK] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_A_VCP_SNOMED_SubjCode_ID_V_UNIFIEDCODESET] FOREIGN KEY ([SubjCode_ID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[VCP_SNOMED] NOCHECK CONSTRAINT [FK_A_VCP_SNOMED_SubjCode_ID_V_UNIFIEDCODESET];


GO
CREATE NONCLUSTERED INDEX [IX_VCP_SNOMED_LegacyCode]
    ON [dbo].[VCP_SNOMED]([ID] ASC, [SNMD_LegacyCode] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [IX_VCP_SNOMED_LEGACYCODE_SUBJCODE]
    ON [dbo].[VCP_SNOMED]([SNMD_LegacyCode] ASC)
    INCLUDE([SubjCode_ID]) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [IX_VCP_SNOMED_SUBJCODE_LEGACYCODE]
    ON [dbo].[VCP_SNOMED]([SubjCode_ID] ASC)
    INCLUDE([SNMD_LegacyCode]) WITH (FILLFACTOR = 70);

