CREATE TABLE [dbo].[VCP_AgeGroup] (
    [AgeFrom]     REAL NULL,
    [AgeTo]       REAL NULL,
    [SubjCode_ID] INT  NULL,
    [ID]          INT  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    CONSTRAINT [VCP_AgeGroup_PK] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_A_VCP_AgeGroup_SubjCode_ID_V_UNIFIEDCODESET] FOREIGN KEY ([SubjCode_ID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[VCP_AgeGroup] NOCHECK CONSTRAINT [FK_A_VCP_AgeGroup_SubjCode_ID_V_UNIFIEDCODESET];


GO
CREATE NONCLUSTERED INDEX [IX_VCP_AgeGroup_SubjCode_SubjCvDo]
    ON [dbo].[VCP_AgeGroup]([SubjCode_ID] ASC) WITH (FILLFACTOR = 70)
    ON [PRIMARY_IDX];

