CREATE TABLE [dbo].[VCP_DiseaseAutoCreationRule] (
    [ID]          INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SubjCode_ID] INT NULL,
    [ReportType1] INT NULL,
    [ReportType2] INT NULL,
    [ReportType3] INT NULL,
    [Option1]     INT NULL,
    [Option2]     INT NULL,
    [Option3]     INT NULL,
    [Option4]     INT NULL,
    [Action1]     INT NULL,
    [Action2]     INT NULL,
    [Action3]     INT NULL,
    [Action4]     INT NULL,
    [AlertLevel]  INT NULL,
    CONSTRAINT [PK_VCP_DiseaseAutoCreationRule] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Action1_V_UnifiedCodeSet] FOREIGN KEY ([Action1]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Action2_V_UnifiedCodeSet] FOREIGN KEY ([Action2]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Action3_V_UnifiedCodeSet] FOREIGN KEY ([Action3]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Action4_V_UnifiedCodeSet] FOREIGN KEY ([Action4]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_AlertLevel_V_UnifiedCodeSet] FOREIGN KEY ([AlertLevel]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Option1_V_UnifiedCodeSet] FOREIGN KEY ([Option1]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Option2_V_UnifiedCodeSet] FOREIGN KEY ([Option2]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Option3_V_UnifiedCodeSet] FOREIGN KEY ([Option3]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_Option4_V_UnifiedCodeSet] FOREIGN KEY ([Option4]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_ReportType1_V_UnifiedCodeSet] FOREIGN KEY ([ReportType1]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_ReportType2_V_UnifiedCodeSet] FOREIGN KEY ([ReportType2]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_ReportType3_V_UnifiedCodeSet] FOREIGN KEY ([ReportType3]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID]),
    CONSTRAINT [FK_VCP_DiseaseAutoCreationRule_SubjCode_ID_V_UnifiedCodeSet] FOREIGN KEY ([SubjCode_ID]) REFERENCES [dbo].[V_UnifiedCodeSet] ([ID])
);

