CREATE FUNCTION FN_CMM_GetAccessibleUserGroups()
RETURNS @tblUGAccess TABLE (SourceUG_ID INT, TargetUG_ID INT)
AS
BEGIN
    DECLARE @lstAllUserGroupServiceCategory TABLE
    (
        UG_ROWID INT,
        vocSVCCAT_ID INT
    )

    INSERT INTO @lstAllUserGroupServiceCategory
    SELECT DISTINCT UGRole.ID AS UG_RowID, ATT.VALUECODE_ID AS vocSVCCAT_ID 
    FROM E_Entity UG (NOLOCK)
        INNER JOIN R_Role UGRole (NOLOCK) ON UGRole.player_ID = UG.ID AND UGRole.classCode = 'ASSIGNED'
        INNER JOIN T_Attribute ATT (NOLOCK) ON ATT.ROLE_ID = UGRole.ID AND ATT.[NAME]='FORMACC' 
        INNER JOIN V_UNIFIEDCODESET UCS_SVCCAT (NOLOCK) ON UCS_SVCCAT.ID=ATT.VALUECODE_ID  
        INNER JOIN A_ACT ACTPROTOCOL (NOLOCK) ON ACTPROTOCOL.TITLE = CAST(UCS_SVCCAT.OTHERINFO AS VARCHAR(300))   
        AND ACTPROTOCOL.CLASSCODE = 'ACT' AND ACTPROTOCOL.MOODCODE = 'DEF'  
        INNER JOIN T_ATTRIBUTE ATTPROTOCOL (NOLOCK) ON ATTPROTOCOL.ACT_ID = ACTPROTOCOL.ID AND ATTPROTOCOL.NAME = 'PROT_FORMNAME_FK'  
        INNER JOIN VCP_UDFORM UDF (NOLOCK) ON UDF.SUBJCODE_ID = ATTPROTOCOL.VALUECODE_ID AND UDF.FRM_INNCM=1 AND UDF.FRM_InProtocol = 1   
        INNER JOIN V_CODEPROPERTY VC (NOLOCK) ON VC.SUBJCODE_ID = ATT.VALUECODE_ID AND ISNULL(VC.VALUEBOOL,0) = 1 
        AND VC.VALUECODE_ID = ATTPROTOCOL.VALUECODE_ID AND VC.PROPERTY =CAST(ATT.ID AS VARCHAR(50))  
    WHERE UG.metaCode = 'UG_RowID' and UG.statusCode = 'active' 
        
    INSERT INTO @tblUGAccess
    SELECT DISTINCT A.UG_ROWID AS SourceUG_ID , B.UG_ROWID AS TargetUG_ID FROM @lstAllUserGroupServiceCategory A
    INNER JOIN @lstAllUserGroupServiceCategory B ON A.UG_ROWID <> B.UG_ROWID
    AND NOT EXISTS(
    SELECT VOCSVCCAT_ID FROM @lstAllUserGroupServiceCategory C WHERE C.UG_ROWID=B.UG_ROWID
    EXCEPT
    SELECT VOCSVCCAT_ID FROM @lstAllUserGroupServiceCategory D WHERE D.UG_ROWID=A.UG_ROWID
    )
    INSERT INTO @tblUGAccess
    SELECT DISTINCT A.UG_ROWID AS SourceUG_ID , A.UG_ROWID AS TargetUG_ID FROM @lstAllUserGroupServiceCategory A
    RETURN
END
