
CREATE FUNCTION [dbo].[FN_CumulativeTypes] (@ID INT, @MetaCode VARCHAR(50))
	RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @TESTS VARCHAR(8000)
	SELECT @TESTS = dbo.STRCONCAT(DISTINCT UCS.fullName) 
	FROM  A_ACT ACTOBS (NOLOCK) 
	INNER JOIN  dbo.V_UnifiedCodeSet UCS (NOLOCK) ON ACTOBS.code_ID = UCS.ID 
	WHERE ACTOBS.Act_CaseCMR_ID = @ID AND ACTOBS.METACODE = @MetaCode 
	RETURN 	@TESTS 
END
