CREATE FUNCTION FN_CMM_GetAccessibleDistictGroups(@SourceDistictGroup_ID INT)
RETURNS TABLE 
AS
RETURN
    SELECT 
        UCSSource.ID AS SOURCEDISTRICTGROUP_ID,
        AccessibleDG.ID AS TARGETDISTRICTGROUP_ID
    FROM V_UNIFIEDCODESET UCSSource (NOLOCK) 
        INNER JOIN V_DOMAIN VD1 (NOLOCK) ON UCSSource.DOMAIN_ID = VD1.ID
        CROSS APPLY 
        (
            SELECT UCSTarget.ID,UCSTarget.FULLNAME 
            FROM V_UNIFIEDCODESET UCSTarget (NOLOCK)
            INNER JOIN V_DOMAIN VD2 (NOLOCK) ON UCSTarget.DOMAIN_ID = VD2.ID 
            AND VD2.DOMAINNAME='DISTRICTGROUP'
            WHERE NOT EXISTS (SELECT VALUECODE_ID FROM V_CODEPROPERTY (NOLOCK) 
            WHERE PROPERTY='GRPD_DISTRICTDR' AND SUBJCODE_ID= UCSTarget.ID
            EXCEPT 
            SELECT VALUECODE_ID FROM V_CODEPROPERTY (NOLOCK) 
            WHERE PROPERTY='GRPD_DISTRICTDR' AND SUBJCODE_ID=UCSSource.ID)
            AND UCSTarget.DOMAIN_ID=VD2.ID AND UCSTarget.ID <> UCSSource.ID
        ) AccessibleDG
    WHERE VD1.DOMAINNAME='DISTRICTGROUP' and UCSSource.ID = @SourceDistictGroup_ID
