
CREATE FUNCTION [dbo].[FN_CMR_AdvanceFilterPARAM_TO_AdvanceFilterTable] (@AdvanceSeachFilterString NVARCHAR(MAX))  
RETURNS @RETURNVALUES TABLE (FRM_DefinitionID INT, SEC_DefinitionID INT, FLD_DefinitionID INT, ValueUCS int, ValueString VARCHAR(MAX), ValueFromDate VARCHAR(100), ValueToDate VARCHAR(100), FilterName VARCHAR(100))
AS  
BEGIN
	
	DECLARE @STARTPOSITION AS INT
	DECLARE @LASTPOSITION AS INT
	DECLARE @STARTPOSITIONINNER AS INT
	DECLARE @LASTPOSITIONINNER AS INT
	DECLARE @TempData as VARCHAR(MAX)
	DECLARE @TempDataINNER as VARCHAR(MAX)
	DECLARE @COUNTER INT

	DECLARE @FRM_DefinitionID INT
	DECLARE @SEC_DefinitionID INT
	DECLARE @FLD_DefinitionID INT
	DECLARE @ValueUCS INT
	DECLARE @ValueString VARCHAR(MAX)
	DECLARE @FilterName VARCHAR(100)
	DECLARE @ValueFromDate VARCHAR(100)
	DECLARE @ValueToDate VARCHAR(100)
	
	SET @STARTPOSITION=0
	SET @LASTPOSITION=0
	SET @STARTPOSITIONINNER=0
	SET @LASTPOSITIONINNER=0
	SET @TempData=''
	SET @TempDataINNER=''
	SET @COUNTER=0

	WHILE CHARINDEX(CHAR(1)+CHAR(2),@AdvanceSeachFilterString,@STARTPOSITION)<>0
	BEGIN
		SET @TempData=''
		SET @STARTPOSITIONINNER=0
		SET @LASTPOSITIONINNER=0
		SET @COUNTER=0
		
		SET @LASTPOSITION=CHARINDEX(CHAR(1)+CHAR(2),@AdvanceSeachFilterString,@STARTPOSITION)
		SET @TempData=SUBSTRING(@AdvanceSeachFilterString,@STARTPOSITION,@LASTPOSITION-@STARTPOSITION)
		SET @STARTPOSITION=@LASTPOSITION+2
		
		WHILE CHARINDEX(CHAR(1)+CHAR(1),@TempData,@STARTPOSITIONINNER)<>0
		BEGIN
			SET @TempDataINNER=''
			SET @LASTPOSITIONINNER=CHARINDEX(CHAR(1)+CHAR(1),@TempData,@STARTPOSITIONINNER)
			SET @TempDataINNER=SUBSTRING(@TempData,@STARTPOSITIONINNER,@LASTPOSITIONINNER-@STARTPOSITIONINNER)
			
			IF @TempDataINNER=''
			BEGIN
				SET @TempDataINNER = NULL
			END
			
			SET @STARTPOSITIONINNER=@LASTPOSITIONINNER+2
			IF @COUNTER=0
				SET @FRM_DefinitionID=@TempDataINNER
			ELSE IF @COUNTER=1
				SET @SEC_DefinitionID=@TempDataINNER
			ELSE IF @COUNTER=2
				SET @FLD_DefinitionID=@TempDataINNER
			ELSE IF @COUNTER=3
				SET @ValueUCS=@TempDataINNER
			ELSE IF @COUNTER=4
				SET @ValueString=@TempDataINNER
			ELSE IF @COUNTER=5
				SET @ValueFromDate=@TempDataINNER
			ELSE IF @COUNTER=6					
				SET @ValueToDate=@TempDataINNER
			ELSE IF @COUNTER=7
				SET @FilterName=@TempDataINNER
			SET @COUNTER=@COUNTER+1
		END
		INSERT INTO @RETURNVALUES VALUES(@FRM_DefinitionID,@SEC_DefinitionID,@FLD_DefinitionID,@ValueUCS,@ValueString,@ValueFromDate,@ValueToDate,@FilterName)
	END
	RETURN
END
