CREATE  FUNCTION [dbo].[FN_CMR_GetInstanceIDsForAudit](@IDs VARCHAR(MAX),@Type varchar(200))
RETURNS @InstanceIDTABLE TABLE  
( InstanceID Int )  
AS  
BEGIN 
	IF @Type='CLIENTRECORD' 
	BEGIN
		INSERT INTO @InstanceIDTABLE
		SELECT A_ACT.ID FROM A_ACT FOLDER (NOLOCK)  
		INNER JOIN A_ACTRELATIONSHIP (NOLOCK) ON A_ACTRELATIONSHIP.SOURCE_ID=FOLDER.ID AND A_ACTRELATIONSHIP.TYPECODE='COMP'  
		INNER JOIN A_ACT (NOLOCK) ON A_ACT.ID=A_ACTRELATIONSHIP.TARGET_ID AND A_ACT.CLASSCODE IN('DOCSECT','DOCBODY')  
		WHERE FOLDER.ID IN(SELECT Value FROM  dbo.[ParmsToList](@IDs)) AND FOLDER.CLASSCODE='FOLDER'  
		
		RETURN
	END
	ELSE
	IF @Type='SERVICERECORD'
	BEGIN
		INSERT INTO @InstanceIDTABLE
		
		SELECT A_ACT.ID FROM A_Act (NOLOCK) 
		INNER JOIN A_ActRelationship (NOLOCK) on A_ActRelationship.target_ID=A_ACT.ID and typeCode='COMP'
		INNER JOIN AX_Services (NOLOCK) on AX_Services.SVC_ID=A_ActRelationship.source_ID
		WHERE A_Act.classCode in('DOCSECT','DOCBODY') and SVC_ID IN(SELECT Value FROM  dbo.[ParmsToList](@IDs))
		
		UNION
				
		SELECT A_Act.ID
		FROM A_Act (NOLOCK) 
		INNER JOIN A_ActRelationship ACTREL (NOLOCK) on ACTREL.target_ID=A_ACT.ID AND ACTREL.typeCode='COMP' AND  A_Act.classCode = 'DOCSECT'
		INNER JOIN A_Act ACTFLDR (NOLOCK) ON ACTREL.source_ID = ACTFLDR.ID AND ACTFLDR.classCode ='FOLDER'
		INNER JOIN P_Participation PART (NOLOCK) ON ACTFLDR.ID = PART.Act_ID AND PART.typeCode='SBJ'
		INNER JOIN R_Role ROLEMBR (NOLOCK) ON PART.Role_ID = ROLEMBR.ID AND ROLEMBR.classCode ='MBR'
		INNER JOIN R_Role ROLEEXPR (NOLOCK) ON ROLEMBR.scoper_id = ROLEEXPR.Player_ID
		INNER JOIN P_Participation PARTIND (NOLOCK) ON ROLEEXPR.ID = PARTIND.Role_ID AND PARTIND.typeCode='IND'
		INNER JOIN A_Act ACTSVC (NOLOCK) ON PARTIND.Act_ID = ACTSVC.ID AND ACTSVC.classCode ='CASE' AND ACTSVC.metaCode ='SVC_ID'
		INNER JOIN AX_Services (NOLOCK) on AX_Services.SVC_ID = ACTSVC.ID
		WHERE AX_Services.SVC_ID IN(SELECT Value FROM  dbo.[ParmsToList](@IDs))
		
		RETURN
	END
	RETURN
END 


