

CREATE FUNCTION [DBO].[FN_CONCATEMANUALSUSCEPTIBILITYRESULT]  (@LABR_ROWID AS INT)
	RETURNS NVARCHAR(MAX)
AS
BEGIN 
	IF @LABR_ROWID IS NULL 
	BEGIN 
		RETURN '' 
	END 
	
	DECLARE @RETURNTEXT AS NVARCHAR(MAX)

	
		SELECT @RETURNTEXT=COALESCE(@RETURNTEXT + '|', '') + ISNULL(V_UNIFIEDCODESET.CONCEPTCODE,'')
		FROM V_UNIFIEDCODESET (NOLOCK)
		INNER JOIN V_CODEPROPERTY (NOLOCK) ON V_CODEPROPERTY.VALUECODE_ID=V_UNIFIEDCODESET.ID
		WHERE V_CODEPROPERTY.SUBJCODE_ID=@LABR_ROWID

	RETURN @RETURNTEXT 
END


