
CREATE FUNCTION [dbo].[FN_DiseaseGroups] (@ID INT)
	RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @GRPS VARCHAR(8000)
	SELECT @GRPS = dbo.STRCONCAT(DISTINCT UCS.fullName) FROM  V_CODEPROPERTY VCP (NOLOCK)		
	INNER JOIN  dbo.V_UnifiedCodeSet UCS (NOLOCK) ON VCP.subjCode_ID=UCS.id
	AND VCP.VALUECODE_ID =@ID
	INNER JOIN  dbo.V_TermDictionary VTD (NOLOCK) ON VTD.termCode_ID= UCS.id
	AND VTD.ACTIVE = 1
	RETURN 	@GRPS
END

