
CREATE FUNCTION [dbo].[FN_GetConcatenatedMRN] 
(
	@PersonID INT
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
	DECLARE @MRN NVARCHAR(MAX)
	SET @MRN = ''

	SELECT  @MRN = CASE WHEN @MRN='' THEN ISNULL(DVPR_MRN, '') ELSE @MRN + CHAR(1) + ISNULL(DVPR_MRN, '') END
	FROM DV_PHPersonalRecord (nolock) WHERE DVPR_PersonDR = @PersonID

	RETURN @MRN
END
