CREATE FUNCTION [dbo].[FN_GetSiteID] ()
	RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @SITEID VARCHAR(20)
	
	SELECT @SITEID = CAST((CASE WHEN VAL.value='' THEN CONFIG.defaultvalue ELSE VAL.value END) AS VARCHAR(20))  
	FROM S_CONFIGDEFINITION CONFIG (NOLOCK)
	INNER JOIN S_CONFIGVALUE VAL (NOLOCK) ON VAL.configdefinition_id = CONFIG.id
	WHERE CONFIG.[KEY]='SITEID'
	
	RETURN @SITEID
END

