
CREATE FUNCTION [dbo].[FN_HasAlternate_Contact](@CODE_ID int)  
RETURNS BIT  
AS  
BEGIN  

DECLARE @HASRECORDS BIT;  
DECLARE @COUNT INT;  

SELECT @COUNT = COUNT(PROT.ID)
FROM 
V_UNIFIEDCODESET UCS (NOLOCK)
INNER JOIN A_ACT PROT (NOLOCK) ON PROT.TITLE = CONVERT(VARCHAR(8000),UCS.[OTHERINFO]) AND PROT.CLASSCODE = 'ACT' AND PROT.METACODE = 'PROT_ID' AND PROT.MOODCODE = 'DEF' AND PROT.STATUSCODE = 'ACTIVE' AND VALUEBOOL = 1
WHERE UCS.ID = @CODE_ID

IF @COUNT>0 SET @HASRECORDS=1 ELSE SET @HASRECORDS=0  
  
RETURN @HASRECORDS; 
END 

