
CREATE FUNCTION [dbo].[FN_HasFormBeingExported](@ServiceId int,@SelectedForm varchar(100))
RETURNS BIT
AS
BEGIN
DECLARE @hasRecords BIT;
Declare @conceptCode varchar(10);
Declare @Count int;


IF @SelectedForm='CFDC' OR @SelectedForm='CDIC' OR  @SelectedForm='EPIC'
BEGIN

IF @SelectedForm='CFDC' --Case Flow & DOT � Case Tab
						BEGIN
								SELECT @Count=COUNT(*) FROM A_ACT ACTDOCBODY (NOLOCK)
								INNER JOIN A_ACT DOCSECACT (NOLOCK) ON DOCSECACT.ACT_PARENT_ID=ACTDOCBODY.ID
								WHERE ACTDOCBODY.ACT_PARENT_ID=@ServiceId AND ACTDOCBODY.CLASSCODE='DOCBODY' AND 
								ACTDOCBODY.CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','CFD') AND 
								DOCSECACT.METACODE IN ('BACT_ID','CXR_ID','DOTWRKL_ID','PPD_ID','SUSC_ID','TBMED_ID','TBSITE_ID','TBTREAT_ID') AND DOCSECACT.STATUSCODE<>'nullified'
						END
							ELSE	
IF @SelectedForm='CDIC'	--Communicable Disease Investigation � Case Tab
						BEGIN
								SELECT @Count=COUNT(*) FROM A_ACT ACTDOCBODY (NOLOCK)
								INNER JOIN A_ACT DOCSECACT (NOLOCK) ON DOCSECACT.ACT_PARENT_ID=ACTDOCBODY.ID
								WHERE ACTDOCBODY.ACT_PARENT_ID=@ServiceId AND ACTDOCBODY.CLASSCODE='DOCBODY' AND 
								ACTDOCBODY.CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','CDI') AND 
								DOCSECACT.METACODE IN ('CDCASE_ID','CDCASESYMP_ID') AND DOCSECACT.STATUSCODE<>'nullified'
						END
							ELSE
IF @SelectedForm='EPIC' --Epidemiology Investigation � Case Tab
						BEGIN
								SELECT @Count=COUNT(*) FROM A_ACT ACTDOCBODY (NOLOCK)
								INNER JOIN A_ACT DOCSECACT (NOLOCK) ON DOCSECACT.ACT_PARENT_ID=ACTDOCBODY.ID
								WHERE ACTDOCBODY.ACT_PARENT_ID=@ServiceId AND ACTDOCBODY.CLASSCODE='DOCBODY' AND 
								ACTDOCBODY.CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','EPI') AND 
								DOCSECACT.METACODE IN ('TBEPICASE_ID') AND DOCSECACT.STATUSCODE<>'nullified'						
						END
							
END
--Communicable Disease Investigation � Alternate Contact Tab or Communicable Disease Investigation � Contact Tab or Epidemiology Investigation � Contact Tab
ELSE IF @SelectedForm='CDACN' OR @SelectedForm='CDICN' OR @SelectedForm='EPICN'
BEGIN
								SET @conceptCode=CASE WHEN @SelectedForm='CDACN' OR @SelectedForm='CDICN' THEN 'CDI' WHEN @SelectedForm='EPICN' THEN 'EPI' END
								SELECT @Count=COUNT([ACTREL].ID) FROM A_ACT [ACTDOCBODY] (NOLOCK)
								INNER JOIN A_ACTRELATIONSHIP [ACTREL] (NOLOCK) ON [ACTDOCBODY].ID=[ACTREL].SOURCE_ID AND [ACTREL].TYPECODE='REFR'
								INNER JOIN P_PARTICIPATION [PART] (NOLOCK) ON [PART].ACT_ID=[ACTREL].TARGET_ID AND [PART].TYPECODE='SBJ'
								INNER JOIN R_ROLE [CONTACTROLE] (NOLOCK) ON [CONTACTROLE].ID=[PART].ROLE_ID AND [CONTACTROLE].CLASSCODE='MBR' AND [CONTACTROLE].STATUSCODE<>'nullified'
								WHERE [ACTDOCBODY].ACT_PARENT_ID=@ServiceId AND [ACTDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10',@conceptCode)
END

--Encounters � General Tab
ELSE IF @SelectedForm='ENCG'
BEGIN
								SELECT @Count=COUNT([ENCCHID_ACTS].ID) FROM A_ACT [CASEACT] (NOLOCK)
								INNER JOIN A_ACT [ENCDOCBODY] (NOLOCK) ON [CASEACT].ACT_PARENT_ID=[ENCDOCBODY].ACT_PARENT_ID
								INNER JOIN A_ACT [ENCCHID_ACTS] (NOLOCK) ON [ENCDOCBODY].ID=[ENCCHID_ACTS].ACT_PARENT_ID
								WHERE [CASEACT].ID=@ServiceId AND [ENCDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','ENC')
								AND [ENCCHID_ACTS].METACODE IN ('MGMTEPISD_ID','PERREV_ID','MGMTCNTY_ID','DIAGHIST_ID','MEDHIST_ID') AND [ENCCHID_ACTS].STATUSCODE<>'nullified'
	
						If @Count=0 --Check for if exists any Encounters Workers 
			BEGIN
	
								SELECT @Count=COUNT(*) FROM A_ACT ACTDOCBODY (NOLOCK)
								INNER JOIN A_ACT ENCWORKERACT (NOLOCK) ON ENCWORKERACT.ACT_PARENT_ID=ACTDOCBODY.ID
								INNER JOIN A_ACT FOLDER (NOLOCK) ON FOLDER.ID=ACTDOCBODY.ACT_PARENT_ID
								INNER JOIN A_ACT CASEACT (NOLOCK) ON CASEACT.ACT_PARENT_ID=FOLDER.ID
								WHERE CASEACT.ID=@ServiceId AND ACTDOCBODY.CLASSCODE='DOCBODY' AND 
								ACTDOCBODY.CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','ENC') AND 
								ENCWORKERACT.METACODE IN ('ENCWRKL_ID') AND ENCWORKERACT.STATUSCODE<>'nullified'
	 
			END
END

--TB History � TB History Tab.
ELSE IF @SelectedForm='TBH'
BEGIN
								SELECT @Count=COUNT(*) FROM  A_ACT [TBHISTORY_DOCBODY] (NOLOCK)
								WHERE [TBHISTORY_DOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','TBH')
								AND [TBHISTORY_DOCBODY].ACT_PARENT_ID=@ServiceId  -- nullified not check required as in UI no option to delete
END

--Referral � Main Tab
ELSE IF @SelectedForm='REFM' OR @SelectedForm='REFT' OR @SelectedForm='REFP'
BEGIN
								SELECT  @Count=COUNT(*) FROM A_ACTRELATIONSHIP (NOLOCK)
								INNER JOIN A_ACT [REFDOCBODY] (NOLOCK) ON [REFDOCBODY].ID=A_ACTRELATIONSHIP.TARGET_ID AND A_ACTRELATIONSHIP.TYPECODE='COMP'
								INNER JOIN A_ACT [DOCSECACT] (NOLOCK) ON [DOCSECACT].ACT_PARENT_ID=[REFDOCBODY].ID
								WHERE SOURCE_ID=@ServiceId 
								AND [REFDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','REF')
								AND [DOCSECACT].METACODE in ('REFINFO_ID', 'PROV_ID', 'REFDISP_ID', 'HLTHHIST_ID') AND [DOCSECACT].STATUSCODE<>'nullified'
END
ELSE IF @SelectedForm='REFT' --Referral TB Tab
BEGIN
								SELECT  @Count=COUNT(*) FROM A_ACTRELATIONSHIP (NOLOCK)
								INNER JOIN A_ACT [REFDOCBODY] (NOLOCK) ON [REFDOCBODY].ID=A_ACTRELATIONSHIP.TARGET_ID AND A_ACTRELATIONSHIP.TYPECODE='COMP'
								INNER JOIN A_ACT [DOCSECACT] (NOLOCK) ON [DOCSECACT].ACT_PARENT_ID=[REFDOCBODY].ID
								WHERE SOURCE_ID=@ServiceId 
								AND [REFDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','REF')
								AND [DOCSECACT].METACODE in ('TBHIST_ID', 'PPDHIST_ID', 'CXRHIST_ID', 'BACTHIST_ID', 'TBMEDHIST_ID') AND [DOCSECACT].STATUSCODE<>'nullified'
END
ELSE IF @SelectedForm='REFP'--Referral Perinatal Tab
BEGIN
								SELECT  @Count=COUNT(*) FROM A_ACTRELATIONSHIP (NOLOCK)
								INNER JOIN A_ACT [REFDOCBODY] (NOLOCK) ON [REFDOCBODY].ID=A_ACTRELATIONSHIP.TARGET_ID AND A_ACTRELATIONSHIP.TYPECODE='COMP'
								INNER JOIN A_ACT [DOCSECACT] (NOLOCK) ON [DOCSECACT].ACT_PARENT_ID=[REFDOCBODY].ID
								WHERE SOURCE_ID=@ServiceId 
								AND [REFDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','REF')
								AND [DOCSECACT].METACODE in ('PERIHIST_ID') AND [DOCSECACT].STATUSCODE<>'nullified'
END

ELSE IF @SelectedForm='RVTM' --RVCT Tab  SBANSAL Issue#117578
BEGIN  
        SELECT  @Count=COUNT(*) FROM A_ACT (NOLOCK)  
        INNER JOIN A_ACT [RVCTDOCBODY] (NOLOCK) ON [RVCTDOCBODY].ID=A_ACT.ACT_PARENT_ID 
        WHERE [RVCTDOCBODY].ACT_CASENCM_ID=@ServiceId   
        AND [RVCTDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','RVT')  
        AND A_ACT.METACODE ='RVCTPG_ID' AND A_ACT.STATUSCODE<>'nullified'  
END 
ELSE IF @SelectedForm='RVTF1' --RVCTFU1 Tab  SBANSAL Issue#117578
BEGIN  
        SELECT  @Count=COUNT(*) FROM A_ACT (NOLOCK)  
        INNER JOIN A_ACT [RVCTDOCBODY] (NOLOCK) ON [RVCTDOCBODY].ID=A_ACT.ACT_PARENT_ID 
        WHERE [RVCTDOCBODY].ACT_CASENCM_ID=@ServiceId   
        AND [RVCTDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','RVT')  
        AND A_ACT.METACODE ='RVCTFU1_ID' AND A_ACT.STATUSCODE<>'nullified'  
END 
ELSE IF @SelectedForm='RVTF2' -- RVCTFU2 Tab  SBANSAL Issue#117578
BEGIN  
        SELECT  @Count=COUNT(*) FROM A_ACT (NOLOCK)  
        INNER JOIN A_ACT [RVCTDOCBODY] (NOLOCK) ON [RVCTDOCBODY].ID=A_ACT.ACT_PARENT_ID 
        WHERE [RVCTDOCBODY].ACT_CASENCM_ID=@ServiceId   
        AND [RVCTDOCBODY].CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.3.33.4.2.4.5.10','RVT')  
        AND A_ACT.METACODE ='RVCTFU2_ID' AND A_ACT.STATUSCODE<>'nullified'  
END 
IF @Count>0 SET @hasRecords=1 ELSE SET @hasRecords=0

RETURN @HASRECORDS;
END


