
CREATE FUNCTION [dbo].[FN_HepatitisTests] (@ID INT)
	RETURNS VARCHAR(2048)
AS
BEGIN
	DECLARE @str VARCHAR(2048)
	DECLARE @fullName AS VARCHAR(100)
	DECLARE @COUNT AS INT
	SET @COUNT=0
	
	DECLARE OBS_cursor CURSOR FOR 	
		SELECT DISTINCT UCS.fullName 
		FROM  A_ACT ACTOBS 		
		LEFT JOIN  dbo.V_UnifiedCodeSet UCS ON ACTOBS.code_ID=UCS.ID
		INNER JOIN A_ActRelationship ACTRELOBS ON ACTRELOBS.TARGET_ID=ACTOBS.[ID] AND ACTOBS.CLASSCODE='OBS' AND ACTOBS.METACODE='DIHT_HepatitisTestDR'
		INNER JOIN A_ACT ACTTOPIC ON ACTRELOBS.SOURCE_ID = ACTTOPIC.[ID] AND ACTTOPIC.CLASSCODE='TOPIC'
		INNER JOIN A_ActRelationship ACTRELTOPIC ON ACTRELTOPIC.TARGET_ID=ACTTOPIC.[ID]
		INNER JOIN A_ACT ACTDOCBODY ON ACTDOCBODY.ID = ACTRELTOPIC.SOURCE_ID AND ACTDOCBODY.CLASSCODE='DOCBODY'
		INNER JOIN A_ActRelationship ACTRELDOCBODY ON ACTDOCBODY.[ID] = ACTRELDOCBODY.TARGET_ID
		INNER JOIN DV_DiseaseIncident ON DV_DiseaseIncident.DVDI_RowID = ACTRELDOCBODY.SOURCE_ID AND DV_DiseaseIncident.DVDI_RowID=@ID		
	OPEN OBS_cursor

	FETCH NEXT FROM OBS_cursor 
	INTO @fullName

		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @fullName<>''
			BEGIN
				IF @COUNT = 0
				BEGIN
					SET @str = @fullName
					SET @COUNT = 1
				END
				ELSE
				BEGIN
					SET @str = @str + ', ' + @fullName
				END
			END
			FETCH NEXT FROM OBS_cursor 
			INTO @fullName
		END
	CLOSE OBS_cursor
   	DEALLOCATE OBS_cursor
	RETURN @str
END
