
CREATE FUNCTION [dbo].[FN_IsUDFSharedBetweenCMRandNCM]  (@CASEID INT, @SharedCASEID INT)  
RETURNS BIT  
AS  
BEGIN   
 DECLARE @result AS BIT   
 SELECT @result= CASE WHEN COUNT(CASE1.METACODE) >0 THEN 1 ELSE 0 END FROM A_ACT CASEACT (NOLOCK)
INNER JOIN A_ACTRELATIONSHIP (NOLOCK) ON A_ACTRELATIONSHIP.SOURCE_ID=CASEACT.ID
INNER JOIN A_ACT UDF (NOLOCK) ON UDF.ID=A_ACTRELATIONSHIP.TARGET_ID AND UDF.CLASSCODE='DOCBODY'
INNER JOIN A_ACTRELATIONSHIP CASEREL1 (NOLOCK) ON CASEREL1.TARGET_ID=UDF.ID 
INNER JOIN A_ACT CASE1 (NOLOCK) ON CASE1.ID=CASEREL1.SOURCE_ID AND CASE1.CLASSCODE='CASE' AND CASE1.METACODE IN('PR_ROWID','SVC_ID') AND CASE1.STATUSCODE NOT IN('TERMINATED','NULLIFIED') 
WHERE CASEACT.ID=@CASEID AND CASE1.ID = @SharedCASEID AND CASE1.METACODE<>CASEACT.METACODE 

RETURN @result  
END  

