
CREATE FUNCTION [dbo].[FN_LAB_CHECK]  (@CASEID INT)
	RETURNS INT
AS
BEGIN
	DECLARE @COUNT INT
SELECT @COUNT=COUNT(*) FROM A_Act DILR (nolock) 
INNER JOIN Ax_LabReport AX (nolock) ON AX.DILR_ID=DILR.ID AND AX.DILR_IsFromHL7 = 1  
WHERE DILR.Act_parent_Id=@CASEID AND DILR.metaCode='DILR_ID' AND DILR.statusCode='ACTIVE'   
	IF @COUNT>0 SET @COUNT= 1
	RETURN @COUNT
END
