CREATE FUNCTION [dbo].[FN_LAB_ACTID]  (@ID INT)
    RETURNS INT
AS
BEGIN
    DECLARE @TOP_ACT_ID INT

    SELECT TOP 1 @TOP_ACT_ID=A_ACT.ID FROM A_ACT (NOLOCK) 
    WHERE METACODE='DILR_ID' AND A_ACT.Act_Parent_ID=@ID
    ORDER BY AvailabilityTime DESC, ID DESC
    RETURN @TOP_ACT_ID
END

