
CREATE FUNCTION [dbo].[FN_NCM_GetAccessibleServiceCategoriesByUserGroupDR](@UserGroupDR INT)  
RETURNS 
	@SVCCatIDTABLE TABLE    
	( SVCCatID Int )    
AS    
BEGIN   
  INSERT INTO @SVCCatIDTABLE  

SELECT  DISTINCT ATT.valueCode_ID as SVCCatID  
	FROM   
		T_Attribute ATT (NOLOCK)  
		INNER JOIN V_UNIFIEDCODESET UCS_SVCCAT (NOLOCK) ON UCS_SVCCAT.ID=ATT.VALUECODE_ID AND ATT.[NAME]='FORMACC' 
		INNER JOIN A_ACT ACTPROTOCOL (NOLOCK) ON ACTPROTOCOL.TITLE = CAST(UCS_SVCCAT.OTHERINFO AS VARCHAR(300))   
			   AND ACTPROTOCOL.CLASSCODE = 'ACT'
		INNER JOIN T_ATTRIBUTE ATTPROTOCOL (NOLOCK) ON ATTPROTOCOL.ACT_ID = ACTPROTOCOL.ID AND ATTPROTOCOL.NAME = 'PROT_FORMNAME_FK'  
		INNER JOIN V_CODEPROPERTY VC (NOLOCK) ON  VC.PROPERTY =CAST(ATT.ID AS VARCHAR(50)) AND VC.SUBJCODE_ID = ATT.VALUECODE_ID AND VC.VALUEBOOL = 1 
		AND VC.VALUECODE_ID = ATTPROTOCOL.VALUECODE_ID  
		INNER JOIN R_Role (NOLOCK) ON ATT.Role_ID = R_Role.ID   
		WHERE   R_Role.[player_ID] =  @UserGroupDR   

	RETURN   
END   

