
CREATE FUNCTION [dbo].[FN_RecordIsClosed]  (@INTSTATUSDR INT,@INTDISEASEDR INT, @PR_TypeDR INT )  
 RETURNS BIT  
AS  
BEGIN   
 DECLARE @OUTPUT AS BIT   
 DECLARE @PR_TYPE_Code AS VARCHAR(50)  
 DECLARE @INT_OtherWorkFlowID AS INT   
   
   
 SET @OUTPUT=0;  
 SET @INT_OtherWorkFlowID=0;  
 SET @PR_TYPE_Code='DI';  
   
 IF @INTSTATUSDR <> ''  
 BEGIN  
  IF @PR_TypeDR > 0  
  BEGIN  
   SELECT @PR_TYPE_Code = CONCEPTCODE  FROM V_UNIFIEDCODESET (nolock) WHERE ID=@PR_TypeDR  
   IF @PR_TYPE_Code = 'CI'  
   BEGIN   
    SELECT @INT_OtherWorkFlowID= ISNULL(ContactInvestigationWorkFlowCode_ID,0) FROM VCP_DISEASE (nolock) WHERE SUBJCODE_ID = @INTDISEASEDR  
   END  
   ELSE IF @PR_TYPE_Code = 'OB'  
   BEGIN   
    SELECT @INT_OtherWorkFlowID= ISNULL(OutbreakWorkFlowDR,0) FROM VCP_DISEASE (nolock) WHERE SUBJCODE_ID = @INTDISEASEDR  
   END 
   --SugannyaB CMR 11.0.0.1 Issue#104370  For verifying Animal Report Records	 
   ELSE IF @PR_TYPE_Code = 'AR'  
   BEGIN   
    SELECT @INT_OtherWorkFlowID= ISNULL(AnimalReportWorkflowDR,0) FROM VCP_DISEASE (nolock) WHERE SUBJCODE_ID = @INTDISEASEDR  
   END  
   ELSE IF @PR_TYPE_Code = 'GE'  
   BEGIN   
    SELECT @INT_OtherWorkFlowID= ISNULL(WorkFlowDR,0) FROM VCP_GroupEventType (nolock) WHERE SUBJCODE_ID = @INTDISEASEDR  
   END 
  END  
     
      
  IF @PR_TYPE_Code = 'CI' AND @INT_OtherWorkFlowID >0  
   BEGIN   
     SET @OUTPUT = (SELECT  TOP 1 CASE WHEN VALUECODE_ID=@INTSTATUSDR THEN 1 ELSE 0 END   
    FROM  [V_UNIFIEDCODESET] (NOLOCK)   
    INNER JOIN [VCP_DISEASE] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[VCP_DISEASE].[ContactInvestigationWorkFlowCode_ID]   
    INNER JOIN [V_CODEPROPERTY] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[V_CODEPROPERTY].[SUBJCODE_ID]  
    WHERE  [VCP_DISEASE].[SUBJCODE_ID] = @INTDISEASEDR AND [V_CODEPROPERTY].[PROPERTY] = 'WSF_ROWID'  
    ORDER BY [V_CODEPROPERTY].[VALUEINT] DESC)  
   END  
  ELSE IF @PR_TYPE_Code = 'OB' AND @INT_OtherWorkFlowID >0  
   BEGIN  
    SET @OUTPUT = (SELECT  TOP 1 CASE WHEN VALUECODE_ID=@INTSTATUSDR THEN 1 ELSE 0 END   
    FROM [V_UNIFIEDCODESET] (NOLOCK)   
    INNER JOIN [VCP_DISEASE] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[VCP_DISEASE].[OutbreakWorkFlowDR]    
    INNER JOIN [V_CODEPROPERTY] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[V_CODEPROPERTY].[SUBJCODE_ID]  
    WHERE  [VCP_DISEASE].[SUBJCODE_ID] = @INTDISEASEDR AND [V_CODEPROPERTY].[PROPERTY] = 'WSF_ROWID'  
    ORDER  BY [V_CODEPROPERTY].[VALUEINT] DESC)  
   END  
--SugannyaB CMR 11.0.0.1 Issue#104370  For verifying Animal Report Records
  ELSE IF @PR_TYPE_Code = 'AR' AND @INT_OtherWorkFlowID >0  
   BEGIN  
    SET @OUTPUT = (SELECT  TOP 1 CASE WHEN VALUECODE_ID=@INTSTATUSDR THEN 1 ELSE 0 END   
    FROM [V_UNIFIEDCODESET] (NOLOCK)   
    INNER JOIN [VCP_DISEASE] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[VCP_DISEASE].[AnimalReportWorkflowDR]    
    INNER JOIN [V_CODEPROPERTY] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[V_CODEPROPERTY].[SUBJCODE_ID]  
    WHERE  [VCP_DISEASE].[SUBJCODE_ID] = @INTDISEASEDR AND [V_CODEPROPERTY].[PROPERTY] = 'WSF_ROWID'  
    ORDER  BY [V_CODEPROPERTY].[VALUEINT] DESC)  
   END 
   ELSE IF @PR_TYPE_Code = 'GE' AND @INT_OtherWorkFlowID >0  
   BEGIN  
    SET @OUTPUT = (SELECT  TOP 1 CASE WHEN VALUECODE_ID=@INTSTATUSDR THEN 1 ELSE 0 END   
    FROM [V_UNIFIEDCODESET] (NOLOCK)   
    INNER JOIN [VCP_GroupEventType] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[VCP_GroupEventType].WorkFlowDR    
    INNER JOIN [V_CODEPROPERTY] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[V_CODEPROPERTY].[SUBJCODE_ID]  
    WHERE  [VCP_GroupEventType].[SUBJCODE_ID] = @INTDISEASEDR AND [V_CODEPROPERTY].[PROPERTY] = 'WSF_ROWID'  
    ORDER  BY [V_CODEPROPERTY].[VALUEINT] DESC)  
   END   
  ELSE  
   BEGIN  
    SET @OUTPUT = (SELECT  TOP 1 CASE WHEN VALUECODE_ID=@INTSTATUSDR THEN 1 ELSE 0 END   
     FROM [V_UNIFIEDCODESET] (NOLOCK)   
     INNER JOIN [VCP_DISEASE] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[VCP_DISEASE].[WORKFLOWCODE_ID]   
    INNER JOIN [V_CODEPROPERTY] (NOLOCK) ON  [V_UNIFIEDCODESET].[ID]=[V_CODEPROPERTY].[SUBJCODE_ID]  
    WHERE  [VCP_DISEASE].[SUBJCODE_ID] = @INTDISEASEDR AND [V_CODEPROPERTY].[PROPERTY] = 'WSF_ROWID'   
    ORDER BY [V_CODEPROPERTY].[VALUEINT] DESC)  
   END    
     
 END  
 RETURN @OUTPUT  
END  

