
CREATE FUNCTION [dbo].[GetDeletedPHPersonalRecordIDsByUDFieldFilter]
(
	@UDSectionID INT,
	@UDFieldID INT,
	@UDFieldValue VARCHAR(MAX),
	@UDFieldType VARCHAR(2),
	@RecordActID INT ,
	@UserDR INT
)
RETURNS @tblPHRecordIDs TABLE 
(
	RecordID Int
)
AS
BEGIN
Declare @UDFieldValue_UCSID INT
	IF @RecordActID = -1 
		SET @RecordActID = -2147483648
		
	IF @UDFieldType = '10'
		SET @UDFieldValue_UCSID = -1
	ELSE
		SET @UDFieldValue_UCSID = Cast(@UDFieldValue AS INT)

			--Normal Form
			INSERT INTO @tblPHRecordIDs
			
			SELECT DVPR_ROWID FROM DV_PHDeletedPersonalRecord (NOLOCK)
				INNER JOIN A_ACTRELATIONSHIP ACTREL (NOLOCK) ON DV_PHDeletedPersonalRecord.DVPR_ROWID = ACTREL.SOURCE_ID AND ACTREL.TYPECODE='COMP'
				INNER JOIN A_ACT A_UDFORM (NOLOCK) ON ACTREL.TARGET_ID = A_UDFORM.ID AND A_UDFORM.CLASSCODE='DOCBODY'
				INNER JOIN A_ACT A_UDSECT (NOLOCK) ON A_UDFORM.ID = A_UDSECT.ACT_PARENT_ID AND A_UDSECT.CLASSCODE='DOCSECT' AND A_UDSECT.CODE_ID = @UDSectionID
				INNER JOIN AX_UDFVALUES (NOLOCK) ON A_UDSECT.ID = AX_UDFVALUES.ACT_PARENT_ID AND AX_UDFVALUES.METACODE_UCSID = @UDFieldID	
			WHERE
			(
				(@RecordActID =-2147483648 OR DV_PHDeletedPersonalRecord.DVPR_ROWID = @RecordActID)
				AND
				(
					(@UDFieldType='10' AND AX_UDFVALUES.VALUESTRING = @UDFieldValue)
					OR
					(@UDFieldType <> '10' AND (AX_UDFVALUES.VALUE_UCSID = @UDFieldValue_UCSID))
				)
				
			)
			
			UNION
					
			--Add-On UDSection and Shared Record Section			
			SELECT DVPR_ROWID FROM DV_PHDeletedPersonalRecord (NOLOCK)
				INNER JOIN A_ACTRELATIONSHIP ACTREL (NOLOCK) ON DV_PHDeletedPersonalRecord.DVPR_ROWID = ACTREL.SOURCE_ID AND ACTREL.TYPECODE='COMP'
				INNER JOIN A_ACT A_UDSECT (NOLOCK) ON ACTREL.TARGET_ID = A_UDSECT.ID AND A_UDSECT.CLASSCODE='DOCSECT'  AND A_UDSECT.CODE_ID = @UDSectionID
				INNER JOIN AX_UDFVALUES (NOLOCK) ON A_UDSECT.ID = AX_UDFVALUES.ACT_PARENT_ID	AND AX_UDFVALUES.METACODE_UCSID = @UDFieldID
			WHERE 
			(
				(@RecordActID =-2147483648 OR DV_PHDeletedPersonalRecord.DVPR_ROWID = @RecordActID)
				AND
				(
					(@UDFieldType='10' AND AX_UDFVALUES.VALUESTRING = @UDFieldValue)
					OR
					(@UDFieldType <> '10' AND (AX_UDFVALUES.VALUE_UCSID = @UDFieldValue_UCSID))
				)
				
			)
			
			UNION
					
			--Add-On UDSection and Shared Person Section
			SELECT DVPR_ROWID FROM DV_PHDeletedPersonalRecord (NOLOCK)
				INNER JOIN A_Act CASEACT (NOLOCK) ON DV_PHDeletedPersonalRecord.DVPR_RowID = CASEACT.ID
				INNER JOIN A_ACTRELATIONSHIP ACTREL (NOLOCK) ON CASEACT.ACT_PARENT_ID = ACTREL.SOURCE_ID AND ACTREL.TYPECODE='COMP'
				INNER JOIN A_ACT A_UDSECT (NOLOCK) ON ACTREL.TARGET_ID = A_UDSECT.ID AND A_UDSECT.CLASSCODE='DOCSECT' AND A_UDSECT.CODE_ID = @UDSectionID
				INNER JOIN AX_UDFVALUES (NOLOCK) ON A_UDSECT.ID = AX_UDFVALUES.ACT_PARENT_ID	AND AX_UDFVALUES.METACODE_UCSID = @UDFieldID
			WHERE 
			(
				(@RecordActID =-2147483648 OR DV_PHDeletedPersonalRecord.DVPR_ROWID = @RecordActID)
				AND
				(
					(@UDFieldType='10' AND AX_UDFVALUES.VALUESTRING = @UDFieldValue)
					OR
					(@UDFieldType <> '10' AND (AX_UDFVALUES.VALUE_UCSID = @UDFieldValue_UCSID))
				)
				
			)
			
			UNION
			
			SELECT DVPR_ROWID FROM DV_PHDeletedPersonalRecord (NOLOCK)
				WHERE DVPR_USERDR = @UserDR AND (@RecordActID =-2147483648 OR DV_PHDeletedPersonalRecord.DVPR_ROWID = @RecordActID)

RETURN
END

