CREATE FUNCTION [dbo].[GetImportedRecordIDsByUDFieldFilter]  
(  
 @UDSectionID INT,  
 @UDFieldID INT,  
 @UDFieldValue VARCHAR(MAX),  
 @UDFieldType VARCHAR(2),  
 @RecordActID INT ,  
 @RecordType VARCHAR(MAX),  
 @UserDR INT  
)  
RETURNS @tblPHRecordIDs TABLE   
(  
 RecordID Int  
)  
AS  
BEGIN  
DECLARE @UDFieldValue_UCSID INT  
 IF @RecordActID = -1   
  SET @RecordActID = -2147483648  
	
 IF @UDFieldType = '10'  
  SET @UDFieldValue_UCSID = -1  
 ELSE  
  SET @UDFieldValue_UCSID = Cast(@UDFieldValue AS INT)  

IF @RecordType = 'Personal Record' OR @RecordType = ''  
	BEGIN
		--Normal Form
		INSERT INTO @tblPHRecordIDs
		SELECT PHCASE.ID FROM	A_ACT PHCASE (NOLOCK)
			INNER JOIN A_ACT FOLDER (NOLOCK) ON FOLDER.ID=PHCASE.ACT_PARENT_ID AND FOLDER.CLASSCODE='FOLDER'
			INNER JOIN P_PARTICIPATION (NOLOCK) ON P_PARTICIPATION.ACT_ID=FOLDER.ID AND P_PARTICIPATION.TYPECODE='SBJ' 
			INNER JOIN R_ROLE PATROLE (NOLOCK) ON PATROLE.ID=P_PARTICIPATION.ROLE_ID AND PATROLE.CLASSCODE='PAT'	AND PATROLE.statusCode <> 'nullified' AND PATROLE.statusCode <> 'terminated'
			INNER JOIN A_ACTRELATIONSHIP ACTREL (NOLOCK) ON PHCASE.ID = ACTREL.SOURCE_ID AND ACTREL.TYPECODE='COMP'	    
			INNER JOIN A_ACT A_UDFORM (NOLOCK) ON ACTREL.TARGET_ID = A_UDFORM.ID AND A_UDFORM.CLASSCODE='DOCBODY'  
			INNER JOIN A_ACT A_UDSECT (NOLOCK) ON A_UDFORM.ID = A_UDSECT.ACT_PARENT_ID AND A_UDSECT.CLASSCODE='DOCSECT' AND A_UDSECT.CODE_ID = @UDSectionID  
			INNER JOIN AX_UDFVALUES (NOLOCK) ON A_UDSECT.ID = AX_UDFVALUES.ACT_PARENT_ID AND AX_UDFVALUES.METACODE_UCSID = @UDFieldID   
		WHERE  
			(
				(@RecordActID =-2147483648 OR PHCASE.ID = @RecordActID)  
				AND((@UDFieldType='10' AND AX_UDFVALUES.VALUESTRING = @UDFieldValue)OR(@UDFieldType <> '10' 
				AND (AX_UDFVALUES.VALUE_UCSID = @UDFieldValue_UCSID)))
			)
		UNION
		--Add-On UDSection and Shared Record Section   	  
		SELECT PHCASE.ID FROM A_ACT PHCASE  (NOLOCK)
			INNER JOIN A_ACT FOLDER (NOLOCK) ON FOLDER.ID=PHCASE.ACT_PARENT_ID AND FOLDER.CLASSCODE='FOLDER' 
			INNER JOIN P_PARTICIPATION (NOLOCK) ON P_PARTICIPATION.ACT_ID=FOLDER.ID AND P_PARTICIPATION.TYPECODE='SBJ' 
			INNER JOIN R_ROLE PATROLE (NOLOCK) ON PATROLE.ID=P_PARTICIPATION.ROLE_ID AND PATROLE.CLASSCODE='PAT'	AND PATROLE.statusCode <> 'nullified' AND PATROLE.statusCode <> 'terminated'
			INNER JOIN A_ACTRELATIONSHIP ACTREL (NOLOCK) ON PHCASE.ID = ACTREL.SOURCE_ID AND ACTREL.TYPECODE='COMP'  
			INNER JOIN A_ACT A_UDSECT (NOLOCK) ON ACTREL.TARGET_ID = A_UDSECT.ID AND A_UDSECT.CLASSCODE='DOCSECT'  AND A_UDSECT.CODE_ID = @UDSectionID  
			INNER JOIN AX_UDFVALUES (NOLOCK) ON A_UDSECT.ID = AX_UDFVALUES.ACT_PARENT_ID AND AX_UDFVALUES.METACODE_UCSID = @UDFieldID  
		WHERE   
			(  
				(@RecordActID =-2147483648 OR PHCASE.ID = @RecordActID)AND  
				((@UDFieldType='10' AND AX_UDFVALUES.VALUESTRING = @UDFieldValue) OR  
				 (@UDFieldType <> '10' AND (AX_UDFVALUES.VALUE_UCSID = @UDFieldValue_UCSID)))       
			)
	UNION  
		SELECT PHCASE.ID FROM A_ACT PHCASE  (NOLOCK)
			INNER JOIN A_ACT FOLDER (NOLOCK) ON FOLDER.ID=PHCASE.ACT_PARENT_ID AND FOLDER.CLASSCODE='FOLDER' 
			INNER JOIN P_PARTICIPATION (NOLOCK) ON P_PARTICIPATION.ACT_ID=FOLDER.ID AND P_PARTICIPATION.TYPECODE='AUT' 
			INNER JOIN R_ROLE PATROLE (NOLOCK) ON PATROLE.ID=P_PARTICIPATION.ROLE_ID AND PATROLE.CLASSCODE='PAT' AND PATROLE.statusCode <> 'nullified' AND PATROLE.statusCode <> 'terminated'	
		WHERE PATROLE.PLAYER_ID = @UserDR AND (@RecordActID =-2147483648 OR PHCASE.ID = @RecordActID)
	END
RETURN
END

