--BLK Function created to get the Linked DI Folder and Section ID
CREATE FUNCTION [dbo].[GetLinkedDIFolderAndSectionID]()
RETURNS @DIFOLDERANDSECTIONTABLE TABLE  
(  
    PHCASEID  INT,  
    LINKEDACTID  INT,
    LINKEDCIID INT,
    CONTACTSECDEFID  INT
)  
AS  
BEGIN --BLK BEGIN FUNCTION
  DECLARE @INDISID AS INT
  DECLARE @CIADDONSECTIONID AS INT                  
    SET @INDISID = (
    SELECT TOP 1 UCS.ID FROM [V_UNIFIEDCODESET] UCS (NOLOCK)
    INNER JOIN V_DOMAIN UCSDOMAIN (NOLOCK) ON  UCSDOMAIN.ID=[UCS].[DOMAIN_ID]      AND  UCSDOMAIN.DOMAINNAME = 'APPFORM' 
    WHERE  UCS.[CONCEPTCODE] = 'INDIS')

    DECLARE @DIFOLDERANDSECTIONTABLE_TMP TABLE  
    (  
        PHCASEID  INT,  
        LINKEDACTID  INT,
        LINKEDCIID INT,
        CONTACTSECDEFID  INT
    ) 

    INSERT @DIFOLDERANDSECTIONTABLE_TMP  
    SELECT 
    [LPA_D1].[DVPR_ROWID] AS [PHCASEID],
    [LPA_D4].[ID] AS [LINKEDACTID],
    [LPA_C3].[DVPR_ROWID] AS [LINKEDCIID],
    ISNULL([LPA_C5].[CONTACTSUDSECTIONCODE_ID],0) AS [CONTACTSECDEFID]
    FROM (((( [DV_PHPERSONALRECORD] [LPA_D1] (NOLOCK) 
    INNER JOIN [A_ACTRELATIONSHIP] [LPA_A2] (NOLOCK) ON  [LPA_D1].[DVPR_ROWID]=[LPA_A2].[SOURCE_ID] AND ( ( [LPA_A2].[TYPECODE] = 'DRIV' AND [LPA_A2].[METACODE] = 'PR_INCIDENTDR' AND [LPA_A2].[TYPECODE_ORTX] = 'CREATE INCIDENT'))) 
    INNER JOIN [DV_PHPERSONALRECORD] [LPA_C3] (NOLOCK) ON  [LPA_C3].[DVPR_ROWID]=[LPA_A2].[TARGET_ID]) 
    INNER JOIN [A_ACT] [LPA_D4] (NOLOCK) ON  [LPA_C3].[DVPR_ROWID]=[LPA_D4].[ACT_PARENT_ID] AND ( ( [LPA_D4].[CLASSCODE] = 'DOCBODY' AND [LPA_D4].[CODE_ID] = @INDISID))) 
    INNER JOIN [VCP_DISEASE] [LPA_C5] (NOLOCK) ON  [LPA_C3].[DVPR_DISEASECODE_ID]=[LPA_C5].[SUBJCODE_ID]) 
     

    INSERT @DIFOLDERANDSECTIONTABLE  
    SELECT
    [LINKEDCI].[PHCASEID] AS [PHCASEID], 
    [LPA_F3].[ID] AS LINKEDACTID,
    NULL AS LINKEDCIID,
    ISNULL([LPA_D7].[CONTACTSUDSECTIONCODE_ID],0) AS [CONTACTSECDEFID]
    FROM ((((((( [P_PARTICIPATION] (NOLOCK)
    INNER JOIN 
    (
        SELECT [PHCASEID],[LINKEDCIID] FROM @DIFOLDERANDSECTIONTABLE_TMP 
                    
    ) AS LINKEDCI ON [P_PARTICIPATION].ACT_ID=[LINKEDCI].[LINKEDCIID] AND [P_PARTICIPATION].[METACODE] = 'RLENT_PERSONALRECORDDR'            
    INNER JOIN [R_ROLE] [LPA_M1] (NOLOCK) ON [LPA_M1].[ID]=[P_PARTICIPATION].[ROLE_ID] AND (([LPA_M1].[CLASSCODE] = 'MBR')))
    INNER JOIN [P_PARTICIPATION] [LPA_S2] (NOLOCK) ON  [LPA_M1].[ID]=[LPA_S2].[ROLE_ID] AND ( ( [LPA_S2].[TYPECODE] = 'SBJ'))) 
    INNER JOIN [A_ACT] [LPA_F3] (NOLOCK) ON  [LPA_F3].[ID]=[LPA_S2].[ACT_ID] AND ( ( [LPA_F3].[CLASSCODE] = 'FOLDER'))) 
    INNER JOIN [R_ROLE] [LPA_E4] (NOLOCK) ON  [LPA_M1].[SCOPER_ID]=[LPA_E4].[PLAYER_ID] AND ( ( [LPA_E4].[CLASSCODE] = 'EXPR'))) 
    INNER JOIN [P_PARTICIPATION] [LPA_I5] (NOLOCK) ON  [LPA_E4].[ID]=[LPA_I5].[ROLE_ID] AND ( ( [LPA_I5].[TYPECODE] = 'IND'))) 
    INNER JOIN [DV_PHPERSONALRECORD] [LPA_C6] (NOLOCK) ON  [LPA_C6].[DVPR_ROWID]=[LPA_I5].[ACT_ID]) 
    INNER JOIN [VCP_DISEASE] [LPA_D7] (NOLOCK) ON  [LPA_C6].[DVPR_DISEASECODE_ID]=[LPA_D7].[SUBJCODE_ID]) 
     

    --GET THE LINKED CONTACT INVESTIGATION DOCBODY AND ADDONSECTION ID
    INSERT @DIFOLDERANDSECTIONTABLE  
    SELECT 
    TMP1.[PHCASEID],
    TMP1.[LINKEDACTID],
    TMP1.[LINKEDCIID],
    TMP1.[CONTACTSECDEFID]
    FROM @DIFOLDERANDSECTIONTABLE_TMP TMP1
    LEFT JOIN @DIFOLDERANDSECTIONTABLE TMP ON TMP.PHCASEID = TMP1.PHCASEID  AND TMP.[CONTACTSECDEFID]=TMP1. [CONTACTSECDEFID]
    WHERE TMP.PHCASEID IS NULL  
    --GET THE CONTACT FOLDER AND ADDONSECTION ID LINKED WITH THE CI

    
--GET THE CONTACT FOLDER AND ADDONSECTION ID LINKED WITH THE DI
     
    INSERT @DIFOLDERANDSECTIONTABLE  
    SELECT
    [P_PARTICIPATION].[ACT_ID] AS [PHCASEID],
    [LPA_F3].[ID] AS LINKEDACTID,
    NULL AS LINKEDCIID,
    ISNULL([LPA_D7].[CONTACTSUDSECTIONCODE_ID],0) AS [CONTACTSECDEFID]
    FROM ((((((( 
    [R_ROLE] [LPA_M1] (NOLOCK) 
    INNER JOIN [P_PARTICIPATION] (NOLOCK) ON  [LPA_M1].[ID]=[P_PARTICIPATION].[ROLE_ID] AND ( ( [LPA_M1].[CLASSCODE] = 'MBR'))) 
    INNER JOIN [P_PARTICIPATION] [LPA_S2] (NOLOCK) ON  [LPA_M1].[ID]=[LPA_S2].[ROLE_ID] AND ( ( [LPA_S2].[TYPECODE] = 'SBJ'))) 
    INNER JOIN [A_ACT] [LPA_F3] (NOLOCK) ON  [LPA_F3].[ID]=[LPA_S2].[ACT_ID] AND ( ( [LPA_F3].[CLASSCODE] = 'FOLDER'))) 
    INNER JOIN [R_ROLE] [LPA_E4] (NOLOCK) ON  [LPA_M1].[SCOPER_ID]=[LPA_E4].[PLAYER_ID] AND ( ( [LPA_E4].[CLASSCODE] = 'EXPR'))) 
    INNER JOIN [P_PARTICIPATION] [LPA_I5] (NOLOCK) ON  [LPA_E4].[ID]=[LPA_I5].[ROLE_ID] AND ( ( [LPA_I5].[TYPECODE] = 'IND'))) 
    INNER JOIN [DV_PHPERSONALRECORD] [LPA_C6] (NOLOCK) ON  [LPA_C6].[DVPR_ROWID]=[LPA_I5].[ACT_ID]) 
    INNER JOIN [VCP_DISEASE] [LPA_D7] (NOLOCK) ON  [LPA_C6].[DVPR_DISEASECODE_ID]=[LPA_D7].[SUBJCODE_ID]) 
    LEFT JOIN @DIFOLDERANDSECTIONTABLE TMP ON TMP.PHCASEID = [P_PARTICIPATION].[ACT_ID]
    WHERE ( ( [P_PARTICIPATION].[METACODE] = 'PR_CONTACTSUBJECTDR')) AND TMP.PHCASEID IS NULL  
      

 RETURN 
END 

