
--BLK Function created to get the Linked CI Folder and Section ID
CREATE  FUNCTION [dbo].[GetLinkedCIFolderAndSectionID]()
RETURNS @CIFOLDERANDSECTIONTABLE TABLE  
(  
    PHCASEID  INT,
    LINKEDACTID  INT,
    LINKEDCIID INT,
    CONTACTSECDEFID  INT, 
    CIADDONSECTIONID INT 
)  
AS  
BEGIN --BLK BEGIN FUNCTION
    DECLARE @INDISID AS INT
    DECLARE @CIADDONSECTIONID AS INT
    SET @INDISID = (
    SELECT TOP 1 UCS.ID FROM [V_UNIFIEDCODESET] UCS  (NOLOCK)
    INNER JOIN V_DOMAIN UCSDOMAIN (NOLOCK) ON  UCSDOMAIN.ID=[UCS].[DOMAIN_ID] AND  UCSDOMAIN.DOMAINNAME = 'APPFORM' 
    WHERE  UCS.[CONCEPTCODE] = 'INDIS')

    --GET THE LINKED CONTACT FOLDER AND ADDONSECTION ID
    INSERT @CIFOLDERANDSECTIONTABLE  
    SELECT [P_PARTICIPATION].[ACT_ID] AS PHCASEID, 
    [LPA_F3].[ID] AS LINKEDACTID,
    NULL AS LINKEDCIID,
    ISNULL([LPA_D7].[CONTACTSUDSECTIONCODE_ID],0) AS [CONTACTSECDEFID], 
    ISNULL([LPA_F9].[CONTACTSUDSECTIONCODE_ID],0) AS [CIADDONSECTIONID]  
    FROM ((((((((( [P_PARTICIPATION] (NOLOCK) 
    INNER JOIN [R_ROLE] [LPA_M1] (NOLOCK) ON  [P_PARTICIPATION].[ROLE_ID]=[LPA_M1].[ID] AND ( ( [LPA_M1].[CLASSCODE] = 'MBR'))) 
    INNER JOIN [P_PARTICIPATION] [LPA_S2] (NOLOCK) ON  [LPA_M1].[ID]=[LPA_S2].[ROLE_ID] AND ( ( [LPA_S2].[TYPECODE] = 'SBJ'))) 
    INNER JOIN [A_ACT] [LPA_F3] (NOLOCK) ON  [LPA_F3].[ID]=[LPA_S2].[ACT_ID] AND ( ( [LPA_F3].[CLASSCODE] = 'FOLDER'))) 
    INNER JOIN [R_ROLE] [LPA_E4] (NOLOCK) ON  [LPA_M1].[SCOPER_ID]=[LPA_E4].[PLAYER_ID] AND ( ( [LPA_E4].[CLASSCODE] = 'EXPR'))) 
    INNER JOIN [P_PARTICIPATION] [LPA_I5] (NOLOCK) ON  [LPA_E4].[ID]=[LPA_I5].[ROLE_ID] AND ( ( [LPA_I5].[TYPECODE] = 'IND'))) 
    INNER JOIN [DV_PHPERSONALRECORD] [LPA_C6] (NOLOCK) ON  [LPA_C6].[DVPR_ROWID]=[LPA_I5].[ACT_ID]) 
    INNER JOIN [VCP_DISEASE] [LPA_D7] (NOLOCK) ON  [LPA_C6].[DVPR_DISEASECODE_ID]=[LPA_D7].[SUBJCODE_ID]) 
    INNER JOIN [A_ACT] [LPA_E8] (NOLOCK) ON  [P_PARTICIPATION].[ACT_ID]=[LPA_E8].[ID]) 
    INNER JOIN [VCP_DISEASE] [LPA_F9] (NOLOCK) ON  [LPA_E8].[CODE_ID]=[LPA_F9].[SUBJCODE_ID]) 
    WHERE ( ( [P_PARTICIPATION].[METACODE] = 'RLENT_PERSONALRECORDDR'))
    --GET THE LINKED CONTACT INVESTIGATION ADDONSECTION ID
    INSERT @CIFOLDERANDSECTIONTABLE 
    SELECT 
    DOCBODYACT.ACT_PARENT_ID AS PHCASEID, 
    DOCBODYACT.ID AS LINKEDACTID,
    NULL AS LINKEDCIID,
    ISNULL(@CIADDONSECTIONID,0) AS [CONTACTSECDEFID], 
    ISNULL(A.CIADDONSECTIONID,0) AS [CIADDONSECTIONID] 
    FROM A_ACT DOCBODYACT (NOLOCK) 
    INNER JOIN 
    (
        SELECT PHCASEID,CIADDONSECTIONID  FROM @CIFOLDERANDSECTIONTABLE 
        WHERE [CONTACTSECDEFID] <> 0 AND [CIADDONSECTIONID] <> 0 AND [CONTACTSECDEFID] <> [CIADDONSECTIONID]
    ) AS A ON DOCBODYACT.ACT_PARENT_ID=A.PHCASEID 
        WHERE DOCBODYACT.CLASSCODE='DOCBODY' AND DOCBODYACT.CODE_ID=@INDISID
    --GET THE INDIVIDUAL CONTACT INVESTIGATION ADDONSECTION ID 
    INSERT @CIFOLDERANDSECTIONTABLE 
    SELECT 
    DOCBODYACT.ACT_PARENT_ID AS PHCASEID, 
    DOCBODYACT.ID AS LINKEDACTID,
    NULL AS LINKEDCIID,
    0 AS [CONTACTSECDEFID], 
    ISNULL([DISCONTADDON].[CONTACTSUDSECTIONCODE_ID],0) AS [CIADDONSECTIONID] 
    FROM A_ACT DOCBODYACT (NOLOCK)  
    INNER JOIN [A_ACTRELATIONSHIP] [ACTREL] (NOLOCK) ON [ACTREL].[SOURCE_ID] = [DOCBODYACT].[ID]
    INNER JOIN [A_ACT] [ACTUDSECTION] (NOLOCK) ON [ACTUDSECTION].[ID] = [ACTREL].[TARGET_ID]
    INNER JOIN [DV_PHPERSONALRECORD][CASEACT] (NOLOCK) ON DOCBODYACT.ACT_PARENT_ID = [CASEACT].[DVPR_ROWID]
    INNER JOIN [VCP_DISEASE][DISCONTADDON] (NOLOCK) ON [CASEACT].[DVPR_DISEASECODE_ID] = [DISCONTADDON].[SUBJCODE_ID] AND [DISCONTADDON].[CONTACTSUDSECTIONCODE_ID] = [ACTUDSECTION].[CODE_ID]
    LEFT JOIN @CIFOLDERANDSECTIONTABLE TMP ON TMP.PHCASEID = DOCBODYACT.ACT_PARENT_ID  
    WHERE DOCBODYACT.CLASSCODE='DOCBODY' AND DOCBODYACT.CODE_ID=@INDISID AND TMP.PHCASEID IS NULL

    
 RETURN 
END

