CREATE FUNCTION [dbo].[MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID]
(@PSNENTITYID INT, @METACODE VARCHAR(100), @ADDRESSPART VARCHAR(50), @USECODE VARCHAR(50))
RETURNS VARCHAR(100)
AS
BEGIN

RETURN
	   (
	   SELECT      
					CASE @ADDRESSPART
						WHEN 'PARTSAL'			THEN T_ENTITYADDRESS.PARTSAL 
						WHEN 'PARTCTY'		THEN T_ENTITYADDRESS.PARTCTY 
						WHEN 'PARTSTA'			THEN T_ENTITYADDRESS.PARTSTA 
						WHEN 'PARTZIP'		THEN T_ENTITYADDRESS.PARTZIP 
						
					END
		FROM  R_ROLE R (NOLOCK) 
INNER JOIN T_ENTITYADDRESS (NOLOCK) ON R.SCOPER_ID=ENTITY_ID AND USECODE=@USECODE and R.PLAYER_ID = @PSNENTITYID  AND R.CLASSCODE = 'LOCE' AND R.METACODE = @METACODE AND STATUSCODE<>'NULLIFIED'
		)
END
