
CREATE FUNCTION [DBO].[MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYADDRESSID]  
(@ENTITYADDRID INT, @NAME VARCHAR(50))  
RETURNS INT 
AS  
BEGIN  
RETURN (  
SELECT        
T_ATTRIBUTE.VALUEINTEGER 
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITYADDRESS_ID = @ENTITYADDRID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
