
CREATE FUNCTION [DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS BIT
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUEBOOL'  THEN  VALUEBOOL
WHEN 'ISVALUENULL' THEN ISVALUENULL 
END  
FROM A_ACT  (NOLOCK)
WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
)  
END  
