
CREATE FUNCTION [dbo].[MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE]    
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @ISMONTH BIT)    
RETURNS NVARCHAR(MAX)  
AS    
BEGIN    
  
RETURN (    
SELECT
CASE WHEN @ISMONTH  = 1 THEN
	CASE WHEN SUBSTRING(EFFECTIVETIME_TXT, 5, 2) = '00' THEN ''
		 ELSE SUBSTRING(EFFECTIVETIME_TXT, 5, 2)   
	END
ELSE
	CASE WHEN SUBSTRING(EFFECTIVETIME_TXT, 1, 4) = '0000' THEN ''
		 ELSE SUBSTRING(EFFECTIVETIME_TXT, 1, 4)   
	END		
END

FROM A_ACT  (NOLOCK)  
WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID) AND (EFFECTIVETIME_TXT IS NOT NULL) 
)    
END    

