
CREATE FUNCTION [dbo].[MDF_ATTR_GETVALUECODEID_ENTATTR_BYACTID]  
	(@ACTID INT,  @NAME VARCHAR(50))  
	RETURNS INT
AS  
BEGIN  
		RETURN (SELECT TOP 1 T_ATTRIBUTE.VALUECODE_ID
		FROM   T_ATTRIBUTE (NOLOCK)
			WHERE (T_ATTRIBUTE.ACT_ID = @ACTID AND T_ATTRIBUTE.[NAME] = @NAME))
END  

