
CREATE FUNCTION [DBO].[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS DATETIME  
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUETS'   THEN VALUETS 
WHEN 'VALUETSEND'  THEN VALUETSEND 
WHEN 'EFFECTIVETIME_BEG' THEN EFFECTIVETIME_BEG 
WHEN 'EFFECTIVETIME_END' THEN EFFECTIVETIME_END 
END  
FROM A_ACT  (NOLOCK)
WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
)  
END  
