
CREATE FUNCTION [DBO].[MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID]  
(@ENTITYID INT, @NAME VARCHAR(50))  
RETURNS INT
AS  
BEGIN  

RETURN (  
SELECT        
T_ATTRIBUTE.VALUEINTEGER 
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITY_ID = @ENTITYID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END
