
CREATE FUNCTION [DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYADDRESSID]  
(@ENTITYADDRID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))  
RETURNS VARCHAR
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUESTRING'  THEN T_ATTRIBUTE.VALUESTRING 
WHEN 'VALUESTRING_TXT' THEN T_ATTRIBUTE.VALUESTRING_TXT 
WHEN 'VALUECODE_ORTX' THEN T_ATTRIBUTE.VALUECODE_ORTX 
END  
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITYADDRESS_ID = @ENTITYADDRID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
