
CREATE FUNCTION [DBO].[MDF_ATTR_GETDATEVALUE_ENTATTR_BYROLEID]  
(@ROLEID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))  
RETURNS DATETIME  
AS  
BEGIN  

	RETURN (  
		SELECT        
			CASE @VALUETYPE   
				WHEN 'VALUETS'   THEN T_ATTRIBUTE.VALUETS 
				WHEN 'VALUETSEND'  THEN T_ATTRIBUTE.VALUETSEND 
			END  
		FROM      T_ATTRIBUTE (NOLOCK)
		WHERE     (T_ATTRIBUTE.ROLE_ID = @ROLEID AND T_ATTRIBUTE.[NAME] = @NAME)  
	)  
END  
