
CREATE FUNCTION [DBO].[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS REAL  
AS  
BEGIN  

	RETURN (  
		SELECT        
			CASE @VALUETYPE  
				WHEN 'VALUEREAL'  THEN CAST( VALUEREAL AS REAL)  
				WHEN 'VALUENUMERATOR' THEN CAST( VALUENUMERATOR AS REAL)  
				WHEN 'VALUEDENOMINATOR' THEN CAST( VALUEDENOMINATOR AS REAL)  
				WHEN 'EFFECTIVETIME_DUR' THEN CAST( EFFECTIVETIME_DUR AS REAL)    
			ELSE NULL   
			END  
		FROM         A_ACT  (NOLOCK)
		WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
	)  
END  
