
CREATE FUNCTION [DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYENTITYID]  
(@ENTITYID INT, @NAME VARCHAR(50))  
RETURNS BIT
AS  
BEGIN  

RETURN (  
SELECT        
T_ATTRIBUTE.VALUEBOOL 
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITY_ID = @ENTITYID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END
