
CREATE FUNCTION [dbo].[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID]
(@ACTID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))
	RETURNS VARCHAR(8000)
AS
BEGIN
	RETURN	(
	SELECT TOP 1   
		CASE @VALUETYPE
			WHEN 'VALUESTRING'		THEN T_ATTRIBUTE.VALUESTRING 
			WHEN 'VALUESTRING_TXT'	THEN T_ATTRIBUTE.VALUESTRING_TXT
			WHEN 'VALUESTRING_CODE' THEN T_ATTRIBUTE.VALUESTRING_CODE  
		END
	FROM T_ATTRIBUTE  (NOLOCK) 
	WHERE T_ATTRIBUTE.ACT_ID = @ACTID AND T_ATTRIBUTE.[NAME] = @NAME
	)
END
