
CREATE FUNCTION [dbo].[MDF_ENTLOCNAME_ENTITY_BYPSNENTITYID]
(@PSNENTITYID INT,@METACODE VARCHAR(100),@USECODE VARCHAR(50))  
RETURNS VARCHAR(250)  
AS
BEGIN

RETURN
	   (
	   SELECT   ENTNAME.TRIVIALNAME     
		FROM  R_ROLE R (NOLOCK) 
		INNER JOIN  T_ENTITYNAME ENTNAME (NOLOCK) on 
		R.PLAYER_ID = @PSNENTITYID  AND R.CLASSCODE = 'LOCE' AND R.METACODE = @METACODE AND STATUSCODE<>'NULLIFIED' 
		AND ENTNAME.ENTITY_ID=R.SCOPER_ID AND ENTNAME.USECODE=@USECODE
		)
END

