CREATE FUNCTION [DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYROLEID]  
(@ROLEID INT,  @NAME VARCHAR(50))  
RETURNS BIT
AS  
BEGIN  

RETURN (  
SELECT        
T_ATTRIBUTE.VALUEBOOL 
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ROLE_ID = @ROLEID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
