
CREATE FUNCTION [DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS DATETIME  
AS  
BEGIN  

	RETURN (  
		SELECT        
			CASE @VALUETYPE   
				WHEN 'VALUETS'   THEN VALUETS   
				WHEN 'VALUETSEND'  THEN VALUETSEND   
				WHEN 'EFFECTIVETIME_BEG'THEN  EFFECTIVETIME_BEG  
				WHEN 'EFFECTIVETIME_END'THEN  EFFECTIVETIME_END 
				WHEN 'EFFECTIVETIME_END'THEN  EFFECTIVETIME_END 
				WHEN 'ACTIVITYTIME_END' THEN  ACTIVITYTIME_END
				WHEN 'ACTIVITYTIME_BEG' THEN  ACTIVITYTIME_BEG
				WHEN 'AVAILABILITYTIME' THEN  AVAILABILITYTIME
			END  
		FROM A_ACT  (NOLOCK)
		WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
	)  
END  
