
CREATE FUNCTION [dbo].[MDF_ATTR_GETVALUECODEID_ENTATTR_BYROLEID]  
	(@ROLEID INT,  @NAME VARCHAR(50))  
	RETURNS REAL
AS  
BEGIN  

RETURN (  
	SELECT TOP 1       
	T_ATTRIBUTE.VALUECODE_ID
	FROM   T_ATTRIBUTE (NOLOCK)
	WHERE (T_ATTRIBUTE.ROLE_ID = @ROLEID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
