
CREATE FUNCTION [dbo].[MDF_ATTR_GETSTRINGVALUE_ATTRUCS_BYENTITYADDRESSID]  
(@ENTITYADDRID INT, @NAME VARCHAR(50))  
RETURNS VARCHAR(255)  
AS  
BEGIN  

RETURN (  
SELECT    V_UNIFIEDCODESET.FULLNAME 
FROM      T_ATTRIBUTE (NOLOCK) 
			INNER JOIN V_UNIFIEDCODESET (NOLOCK) ON V_UNIFIEDCODESET.ID = T_ATTRIBUTE.VALUECODE_ID
WHERE     (T_ATTRIBUTE.ENTITYADDRESS_ID = @ENTITYADDRID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END

