
CREATE FUNCTION [DBO].[MDF_ATTR_GETDATETIMEVALUE_ENTATTR_BYENTITYADDRESSID]  
(@ENTITYADDRID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))  
RETURNS DATETIME
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUETS'   THEN T_ATTRIBUTE.VALUETS 
WHEN 'VALUETSEND'  THEN T_ATTRIBUTE.VALUETSEND 
END  
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITYADDRESS_ID = @ENTITYADDRID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
