
CREATE FUNCTION [dbo].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID]
(@ACTID INT,  @NAME VARCHAR(50))
RETURNS BIT
AS
BEGIN

RETURN	(
	SELECT      
		T_ATTRIBUTE.VALUEBOOL 
	FROM T_ATTRIBUTE  (NOLOCK) 
	WHERE T_ATTRIBUTE.ACT_ID = @ACTID AND T_ATTRIBUTE.[NAME] = @NAME
	)
END
