
CREATE FUNCTION [DBO].[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS INT
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUEINTEGER'  THEN VALUEINTEGER 
WHEN 'VALUECODE_ID'  THEN VALUECODE_ID
END  
FROM A_ACT  (NOLOCK)
WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
)  
END  
