CREATE FUNCTION [DBO].[MDF_ATTR_GETREALVALUE_ENTATTR_BYROLEID]  
(@ROLEID INT,  @NAME VARCHAR(50))  
RETURNS REAL
AS  
BEGIN  

RETURN (  
SELECT        
T_ATTRIBUTE.VALUEREAL 
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ROLE_ID = @ROLEID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  
