CREATE FUNCTION [DBO].[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]      
 (@CONCEPTCODE VARCHAR(50), @PARENT_ACTID INT, @ISRISKGROUP BIT)      
RETURNS BIT    
AS      
BEGIN      
	  
DECLARE @RETURNVALUE AS BIT ;  
SELECT @RETURNVALUE = ACT_ELE.VALUEBOOL 
  FROM V_UNIFIEDCODESET UCS (NOLOCK) 
  INNER JOIN V_DOMAIN (NOLOCK) ON UCS.DOMAIN_ID=V_DOMAIN.ID AND UCS.CONCEPTCODE=@CONCEPTCODE   
  INNER JOIN A_ACT ACT_ELE (NOLOCK) ON UCS.ID=ACT_ELE.CODE_ID AND ACT_ELE.ACT_PARENT_ID=@PARENT_ACTID 
  WHERE
	--THE EXPRESSION "IF A THEN B ELSE C" CAN BE WRITTEN IN THE FORM "((NOT A) OR B) AND (A OR C)"
	((@ISRISKGROUP <> 1) OR 
		(V_DOMAIN.DOMAINOID = '2.16.840.1.113883.3.33.4.2.2.5.734' AND 
		 V_DOMAIN.DOMAINNAME = 'ELIGIBILITYRISKGRP' AND 
		 ACT_ELE.METACODE = 'VISITGRP_RISKGRP')) 
	AND 
	((@ISRISKGROUP = 1) OR 
		(V_DOMAIN.DOMAINOID = '2.16.840.1.113883.3.33.4.2.2.5.733' AND 
		 V_DOMAIN.DOMAINNAME = 'ELIGIBILITYTARGETGRP' AND 
		 ACT_ELE.METACODE = 'VISITGRP_TARGETGRP'))
	
RETURN @RETURNVALUE    
END
