CREATE FUNCTION [DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]  
(@METACODE VARCHAR(50), @PARENT_ACTID INT, @VALUETYPE VARCHAR(100))  
RETURNS NVARCHAR(MAX)
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUESTRING'  THEN  VALUESTRING 
WHEN 'VALUESTRING_TXT' THEN  VALUESTRING_TXT   
WHEN 'TITLE'   THEN [TITLE] 
WHEN 'EFFECTIVETIME_TXT' THEN EFFECTIVETIME_TXT 
WHEN 'TEXT'    THEN CAST( [TEXT] AS NVARCHAR(MAX))  

END  
FROM A_ACT  (NOLOCK)
WHERE (METACODE = @METACODE) AND (ACT_PARENT_ID = @PARENT_ACTID)  
)  
END  
