
CREATE FUNCTION [DBO].[MDF_UCS_FULLNAME_OBSUCS_BYACTID]
(@ACTID INT, @VALUETYPE VARCHAR(100), @METACODE VARCHAR(100))
RETURNS VARCHAR(255)
AS
--THIS FUNCTION USES A CASE STATEMENT TO DETERMINE WHICH FIELD TO USE IN THE JOIN CLAUSE
BEGIN                    
	RETURN
		(               
			SELECT     V_UNIFIEDCODESET.FULLNAME
			FROM         A_ACT (NOLOCK)  INNER JOIN A_OBSERVATION (NOLOCK) ON A_OBSERVATION.ID=A_ACT.ID 
						 INNER JOIN  V_UNIFIEDCODESET (NOLOCK) ON 
							CASE @VALUETYPE
								WHEN 'INTERPRETATIONCODE_ID'					THEN A_OBSERVATION.INTERPRETATIONCODE_ID
								WHEN 'METHODCODE_ID'	THEN A_OBSERVATION.METHODCODE_ID
								WHEN 'TARGETSITECODE_ID'	THEN A_OBSERVATION.TARGETSITECODE_ID
							END
						= V_UNIFIEDCODESET.ID
			WHERE A_ACT.ID=@ACTID AND A_ACT.METACODE=@METACODE
		)
END
