
CREATE FUNCTION [DBO].[MDF_ENTITYNAME_GETVALUE_BYENTITYID]
(@ENTITYID INT,@USECODE VARCHAR(50),@VALUETYPE VARCHAR(50))
RETURNS VARCHAR(100)
AS
BEGIN

RETURN
	   (
		SELECT 
			CASE @VALUETYPE
				WHEN 'TRIVIALNAME' THEN ENTNAME.TRIVIALNAME
				WHEN 'PARTFAM' THEN ENTNAME.PARTFAM
				WHEN 'PARTGIV' THEN ENTNAME.PARTGIV
				WHEN 'PARTMID' THEN ENTNAME.PARTMID
				ELSE  CAST('INVALID VALUE TYPE' AS VARCHAR(100))  
			END 
				
		FROM 
			T_ENTITYNAME ENTNAME (NOLOCK)
		WHERE
			ENTNAME.ENTITY_ID=@ENTITYID AND ENTNAME.USECODE=@USECODE
		)
END
