
CREATE FUNCTION [DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE]
(@TRGACTID INT, @SRCACTMETACODE VARCHAR(50), @ACTRELTYPECODE VARCHAR(50), @VALUETYPE VARCHAR(100))
RETURNS DATETIME
AS
BEGIN

RETURN	(
		SELECT      
					CASE @VALUETYPE
						WHEN 'VALUETS'			THEN  ACT_SRC.VALUETS 
						WHEN 'VALUETSEND'		THEN  ACT_SRC.VALUETSEND 
						WHEN 'EFFECTIVETIME_BEG' THEN ACT_SRC.EFFECTIVETIME_BEG
						WHEN 'EFFECTIVETIME_END' THEN ACT_SRC.EFFECTIVETIME_END						
					END

		FROM        DBO.A_ACTRELATIONSHIP ACTREL (NOLOCK) 
					INNER JOIN DBO.A_ACT ACT_SRC (NOLOCK) ON  ACT_SRC.ID = ACTREL.SOURCE_ID AND ACT_SRC.METACODE = @SRCACTMETACODE 

		WHERE		ACTREL.TARGET_ID  = @TRGACTID AND ACTREL.TYPECODE = @ACTRELTYPECODE
		)

END
