
CREATE FUNCTION [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYROLEID]  
(@ROLEID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))  
RETURNS VARCHAR(8000)  
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUESTRING'  THEN T_ATTRIBUTE.VALUESTRING 
WHEN 'VALUESTRING_TXT' THEN T_ATTRIBUTE.VALUESTRING_TXT 
END  
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ROLE_ID = @ROLEID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  

