
CREATE FUNCTION [DBO].[MDF_UCS_FULLNAME_ACTUCS_BYACTID]
(@ACTID INT, @VALUETYPE VARCHAR(100))
RETURNS VARCHAR(255)
AS
--THIS FUNCTION USES A CASE STATEMENT TO DETERMINE WHICH FIELD TO USE IN THE JOIN CLAUSE
BEGIN                    
	RETURN
		(               
			SELECT     V_UNIFIEDCODESET.FULLNAME
			FROM         A_ACT (NOLOCK) INNER JOIN  V_UNIFIEDCODESET  (NOLOCK) ON 
							CASE @VALUETYPE
								WHEN 'CODE_ID'					THEN A_ACT.CODE_ID
								WHEN 'LANGUAGECODE_ID'			THEN A_ACT.LANGUAGECODE_ID
								WHEN 'CONFIDENTIALITYCODE_ID'	THEN A_ACT.CONFIDENTIALITYCODE_ID
								WHEN 'EFFECTIVETIME_FRQ_ID'		THEN A_ACT.EFFECTIVETIME_FRQ_ID
								WHEN 'PRIORITYCODE_ID'			THEN A_ACT.PRIORITYCODE_ID
								WHEN 'UNCERTAINTYCODE_ID'		THEN A_ACT.UNCERTAINTYCODE_ID
								WHEN 'VALUECODE_ID'				THEN A_ACT.VALUECODE_ID
						END
						= V_UNIFIEDCODESET.ID
			WHERE     (A_ACT.ID = @ACTID)
		)
END
