
CREATE FUNCTION [dbo].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID]  
(@ENTITYID INT, @VALUETYPE VARCHAR(100), @NAME VARCHAR(50))  
RETURNS VARCHAR(MAX) --SKUMAR IssueNbr:110418 08/09/2011
AS  
BEGIN  

RETURN (  
SELECT        
CASE @VALUETYPE  
WHEN 'VALUESTRING'  THEN T_ATTRIBUTE.VALUESTRING 
WHEN 'VALUESTRING_TXT' THEN T_ATTRIBUTE.VALUESTRING_TXT 
WHEN 'VALUECODE_ORTX' THEN T_ATTRIBUTE.VALUECODE_ORTX 
END  
FROM      T_ATTRIBUTE (NOLOCK)
WHERE     (T_ATTRIBUTE.ENTITY_ID = @ENTITYID AND T_ATTRIBUTE.[NAME] = @NAME)  
)  
END  

