CREATE FUNCTION [DBO].[ParmArrayStringToIntTable] (@INTVALPMARY VARCHAR(MAX))
RETURNS @VAL TABLE (INTVAL INT)
AS
BEGIN
	DECLARE 
	@CHARPOSITION INT,
	@CHARLENTH INT,
	@TXT VARCHAR(20)

	SET @TXT = ''
	SET @CHARLENTH = LEN(@INTVALPMARY)
	SET @CHARPOSITION = 1
	
	WHILE @CHARPOSITION <= @CHARLENTH + 1
	BEGIN
		IF SUBSTRING(@INTVALPMARY,@CHARPOSITION,1) IN('0','1','2','3','4','5','6','7','8','9','-')
			BEGIN
				SET @TXT = @TXT + SUBSTRING(@INTVALPMARY,@CHARPOSITION,1)
			END
		ELSE
			BEGIN
				INSERT INTO @VAL (INTVAL) VALUES(@TXT)
				SET @TXT = ''
			END
		SET @CHARPOSITION  = @CHARPOSITION + 1
	END
	RETURN
END
