CREATE FUNCTION [dbo].[ParmArrayStringToPropertyValueTableInt] (@SECTIONVALPMARY VARCHAR(MAX))
	RETURNS @SECTIONVAL TABLE (SECTIONVALTMPID INT, SECTIONDEFID INT)
AS
BEGIN
	DECLARE 
	@CHARPOSITION INT,
	@CHARLENTH INT,
	@TXT VARCHAR(20),
	@ATTRIBUTEID INTEGER,
	@ATTRIBUTEVALUE INT,
	@UPDATED BIT 

	SET @TXT = ''
	SET @UPDATED = 1
	SET @CHARLENTH = LEN(@SECTIONVALPMARY)
	SET @CHARPOSITION = 1
	SET @ATTRIBUTEID=0
	WHILE @CHARPOSITION <= @CHARLENTH + 1
		BEGIN
			IF SUBSTRING(@SECTIONVALPMARY,@CHARPOSITION,1) IN('0','1','2','3','4','5','6','7','8','9','-')
				BEGIN
					SET @TXT = @TXT + SUBSTRING(@SECTIONVALPMARY,@CHARPOSITION,1)
					SET @UPDATED = 0
				END
			ELSE
				BEGIN
					IF @UPDATED = 0
						BEGIN
							IF @ATTRIBUTEID=0
								BEGIN
									SET @ATTRIBUTEID = CAST(@TXT AS INT)
								END
							ELSE
								BEGIN
									SET @ATTRIBUTEVALUE = CAST(@TXT AS INT)
									INSERT INTO @SECTIONVAL (SECTIONVALTMPID, SECTIONDEFID) VALUES(@ATTRIBUTEID,@ATTRIBUTEVALUE)
									SET @ATTRIBUTEID=0
								END
							SET @TXT = ''
							SET @UPDATED = 1
						END
				END

			SET @CHARPOSITION  = @CHARPOSITION + 1
		END
	RETURN
END
