
CREATE FUNCTION [dbo].[PmAry_FieldVal_toValTable] (@UD_FIELDVALUES UD_FIELDVALUESTYPE READONLY)  
RETURNS @FIELDVALTBL TABLE (SECTIONVALTMPID INT, FIELDDEFID INT,VALUEDATE DATETIME,VALUESTRING VARCHAR(MAX),VALUE_ENTITYID INT, VALUE_ACTID INT, VALUE_UCSID INT, VALTYPEID INT)  
AS  
BEGIN   

DECLARE @TEMP TABLE (UDSEC_SectionValID INT, UDVAL_FieldDefID INT,UDVAL_Value VARCHAR(MAX), UDVAL_FieldType VARCHAR(20))
INSERT INTO @TEMP
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,A.UDVAL_Value, V_UNIFIEDCODESET.CONCEPTCODE AS UDVAL_FieldType
FROM V_UNIFIEDCODESET(NOLOCK) 
INNER JOIN VCP_UDFIELD(NOLOCK) ON V_UNIFIEDCODESET.ID = VCP_UDFIELD.FIELD_TYPECODE_ID
INNER JOIN  @UD_FIELDVALUES  A ON VCP_UDFIELD.SUBJCODE_ID = A.UDVAL_FieldDefID

INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,NULL, A.UDVAL_Value, NULL,-1,NULL,UDVAL_FieldType FROM   @TEMP A WHERE A.UDVAL_FieldType IN ('2','10','11','19')
   
INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,NULL,NULL, NULL,-1,CASE CAST(A.UDVAL_Value AS INT) WHEN '' THEN NULL ELSE CAST(A.UDVAL_Value AS INT) END,UDVAL_FieldType FROM   @TEMP A WHERE A.UDVAL_FieldType IN ('3','7','6','9') 

INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,NULL,NULL, NULL,NULL,CAST(A.UDVAL_Value AS INT),UDVAL_FieldType FROM   @TEMP A WHERE A.UDVAL_FieldType='4'

INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,NULL,NULL, CASE SUBSTRING(A.UDVAL_Value, CHARINDEX(CHAR(1), A.UDVAL_Value) + 2, LEN(A.UDVAL_Value)) WHEN '' THEN NULL ELSE CAST (SUBSTRING(A.UDVAL_Value, CHARINDEX(CHAR(1), A.UDVAL_Value) + 2, LEN(A.UDVAL_Value))  AS INT) END,
1, NULL, UDVAL_FieldType 
FROM  @TEMP A 
INNER JOIN V_UnifiedCodeSet(NOLOCK) UCS ON UCS.ID=A.UDVAL_FieldDefID AND UCS.SHORTNAME IN('LOCATION','PERSON', 'REPORT SOURCE', 'LABORATORY', 'SYSTEM USER', 'INVESTIGATOR', 'CASE MANAGER')
WHERE A.UDVAL_FieldType='12'

INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,NULL,NULL, NULL,
1, CASE SUBSTRING(A.UDVAL_Value, CHARINDEX(CHAR(1), A.UDVAL_Value) + 2, LEN(A.UDVAL_Value)) WHEN '' THEN NULL ELSE CAST (SUBSTRING(A.UDVAL_Value, CHARINDEX(CHAR(1), A.UDVAL_Value) + 2, LEN(A.UDVAL_Value))  AS INT) END,
UDVAL_FieldType 
FROM  @TEMP A 
INNER JOIN V_UnifiedCodeSet(NOLOCK) UCS ON UCS.ID=A.UDVAL_FieldDefID AND UCS.SHORTNAME IN('CENSUS TRACT','LOINC','SNOMED')
WHERE A.UDVAL_FieldType='12'

INSERT INTO @FIELDVALTBL (SECTIONVALTMPID, FIELDDEFID,VALUEDATE,VALUESTRING,VALUE_ENTITYID, VALUE_ACTID, VALUE_UCSID, VALTYPEID)
SELECT A.UDSEC_SectionValID,A.UDVAL_FieldDefID,CASE A.UDVAL_Value WHEN '' THEN NULL ELSE CONVERT(DATETIME,A.UDVAL_Value) END,NULL, NULL,NULL,NULL,UDVAL_FieldType FROM   @TEMP A WHERE A.UDVAL_FieldType='5'

RETURN  
END

