
CREATE FUNCTION [dbo].[UDF_GetEntityNameAsText](  
 @FIELDDEFID int,
 @ENTITYID INT 
)  
RETURNS VARCHAR(MAX)  
AS  
BEGIN  
DECLARE @RTEXT AS VARCHAR(MAX)   
DECLARE @LINKTYPE VARCHAR(MAX) 

SET @LINKTYPE = (SELECT SHORTNAME FROM V_UNIFIEDCODESET (NOLOCK) WHERE (ID = @FIELDDEFID))  

IF @LINKTYPE IN ('PERSON','LOCATION','REPORT SOURCE')
SET @ENTITYID = [dbo].[UDF_GetEntityRoot](@ENTITYID)

SET @RTEXT =  
    CASE @LINKTYPE  
    WHEN 'PERSON'   THEN (SELECT ISNULL(PARTFAM,'') + ' ,' + ISNULL(PARTGIV,'') FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
    WHEN 'LOCATION'  THEN (SELECT ISNULL(TRIVIALNAME,'')  FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
    WHEN 'REPORT SOURCE' THEN (SELECT ISNULL(TRIVIALNAME,'')  FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
    WHEN 'LABORATORY'  THEN (SELECT ISNULL(TRIVIALNAME,'')  FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )    
    WHEN 'SYSTEM USER'  THEN (SELECT ISNULL(PARTFAM,'') + ' , ' + ISNULL(PARTGIV,'') FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)    
    WHEN 'INVESTIGATOR' THEN (SELECT ISNULL(PARTFAM,'') + ' , ' + ISNULL(PARTGIV,'') FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)    
    WHEN 'CASE MANAGER' THEN (SELECT ISNULL(PARTFAM,'') + ' , ' + ISNULL(PARTGIV,'') + ' ||' + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID) 
END 
  
RETURN @RTEXT  
END

