CREATE FUNCTION [dbo].[UDF_GetFieldValueAsText](
    @VALUEREAL REAL ,
    @VALUEINTEGER INT ,
    @VALUEBOOL BIT ,
    @VALUEDATE DATETIME ,
    @VALUESTRING VARCHAR(MAX),
    @ENTITYID INT,
    @ACTID INT,
    @UCSID INT,
    @FIELDDEFID INT,
    @FETCHINTERNALVALUE BIT,
    @PHDATETIMEFORMAT VARCHAR(MAX) = 'mm/dd/yyyy'
)
RETURNS VARCHAR(MAX)
AS
BEGIN
    DECLARE @RTEXT AS VARCHAR(MAX)
    
    IF @VALUEREAL IS NOT NULL
    SET @RTEXT =  CAST(@VALUEREAL AS VARCHAR(MAX))

    IF  @VALUEINTEGER IS NOT NULL
    SET @RTEXT =  CAST(@VALUEINTEGER AS VARCHAR(MAX))
    
    IF  @VALUEDATE IS NOT NULL
        SET @RTEXT = CAST(@VALUEDATE As Date)
    
    IF  @VALUESTRING IS NOT NULL
    SET @RTEXT =  @VALUESTRING

    IF  @ENTITYID != -1
        BEGIN
            DECLARE @LINKTYPE VARCHAR(MAX)
            SET @LINKTYPE = (SELECT SHORTNAME FROM V_UNIFIEDCODESET (NOLOCK) WHERE (ID = @FIELDDEFID))
            SET @RTEXT =
              CASE @LINKTYPE
                 WHEN 'PERSON'          THEN (SELECT ISNULL(PARTFAM,'') + ',' + ISNULL(PARTGIV,'') + '||' + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)
                 WHEN 'CENSUS TRACT'    THEN (SELECT ISNULL(FULLNAME,'') + '||' + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID )
                 WHEN 'LOINC'           THEN (SELECT ISNULL(FULLNAME,'') + '||' + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID )
                 WHEN 'LOCATION'        THEN (SELECT ISNULL(TRIVIALNAME,'') + '||' + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )
                 WHEN 'SNOMED'          THEN (SELECT ISNULL(FULLNAME,'') + '||' + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID)
                 WHEN 'REPORT SOURCE'   THEN (SELECT ISNULL(TRIVIALNAME,'') + '||' + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )
                 WHEN 'LABORATORY'      THEN (SELECT ISNULL(TRIVIALNAME,'') + '||' + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
                 WHEN 'SYSTEM USER'     THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + '||' + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
                 WHEN 'INVESTIGATOR'    THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + '||' + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
                 WHEN 'CASE MANAGER'    THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + '||' + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
                 ELSE 'Invalid Link Type ' + @LINKTYPE + ' ' +  CAST(@UCSID AS VARCHAR(25))
              END
        END

    IF  @ACTID != -1
    SET @RTEXT =  CAST(@ACTID AS VARCHAR(MAX))

    IF  @UCSID IS NOT NULL
    BEGIN
        IF @FETCHINTERNALVALUE =1
        BEGIN
            SET @RTEXT =  (SELECT CONCEPTCODE FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID)
        END
        ELSE
        BEGIN
            SET @RTEXT =  (SELECT TOP 1 (CASE WHEN COUNT(FULLNAME)>1 OR MAX(ISNULL(TERMDISPLAY,''))='' THEN FULLNAME ELSE TERMDISPLAY END) AS FULLNAME    
                    FROM V_UNIFIEDCODESET (nolock) LEFT JOIN V_TERMDICTIONARY (nolock) ON V_UNIFIEDCODESET.ID=V_TERMDICTIONARY.TERMCODE_ID 
                    WHERE V_UNIFIEDCODESET.ID=@UCSID
                    GROUP BY V_UNIFIEDCODESET.FULLNAME,V_TERMDICTIONARY.NAME,V_TERMDICTIONARY.TERMDISPLAY)
        END
    END
    RETURN @RTEXT
END
