CREATE FUNCTION [dbo].[UDF_GetFieldUCSValueAsConceptCode](  
    @UCSID INT
)
RETURNS VARCHAR(50)
AS
BEGIN
    DECLARE @RTEXT AS VARCHAR(50)
    SET @RTEXT =''
    IF  @UCSID IS NOT NULL
            SET @RTEXT =  (SELECT CONCEPTCODE FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID)

    RETURN @RTEXT
END
