

CREATE   FUNCTION [dbo].[UDForm_ReturnFieldAsText](@FIELDDEFID INT,@STRING VARCHAR(MAX), @DATE DATETIME, @ENTITYID INT, @UCSID INT)  
RETURNS VARCHAR(MAX)  
AS  
BEGIN  
 DECLARE   
  @RSTRING VARCHAR(MAX),  
  @VALTYPEID INT  
    
  SET @VALTYPEID = (SELECT V_UNIFIEDCODESET.CONCEPTCODE  
        FROM V_UNIFIEDCODESET (NOLOCK)  
        INNER JOIN VCP_UDFIELD (NOLOCK) ON V_UNIFIEDCODESET.ID = VCP_UDFIELD.FIELD_TYPECODE_ID  
        WHERE (VCP_UDFIELD.SUBJCODE_ID = @FIELDDEFID)  
        )  
   --Text   
   IF @VALTYPEID IN ('10','11','2')  
   SET @RSTRING = @STRING  
  
   --Date ('Date')  
   IF @VALTYPEID IN ('5')  
   SET @RSTRING = CONVERT(VARCHAR(MAX),@DATE,126)  
  
   --if @ValTypeId in ('Link Person','Link Location','Link Census Tract')  
   --UCSID  
   IF @VALTYPEID ='12'  
       BEGIN  
      DECLARE @LINKTYPE VARCHAR(MAX)  
      SET @LINKTYPE = (SELECT SHORTNAME FROM V_UNIFIEDCODESET (NOLOCK) WHERE (ID = @FIELDDEFID))  
      SET @RSTRING =  
        CASE @LINKTYPE  
        WHEN 'PERSON'   THEN (SELECT ISNULL(PARTFAM,'') + ',' + ISNULL(PARTGIV,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
        WHEN 'CENSUS TRACT' THEN (SELECT ISNULL(FULLNAME,'') + Char(1) + Char(1) + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = @UCSID )  
        WHEN 'LOINC'   THEN (SELECT ISNULL(NULLIF(V_TERMDICTIONARY.TERMDISPLAY ,''),V_UNIFIEDCODESET.FULLNAME) + + Char(1) + Char(1) + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) LEFT JOIN V_TERMDICTIONARY (NOLOCK) ON V_UNIFIEDCODESET.ID=V_TERMDICTIONARY.TERMCODE_ID WHERE V_UNIFIEDCODESET.ID = @UCSID)  
        WHEN 'LOCATION'  THEN (SELECT ISNULL(TRIVIALNAME,'') +  Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
        WHEN 'SNOMED'   THEN (SELECT ISNULL(NULLIF(V_TERMDICTIONARY.TERMDISPLAY ,''),V_UNIFIEDCODESET.FULLNAME) + + Char(1) + Char(1) + CAST(@UCSID AS VARCHAR(25)) FROM V_UNIFIEDCODESET (NOLOCK) LEFT JOIN V_TERMDICTIONARY (NOLOCK) ON V_UNIFIEDCODESET.ID=V_TERMDICTIONARY.TERMCODE_ID WHERE V_UNIFIEDCODESET.ID = @UCSID)  
        WHEN 'REPORT SOURCE' THEN (SELECT ISNULL(TRIVIALNAME,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
        WHEN 'LABORATORY' THEN (SELECT ISNULL(TRIVIALNAME,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(25)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID )  
        WHEN 'SYSTEM USER' THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
        WHEN 'INVESTIGATOR' THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
        WHEN 'CASE MANAGER' THEN (SELECT ISNULL(PARTFAM,'') + ', ' + ISNULL(PARTGIV,'') + Char(1) + Char(1) + CAST(@ENTITYID AS VARCHAR(MAX)) FROM T_ENTITYNAME (NOLOCK) WHERE ENTITY_ID = @ENTITYID)  
        ELSE 'Invalid Link Type ' + @LINKTYPE + ' ' +  CAST(@UCSID AS VARCHAR(25))  
        END  
     END  
     
   
   IF @VALTYPEID IN ('3','4','6','7','9')  
   SET @RSTRING = CAST(@UCSID AS INT)
   SET @RSTRING = ISNULL(@RSTRING,'')

Return @RSTRING  
END  


