
Create VIEW [AtlasInternal].[VIEW_NCM_VISIT_NEWBORNINFANT]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_NEWBORNINFANT.ID AS INFT_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_NEWBORNINFANT',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_NEWBORNINFANT,
	CASE WHEN ACT_ALERTNOTALERT.TEXT LIKE 'ALERT' THEN 1 WHEN ACT_ALERTNOTALERT.TEXT LIKE 'NOT ALERT' THEN 0 ELSE NULL END AS INFT_ALERTNOTALERT,
	CASE WHEN ACT_QUIETACTIVE.TEXT LIKE 'QUIET' THEN 1 WHEN ACT_QUIETACTIVE.TEXT LIKE 'ACTIVE' THEN 0 ELSE NULL END AS INFT_QUIETACTIVE,
	CASE WHEN ACT_SLEEPS.TEXT LIKE 'SLEEPS' THEN 1 WHEN ACT_QUIETACTIVE.TEXT LIKE 'CRIES' THEN 0 ELSE NULL END AS INFT_SLEEPS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_EASILYCONSOLED',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_EASILYCONSOLED,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_FONTANELLES_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_FONTANELLES,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_MUSCLETONE_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_MUSCLETONE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_BEHAVIOR_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_BEHAVIOR,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_SKININTACT',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_SKININTACT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_Jaundice',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_JAUNDICE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_DRUGSORALCOHOL',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_DRUGSORALCOHOL,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_TOXSCREEN_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_TOXSCREEN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_TOXDRUG_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_TOXDRUG,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('INFT_WETDIAPERS',ACT_NEWBORNINFANT.ID,'VALUENUMERATOR') AS INFT_WETDIAPERS,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('INFT_BMS',ACT_NEWBORNINFANT.ID,'VALUENUMERATOR') AS INFT_BMS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_BMS',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_STOOL,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_APPROPTASKS',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_APPROPTASKS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INFT_PREPAREDFORSCHOOL_FK',ACT_NEWBORNINFANT.ID,'VALUECODE_ID') AS INFT_PREPAREDFORSCHOOL,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_AGEAPPROPDISCIPLINE',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_AGEAPPROPDISCIPLINE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_AGEAPPROPTOYS',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_AGEAPPROPTOYS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_RECIPROCALCONNECTEDNESS',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_RECIPROCALCONNECTEDNESS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_WELLCHILDCARE',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_WELLCHILDCARE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_ADEQUATEGROWTH',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_ADEQUATEGROWTH,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_TOILETTRAINING',ACT_NEWBORNINFANT.ID,'VALUEBOOL') AS INFT_TOILETTRAINING,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_NCASTTEACH',ACT_NEWBORNINFANT.ID,'VALUESTRING') AS INFT_NCASTTEACH,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_NCASTFEED',ACT_NEWBORNINFANT.ID,'VALUESTRING') AS INFT_NCASTFEED,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('INFT_HOMESCORE',ACT_NEWBORNINFANT.ID,'VALUESTRING') AS INFT_HOMESCORE,
	ACT_NEWBORNINFANT.TEXT AS INFT_COMMENTS
FROM 
	A_ACT ACT_NEWBORNINFANT (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_NEWBORNINFANT.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
	LEFT JOIN A_ACT ACT_ALERTNOTALERT (NOLOCK) ON ACT_ALERTNOTALERT.ACT_PARENT_ID=ACT_NEWBORNINFANT.ID AND ACT_ALERTNOTALERT.METACODE='INFT_ALERTNOTALERT'
	LEFT JOIN A_ACT ACT_QUIETACTIVE (NOLOCK) ON ACT_QUIETACTIVE.ACT_PARENT_ID=ACT_NEWBORNINFANT.ID AND ACT_QUIETACTIVE.METACODE='INFT_QUIETACTIVE'
	LEFT JOIN A_ACT ACT_SLEEPS (NOLOCK) ON ACT_SLEEPS.ACT_PARENT_ID=ACT_NEWBORNINFANT.ID AND ACT_SLEEPS.METACODE='INFT_SLEEPS' 
WHERE 
	ACT_NEWBORNINFANT.METACODE='INFT_ID' AND ACT_NEWBORNINFANT.STATUSCODE='ACTIVE'

