
CREATE VIEW [AtlasInternal].[VIEW_NCM_REFERRAL_INFO]            
AS 
SELECT 
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFINFO_REFERREDBY',REFACT.[ID],'VALUESTRING') AS [REFERRED BY],            
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFINFO_REFERRALAGENCY',REFACT.[ID],'VALUESTRING') AS [REFERRAL AGENCY],            
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFINFO_REFERREDBYPHONE',REFACT.[ID],'VALUESTRING') AS [REFERRAL AGENCY PHONENUMBER],
	RRPT_NAME.PARTFAM AS REPORTPER_FIRST, 
	RRPT_NAME.PARTGIV AS REPORTPER_LAST,
	DOCBODY.AVAILABILITYTIME AS [DATE TAKEN],            
	DOCBODY.AVAILABILITYTIME AS [TIME TAKEN],
	CASEMGR.PARTFAM AS CASEMGR_FIRST,
	CASEMGR.PARTGIV AS CASEMGR_LAST, 
	PARTSVC.TIME_BEG AS [DATE ASSIGNED], 
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('REFINFO_JURISDICTION_FK',REFACT.[ID],'VALUECODE_ID') AS REGION,            
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(VAL_COUNTY.VALUECODE_ID) AS [COUNTY OF RESIDENCE] , 
	DV_SERVICE.DVSVC_ROWID AS [SVC_ID],            
	DV_SERVICE.DVSVC_PATIENT_FK AS PAT_ID,
	PARTSVC.TIME_BEG AS [TIME ASSIGNED]       
FROM 
	A_ACT REFACT(NOLOCK)
	INNER JOIN A_ACT(NOLOCK) DOCBODY ON REFACT.ACT_PARENT_ID=DOCBODY.ID AND DOCBODY.CLASSCODE='DOCBODY' AND DOCBODY.STATUSCODE = 'Active'
	INNER JOIN A_ACTRELATIONSHIP REFDOCBODY (NOLOCK) ON REFDOCBODY.TARGET_ID=DOCBODY.ID
	INNER JOIN DV_SERVICE (NOLOCK) ON REFDOCBODY.SOURCE_ID=DV_SERVICE.DVSVC_ROWID 
	LEFT JOIN T_ENTITYNAME CASEMGR (NOLOCK) ON DV_SERVICE.DVSVC_CASEMANAGER_FK=CASEMGR.ENTITY_ID AND CASEMGR.USECODE='L'
	LEFT JOIN A_ACT ACT_COUNTY (NOLOCK) ON ACT_COUNTY.ACT_PARENT_ID=REFACT.ID AND ACT_COUNTY.METACODE='REFINFO_RESIDENCECOUNTY_FK'
	LEFT JOIN T_VALUE VAL_COUNTY (NOLOCK) ON VAL_COUNTY.ACT_ID=ACT_COUNTY.ID
	LEFT JOIN P_PARTICIPATION(NOLOCK) PARTSVC ON PARTSVC.ACT_ID=DV_SERVICE.DVSVC_ROWID AND PARTSVC.TYPECODE='PPRF'            
	LEFT JOIN P_PARTICIPATION(NOLOCK) PARTREF ON PARTREF.ACT_ID=REFACT.ID AND PARTREF.TYPECODE='INF'            
	LEFT JOIN R_ROLE(NOLOCK) RRPT ON RRPT.ID=PARTREF.ROLE_ID AND RRPT.CLASSCODE='AGNT' 
	LEFT JOIN T_ENTITYNAME RRPT_NAME (NOLOCK) ON RRPT.PLAYER_ID=RRPT_NAME.ENTITY_ID AND RRPT_NAME.USECODE='L'
WHERE
	REFACT.METACODE='REFINFO_ID' 

