
CREATE VIEW [ATLASINTERNAL].[VIEW_CMN_UCSFULLNAMEPARENTACTVALUECODEID] 
AS
SELECT 
	A_ACT.ACT_PARENT_ID,
	A_ACT.CLASSCODE,
	A_ACT.METACODE,
	V_UNIFIEDCODESET.FULLNAME 
FROM 
	A_ACT (NOLOCK) 
	INNER JOIN V_UNIFIEDCODESET  (NOLOCK) ON  A_ACT.VALUECODE_ID = V_UNIFIEDCODESET.ID 
WHERE 
	A_ACT.VALUECODE_ID IS NOT NULL
