
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CDCASE_CASECONTROL]
AS

SELECT 
	ACT_DOCSECT.ID AS CDCASECTRL_ID,
	E_ENTITY.ID AS CDCASECTRL_PATIENT_FK,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSLABCLEARANCE', ACT_DOCSECT.ID, 'VALUEBOOL') AS CDCASECTRL_NEEDSLABCLEARANCE,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSLABCLEARANCE', ACT_DOCSECT.ID, 'EFFECTIVETIME_BEG') AS CDCASECTRL_CLEARANCEBEGUN,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSLABCLEARANCE', ACT_DOCSECT.ID, 'EFFECTIVETIME_END') AS CDCASECTRL_CLEARANCECOMPLETED,

	ACT_NEEDSRESTR.VALUEBOOL AS CDCASECTRL_NEEDSRESTRICTION,
	ACT_NEEDSRESTR.EFFECTIVETIME_BEG AS CDCASECTRL_RESTRICTIONBEGUN,
	ACT_NEEDSRESTR.EFFECTIVETIME_END AS CDCASECTRL_RESTRICTIONREMOVED,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](ACT_NEEDSRESTR.ID, 'CDCASECTRL_RESTRICTIONLETTERSENT', 'SUBJ', 'EFFECTIVETIME_BEG') AS CDCASECTRL_RESTRICTIONLETTERSENT,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](ACT_NEEDSRESTR.ID, 'CDCASECTRL_RESTRICTIONREMOVALLETTERSENT', 'SUBJ', 'EFFECTIVETIME_BEG') AS CDCASECTRL_RESTRICTIONREMOVALLETTERSENT,

	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSOBSERVATION', ACT_DOCSECT.ID, 'VALUEBOOL') AS CDCASECTRL_NEEDSOBSERVATION,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSOBSERVATION', ACT_DOCSECT.ID, 'EFFECTIVETIME_BEG') AS CDCASECTRL_OBSERVATIONBEGUN,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSOBSERVATION', ACT_DOCSECT.ID, 'EFFECTIVETIME_END') AS CDCASECTRL_OBSERVATIONREMOVED,

	ACT_NEEDSISOL.VALUEBOOL AS CDCASECTRL_NEEDSISOLATION,
	ACT_NEEDSISOL.EFFECTIVETIME_BEG AS CDCASECTRL_ISOLATIONBEGUN,
	ACT_NEEDSISOL.EFFECTIVETIME_END AS CDCASECTRL_ISOLATIONREMOVED,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](ACT_NEEDSISOL.ID, 'CDCASECTRL_ISOLATIONLETTERSENT', 'SUBJ', 'EFFECTIVETIME_BEG') AS CDCASECTRL_ISOLATIONLETTERSENT,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](ACT_NEEDSISOL.ID, 'CDCASECTRL_ISOLATIONREMOVALLETTERSENT', 'SUBJ', 'EFFECTIVETIME_BEG') AS CDCASECTRL_ISOLATIONREMOVALLETTERSENT,

	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSTREATMENT', ACT_DOCSECT.ID, 'VALUEBOOL') AS CDCASECTRL_NEEDSTREATMENT,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSTREATMENT', ACT_DOCSECT.ID, 'EFFECTIVETIME_BEG') AS CDCASECTRL_TREATMENTBEGUN,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSTREATMENT', ACT_DOCSECT.ID, 'EFFECTIVETIME_END') AS CDCASECTRL_TREATMENTCOMPLETED,

	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSPROPHYLAXIS', ACT_DOCSECT.ID, 'VALUEBOOL') AS CDCASECTRL_NEEDSPROPHYLAXIS,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSPROPHYLAXIS', ACT_DOCSECT.ID, 'EFFECTIVETIME_BEG') AS CDCASECTRL_PROPHYLAXISBEGUN,
	[DBO].[MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSPROPHYLAXIS', ACT_DOCSECT.ID, 'EFFECTIVETIME_END') AS CDCASECTRL_PROPHYLAXISCOMPLETED,

	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('CDCASECTRL_NEEDSIMMUNIZATION', ACT_DOCSECT.ID, 'VALUEBOOL') AS CDCASECTRL_NEEDSIMMUNIZATION

FROM
	A_ACT ACT_DOCSECT (NOLOCK) 
	INNER JOIN A_ACT ACT_DOCBODY (NOLOCK) ON ACT_DOCSECT.ACT_PARENT_ID = ACT_DOCBODY.ID AND ACT_DOCBODY.CLASSCODE = 'DOCBODY'
	INNER JOIN A_ACT ACT_CASE (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID = ACT_CASE.ID AND ACT_CASE.CLASSCODE = 'CASE' AND ACT_CASE.METACODE = 'SVC_ID'
	INNER JOIN S_LINK (NOLOCK) ON S_LINK.ACT1_ID = ACT_CASE.ID AND S_LINK.[NAME] = 'PATIENT-CASE'
	INNER JOIN E_ENTITY (NOLOCK) ON S_LINK.ENTITY2_ID = E_ENTITY.ID AND E_ENTITY.CLASSCODE = 'PSN'
	LEFT JOIN A_ACT ACT_NEEDSRESTR (NOLOCK) ON ACT_NEEDSRESTR.ACT_PARENT_ID =  ACT_DOCSECT.ID AND ACT_NEEDSRESTR.CLASSCODE = 'OBS' AND ACT_NEEDSRESTR.METACODE = 'CDCASECTRL_NEEDSRESTRICTION'
	LEFT JOIN A_ACT ACT_NEEDSISOL (NOLOCK) ON ACT_NEEDSISOL.ACT_PARENT_ID =  ACT_DOCSECT.ID AND ACT_NEEDSISOL.CLASSCODE = 'OBS' AND ACT_NEEDSISOL.METACODE = 'CDCASECTRL_NEEDSISOLATION'
WHERE 
	ACT_DOCSECT.CLASSCODE = 'DOCSECT' AND
	ACT_DOCSECT.STATUSCODE <> 'NULLIFIED' AND
	ACT_DOCSECT.METACODE = 'CDCASECTRL_ID'

