
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_IMMUNIZATIONS]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_IMMUNIZATION.ID AS IMMU_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('IMMU_IMMU', ACT_IMMUNIZATION.ID, 'VALUEBOOL') AS IMMU_IMMU,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('IMMU_IMMUUPTODATE', ACT_IMMUNIZATION.ID, 'VALUEBOOL') AS IMMU_IMMUUPTODATE
FROM 
	A_ACT ACT_IMMUNIZATION (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_IMMUNIZATION.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_IMMUNIZATION.METACODE='IMMU_ID' AND ACT_IMMUNIZATION.STATUSCODE='ACTIVE'
