
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_BACTERIOLOGY]
AS
SELECT
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	ACT_BACT.ID AS BACT_ID,
	DBO.[MDF_UCS_FULLNAME_OBSUCS_BYACTID] (ACT_SMEAR.ID , 'INTERPRETATIONCODE_ID', 'BACT_SMEAR_FK') AS BACT_SMEAR_TEXT,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID] (OBSCULTURE.INTERPRETATIONCODE_ID) AS BACT_CULTURE_TEXT,
	ACT_BACT.EFFECTIVETIME_BEG AS BACT_DATE,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE] (ACT_BACT.ID, 'BACT_NEXTDUEDATE', 'SEQL', 'EFFECTIVETIME_BEG') AS BACT_NEXTDUEDATE,
	ACT_BACT.TEXT AS BACT_COMMENTS,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](SPECIMENENTITY.CODE_ID) AS BACT_SPECIMENTYPE_TEXT,
	SPECIMENENTITY.DESC_TEXT AS BACT_NUMBERTAKEN  
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_BACT (NOLOCK) ON ACT_BACT.ACT_PARENT_ID=DOCBODY.ID AND ACT_BACT.METACODE='BACT_ID' AND ACT_BACT.STATUSCODE <> 'NULLIFIED'
	LEFT JOIN A_OBSERVATION OBSCULTURE (NOLOCK) ON OBSCULTURE.ID=ACT_BACT.ID
	LEFT JOIN P_PARTICIPATION (NOLOCK) ON P_PARTICIPATION.ACT_ID=ACT_BACT.ID AND P_PARTICIPATION.TYPECODE='SPC'
	LEFT JOIN R_ROLE  (NOLOCK) ON R_ROLE.ID=P_PARTICIPATION.ROLE_ID AND R_ROLE.CLASSCODE='SPEC' 
	LEFT JOIN E_ENTITY SPECIMENENTITY (NOLOCK) ON SPECIMENENTITY.ID=R_ROLE.PLAYER_ID AND SPECIMENENTITY.CLASSCODE='MAT'
	LEFT JOIN A_ACT ACT_SMEAR (NOLOCK) ON ACT_SMEAR.ACT_PARENT_ID=ACT_BACT.ID AND ACT_SMEAR.METACODE='BACT_SMEAR_FK'
