
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CDCASE_MEDICATION]
AS
SELECT 
	ACT_CDMED.EFFECTIVETIME_BEG AS CDMED_DATEBEGUN,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDMED.CODE_ID) AS CDMED_MEDICATION, 
	SUBADM.DOSEQUANTITY_LO AS CDMED_DOSAGE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(SUBADM.DOSEQUANTITY_ALT_UNIT_ID) AS CDMED_UNIT,
	DBO.MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID(ACT_CDMED.ID,'CDMED_ISPERBODYWEIGHT') AS CDMED_ISPERBODYWEIGHT,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(SUBADM.ROUTECODE_ID) AS CDMED_ROUTE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDMED.EFFECTIVETIME_FRQ_ID) AS CDMED_FREQUENCY,
	ACT_CDMED.EFFECTIVETIME_DUR AS CDMED_DURATION,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDMED.EFFECTIVETIME_DUR_UNIT) AS CDMED_TIMEUNIT,
	SUBADM.MAXDOSEQUANTITY_NMR AS CDMED_TOTALDOSAGE,
	ACT_CDMED.EFFECTIVETIME_END AS CDMED_DATESTOPPED,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACTRES.REASONCODE_ID) AS CDMED_REASONSTOPPED,
	ACT_CDMED.TEXT AS CDMED_COMMENTS, 
	DVSVC.DVSVC_ROWID AS [SVC_ID],
	DVSVC.DVSVC_PATIENT_FK AS [PAT_ID]
FROM DBO.A_ACT AS ACT_CDMED (NOLOCK) 
	INNER JOIN A_SUBSTANCEADMINISTRATION SUBADM (NOLOCK) ON SUBADM.ID = ACT_CDMED.ID 
	INNER JOIN A_ACT ACT_CDI (NOLOCK) ON ACT_CDI.ID = ACT_CDMED.ACT_PARENT_ID
	INNER JOIN DV_SERVICE DVSVC (NOLOCK) ON DVSVC.DVSVC_ROWID = ACT_CDI.ACT_PARENT_ID 
	LEFT JOIN DBO.T_ACTREASON ACTRES (NOLOCK) ON ACTRES.ACT_ID = ACT_CDMED.ID
WHERE 
	ACT_CDMED.MOODCODE = 'RQO' AND ACT_CDMED.METACODE = 'CDMED_ID' AND ACT_CDMED.CLASSCODE = 'SBADM' AND ACT_CDMED.STATUSCODE='ACTIVE'
