
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_ENVIRONMENT]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_ENV.ID AS ENV_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_ENVIRONMENT', ACT_ENV.ID, 'VALUEBOOL') AS ENV_ENVIRONMENT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_POISONPROOFED', ACT_ENV.ID, 'VALUEBOOL') AS ENV_POISONPROOFED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FIREARMSINHOME', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FIREARMSINHOME,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FIREARMSLOCKED', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FIREARMSLOCKED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_SMOKEDETECTORS', ACT_ENV.ID, 'VALUEBOOL') AS ENV_SMOKEDETECTORS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_INFESTATION', ACT_ENV.ID, 'VALUEBOOL') AS ENV_INFESTATION,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_OUTLETSCOVERED', ACT_ENV.ID, 'VALUEBOOL') AS ENV_OUTLETSCOVERED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_CABINETSLATCHED', ACT_ENV.ID, 'VALUEBOOL') AS ENV_CABINETSLATCHED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FALLINGRISK', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FALLINGRISK,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FALLRISKWALKWAY', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FALLRISKWALKWAY,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FALLRISKSTEPS', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FALLRISKSTEPS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FALLRISKWIRING', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FALLRISKWIRING,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_FALLRISKBATH', ACT_ENV.ID, 'VALUEBOOL') AS ENV_FALLRISKBATH,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_INFESTLICE', ACT_ENV.ID, 'VALUEBOOL') AS ENV_INFESTLICE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_INFESTFLEA', ACT_ENV.ID, 'VALUEBOOL') AS ENV_INFESTFLEA,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_INFESTROACH', ACT_ENV.ID, 'VALUEBOOL') AS ENV_INFESTROACH,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_INFESTRODENT', ACT_ENV.ID, 'VALUEBOOL') AS ENV_INFESTRODENT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_LEADEXPOSURE', ACT_ENV.ID, 'VALUEBOOL') AS ENV_LEADEXPOSURE,  
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ENV_SECONDHANDSMOKE', ACT_ENV.ID, 'VALUEBOOL') AS ENV_SECONDHANDSMOKE,  
	ACT_ENV.TEXT AS ENV_COMMENTS
FROM 
	A_ACT ACT_ENV (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_ENV.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_ENV.METACODE='ENV_ID' AND ACT_ENV.STATUSCODE='ACTIVE'
