 
CREATE VIEW [AtlasInternal].[VIEW_NCM_CD_CONTACT_INFORMATION]
AS
SELECT 
PATIENT_ID AS PATIENT_ID,
SERVICE_ID AS SERVICE_ID,                      --Saravanakumar Issue #110413 08/16/2011
CONTDEMO_CONTACT_ID AS CONTDEMO_CONTACT_ID,
CONTDEMO_LASTNAME AS CONTDEMO_LASTNAME,
CONTDEMO_FIRSTNAME AS CONTDEMO_FIRSTNAME,
CONTDEMO_MIDDLENAME AS CONTDEMO_MIDDLENAME,
CONTDEMO_NAMESUFFIX AS CONTDEMO_NAMESUFFIX,
CONTDEMO_SSN AS CONTDEMO_SSN,
CONTDEMO_SSNSTATUS AS CONTDEMO_SSNSTATUS,
CONTDEMO_ADDRESS AS CONTDEMO_ADDRESS,
CONTDEMO_CITY AS CONTDEMO_CITY,
CONTDEMO_STATE AS CONTDEMO_STATE,
CONTDEMO_ZIP AS CONTDEMO_ZIP,
CONTDEMO_CENSUSTRACT AS CONTDEMO_CENSUSTRACT,
CONTDEMO_HOMEPHONE AS CONTDEMO_HOMEPHONE,
CONTDEMO_ALTERNATEPHONE AS CONTDEMO_ALTERNATEPHONE,
CONTDEMO_GENDER AS CONTDEMO_GENDER,
CONTDEMO_DOB AS CONTDEMO_DOB,
-- +SKUMAR IssueNbr:110410 08/12/2011 
CONTDEMO_EMAILID,
CONTDEMO_ELECTRONICCONTACT,
CONTDEMO_AGE,
-- -SKUMAR IssueNbr:110410 08/12/2011 
-- +Saravanakumar Issue #110413 08/16/2011
CONTDEMO_AGEMONTHS AS CONTDEMO_AGEMONTHS,
CONTDEMO_AGEDAYS AS CONTDEMO_AGEDAYS,
-- -Saravanakumar Issue #110413 08/16/2011
CONTDEMO_COMPANYSCHOOL AS CONTDEMO_COMPANYSCHOOL,
CONTDEMO_COMPANYSCHOOLTEPHONE AS CONTDEMO_COMPANYSCHOOLTEPHONE,
CONTDEMO_SUPERVISORTEACHER AS CONTDEMO_SUPERVISORTEACHER,
CONTDEMO_LASTWORKED AS CONTDEMO_LASTWORKED,
CONTDEMO_COMPANYSCHOOLADDRESS AS CONTDEMO_COMPANYSCHOOLADDRESS,
CONTDEMO_COMPANYSCHOOLCITY AS CONTDEMO_COMPANYSCHOOLCITY,
CONTDEMO_COMPANYSCHOOLSTATE AS CONTDEMO_COMPANYSCHOOLSTATE,
CONTDEMO_COMPANYSCHOOLZIPCODE AS CONTDEMO_COMPANYSCHOOLZIPCODE,
CONTDEMO_PRIMARYLANGUAGE AS CONTDEMO_PRIMARYLANGUAGE,
CONTDEMO_OCCUPATION AS CONTDEMO_OCCUPATION,
CONTDEMO_ETHNICITY AS CONTDEMO_ETHNICITY
FROM [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION]
WHERE CONTACT_FORMLINK='CDI'
