
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_EXERCISEFITNESS]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_EXERCISEFITNESS.ID AS EXER_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('EXER_EXERCISEFITNESS', ACT_EXERCISEFITNESS.ID, 'VALUEBOOL') AS EXER_EXERCISEFITNESS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('EXER_EXERCISES', ACT_EXERCISEFITNESS.ID, 'VALUEBOOL') AS EXER_EXERCISES,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_EXERCISEFITNESS.EFFECTIVETIME_FRQ_ID) AS EXER_FREQUENCY
FROM 
	A_ACT ACT_EXERCISEFITNESS (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_EXERCISEFITNESS.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_EXERCISEFITNESS.METACODE='EXER_ID' AND ACT_EXERCISEFITNESS.STATUSCODE='ACTIVE'
