
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_DETAILS]
AS
SELECT 
	VPATIENTFOLDER.PATIENT_ID AS VISITDTL_PATIENT_FK,
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_VISITDETAIL.EFFECTIVETIME_BEG  AS VISITDTL_VISITDATE,
	ACT_VISITDETAIL.EFFECTIVETIME_BEG  AS VISITDTL_VISITTIME,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_VISITDETAIL.ID,'CODE_ID') AS VISITDTL_ACTIVITY,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYACTID] (ACT_VISITDETAIL.ID,'VALUECODE_ID','VISITDTL_TYPEOFVISIT_FK') AS VISITDTL_TYPE,
	(ENTITYNAME_MANAGER.PARTFAM + ', ' + ENTITYNAME_MANAGER.PARTGIV) AS VISITDTL_SEENBY,
	DBO.[MDF_UCS_FULLNAME_UCS_BYUCSID](ROLE_MANAGER.CODE_ID) AS VISITDTL_LISCENCE,
	ACT_VISITDETAIL.EFFECTIVETIME_DUR AS VISITDTL_HOURSSPENT,
	DBO.[MDF_UCS_FULLNAME_UCS_BYUCSID](ENCOUNTER.ACUITYLEVELCODE_ID) AS VISITDTL_OUTCOME
FROM 
	[VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=VPATIENTFOLDER.ACT_FOLDER_ID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ACT_PARENT_ID=DOCBODY.ID AND ACT_VISITDETAIL.METACODE='VISITDTL_ID' AND ACT_VISITDETAIL.STATUSCODE = 'ACTIVE'
	INNER JOIN A_PATIENTENCOUNTER ENCOUNTER  (NOLOCK) ON ENCOUNTER.ID=ACT_VISITDETAIL.ID
	INNER JOIN P_PARTICIPATION PARTICIPATION_MANAGER  (NOLOCK) ON PARTICIPATION_MANAGER.ACT_ID=ACT_VISITDETAIL.ID AND PARTICIPATION_MANAGER.TYPECODE='PRF'
	INNER JOIN R_ROLE ROLE_MANAGER  (NOLOCK) ON ROLE_MANAGER.ID=PARTICIPATION_MANAGER.ROLE_ID AND ROLE_MANAGER.CLASSCODE='AGNT'
	INNER JOIN E_ENTITY ENTITY_SEENBY  (NOLOCK) ON ENTITY_SEENBY.ID=ROLE_MANAGER.PLAYER_ID AND ENTITY_SEENBY.CLASSCODE='PSN'
	INNER JOIN T_ENTITYNAME ENTITYNAME_MANAGER  (NOLOCK) ON ENTITYNAME_MANAGER.ENTITY_ID=ENTITY_SEENBY.ID AND ENTITYNAME_MANAGER.USECODE='L'
