
CREATE VIEW [AtlasInternal].[VIEW_NCM_VISIT_POSTPARTUM]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_POSTPARTUM.ID AS POSTPARTUM_ID, 
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_POSTPARTUM',ACT_POSTPARTUM.ID,'VALUEBOOL')  AS POSTPART_POSTPARTUM,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_DELIVERY_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID') AS POSTPART_DELIVERY_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('POSTPART_DELIVERY_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID')AS POSTPART_DELIVERY_TEXT,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('POSTPART_WEEKS',ACT_POSTPARTUM.ID,'VALUENUMERATOR') AS POSTPART_WEEKS,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_COMPLICATIONS',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_COMPLICATIONS,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_DEPRESSION',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_DEPRESSION,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_TREATMENT',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_TREATMENT, 
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_LOCHIA_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID') AS POSTPART_LOCHIA_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('POSTPART_LOCHIA_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID')AS POSTPART_LOCHIA_TEXT,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_PIHSS',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_PIHSS, 
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_EPISIOTOMY',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_EPISIOTOMY, 
	DBO.[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_EPISINCISION',ACT_POSTPARTUM.ID,'VALUESTRING')  AS POSTPART_EPISINCISION, 
	DBO.[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_APPOINTMENT',ACT_POSTPARTUM.ID,'VALUETS') AS POSTPART_APPOINTMENT, 
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_BREASTFEEDING_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID') AS POSTPART_BREASTFEEDING_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('POSTPART_BREASTFEEDING_FK',ACT_POSTPARTUM.ID,'VALUECODE_ID')AS POSTPART_BREASTFEEDING_TEXT,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('POSTPART_BREASTFEEDING',ACT_POSTPARTUM.ID,'VALUEBOOL') AS POSTPART_BREASTFEEDING   --NT ISSUE#77832 5/14/2010
FROM 
	A_ACT ACT_POSTPARTUM (NOLOCK)
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_POSTPARTUM.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_POSTPARTUM.METACODE='POSTPART_ID'

