CREATE VIEW [AtlasInternal].[VIEW_ClientRecord_Notes_CMMode]
AS
SELECT 
ACT_FOLDER.ID AS ACTFOLDER_ID, 
CAST(PATNOTE.[TEXT] AS VARCHAR(MAX)) AS [PAT_NOTES]
FROM 
DBO.A_ACT ACT_FOLDER (NOLOCK) 
INNER JOIN (SELECT MIN(ID) AS ID, ACT_PARENT_ID FROM DBO.A_ACT (NOLOCK) WHERE METACODE='PER_NOTES' GROUP BY ACT_PARENT_ID) PATNOTEMIN ON PATNOTEMIN.ACT_PARENT_ID=ACT_FOLDER.ID AND ACT_FOLDER.CLASSCODE='FOLDER'
INNER JOIN DBO.A_ACT PATNOTE (NOLOCK) ON PATNOTE.ID=PATNOTEMIN.ID AND PATNOTE.METACODE='PER_NOTES' 

