
CREATE VIEW [AtlasInternal].[VIEW_ClientRecord_Programs_CMMode]
AS
SELECT  
    ACT_PROG.[ID] AS PROG_PROGRAMID, 
    VPATIENTFOLDER.PATIENT_ID AS PROG_PATIENTID, 
    [DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](ACT_PROG.CODE_ID) AS PROG_PROGRAM,
    [DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PROG_ISELIGIBLE', ACT_PROG.ID, 'VALUEBOOL') AS PROG_ISELIGIBLE, 
    ACT_PROG.EFFECTIVETIME_BEG AS PROG_ENROLLEDDATE,
    ACT_PROG.[VALUEBOOL] AS PROG_ISCURRENT,
    (CASE ISNUMERIC(T_InstanceIdentifier.extension) 
        WHEN 1 THEN CAST(T_InstanceIdentifier.extension AS INTEGER)
        ELSE NULL END) as PER_CLIENTID --MSaha #147388 [ Converted PER_CLIENTID to Integer to get correct datatype when exported. ]
FROM 
    DBO.A_ACT ACT_PROG (NOLOCK) 
    INNER JOIN [AtlasInternal].[VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER  (NOLOCK) ON ACT_PROG.ACT_PARENT_ID = VPATIENTFOLDER.ACT_FOLDER_ID AND VPATIENTFOLDER.PATIENT_STATUSCODE='active'
    inner join T_InstanceIdentifier (nolock) on T_InstanceIdentifier.Entity_ID = VPATIENTFOLDER.PATIENT_ID   and root = '2.16.840.1.113883.3.33.4.2.4.11.2'+ [dbo].[FN_GetSiteID]() +'.1'
WHERE 
    ACT_PROG.METACODE='PROG_ID' AND ACT_PROG.STATUSCODE = 'ACTIVE'

