CREATE VIEW [AtlasInternal].[VIEW_NCM_EPIDEMIOLOGY_CASESUSPECT]
AS
SELECT DV_PHCASE.DVSVC_ROWID AS TBEPICASE_SERVICEID, DV_PHCASE.DVSVC_PATIENT_FK AS TBEPICASE_PATIENTID,ACT_EPICASE.ID AS TBEPICASE_ID,
DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBEPICASE_COUGH',ACT_EPICASE.ID,'VALUEBOOL') AS TBEPICASE_COUGH,
CASE WHEN ACT_CULTURE.MOODCODE ='EVN' THEN 'True' ELSE 'False' END AS TBEPICASE_CULTURE,
CASE WHEN ACT_CULTURE.MOODCODE ='EVN' THEN [DBO].[MDF_UCS_FULLNAME_OBSUCS_BYACTID](ACT_CULTURE.ID,'INTERPRETATIONCODE_ID','TBEPICASE_CULTURE') ELSE '' END AS TBEPICASE_CULTUREPOSITIVENEGATIVE,
CASE WHEN ACT_SMEAR.MOODCODE ='EVN' THEN 'True' ELSE 'False' END AS TBEPICASE_SMEAR,
CASE WHEN ACT_SMEAR.MOODCODE ='EVN' THEN [DBO].[MDF_UCS_FULLNAME_OBSUCS_BYACTID](ACT_SMEAR.ID,'INTERPRETATIONCODE_ID','TBEPICASE_SMEAR') ELSE '' END AS TBEPICASE_SMEARPOSITIVENEGATIVE,
CASE WHEN ACT_PROBE.MOODCODE ='EVN' THEN 'True' ELSE 'False' END AS TBEPICASE_PROBE,
CASE WHEN ACT_PROBE.MOODCODE ='EVN' THEN [DBO].[MDF_UCS_FULLNAME_OBSUCS_BYACTID](ACT_PROBE.ID,'INTERPRETATIONCODE_ID','TBEPICASE_PROBE') ELSE '' END  AS TBEPICASE_PROBEPOSITIVENEGATIVE,
DBO.[MDF_UCS_FULLNAME_ACTOBSERVATION_BYPARENTACTID](ACT_EPICASE.ID,'INTERPRETATIONCODE_ID','TBEPICASE_CXRRESULT_FK') AS TBEPICASE_CXRRESULT,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBEPICASE_CXRTYPE_FK',ACT_EPICASE.ID,'VALUECODE_ID') AS TBEPICASE_CXRTYPE,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBEPICASE_CXRCONDITION_FK',ACT_EPICASE.ID,'VALUECODE_ID') AS TBEPICASE_CXRCONDITION,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBEPICASE_ARPEMONTH_FK',ACT_EPICASE.ID,'VALUECODE_ID') AS TBEPICASE_ARPEMONTH,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBEPICASE_ARPEYEAR_FK',ACT_EPICASE.ID,'VALUECODE_ID') AS TBEPICASE_ARPEYEAR,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBEPICASE_HIVTEST_FK',ACT_EPICASE.ID,'CODE_ID') AS TBEPICASE_HIVTEST
FROM A_ACT ACT_EPICASE  (NOLOCK) 
INNER JOIN A_ACT ACT_DOCBODY (NOLOCK) ON ACT_EPICASE.ACT_PARENT_ID=ACT_DOCBODY.ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
INNER JOIN DV_SERVICE DV_PHCASE (NOLOCK) ON DV_PHCASE.DVSVC_ROWID=ACT_DOCBODY.ACT_PARENT_ID
LEFT JOIN (A_ACTRELATIONSHIP ACTREL_CULTURE (NOLOCK) INNER JOIN A_ACT ACT_CULTURE (NOLOCK) ON ACT_CULTURE.ID=ACTREL_CULTURE.TARGET_ID AND ACT_CULTURE.CLASSCODE='OBS' AND ACT_CULTURE.METACODE='TBEPICASE_CULTURE') ON ACTREL_CULTURE.SOURCE_ID=ACT_EPICASE.ID AND
ACTREL_CULTURE.TYPECODE='COMP'
LEFT JOIN (A_ACTRELATIONSHIP ACTREL_SMEAR (NOLOCK) INNER JOIN A_ACT ACT_SMEAR (NOLOCK) ON  ACT_SMEAR.ID=ACTREL_SMEAR.TARGET_ID AND ACT_SMEAR.CLASSCODE='OBS' AND ACT_SMEAR.METACODE='TBEPICASE_SMEAR') ON ACTREL_SMEAR.SOURCE_ID=ACT_EPICASE.ID AND
ACTREL_SMEAR.TYPECODE='COMP'
LEFT JOIN (A_ACTRELATIONSHIP ACTREL_PROBE (NOLOCK) INNER JOIN A_ACT ACT_PROBE (NOLOCK) ON ACT_PROBE.ID=ACTREL_PROBE.TARGET_ID AND ACT_PROBE.CLASSCODE='OBS' AND ACT_PROBE.METACODE='TBEPICASE_PROBE') ON ACTREL_PROBE.SOURCE_ID=ACT_EPICASE.ID AND
ACTREL_PROBE.TYPECODE='COMP'
WHERE ACT_EPICASE.CLASSCODE='DOCSECT' AND ACT_EPICASE.METACODE='TBEPICASE_ID' AND ACT_EPICASE.STATUSCODE = 'ACTIVE'


