
CREATE VIEW [AtlasInternal].[View_CMMode_NonShared_UDFData]
AS
WITH CTE_PHDATEFIELDFORMAT(DATEFIELDFORMAT)
AS
(
    SELECT 
    CASE 
        WHEN ISNULL(VAL.Value,'')='' THEN CAST(CONFIG.defaultValue AS VARCHAR)
        ELSE CAST(VAL.Value AS VARCHAR)
    END AS DATEFIELDFORMAT
    FROM S_CONFIGDEFINITION (nolock)CONFIG
    INNER JOIN S_CONFIGVALUE(nolock) VAL ON VAL.configdefinition_id = CONFIG.id
    WHERE CONFIG.[KEY]='PHDateFieldFormat'
) 
-- Get UDForms attached with Services and UDForms dircetly attached to the Client.
SELECT 
AREL.SOURCE_ID AS [RECORD_ID],    
ACT_FORM.ID  AS [FORM_INSTANCE_ID],
VCP_UDForm.FRM_ID [FORM_DEF_DR],  
VUCS_FORM.FULLNAME AS [FORM_NAME],  
VCP_UDForm.FRM_InCMR [FORM_SHOW_IN_CMR],    
VCP_UDForm.FRM_InNCM [FORM_SHOW_IN_CMM] , 
(CASE WHEN ISNULL(T_ATTRIBUTE.valueString, '') = '' THEN VCP_UDForm.FRM_DESC ELSE T_ATTRIBUTE.valueString END) AS [FORM_DESCRIPTION],  
ACT_FORM.EFFECTIVETIME_BEG AS [FORM_CREATEDATE] , 
ACT_SECTION.ID AS [SECTION_INSTANCE_ID],  
VCP_Section.SEC_ID  AS [SECTION_DEF_DR],   
VUCS_SECTION.fullName AS [SECTION_NAME],
(CASE WHEN (SELECT VTD.ACTIVE FROM V_TERMDICTIONARY VTD (NOLOCK) WHERE VUCS_SECTION.ID=VTD.TERMCODE_ID) > 0 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS],    
CASE WHEN VCP_Section.SEC_IsListSection > 0 THEN 'LIST' ELSE 'NON-LIST' END AS [SECTION_TYPE],  
(SELECT ListSectionNumber FROM [GetListSectionNumber] (ACT_FORM.ID,0)  WHERE SecActID = ACT_SECTION.ID) AS [SECTION_NUMBER] ,
AX_UDFVALUES.ID AS [FIELD_INSTANCE_ID], 
VCP_Field.Field_ID AS [FIELD_DEF_DR],     
VUCS_FIELD.FULLNAME AS [FIELD_NAME], 
(CASE WHEN VCP_Field.FIELD_IsRequired=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],
(CASE WHEN ax_UDFvalues.VALUE_ENTITYID > 1 Then 
(SELECT [dbo].[UDF_GetEntityNameAsText](Ax_UDFValues.metaCode_UCSID,ax_UDFvalues.VALUE_ENTITYID) AS Expr1)
ELSE
(SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, Ax_UDFValues.valueDateTime, Ax_UDFValues.valueString, ax_UDFvalues.VALUE_ENTITYID, -1, Ax_UDFValues.value_UCSID, Ax_UDFValues.metaCode_UCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1) END) As [FIELD_VALUE],
(CASE WHEN ax_UDFvalues.VALUE_ENTITYID > 0 Then 
    CAST(ax_UDFvalues.VALUE_ENTITYID AS varchar(100))
ELSE
(SELECT dbo.UDF_GetFieldUCSValueAsConceptCode(Ax_UDFValues.value_UCSID) AS Expr1) END) AS [FIELD_CONCEPT_CODE_VALUE],  
(Case when VTDField.Active=1 then 'ACTIVE' else 'INACTIVE' END)  AS [FIELD_STATUS],  
UCSFieldType.FullName AS [FIELD_TYPE]
FROM CTE_PHDATEFIELDFORMAT, A_ACT AS ACT_FORM (NOLOCK)
INNER JOIN A_ActRelationship AREL(NOLOCK) ON AREL.TARGET_ID=ACT_FORM.ID AND AREL.TYPECODE='COMP' AND ACT_FORM.CLASSCODE='DOCBODY'   AND ACT_FORM.STATUSCODE='active'   
INNER JOIN A_ACT PHCASE (NOLOCK)ON AREL.SOURCE_ID=PHCASE.ID AND PHCASE.Statuscode NOT IN ('nullified','terminated')
INNER JOIN A_ACT AS ACT_SECTION (NOLOCK)ON ACT_SECTION.ACT_PARENT_ID =ACT_FORM.ID AND ACT_SECTION.CLASSCODE='DOCSECT' 
INNER JOIN AX_UDFVALUES (NOLOCK) ON ACT_SECTION.ID = AX_UDFVALUES.ACT_PARENT_ID
INNER JOIN V_UNIFIEDCODESET VUCS_FORM(NOLOCK) ON VUCS_FORM.ID = ACT_FORM.CODE_ID    ---SKUMAR IssueNbr:89539
INNER JOIN VCP_UDForm (NOLOCK)ON VCP_UDForm.SubjCode_Id = VUCS_FORM.ID
INNER JOIN V_UNIFIEDCODESET VUCS_FIELD (NOLOCK)ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID
INNER JOIN VCP_UDField VCP_Field (NOLOCK) ON VCP_Field.SubjCode_Id = VUCS_FIELD.ID
INNER JOIN V_UNIFIEDCODESET VUCS_SECTION (NOLOCK)ON  VUCS_SECTION.ID=ACT_SECTION.CODE_ID
INNER JOIN VCP_UDSection VCP_Section (NOLOCK)ON VCP_Section.subjCode_Id = VUCS_SECTION.ID
LEFT JOIN T_ATTRIBUTE(NOLOCK) ON ACT_FORM.ID = T_ATTRIBUTE.ACT_ID AND T_ATTRIBUTE.NAME = 'UDFORM_Description' ---SKUMAR IssueNbr:89539
INNER Join V_TermDictionary (NOLOCK) VTDField on VTDField.termCode_ID=  VUCS_FIELD.ID   
INNER Join V_UnifiedCodeSet (NOLOCK) UCSFieldType on UCSFieldType.ID=VCP_Field.FIELD_TypeCode_ID    

