
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_AGE4TO9]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_AGE4X9.ID AS AGE4X9_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_AGE4TO9',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_AGE4TO9,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_CARENURTURE',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_CARENURTURE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_TASKORIENT',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_TASKORIENT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_APPROPDISCIP',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_APPROPDISCIP,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_APPROPEXPECT',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_APPROPEXPECT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_APPROPTOYS',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_APPROPTOYS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_APPROPPLAY',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_APPROPPLAY,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('AGE4X9_CPS_FK',ACT_AGE4X9.ID,'VALUECODE_ID') AS AGE4X9_CPS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('AGE4X9_FOSTER_FK',ACT_AGE4X9.ID,'VALUECODE_ID') AS AGE4X9_FOSTER,
	ACT_SCHOOLNAME.TEXT AS AGE4X9_SCHOOLNAME,ACT_SCHOOLGRADE.TEXT AS AGE4X9_SCHOOLGRADE,ACT_SCHOOLPROG.TEXT AS AGE4X9_SCHOOLPROG,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_PERFGRADE',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_PERFGRADE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_READS',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_READS,
	ACT_READS.TEXT AS AGE4X9_READLANG,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_WRITES',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_WRITES,
	ACT_WRITES.TEXT AS AGE4X9_WRITELANG,ACT_SCHOOLBEHAVIOR.TEXT AS AGE4X9_SCHOOLBEHAVIOR,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_SELFCARE',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_SELFCARE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_TOILETTRAIN',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_TOILETTRAIN,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_BEDWET',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_BEDWET,
	ACT_BEDTIME.TEXT AS AGE4X9_BEDTIME,ACT_SLEEPHRS.TEXT AS AGE4X9_SLEEPHRS,ACT_NAPHRS.TEXT AS AGE4X9_NAPHRS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('AGE4X9_SLEEPLOC_FK',ACT_AGE4X9.ID,'VALUECODE_ID') AS AGE4X9_SLEEPLOC,
	ACT_RITUALS.TEXT AS AGE4X9_RITUALS,ACT_CONCERNS.TEXT AS AGE4X9_CONCERNS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_SEXQUESTION',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_SEXQUESTION,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_TOBACCOED',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_TOBACCOED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_ALCOHOLED',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_ALCOHOLED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('AGE4X9_DRUGSED',ACT_AGE4X9.ID,'VALUEBOOL') AS AGE4X9_DRUGSED,
	ACT_COMMENTS.TEXT AS AGE4X9_COMMENTS
FROM 
	A_ACT ACT_AGE4X9 (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_AGE4X9.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
	LEFT JOIN A_ACT ACT_SCHOOLNAME (NOLOCK) ON ACT_SCHOOLNAME.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_SCHOOLNAME.METACODE='AGE4X9_SCHOOLNAME' 
	LEFT JOIN A_ACT ACT_SCHOOLGRADE (NOLOCK) ON ACT_SCHOOLGRADE.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_SCHOOLGRADE.METACODE='AGE4X9_SCHOOLGRADE'
	LEFT JOIN A_ACT ACT_SCHOOLPROG (NOLOCK) ON ACT_SCHOOLPROG.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_SCHOOLPROG.METACODE='AGE4X9_SCHOOLPROG'
	LEFT JOIN A_ACT ACT_READS (NOLOCK) ON ACT_READS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_READS.METACODE='AGE4X9_READS'
	LEFT JOIN A_ACT ACT_WRITES (NOLOCK) ON ACT_WRITES.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_WRITES.METACODE='AGE4X9_WRITES'
	LEFT JOIN A_ACT ACT_SCHOOLBEHAVIOR (NOLOCK) ON ACT_SCHOOLBEHAVIOR.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_SCHOOLBEHAVIOR.METACODE='AGE4X9_SCHOOLBEHAVIOR'
	LEFT JOIN A_ACT ACT_BEDTIME (NOLOCK) ON ACT_BEDTIME.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_BEDTIME.METACODE='AGE4X9_BEDTIME'
	LEFT JOIN A_ACT ACT_SLEEPHRS (NOLOCK) ON ACT_SLEEPHRS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_SLEEPHRS.METACODE='AGE4X9_SLEEPHRS'
	LEFT JOIN A_ACT ACT_NAPHRS (NOLOCK) ON ACT_NAPHRS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_NAPHRS.METACODE='AGE4X9_NAPHRS'
	LEFT JOIN A_ACT ACT_RITUALS (NOLOCK) ON ACT_RITUALS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_RITUALS.METACODE='AGE4X9_RITUALS'
	LEFT JOIN A_ACT ACT_CONCERNS (NOLOCK) ON ACT_CONCERNS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_CONCERNS.METACODE='AGE4X9_CONCERNS'
	LEFT JOIN A_ACT ACT_COMMENTS (NOLOCK) ON ACT_COMMENTS.ACT_PARENT_ID=ACT_AGE4X9.ID AND ACT_COMMENTS.METACODE='AGE4X9_COMMENTS'
WHERE 
	ACT_AGE4X9.METACODE='AGE4X9_ID'
