
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_EPIDEMIOLOGY_TBSITELOCATION]
AS
SELECT VIEW_TBSITE.TBSITE_SERVICE_FK AS TBSITELOC_SERVICE_FK, VIEW_TBSITE.TBSITE_PATIENT_FK AS TBSITELOC_PATIENT_FK,ACT_TBSITELOC.ID AS TBSITELOC_ID,
DBO.[MDF_UCS_FULLNAME_UCS_BYUCSID](ACT_TBSITELOC.CODE_ID) AS TBSITELOC_SITE,
DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITELOC_ISMAJORSITE',ACT_TBSITELOC.ID,'VALUEBOOL') AS TBSITELOC_ISMAJORSITE

FROM A_ACT ACT_TBSITELOC (NOLOCK) 
INNER JOIN [ATLASINTERNAL].[VIEW_NCM_EPIDEMIOLOGY_TBSITE] VIEW_TBSITE (NOLOCK) ON VIEW_TBSITE.TBSITE_ID=ACT_TBSITELOC.ACT_PARENT_ID

WHERE ACT_TBSITELOC.CLASSCODE='OBS' AND ACT_TBSITELOC.METACODE='TBSITELOC_ID' AND ACT_TBSITELOC.STATUSCODE <> 'NULLIFIED'

