
CREATE VIEW [AtlasInternal].[VIEW_NCM_PATIENTDATA_SERVICES]
AS
SELECT 
	VIEW_SERVICE.SVC_SERVICEID AS SVC_SERVICEID, 
	VIEW_SERVICE.SVC_CODE_ID as SVC_CODE_ID,
	VIEW_SERVICE.SVC_PATIENTID AS SVC_PATIENTID,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SERVICE.SVC_CODE_ID) AS SVC_INITIALSERVICE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SERVICE.SVC_CURRENTSERVICE_UCSID) AS SVC_CURRENTSERVICE, 
	VIEW_SERVICE.SVC_CURRENTSERVICE_UCSID AS SVC_CURRENTSERVICE_UCSID,
	VIEW_SERVICE.SVC_INITIALSERVICEDATE AS SVC_INITIALSERVICEDATE, 
	VIEW_SERVICE.SVC_CURRENTSERVICEDATE AS SVC_CURRENTSERVICEDATE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SERVICE.SVC_STATUS_UCSID) AS SVC_STATUS, 
	VIEW_SERVICE.SVC_STATUS_UCSID AS SVC_STATUS_UCSID,
	PHCASE.DXDATE AS SVC_STATUSCHANGEDATE, 
	ISNULL(VIEWCASEMGR.CASEMGR_PARTFAM, '') + ISNULL(',' + VIEWCASEMGR.CASEMGR_PARTGIV, '') AS SVC_CASEMANAGER, 
	PART.TIME_BEG AS SVC_CASEMGRDATEASSIGNED,
	VIEW_SERVICE.SVC_JURISDICTIONCODEID AS SVC_JURISDICTIONCODEID	
FROM 
	[AtlasInternal].VIEW_NCM_SUB_PATIENTDATA_SERVICES VIEW_SERVICE
	INNER JOIN DBO.A_PUBLICHEALTHCASE PHCASE (NOLOCK) ON PHCASE.ID = VIEW_SERVICE.SVC_SERVICEID 
	LEFT JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CASEMANAGER] VIEWCASEMGR  (NOLOCK) ON VIEWCASEMGR.CASEMGR_ID = VIEW_SERVICE.DVSVC_CASEMANAGER_FK 
	LEFT JOIN DBO.P_PARTICIPATION PART (NOLOCK) ON PART.ACT_ID = VIEW_SERVICE.SVC_SERVICEID AND PART.TYPECODE = 'PPRF'

