
CREATE VIEW [AtlasInternal].[VIEW_NCM_CD_CONTACT_DESCRIPTION]
AS
SELECT 
CONTACTINFOVIEW.PATIENT_ID AS PATIENT_ID,
CONTACTINFOVIEW.SERVICE_ID AS SERVICE_ID,     --Saravanakumar Issue #110413 08/16/2011
CONTACTINFOVIEW.CONTDEMO_CONTACT_ID AS CONTDEMO_ID,
ACT_CONTACTDESCRIPTION.ID AS CDCONTDESC_ID,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUECODE_ID','CDCONTDESC_CONTACTTYPE_FK') AS CDCONTDESC_CONTACTTYPE_TEXT,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUECODE_ID','CDCONTDESC_RELATION_FK') AS CDCONTDESC_RELATION_TEXT,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUECODE_ID','CDCONTDESC_CIRCLE_FK') AS CDCONTDESC_CIRCLE_TEXT,
DBO.MDF_ATTR_GETDATEVALUE_ENTATTR_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUETS','CDCONTDESC_EXPOSUREBEGAN') AS CDCONTDESC_EXPOSUREBEGAN,
DBO.MDF_ATTR_GETDATEVALUE_ENTATTR_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUETSEND','CDCONTDESC_EXPOSUREBEGAN') AS CDCONTDESC_EXPOSUREENDED,
ENTITYNAME_INVESTIGATOR.PARTFAM + ', ' + ENTITYNAME_INVESTIGATOR.PARTGIV AS CDCONTDESC_INVESTIGATOR_TEXT,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYROLEID(CONTACTINFOVIEW.MEMBER_ROLE_ID,'VALUECODE_ID','CDCONTDESC_PRIORITY_FK') AS CDCONTDESC_PRIORITY_TEXT,
-- +Saravanakumar Issue #110413 08/16/2011
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_CONTACTDESCRIPTION.ACT_PARENT_ID,'VALUECODE_ID','CDCONTDESC_Jurisdiction_FK') AS CDCONTDESC_JURISDICTION_TEXT,
DBO.[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID](ACT_CONTACTDESCRIPTION.ACT_PARENT_ID,'VALUESTRING','CDCONTDESC_ClusterID') AS CDCONTDESC_CLUSTERID,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_CONTACTDESCRIPTION.ACT_PARENT_ID,'VALUECODE_ID','CDCONTDESC_Status_FK') AS CDCONTDESC_STATUS_TEXT
-- -Saravanakumar Issue #110413 08/16/2011
FROM  A_ACT ACT_CONTACTDESCRIPTION (NOLOCK) 
INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] CONTACTINFOVIEW (NOLOCK) ON ACT_CONTACTDESCRIPTION.ACT_PARENT_ID=CONTACTINFOVIEW.CONTACT_FOLDER_ID AND CONTACTINFOVIEW.CONTACT_FORMLINK='CDI'
LEFT JOIN R_ROLELINK ROLELINK_INVESTIGATOR (NOLOCK) ON CONTACTINFOVIEW.MEMBER_ROLE_ID=ROLELINK_INVESTIGATOR.SOURCEROLE_ID AND ROLELINK_INVESTIGATOR.TYPECODE='REL' AND ROLELINK_INVESTIGATOR.METACODE='CDCONTDESC_INVESTIGATOR_FK'
LEFT JOIN R_ROLE ROLE_INVESTIGATOR (NOLOCK) ON ROLELINK_INVESTIGATOR.TARGETROLE_ID=ROLE_INVESTIGATOR.ID AND ROLE_INVESTIGATOR.CLASSCODE='AGNT'
LEFT JOIN T_ENTITYNAME ENTITYNAME_INVESTIGATOR (NOLOCK) ON ROLE_INVESTIGATOR.PLAYER_ID=ENTITYNAME_INVESTIGATOR.ENTITY_ID
WHERE ACT_CONTACTDESCRIPTION.METACODE='CDCONTDESC_ID' AND
ACT_CONTACTDESCRIPTION.STATUSCODE<>'NULLIFIED'
