
CREATE VIEW [ATLASINTERNAL].[VIEW_CMN_PATIENTDATA_ADDRESS]
AS
SELECT
	ENTITY_PSN.ID AS [ADR_PATIENTID],
	ENTADDR.ID AS [ADR_ID],
	ENTADDR.PARTAPTNUM AS [ADR_APARTMENT],
	ENTADDR.PARTSAL AS [ADR_ADDRESS],
	ENTADDR.PARTCTY AS [ADR_CITY],
	ENTADDR.PARTSTA AS [ADR_STATE],
	ENTADDR.PARTZIP AS [ADR_ZIP],
	ENTADDR.PARTCEN AS [ADR_CENSUSTRACT],
	ENTADDR.VALIDTIME_BEG AS [ADR_ENTRYDATE],
	ENTITY_PSN.ENTITYHX_ID, 
	ENTITY_PSN.CLASSCODE
FROM
	DBO.E_ENTITY ENTITY_PSN (NOLOCK) 
	INNER JOIN DBO.T_ENTITYADDRESS ENTADDR (NOLOCK) ON ENTITY_PSN.ID = ENTADDR.ENTITY_ID AND ENTADDR.USECODE = 'H'
WHERE
	ENTITY_PSN.CLASSCODE = 'PSN'
