
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_EPICONTACTS_TBSX]
AS

SELECT  
	VIEW_SUB_EPICONT.PATIENT_FK AS TBCONTSYMP_PATIENT_FK,
	VIEW_SUB_EPICONT.SERVICE_FK AS TBCONTSYMP_CASE_FK,
	VIEW_SUB_EPICONT.ACT_ID AS TBCONTSYMP_ID,
	
	VIEW_SUB_EPICONT.ACT_EFFECTIVETIME_BEG AS TBCONTSYMP_DATEOFONSET,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(VIEW_SUB_EPICONT.ACT_VALUECODE_ID) AS TBCONTSYMP_SYMPTOM,
	VIEW_SUB_EPICONT.ACT_EFFECTIVETIME_END AS TBCONTSYMP_DATEENDED,
	VIEW_SUB_EPICONT.ACT_TEXT AS TBCONTSYMP_COMMENTS

FROM 
	[ATLASINTERNAL].[VIEW_SUB_NCM_EPICONTACT]  VIEW_SUB_EPICONT
				
WHERE  
	VIEW_SUB_EPICONT.ACT_CLASSCODE = 'OBS' AND VIEW_SUB_EPICONT.ACT_METACODE = 'TBCONTSYMP_ID' 

