

CREATE VIEW [AtlasInternal].[VIEW_NCM_CDCase_Immunization] AS

SELECT 
	CDIMM.ID AS CASEIMMUN_ID,
	VF.PATIENT_ID AS CASEIMMUN_PATIENT_ID,
	CDIMM.EFFECTIVETIME_BEG AS CASEIMMUN_DATE,
	dbo.MDF_UCS_FullName_UCS_ByUCSId(CDIMM.CODE_ID) AS CASEIMMUN_IMMUNIZATION,
	dbo.MDF_UCS_FullName_UCS_ByUCSId(ATTRB.VALUECODE_ID) AS CASEIMMUN_IMMUNIZATIONTYPE,
	CDIMM.TEXT AS CASEIMMUN_Comments
FROM A_ACT CDIMM (NOLOCK) 
	INNER JOIN A_ACTRELATIONSHIP (NOLOCK) ON A_ACTRELATIONSHIP.TARGET_ID=CDIMM.ID
	INNER JOIN  VIEW_CMN_PATIENTFOLDER VF (NOLOCK) ON  VF.ACT_FOLDER_ID=A_ACTRELATIONSHIP.SOURCE_ID
	LEFT JOIN T_ATTRIBUTE ATTRB (NOLOCK) ON ATTRB.ACT_ID=CDIMM.ID
	WHERE  CDIMM.METACODE='CASEIMMUN_ID' AND CDIMM.CLASSCODE='SBADM'
	AND CDIMM.ACT_PARENT_TYPECODE='COMP' 

 
