
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_COMMRES]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_COMMRES.ID AS COMMRES_ID,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_EMPLOYED',ACT_COMMRES.ID,'VALUEBOOL') AS COMMRES_EMPLOYED,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_JOBTRAINING_FK',ACT_COMMRES.ID,'VALUECODE_ID') AS COMMRES_JOBTRAINING_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('COMMRES_JOBTRAINING_FK',ACT_COMMRES.ID,'VALUECODE_ID')AS COMMRES_JOBTRAINING_TEXT,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_JOBTRAININGTYPE',ACT_COMMRES.ID,'VALUESTRING') AS COMMRES_JOBTRAININGTYPE,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_WORKHISTORY',ACT_COMMRES.ID,'VALUESTRING') AS COMMRES_WORKHISTORY , 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_LEGALNEEDS',ACT_COMMRES.ID,'VALUEBOOL') AS COMMRES_LEGALNEEDS,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_PRIMLEGALNEED_FK',ACT_COMMRES.ID,'VALUECODE_ID') AS COMMRES_PRIMLEGALNEED_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('COMMRES_PRIMLEGALNEED_FK',ACT_COMMRES.ID,'VALUECODE_ID')AS COMMRES_PRIMLEGALNEED_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_CHILDCARE_FK',ACT_COMMRES.ID,'VALUECODE_ID') AS COMMRES_CHILDCARE_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('COMMRES_CHILDCARE_FK',ACT_COMMRES.ID,'VALUECODE_ID')AS COMMRES_CHILDCARE_TEXT,
	ACT_COMMRES.TEXT AS COMMRES_OTHER,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('COMMRES_EDUCATION_FK',ACT_COMMRES.ID,'VALUECODE_ID') AS COMMRES_EDUCATION_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('COMMRES_EDUCATION_FK',ACT_COMMRES.ID,'VALUECODE_ID')AS COMMRES_EDUCATION_TEXT
FROM 
	A_ACT ACT_COMMRES (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_COMMRES.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_COMMRES.METACODE='COMMRES_ID' 
