		
CREATE VIEW [AtlasInternal].[VIEW_NCM_CDALTERNATE_CONTACT_SYMPTOMS]
AS
SELECT 
CONTACTINFOVIEW.PATIENT_ID AS PATIENT_ID,
CONTACTINFOVIEW.SERVICE_ID as SERVICE_ID,
CONTACTINFOVIEW.CONTDEMO_CONTACT_ID AS CONTDEMO_ID,
ACT_CONTACTSYMPTOM.ID AS CDCONTSYMP_ID,
ACT_CONTACTSYMPTOM.EFFECTIVETIME_BEG AS CDCONTSYMP_DATEOFONSET,  
DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCONTSYMP_SYMPTOMSAT1STINTERVIEW',ACT_CONTACTSYMPTOM.ID,'EFFECTIVETIME_BEG') AS                   CDCONTSYMP_DATEOF1STINTERVIEW,
DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCONTSYMP_SYMPTOMSDETAIL',ACT_CONTACTSYMPTOM.ID,'VALUEBOOL') AS CDCONTSYMP_SYMPTOMS,
ACT_CONTACTSYMPTOM.EFFECTIVETIME_DUR AS CDCONTSYMP_HOURSSPENTONCASE   

FROM  A_ACT ACT_CONTACTSYMPTOM (NOLOCK) 
INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] CONTACTINFOVIEW (NOLOCK) ON ACT_CONTACTSYMPTOM.ACT_PARENT_ID=CONTACTINFOVIEW.CONTACT_FOLDER_ID AND CONTACTINFOVIEW.CONTACT_FORMLINK='CDI'
WHERE ACT_CONTACTSYMPTOM.METACODE='CDCONTSYMP_ID' AND
ACT_CONTACTSYMPTOM.MOODCODE='EVN' AND ACT_CONTACTSYMPTOM.STATUSCODE <> 'NULLIFIED'
