
-- [AtlasInternal].[VIEWSYSTEMLABORATORYINFORMATION] --

CREATE   VIEW  [AtlasInternal].[VIEWSYSTEMLABORATORYINFORMATION]
AS
SELECT 
T_INSTANCEIDENTIFIER.EXTENSION as INCIDENTID,
PHCASE.ID AS PHRECORDID,
LABREPORT.ID AS LabReportID,
LABREPORT.TITLE AS ACCESSIONNUMBER,
LABREPORT.CODE_OrTx AS HL7FILENAME,
AXLAB.DILR_ResultTest AS RESULTTEXT,
UCSABNORMALFLAG.FULLNAME AS ABNORMALFLAG,
AXLAB.DILR_ImportStatus AS IMPORTSTATUS,
AXLAB.DILR_IsFromHL7 AS ISFROMHL7,
(CASE WHEN AXLAB.DILR_IsFromHL7 = 1 THEN 'True' ELSE 'False' END) AS ISFROMHL7TEXT,
UCSLABRESULTSTATUS.FULLNAME AS LABRESULTSTATUS,
AXLAB.DILR_LocalOrganismCode AS LOCALORGANISMCODE,
AXLAB.DILR_LocalOrganismDescription AS LOCALORGANISMDESCRIPTION,
AXLAB.DILR_LocalTestCode AS LOCALTESTCODE,
AXLAB.DILR_LocalTestDescription AS LOCALTESTDESCRIPTION,
AXLAB.DILR_Notes AS NOTES,
AXLAB.DILR_OrganismCode AS ORGANISMCODE,
UCSORGCODINGSYSTEM.CONCEPTCODE AS ORGANISMCODINGSYSTEM,
CASE WHEN ISNull(AXLAB.DILR_ISFROMHL7,0)=0 AND AXLAB.DILR_MessageTypeID<>2 THEN (
    SELECT CASE WHEN ISNULL(VT.TERMDISPLAY, '') = '' THEN UCS.fullName ELSE VT.TERMDISPLAY END FROM V_Unifiedcodeset UCS (NOLOCK) 
    LEFT JOIN V_TERMDICTIONARY VT (NOLOCK) ON VT.termCode_Id = UCS.ID WHERE UCS.ID = AXLAB.DILR_OrganismDescription ) 
    ELSE DILR_OrganismDescription END AS ORGANISMDESCRIPTION,
AXLAB.DILR_PatientName AS PATIENTNAME,
AXLAB.DILR_PerformingFacilityID AS PERFORMINGFACILITYID,
AXLAB.DILR_PersonVerifiedResult AS PERSONVERIFIEDRESULT,
AXLAB.DILR_PFGEPattern1st AS PFGEPATTERN1ST,
AXLAB.DILR_PFGEPATTERN2ND AS PFGEPATTERN2ND,
AXLAB.DILR_REFERENCERANGE AS REFERENCERANGE,
AXLAB.DILR_RESULTDATE AS RESULTDATE,
UCSResult.FULLNAME AS RESULTSTATUS,
AXLAB.DILR_RESULTUNIT AS RESULTUNIT,
AXLAB.DILR_RESULTVALUE AS RESULTVALUE,
AXLAB.DILR_SEROGROUP AS SEROGROUP,
AXLAB.DILR_SEROLOGY AS SEROLOGY,
AXLAB.DILR_SEROTYPE AS SEROTYPE,
AXLAB.DILR_SPECIES AS SPECIES,
UCSSPECBODYSITE.FULLNAME AS SPECBODYSITE,
AXLAB.DILR_SPECCOLLECTEDDATE AS SPECCOLLECTEDDATE,
UCSSPECIMENSOURCE.FULLNAME AS SPECIMENSOURCE,
AXLAB.DILR_SpecimenSourceText AS SPECIMENSOURCETEXT,
AXLAB.DILR_SPECRECEIVEDDATE AS SPECRECEIVEDDATE,
AXLAB.DILR_TESTCODE AS TESTCODE,
UCSTESTCODINGSYSTEM.CONCEPTCODE AS TESTCODINGSYSTEM,
(CASE WHEN ISNULL(AXLAB.DILR_IsFromHL7,0)=0 THEN (CASE WHEN ISNULL(AXLAB.DILR_TestDescription,'')<>'' THEN (CASE WHEN ISNUMERIC(AXLAB.DILR_TestDescription) = 1  THEN DBO.FN_GetUCSFullName(AXLAB.DILR_TestDescription) ELSE AXLAB.DILR_TestDescription END) ELSE '' END) ELSE AXLAB.DILR_TestDescription END) AS TESTDESCRIPTION,
LABREPORT.statuscode as DILR_StatusCode,
AXLAB.DILR_ResultValueEx AS EXTENDEDRESULTVALUE,
AXLAB.DILR_RelevantClinicalInformation AS RELEVANTCLINICALINFORMATION,
AXLAB.DILR_ReasonForStudy AS REASONFORSTUDY

FROM AX_LABREPORT AXLAB (NOLOCK)
INNER JOIN A_ACT LABREPORT (NOLOCK)  ON AXLAB.DILR_ID=LABREPORT.ID  and LABREPORT.METACODE='DILR_ID' AND LABREPORT.CLASSCODE='OBS' AND LABREPORT.statusCode='active'
INNER JOIN A_ACT PHCASE (NOLOCK) on LABREPORT.ACT_PARENT_ID=PHCASE.ID AND PHCASE.METACODE IN('PR_RowID','AI_RowID','OB_RowID') AND (PHCASE.STATUSCODE NOT IN ('terminated', 'NULLIFIED') OR PHCASE.STATUSCODE IS NULL)  
INNER JOIN T_INSTANCEIDENTIFIER (NOLOCK) on PHCASE.ID=T_INSTANCEIDENTIFIER.ACT_ID and ( DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.1%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.8%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.7%')
LEFT JOIN V_UNIFIEDCODESET UCSABNORMALFLAG (NOLOCK) ON AXLAB.DILR_AbnormalFlagCode_ID=UCSABNORMALFLAG.ID  
LEFT JOIN V_UNIFIEDCODESET UCSLABRESULTSTATUS (NOLOCK) ON AXLAB.DILR_LIPTestStatusCode_ID=UCSLABRESULTSTATUS.ID  
LEFT JOIN V_UNIFIEDCODESET UCSResult (NOLOCK) ON AXLAB.DILR_ResultStatusCode_ID=UCSResult.ID  
LEFT JOIN V_UNIFIEDCODESET UCSSPECBODYSITE (NOLOCK) ON AXLAB.DILR_SpecBodySiteCode_ID=UCSSPECBODYSITE.ID  
LEFT JOIN V_UNIFIEDCODESET UCSSPECIMENSOURCE (NOLOCK) ON AXLAB.DILR_SpecimenSourceCode_ID=UCSSPECIMENSOURCE.ID  
LEFT JOIN V_UNIFIEDCODESET UCSTESTCODINGSYSTEM (NOLOCK) ON AXLAB.DILR_TestCodingSystem_ID=UCSTESTCODINGSYSTEM.ID  
LEFT JOIN V_UNIFIEDCODESET UCSORGCODINGSYSTEM (NOLOCK) ON AXLAB.DILR_OrganismCodingSystem_ID=UCSORGCODINGSYSTEM.ID  
LEFT JOIN V_UnifiedCodeSet UCSNameSpace (NOLOCK) ON UCSNameSpace.ID = AXLAB.DILR_SourceCode_ID   
WHERE ISNULL(UCSNameSpace.conceptCode, '') <> 'WEB'
