
CREATE VIEW [AtlasInternal].[VIEW_NCM_REFERRAL_DISPOSITION]         
AS        
SELECT          
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_CLIENTREFUSED',ACTDISP.ID,'VALUEBOOL') AS [CLIENT WAS REFUSED], 
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_IRONLY',ACTDISP.ID,'VALUEBOOL') AS [INFORMATION & REFERRAL ONLY], 
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_UNABLETOLOCATE',ACTDISP.ID,'VALUEBOOL') AS [UNABLE TO LOCATE CLIENT], 
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_MOVEDOUTOFCOUNTY',ACTDISP.ID,'VALUEBOOL') AS [CLIENT MOVED OUT OF COUNTY], 
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_CMRMATCHED',ACTDISP.ID,'VALUEBOOL') AS [LAB REPORT & CMR MATCHED], 
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('REFDISP_TOANOTHERCOUNTY',ACTDISP.ID,'VALUEBOOL') AS [REFERRED TO ANOTHER COUNTY], 
	OTHCOUNTY.[TEXT] AS [OTHER COUNTRY], 
	ACOMMENT.[TEXT] AS [COMMENTS AND FOLLOW UP], 
	DV_SERVICE.DVSVC_ROWID AS [SVC_ID], 
	DV_SERVICE.DVSVC_PATIENT_FK AS PAT_ID 
FROM 
	DV_SERVICE (NOLOCK)
	INNER JOIN A_ACTRELATIONSHIP (NOLOCK) ON A_ACTRELATIONSHIP.SOURCE_ID=DV_SERVICE.DVSVC_ROWID
	INNER JOIN A_ACT (NOLOCK) DOCBODY ON DOCBODY.ID=A_ACTRELATIONSHIP.TARGET_ID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT (NOLOCK) ACTDISP ON ACTDISP.ACT_PARENT_ID = DOCBODY.ID AND ACTDISP.METACODE = 'REFDISP_ID' AND ACTDISP.STATUSCODE NOT IN ('NULLIFIED','TERMINATED')         
	LEFT JOIN DBO.A_ACT(NOLOCK) OTHCOUNTY ON OTHCOUNTY.ACT_PARENT_ID=ACTDISP.ID AND OTHCOUNTY.METACODE = 'REFDISP_TOANOTHERCOUNTY' 
	LEFT JOIN DBO.A_ACT(NOLOCK) ACOMMENT ON ACOMMENT.ACT_PARENT_ID = ACTDISP.ID AND ACOMMENT.METACODE = 'REFDISP_COMMENTS' 

