		
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_INFORMATION_LIST]
AS
SELECT  
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_INFORMATIONLIST.ID AS INFORMATIONLIST_ID,
	DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_INFORMATIONLIST.ID ,'VALUECODE_ID','EDUCALL_INFROMATIONGIVEN_FK') AS INFORMATION_INFORMATIONGIVEN,
	ACT_INFORMATIONLIST.TEXT AS INFORMATION_PACKETIDENTIFIER,
	ACT_INFORMATIONLIST.ACTIVITYTIME_BEG AS INFORMATION_DATEPLANNED,
	ACT_INFORMATIONLIST.EFFECTIVETIME_BEG AS INFORMATION_DATEGIVEN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('EDUCALL_ASSOCSERVICE_FK',ACT_INFORMATIONLIST.ID,'VALUECODE_ID') AS INFORMATION_ASSOCIATEDSERVICE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('EDUCALL_ASSOCCONCERN_FK',ACT_INFORMATIONLIST.ID,'VALUECODE_ID') AS INFORMATION_ASSOCIATEDSCONCERN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('EDUCALL_DISPOSITION_FK',ACT_INFORMATIONLIST.ID,'VALUECODE_ID') AS INFORMATION_DISPOSITION
FROM 
	A_ACT ACT_INFORMATIONLIST (NOLOCK)
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_INFORMATIONLIST.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_INFORMATIONLIST.METACODE='EDUCALL_ID' 
