
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_TBTREATMENT]
AS
SELECT   
	DVSVC.DVSVC_ROWID AS SERVICE_FK,  
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,  
	ACT_TBTREAT.ID AS TBTREAT_ID,  
	[DBO].[MDF_UCS_FULLNAME_OBSUCS_BYACTID](OVERALLSUSC.ID , 'INTERPRETATIONCODE_ID', 'TBTREAT_OVERALLSUSC_FK') AS TBTREAT_OVERALLSUSC_TEXT,  
	ACT_TBTREAT.AVAILABILITYTIME AS TBTREAT_SUSCREPORTSENT,  
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]( 'TBTREAT_TREATMENTPLAN',ACT_TBTREAT.ID,'TEXT') AS TBTREAT_TREATMENTPLAN,  
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]( 'TBTREAT_TREATMENTSUMMARY',ACT_TBTREAT.ID,'TEXT') AS TBTREAT_TREATMENTSUMMARY   
FROM   
	DV_SERVICE DVSVC (NOLOCK)  
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY'   
	INNER JOIN A_ACT ACT_TBTREAT (NOLOCK) ON ACT_TBTREAT.ACT_PARENT_ID=DOCBODY.ID AND ACT_TBTREAT.METACODE='TBTREAT_ID' AND ACT_TBTREAT.STATUSCODE <> 'NULLIFIED'  
	LEFT JOIN A_ACT OVERALLSUSC (NOLOCK) ON ACT_TBTREAT.ID=OVERALLSUSC.ACT_PARENT_ID AND OVERALLSUSC.CLASSCODE='OBS' AND OVERALLSUSC.METACODE='TBTREAT_OVERALLSUSC_FK'
