
CREATE VIEW [AtlasInternal].[VIEW_NCM_EPICONTACT_CONTDEMO]
AS
SELECT 
	VCONTACT.PATIENT_ID,
	VCONTACT.SERVICE_ID,
	VCONTACT.CONTDEMO_CONTACT_ID,
	VCONTACT.CONTDEMO_LASTNAME,
	VCONTACT.CONTDEMO_FIRSTNAME,
	VCONTACT.CONTDEMO_MIDDLENAME,
	VCONTACT.CONTDEMO_NAMESUFFIX,
	VCONTACT.CONTDEMO_SSN,
	VCONTACT.CONTDEMO_SSNSTATUS,
	VCONTACT.CONTDEMO_ADDRESS,
	VCONTACT.CONTDEMO_CITY,
	VCONTACT.CONTDEMO_STATE,
	VCONTACT.CONTDEMO_ZIP,
	VCONTACT.CONTDEMO_CENSUSTRACT,
	VCONTACT.CONTDEMO_HOMEPHONE,
	VCONTACT.CONTDEMO_ALTERNATEPHONE,
	VCONTACT.CONTDEMO_GENDER,
	VCONTACT.CONTDEMO_DOB,
	--Karthik IssueNbr=108876
	VCONTACT.CONTDEMO_AGE,
	VCONTACT.CONTDEMO_AGEMONTHS AS CONTDEMO_AGEMONTHS,
	VCONTACT.CONTDEMO_AGEDAYS AS CONTDEMO_AGEDAYS,
	--Karthik IssueNbr=108876
	VCONTACT.CONTDEMO_COMPANYSCHOOL,
	VCONTACT.CONTDEMO_COMPANYSCHOOLTEPHONE,
	ATTR.ValueString as CONTDEMO_SUPERVISORTEACHER,
	VCONTACT.CONTDEMO_LASTWORKED,
	VCONTACT.CONTDEMO_COMPANYSCHOOLADDRESS,
	VCONTACT.CONTDEMO_COMPANYSCHOOLCITY,
	VCONTACT.CONTDEMO_COMPANYSCHOOLSTATE,
	VCONTACT.CONTDEMO_COMPANYSCHOOLZIPCODE,
	VCONTACT.CONTDEMO_PRIMARYLANGUAGE,
	VCONTACT.CONTDEMO_OCCUPATION,
	VCONTACT.CONTDEMO_ETHNICITY,
	VContact.CONTDEMO_EMAILID,
	VContact.CONTDEMO_ELECTRONICCONTACT,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(T_ADDRESSPART.ADDRESS) AS CONTDEMO_COUNTRYOFBIRTH,
	DBO.[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](VCONTACT.CONTDEMO_CONTACT_ID, 'VALUECODE_ID', 'IMGR_MONTHARRIVEDUSA_FK') AS CONTDEMO_MONTHARRIVEDUSA,
	DBO.[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](VCONTACT.CONTDEMO_CONTACT_ID, 'VALUECODE_ID', 'IMGR_YEARARRIVEDUSA_FK') AS CONTDEMO_YEARARRIVEDUSA,
	DBO.[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](VCONTACT.CONTDEMO_CONTACT_ID, 'VALUECODE_ID', 'TBIMMIGRANTSTATUS_FK') AS CONTDEMO_IMMIGRANTSTATUS,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_HIV.CODE_ID) AS CONTDEMO_HIVTEST_FK,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDEMO_MEDICALCONDITIONS', VCONTACT.CONTACT_FOLDER_ID, 'TEXT') AS CONTDEMO_CONDITIONSCOMMENTS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDEMO_MEDICALCONDITIONS', VCONTACT.CONTACT_FOLDER_ID, 'VALUEBOOL') AS CONTDEMO_MEDICALCONDITIONS
FROM
	[ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] VCONTACT
	LEFT JOIN T_ENTITYADDRESS (NOLOCK) ON T_ENTITYADDRESS.ENTITY_ID = VCONTACT.CONTDEMO_CONTACT_ID AND USECODE = 'BIR'
	LEFT JOIN T_ADDRESSPART (NOLOCK) ON T_ADDRESSPART.ADDRESS_ID = T_ENTITYADDRESS.ID 
	LEFT JOIN A_ACT ACT_HIV (NOLOCK) ON ACT_HIV.ACT_PARENT_ID = VCONTACT.CONTACT_FOLDER_ID 
				AND ACT_HIV.CLASSCODE = 'OBS' AND ACT_HIV.METACODE = 'CONTDEMO_HIVTEST_FK' AND ACT_HIV.MOODCODE = 'EVN'
	LEFT JOIN T_Attribute ATTR (NOLOCK) ON ATTR.ENTITY_ID=VCONTACT.CONTDEMO_CONTACT_ID  AND ATTR.NAME = 'PER_WorkSchoolContact'
WHERE VCONTACT.CONTACT_FORMLINK='EPI'
