
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_TUBERCULOSIS_MEDICATION]
AS
SELECT
	VIEW_SUB_REFTUB.PATIENT_FK AS TBHISTMED_PATIENT_FK,
	VIEW_SUB_REFTUB.SERVICE_FK AS TBHISTMED_SERVICE_FK,
	VIEW_SUB_REFTUB.ACT_ID AS TBHISTMED_ID,
	
	VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_BEG AS TBMEDHIST_DATEBEGUN,
	SUBADMIN.DOSEQUANTITY_LO AS TBMEDHIST_DOSAGE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SUB_REFTUB.ACT_CODE_ID) AS TBMEDHIST_MEDICATION,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](SUBADMIN.DOSEQUANTITY_ALT_UNIT_ID) AS TBMEDHIST_UNIT,
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](VIEW_SUB_REFTUB.ACT_ID, 'TBMEDHIST_ISPERBODYWEIGHT') AS TBMEDHIST_ISPERBODYWEIGHT,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](SUBADMIN.ROUTECODE_ID) AS TBMEDHIST_ROUTE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_FRQ_ID) AS TBMEDHIST_FREQUENCY,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_DUR_UNIT) AS TBMEDHIST_TIMEUNIT,	
	
	VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_DUR AS TBMEDHIST_DURATION,
	SUBADMIN.MAXDOSEQUANTITY_NMR AS TBMEDHIST_TOTALDOSES,
	VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_END AS TBMEDHIST_DATESTOPPED,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](T_ACTREASON.REASONCODE_ID) AS TBMEDHIST_REASONSTOPPED,	
	VIEW_SUB_REFTUB.ACT_TEXT AS TBHISTMED_COMMENTS

FROM   
	DBO.A_SUBSTANCEADMINISTRATION SUBADMIN (NOLOCK) 
	INNER JOIN [ATLASINTERNAL].[VIEW_SUB_REFERRAL_TUBERCULOSIS] VIEW_SUB_REFTUB  (NOLOCK) ON VIEW_SUB_REFTUB.ACT_ID = SUBADMIN.ID 
				AND VIEW_SUB_REFTUB.ACT_METACODE = 'TBMEDHIST_ID' AND VIEW_SUB_REFTUB.ACT_CLASSCODE = 'SBADM'
	LEFT JOIN T_ACTREASON (NOLOCK) ON T_ACTREASON.ACT_ID = VIEW_SUB_REFTUB.ACT_ID  

