
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_ADULTNUTRITION]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_ADLTNUTR.ID AS ADLTNUTR_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ADLTNUTR_ADULTNUTRITION',ACT_ADLTNUTR.ID,'VALUEBOOL') AS ADLTNUTR_ADULTNUTRITION,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ADLTNUTR_HEALTHYDIET',ACT_ADLTNUTR.ID,'VALUEBOOL') AS ADLTNUTR_HEALTHYDIET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('ADLTNUTR_ANEMIA',ACT_ADLTNUTR.ID,'VALUEBOOL') AS ADLTNUTR_ANEMIA,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('ADLTNUTR_FLUIDS_FK',ACT_ADLTNUTR.ID,'VALUECODE_ID') AS ADLTNUTR_FLUIDS,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('ADLTNUTR_CEFFEINEPERDAY',ACT_ADLTNUTR.ID,'VALUENUMERATOR') AS ADLTNUTR_CEFFEINEPERDAY,
	ACT_ADLTNUTR.TEXT AS ADLTNUTR_COMMENTS
FROM 
	A_ACT ACT_ADLTNUTR (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_ADLTNUTR.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_ADLTNUTR.METACODE='ADLTNUTR_ID' AND ACT_ADLTNUTR.STATUSCODE='ACTIVE'
