

CREATE VIEW [AtlasInternal].[VIEW_NCM_CD_CONTACT_IMMUNIZATION]
AS
SELECT 
CONTACTINFOVIEW.PATIENT_ID AS PATIENT_ID,
CONTACTINFOVIEW.SERVICE_ID AS SERVICE_ID,     --Saravanakumar Issue #110413 08/16/2011
CONTACTINFOVIEW.CONTDEMO_CONTACT_ID AS CONTDEMO_CONTACT_ID,
ACT_CONTACTIMMUNIZATION.ID AS CONTIMMUN_ID,
ACT_CONTACTIMMUNIZATION.EFFECTIVETIME_BEG AS CONTIMMUN_DATE,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CONTACTIMMUNIZATION.CODE_ID) AS CONTIMMUN_IMMUNIZATION_TEXT,
DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_CONTACTIMMUNIZATION.ID,'VALUECODE_ID','CONTIMMUN_IMMUNIZATIONTYPE_FK') AS CONTIMMUN_IMMUNIZATIONTYPE_TEXT,
ACT_CONTACTIMMUNIZATION.TEXT AS CONTIMMUN_COMMENTS
FROM   A_ACT ACT_CONTACTIMMUNIZATION (NOLOCK) 
INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] CONTACTINFOVIEW (NOLOCK) ON ACT_CONTACTIMMUNIZATION.ACT_PARENT_ID=CONTACTINFOVIEW.CONTACT_FOLDER_ID AND CONTACTINFOVIEW.CONTACT_FORMLINK='CDI'
WHERE
	ACT_CONTACTIMMUNIZATION.METACODE='CONTIMMUN_ID' AND
	ACT_CONTACTIMMUNIZATION.STATUSCODE<>'NULLIFIED'

