
CREATE VIEW [AtlasInternal].[VIEWSYSTEMLABORATORYINFORMATIONWITHPROVIDERFACILITY]
AS
SELECT T_INSTANCEIDENTIFIER.EXTENSION AS INCIDENTID,
PHCASE.ID AS PHRECORDID,
LABREPORT.ID AS LabReportID,
LABREPORT.title AS ACCESSIONNUMBER, 
LABREPORT.code_OrTx AS HL7FILENAME, 
AXLAB.DILR_ResultTest AS RESULTTEXT,
UCSABNORMALFLAG.fullName AS ABNORMALFLAG,
AXLAB.DILR_ImportStatus AS IMPORTSTATUS, 
AXLAB.DILR_IsFromHL7 AS ISFROMHL7,
UCSLABRESULTSTATUS.fullName AS LABRESULTSTATUS, 
AXLAB.DILR_LocalOrganismCode AS LOCALORGANISMCODE,
AXLAB.DILR_LocalOrganismDescription AS LOCALORGANISMDESCRIPTION, 
AXLAB.DILR_LocalTestCode AS LOCALTESTCODE,
AXLAB.DILR_LocalTestDescription AS LOCALTESTDESCRIPTION,
AXLAB.DILR_Notes AS NOTES, 
AXLAB.DILR_OrganismCode AS ORGANISMCODE,
UCSORGCODINGSYSTEM.CONCEPTCODE AS ORGANISMCODINGSYSTEM, 
CASE WHEN ISNull(AXLAB.DILR_ISFROMHL7,0)=0 AND AXLAB.DILR_MessageTypeID<>2 THEN (
    SELECT CASE WHEN ISNULL(VT.TERMDISPLAY, '') = '' THEN UCS.fullName ELSE VT.TERMDISPLAY END FROM V_Unifiedcodeset UCS (NOLOCK) 
    LEFT JOIN V_TERMDICTIONARY VT (NOLOCK) ON VT.termCode_Id = UCS.ID WHERE UCS.ID = AXLAB.DILR_OrganismDescription ) 
    ELSE DILR_OrganismDescription END AS ORGANISMDESCRIPTION,
AXLAB.DILR_PatientName AS PATIENTNAME, 
AXLAB.DILR_PerformingFacilityID AS PERFORMINGFACILITYID, 
AXLAB.DILR_PersonVerifiedResult AS PERSONVERIFIEDRESULT, 
AXLAB.DILR_PFGEPattern1st AS PFGEPATTERN1ST, 
AXLAB.DILR_PFGEPattern2nd AS PFGEPATTERN2ND, 
AXLAB.DILR_ReferenceRange AS REFERENCERANGE, 
AXLAB.DILR_ResultDate AS RESULTDATE,
UCSResult.fullName AS RESULTSTATUS, 
AXLAB.DILR_ResultUnit AS RESULTUNIT,
AXLAB.DILR_ResultValue AS RESULTVALUE,
AXLAB.DILR_Serogroup AS SEROGROUP, 
AXLAB.DILR_Serology AS SEROLOGY, 
AXLAB.DILR_Serotype AS SEROTYPE,
AXLAB.DILR_Species AS SPECIES, 
UCSSPECBODYSITE.fullName AS SPECBODYSITE, 
AXLAB.DILR_SpecCollectedDate AS SPECCOLLECTEDDATE, 
UCSSPECIMENSOURCE.fullName AS SPECIMENSOURCE, 
AXLAB.DILR_SpecimenSourceText AS SPECIMENSOURCETEXT, -- CMG IssueNbr:-135304
AXLAB.DILR_SpecReceivedDate AS SPECRECEIVEDDATE, 
AXLAB.DILR_TestCode AS TESTCODE,
UCSTESTCODINGSYSTEM.CONCEPTCODE AS TESTCODINGSYSTEM, 
(CASE WHEN ISNULL(AXLAB.DILR_IsFromHL7,0)=0 THEN (CASE WHEN ISNULL(AXLAB.DILR_TestDescription,'')<>'' THEN (CASE WHEN ISNUMERIC(AXLAB.DILR_TestDescription) = 1  THEN DBO.FN_GetUCSFullName(AXLAB.DILR_TestDescription) ELSE AXLAB.DILR_TestDescription END) ELSE '' END) ELSE AXLAB.DILR_TestDescription END) AS TESTDESCRIPTION, 
AXLAB.DILR_ProviderName AS PROVIDERNAME, 
AXLAB.DILR_ProviderID AS PROVIDERID, 
AXLAB.DILR_ProviderAddress AS PROVIDERADDRESS, 
AXLAB.DILR_ProviderCity AS PROVIDERCITY, 
AXLAB.DILR_ProviderState AS PROVIDERSTATE, 
AXLAB.DILR_ProviderCounty AS PROVIDERCOUNTY, 
AXLAB.DILR_ProviderZip AS PROVIDERZIP,
AXLAB.DILR_ProviderPhone AS PROVIDERPHONE, 
AXLAB.DILR_ProviderEmail AS PROVIDEREMAIL, 
AXLAB.DILR_ProviderFax AS PROVIDERFAX, 
AXLAB.DILR_FacilityName AS FACILITYNAME,
AXLAB.DILR_FacilityAddress AS FACILITYADDRESS, 
AXLAB.DILR_FacilityCity AS FACILITYCITY, 
AXLAB.DILR_FacilityState AS FACILITYSTATE,
AXLAB.DILR_FacilityCounty AS FACILITYCOUNTY, 
AXLAB.DILR_FacilityZip AS FACILITYZIP, 
AXLAB.DILR_FacilityPhone AS FACILITYPHONE, 
AXLAB.DILR_PlacerOrderNo AS PLACERORDERNO, 
AXLAB.DILR_FacilityEmail AS FACILITYEMAIL, 
AXLAB.DILR_FacilityID AS FACILITYID,
LABREPORT.statusCode AS DILR_StatusCode,
AXLAB.DILR_ResultValueEx AS EXTENDEDRESULTVALUE,
AXLAB.DILR_RelevantClinicalInformation AS RELEVANTCLINICALINFORMATION,
AXLAB.DILR_ReasonForStudy AS REASONFORSTUDY

FROM dbo.Ax_LabReport AS AXLAB (NOLOCK)
INNER JOIN dbo.A_Act AS LABREPORT (NOLOCK)ON AXLAB.DILR_ID = LABREPORT.ID  AND LABREPORT.classCode='OBS' AND LABREPORT.metaCode = 'DILR_ID' AND LABREPORT.statusCode='active'
INNER JOIN A_ACT PHCASE (NOLOCK) on LABREPORT.ACT_PARENT_ID=PHCASE.ID AND PHCASE.METACODE IN('PR_RowID','AI_RowID','OB_RowID') AND (PHCASE.STATUSCODE NOT IN ('terminated', 'NULLIFIED') OR PHCASE.STATUSCODE IS NULL)  
INNER JOIN T_INSTANCEIDENTIFIER (NOLOCK) on PHCASE.ID=T_INSTANCEIDENTIFIER.ACT_ID  AND (DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.1%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.8%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.7%')
LEFT OUTER JOIN dbo.V_UnifiedCodeSet AS UCSABNORMALFLAG (NOLOCK) ON AXLAB.DILR_AbnormalFlagCode_ID = UCSABNORMALFLAG.ID   
LEFT OUTER JOIN dbo.V_UnifiedCodeSet AS UCSLABRESULTSTATUS (NOLOCK) ON AXLAB.DILR_LIPTestStatusCode_ID = UCSLABRESULTSTATUS.ID  
LEFT OUTER JOIN dbo.V_UnifiedCodeSet AS UCSResult (NOLOCK) ON AXLAB.DILR_ResultStatusCode_ID = UCSResult.ID   
LEFT OUTER JOIN dbo.V_UnifiedCodeSet AS UCSSPECBODYSITE (NOLOCK) ON AXLAB.DILR_SpecBodySiteCode_ID = UCSSPECBODYSITE.ID   
LEFT OUTER JOIN dbo.V_UnifiedCodeSet AS UCSSPECIMENSOURCE (NOLOCK) ON AXLAB.DILR_SpecimenSourceCode_ID = UCSSPECIMENSOURCE.ID  
LEFT OUTER JOIN V_UNIFIEDCODESET AS UCSTESTCODINGSYSTEM (NOLOCK) ON AXLAB.DILR_TestCodingSystem_ID=UCSTESTCODINGSYSTEM.ID  
LEFT OUTER JOIN V_UNIFIEDCODESET AS UCSORGCODINGSYSTEM (NOLOCK) ON AXLAB.DILR_OrganismCodingSystem_ID=UCSORGCODINGSYSTEM.ID   
LEFT JOIN V_UnifiedCodeSet UCSNameSpace (NOLOCK) ON UCSNameSpace.ID = AXLAB.DILR_SourceCode_ID   
WHERE  ISNULL(UCSNameSpace.conceptCode, '') <> 'WEB'

