
Create VIEW [AtlasInternal].[VIEW_NCM_PATIENTDATA_FAMILYMEMBER]
AS
SELECT 
	DV_PERSON.[DVPER_ROWID] AS FAM_PERSONID,
	ENTITY_PSN.ID AS FAM_PATIENTID,
	DV_PERSON.DVPER_LASTNAME AS FAM_LASTNAME,
	DV_PERSON.DVPER_FIRSTNAME AS FAM_FIRSTNAME,
	T_ENTITYNAME.PARTMID AS FAM_MIDDLENAME,
	T_ENTITYNAME.PARTSFX AS FAM_NAMESUFFIX,
	DV_PERSON.DVPER_NCMID AS FAM_FAMILYMEMBER,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](FAMROLE.CODE_ID) AS FAM_RELATION,
	ENTITYADDR_FAMADDR.PARTSAL AS FAM_ADDRESS,
	ENTITYADDR_FAMADDR.PARTCTY AS FAM_CITY,
	ENTITYADDR_FAMADDR.PARTSTA AS FAM_STATE,
	ENTITYADDR_FAMADDR.PARTZIP AS FAM_ZIP,
	ENTITYADDR_FAMADDR.PARTCEN AS FAM_CENSUSTRACT,
	DV_PERSON.DVPER_HOMEPHONE AS FAM_HOMEPHONE,
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](DV_PERSON.DVPER_ROWID, 'A', 'TEL') AS FAM_CELLPHONE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](DV_PERSON.DVPER_SEXCODE_ID) AS FAM_GENDER,
	DV_PERSON.DVPER_DOB AS [FAM_DOB],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](DV_PERSON.DVPER_ETHNICITYCODE_ID) AS FAM_ETHNICITY
	
FROM
	DBO.DV_PERSON (NOLOCK)		
	INNER JOIN DBO.R_ROLE FAMROLE (NOLOCK) ON  FAMROLE.PLAYER_ID = DV_PERSON.DVPER_ROWID AND FAMROLE.CLASSCODE = 'PRS'
	INNER JOIN DBO.E_ENTITY ENTITY_PSN (NOLOCK) ON  FAMROLE.SCOPER_ID = ENTITY_PSN.[ID] AND ENTITY_PSN.CLASSCODE = 'PSN'
	INNER JOIN DBO.T_ENTITYNAME (NOLOCK) ON  T_ENTITYNAME.ENTITY_ID = DV_PERSON.[DVPER_ROWID]
	LEFT JOIN DBO.T_ENTITYADDRESS ENTITYADDR_FAMADDR (NOLOCK) ON ENTITYADDR_FAMADDR.ENTITY_ID = DV_PERSON.[DVPER_ROWID] AND ENTITYADDR_FAMADDR.USECODE = 'H'
WHERE
	DVPER_ISFAMILYMEMBER = '1' 

