
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_CHEMICALDEPENDENCE]  
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_CHEMDEP.ID AS CHEMDEP_ID,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYACTID](ACT_CHEMDEP.ID,'VALUECODE_ID','CHEMDEP_SUBSTANCEABUSEGROUP_FK') AS CHEMDEP_SUBSTANCEABUSEGROUP,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CHEMDEP.CODE_ID) AS CHEMDEP_SUBSTANCEABUSED,
	ASUB.DOSEQUANTITY_LO AS CHEMDEP_SUBSTANCEAMOUNT,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ASUB.DOSEQUANTITY_ALT_UNIT_ID) AS CHEMDEP_SUBSTANCEUNIT,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CHEMDEP.EFFECTIVETIME_FRQ_ID) AS CHEMDEP_SUBSTANCEFREQ,
	ACT_CHEMDEP.EFFECTIVETIME_BEG AS CHEMDEP_ONSET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHEMDEP_ISPROBLEM', ACT_CHEMDEP.ID, 'VALUEBOOL') AS CHEMDEP_ISPROBLEM,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHEMDEP_INTREATMENT', ACT_CHEMDEP.ID, 'VALUEBOOL') AS CHEMDEP_INTREATMENT,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHEMDEP_TREATMENTTYPE_FK',ACT_CHEMDEP.ID,'VALUECODE_ID') AS CHEMDEP_TREATMENTTYPE,
	ACT_CHEMDEP.TEXT AS CHEMDEP_COMMENTS
FROM A_ACT ACT_CHEMDEP (NOLOCK) 
	INNER JOIN A_SUBSTANCEADMINISTRATION ASUB (NOLOCK) ON ASUB.ID=ACT_CHEMDEP.ID
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_CHEMDEP.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_CHEMDEP.METACODE='CHEMDEP_ID' AND ACT_CHEMDEP.STATUSCODE='ACTIVE'
