Create VIEW [AtlasInternal].[VIEW_SUB_CLIENTRECORD_CASEMANAGER_CMMODE]  
AS  
SELECT   
 ENTITY_CASEMGR.ID AS CASEMGR_ID,  
 ENTNAME.PARTFAM AS CASEMGR_PARTFAM,  
 ENTNAME.PARTGIV AS CASEMGR_PARTGIV  
FROM  
 DBO.E_ENTITY ENTITY_CASEMGR (NOLOCK)   
 INNER JOIN DBO.T_ENTITYNAME ENTNAME (NOLOCK) ON ENTNAME.ENTITY_ID = ENTITY_CASEMGR.ID   
