CREATE VIEW [AtlasInternal].[VIEW_NCM_EPICONTACT_CONTDESCRIPTION]
AS

SELECT
	ACT_CONTACTDESCRIPTION.ID AS CONTDESC_ID,
	VCONTACT.PATIENT_ID AS CONTDESC_PATIENT_FK,
	VCONTACT.SERVICE_ID as SERVICE_ID,
	VCONTACT.CONTDEMO_CONTACT_ID AS CONTDESC_CONTACT_FK,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYROLEID](VCONTACT.MEMBER_ROLE_ID, 'VALUECODE_ID', 'CONTDESC_CONTACTTYPE_FK') AS CONTDESC_CONTACTTYPE,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYROLEID](VCONTACT.MEMBER_ROLE_ID, 'VALUECODE_ID', 'CONTDESC_RELATION_FK') AS CONTDESC_RELATION,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYROLEID](VCONTACT.MEMBER_ROLE_ID, 'VALUECODE_ID', 'CONTDESC_CIRCLE_FK') AS CONTDESC_CIRCLE,
	VCONTACT.CONTDESC_DATEIDENTIFIED AS CONTDESC_DATEIDENTIFIED,
[DBO].MDF_ATTR_GETDATEVALUE_ENTATTR_BYROLEID(VCONTACT.MEMBER_ROLE_ID,'VALUETSEND', 'CONTDESC_DATECONTACTBROKEN') AS CONTDESC_DATECONTACTBROKEN,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(VCONTACT.CONTACT_JURISDICTION_ID)AS CONTDESC_JURISDICTION,
	DBO.MDF_UCS_FULLNAME_ATTRUCS_BYROLEID(VCONTACT.MEMBER_ROLE_ID, 'VALUECODE_ID', 'CONTDESC_PRIORITY_FK') AS CONTDESC_PRIORITY, 
	VCONTACT.CONTACT_CLUSTERID AS CONTDESC_CLUSTERID,
	[dbo].MDF_UCS_FullName_UCS_ByUCSId(attr.VALUECODE_ID)  AS CONTDESC_Status,
	ENTITYNAME_INVESTIGATOR.PARTFAM + ', ' + ENTITYNAME_INVESTIGATOR.PARTGIV AS CDCONTDESC_INVESTIGATOR
FROM  
	A_ACT ACT_CONTACTDESCRIPTION (NOLOCK) 
	INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] VCONTACT (NOLOCK) ON ACT_CONTACTDESCRIPTION.ACT_PARENT_ID=VCONTACT.CONTACT_FOLDER_ID AND VCONTACT.CONTACT_FORMLINK='EPI'
	LEFT JOIN R_ROLELINK ROLELINK_INVESTIGATOR (NOLOCK) ON VCONTACT.MEMBER_ROLE_ID=ROLELINK_INVESTIGATOR.SOURCEROLE_ID AND ROLELINK_INVESTIGATOR.TYPECODE='REL' AND ROLELINK_INVESTIGATOR.METACODE='CONTDESC_INVESTIGATOR_FK'
	LEFT JOIN R_ROLE ROLE_INVESTIGATOR (NOLOCK) ON ROLELINK_INVESTIGATOR.TARGETROLE_ID=ROLE_INVESTIGATOR.ID AND 
ROLE_INVESTIGATOR.CLASSCODE='AGNT'
	LEFT JOIN T_ENTITYNAME ENTITYNAME_INVESTIGATOR (NOLOCK) ON ROLE_INVESTIGATOR.PLAYER_ID=ENTITYNAME_INVESTIGATOR.ENTITY_ID
	LEFT JOIN T_Attribute ATTR (NOLOCK) ON ACT_ContactDescription.Act_Parent_ID = ATTR.ACT_ID AND ATTR.[TYPE] = 'CV' AND ATTR.NAME LIKE 'CONTDESC_Status_FK'
WHERE	ACT_CONTACTDESCRIPTION.CLASSCODE = 'DOCSECT' 
		AND ACT_CONTACTDESCRIPTION.METACODE = 'CONTDESC_ID'
		AND ACT_CONTACTDESCRIPTION.MOODCODE = 'EVN'

