
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_VITALSIGN]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_VITALSIGN.ID AS VITALSIGN_ID, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('VITSIGN_VITALSIGNS',ACT_VITALSIGN.ID,'VALUEBOOL') AS VITSIGN_VITALSIGNS,
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_TEMPERATURE',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_TEMPERATURE, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_PULSE',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_PULSE, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_RESPIRATION',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_RESPIRATION, 
	(CONVERT(VARCHAR(3),VAL.VALUENUMERATOR)	+ '/' + CONVERT(VARCHAR(3),VAL.VALUEDENOMINATOR)) AS VITSIGN_BLOODPRESSURE, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_WEIGHT',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_WEIGHT, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_HEIGHT',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_HEIGHT, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_BMI',ACT_VITALSIGN.ID,'VALUEREAL') AS VITSIGN_BMI, 
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_HEADCIRCUMFERENCE',ACT_VITALSIGN.ID,'VALUENUMERATOR') AS VITSIGN_HEADCIRCUMFERENCE, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('VITSIGN_HAPPYWITHWEIGHT',ACT_VITALSIGN.ID,'VALUEBOOL') AS VITSIGN_HAPPYWITHWEIGHT, 
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('VITSIGN_GENERALHYGIENE',ACT_VITALSIGN.ID,'VALUESTRING') AS VITSIGN_GENERALHYGIENE, 
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('VITSIGN_GENERALAPPEARANCE',ACT_VITALSIGN.ID,'VALUESTRING') AS VITSIGN_GENERALAPPEARANCE,
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('VITSIGN_GESTATIONALAGE',ACT_VITALSIGN.ID,'VALUEREAL') AS VITSIGN_GESTATIONALAGE
FROM 
	A_ACT ACT_VITALSIGN (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_VITALSIGN.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
	LEFT JOIN A_ACT ACT_BLOODPRESSURE (NOLOCK) ON ACT_BLOODPRESSURE.ACT_PARENT_ID=ACT_VITALSIGN.ID AND ACT_BLOODPRESSURE.METACODE='VITSIGN_BLOODPRESSURE'
	LEFT JOIN T_VALUE VAL (NOLOCK) ON VAL.ACT_ID=ACT_BLOODPRESSURE.ID
WHERE 
	ACT_VITALSIGN.METACODE='VITSIGN_ID'
