
Create VIEW [AtlasInternal].[VIEW_CMR_INCIDENT_CONTACT_DATA_FOR_CM_MODE] AS 
SELECT     DIID as CLIENTID, CONTACTID, RLENT_FIRSTNAME, RLENT_LASTNAME, RLENT_MIDDLEINITIAL, RLENT_NAMESUFFIX, RLENT_AGE, RLENT_DOB, RLENT_SEX, 
                      RLENT_CONTACTTYPE, RLENT_DATESOFCONTACT, RLENT_STREETADDRESS, RLENT_APARTMENT, RLENT_CITY, RLENT_ZIP, RLENT_PHONE, RLENT_DISTRICT, 
                      RLENT_PROPHYLAXISMEDICATION, RLENT_INVESTIGATORDR, RLENT_PRIORITYDR, RLENT_CLUSTERID, 
                      RLENT_STATUSDR, FOLDERID, RLENT_ELECTRONICCONTACT, RLENT_EMAIL, RLENT_STATE, RLENT_RACE
FROM         [ATLASINTERNAL].[VIEWSYSTEMCONTACTDATA_FOR_CM_MODE]
WHERE     (RECORDTYPE = 'SVC')

