
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_RELATIONSHIP]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_REL.ID AS REL_ID,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_RELATIONSHIPS',ACT_REL.ID,'VALUEBOOL') AS REL_RELATIONSHIPS,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_FOBSUPPORTIVE',ACT_REL.ID,'VALUEBOOL') AS REL_FOBSUPPORTIVE,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_FOBFINANCESUPPORT',ACT_REL.ID,'VALUEBOOL') AS REL_FOBFINANCESUPPORT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_FOBPRESENTHOME',ACT_REL.ID,'VALUEBOOL') AS REL_FOBPRESENTHOME,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_INTERACTIONWCAREGIVER_FK',ACT_REL.ID,'VALUECODE_ID') AS REL_INTERACTIONWCAREGIVER_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('REL_INTERACTIONWCAREGIVER_FK',ACT_REL.ID,'VALUECODE_ID')AS REL_INTERACTIONWCAREGIVER_TEXT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_VISIBLEATTACHMENT',ACT_REL.ID,'VALUEBOOL') AS REL_VISIBLEATTACHMENT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_RESPONDSTOCUES',ACT_REL.ID,'VALUEBOOL') AS REL_RESPONDSTOCUES,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_POSITIVEPARENTING',ACT_REL.ID,'VALUEBOOL') AS REL_POSITIVEPARENTING,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_FAMILYRELATIONS_FK',ACT_REL.ID,'VALUECODE_ID') AS REL_FAMILYRELATIONS_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('REL_FAMILYRELATIONS_FK',ACT_REL.ID,'VALUECODE_ID')AS REL_FAMILYRELATIONS_TEXT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_SUPPORTSYSTEM',ACT_REL.ID,'VALUEBOOL') AS REL_SUPPORTSYSTEM,
	ACT_REL.TEXT AS REL_COMMENTS,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_CLUBORGANIZATION',ACT_REL.ID,'VALUESTRING') AS REL_CLUBORGANIZATION,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_SUPPORTIVEREL_FK',ACT_REL.ID,'VALUECODE_ID') AS REL_SUPPORTIVEREL_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('REL_SUPPORTIVEREL_FK',ACT_REL.ID,'VALUECODE_ID')AS REL_SUPPORTIVEREL_TEXT,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_SPIRITUALACTIVITY',ACT_REL.ID,'VALUESTRING') AS REL_SPIRITUALACTIVITY,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_HOBBYRECREATION',ACT_REL.ID,'VALUESTRING') AS REL_HOBBYRECREATION,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_IHSS',ACT_REL.ID,'VALUEBOOL') AS REL_IHSS,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_IHSS',ACT_REL.ID,'EFFECTIVETIME_TXT') AS REL_IHSS_HRSPERMO,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_IHSS_PROVIDER',ACT_REL.ID,'VALUESTRING') AS REL_IHSS_PROVIDER,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('REL_OTHERSUPPORTSVC_FK',ACT_REL.ID,'VALUECODE_ID') AS REL_OTHERSUPPORTSVC_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('REL_OTHERSUPPORTSVC_FK',ACT_REL.ID,'VALUECODE_ID')AS REL_OTHERSUPPORTSVC_TEXT
FROM 
	A_ACT ACT_REL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_REL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_REL.METACODE='REL_ID'
