
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_EPICONTACTS_DISPOSITION]
AS

SELECT  
	VIEW_SUB_EPICONT.PATIENT_FK AS CONTDISP_PATIENT_FK,
	VIEW_SUB_EPICONT.SERVICE_FK AS CONTDISP_CASE_FK,
	VIEW_SUB_EPICONT.ACT_ID AS CONTDISP_ID,
	
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDISP_NOFOLLOWUP', VIEW_SUB_EPICONT.ACT_ID, 'VALUEBOOL') AS CONTDISP_NOFOLLOWUP,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDISP_FAMILYFOLDER', VIEW_SUB_EPICONT.ACT_ID, 'VALUEBOOL') AS CONTDISP_FAMILYFOLDER,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDISP_LTBICLINICREFERRAL', VIEW_SUB_EPICONT.ACT_ID, 'VALUEBOOL') AS CONTDISP_LTBICLINICREFERRAL,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDISP_PRIVATEMEDICALDOCTOR', VIEW_SUB_EPICONT.ACT_ID, 'VALUEBOOL') AS CONTDISP_PRIVATEMEDICALDOCTOR,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CONTDISP_IJTRANSFER', VIEW_SUB_EPICONT.ACT_ID, 'VALUEBOOL') AS CONTDISP_IJTRANSFER,
	VIEW_SUB_EPICONT.ACT_EFFECTIVETIME_DUR AS CONTDISP_HOURSSPENT,
	VIEW_SUB_EPICONT.ACT_TEXT AS CONTDISP_COMMENTS
	
FROM 
	[ATLASINTERNAL].[VIEW_SUB_NCM_EPICONTACT] VIEW_SUB_EPICONT
	
WHERE 
	VIEW_SUB_EPICONT.ACT_CLASSCODE = 'DOCSECT' AND VIEW_SUB_EPICONT.ACT_METACODE = 'CONTDISP_ID' AND VIEW_SUB_EPICONT.ACT_MOODCODE = 'EVN'

