
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_REFERRAL_LIST]
AS
SELECT  
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_REFERRALLIST.ID AS REFERRALLIST_ID,
	DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_REFERRALLIST.ID ,'VALUECODE_ID','REFALL_REFERRAL_FK') AS REFERRALLIST_REFERRAL,
	ACT_REFERRALLIST.ACTIVITYTIME_BEG AS REFERRALLIST_DATEPLANNED,
	ACT_REFERRALLIST.EFFECTIVETIME_BEG AS REFERRALLIST_DATEINTERVENED,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('REFALL_ASSOCSERVICE_FK',ACT_REFERRALLIST.ID,'VALUECODE_ID') AS REFERRALLIST_ASSOCIATEDSERVICE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('REFALL_ASSOCCONCERN_FK',ACT_REFERRALLIST.ID,'VALUECODE_ID') AS REFERRALLIST_ASSOCIATEDCONCERN,
	ACT_REFERRALLIST.TEXT AS REFERRALLIST_REFERRALDETAILS,
	ACT_REFERRALLOCATION.TEXT AS REFERRALLIST_REFERRALLOCATION, --TEXT IS NOT RETURNING FROM THE FUNCTION , SO ADDED ONE LEFT JOIN USING METACODE='REFALL_LOCATION'
	ACT_REFERRALLOCATION.EFFECTIVETIME_BEG AS REFERRALLIST_REFERRALAPPTDATE,
	ACT_REFERRALFOLLOWUP.TEXT AS REFERRALLIST_THIRTYDAYFOLLOWUP, --TEXT IS NOT RETURNING FROM THE FUNCTION , SO ADDED ONE LEFT JOIN USING METACODE='REFALL_FOLLOWUP'
	ACT_REFERRALFOLLOWUP.EFFECTIVETIME_BEG AS REFERRALLIST_FOLLOWUPDATE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('REFALL_DISPOSITION_FK',ACT_REFERRALLIST.ID,'VALUECODE_ID') AS REFERRALLIST_DISPOSITION
FROM 
	A_ACT ACT_REFERRALLIST (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_REFERRALLIST.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
	LEFT JOIN A_ACT ACT_REFERRALLOCATION (NOLOCK) ON ACT_REFERRALLIST.ID=ACT_REFERRALLOCATION.ACT_PARENT_ID AND ACT_REFERRALLOCATION.METACODE='REFALL_LOCATION'  
	LEFT JOIN A_ACT ACT_REFERRALFOLLOWUP (NOLOCK) ON ACT_REFERRALLIST.ID=ACT_REFERRALFOLLOWUP.ACT_PARENT_ID AND ACT_REFERRALFOLLOWUP.METACODE='REFALL_FOLLOWUP'  
WHERE 
	ACT_REFERRALLIST.METACODE='REFALL_ID' 
