
CREATE VIEW [AtlasInternal].[View_NCM_DOT_Detail]    
AS    
SELECT ACTREL_SERVICEFORM.ID AS SERVICEID, ACT_DOTDETAIL.ID AS DOTDTL_ID,     
CASE ACT_DOTDETAIL.STATUSCODE WHEN 'ACTIVE' THEN 1 ELSE 0 END AS DOTDTL_ACTIVE,     
ROLE_CASEMGR.PLAYER_ID AS DOTDTL_CASEMANAGER_FK, ATTR_INITIALS.VALUESTRING AS DOTDTL_CMINITIALS,     
T_ENTITYNAME_1.PARTFAM + ',' + T_ENTITYNAME_1.PARTGIV AS DOTDTL_CASEMANAGER_TEXT,     
ROLE_CASEMGR.CODE_ID AS DOTDTL_CMLICENSEFK, UCS_LICENSE.FULLNAME AS DOTSUM_LICENSE,     
ACT_DOTDETAIL.EFFECTIVETIME_BEG AS DOTDTL_DATEBEGUN, ACT_DOTDETAIL.EFFECTIVETIME_END AS DOTDTL_DATECOMPLETED,     
ATTR_DATEENDED.VALUETSEND AS DOTDTL_DATEENDED,
ACT_DOTDETAIL.ACTIVITYTIME_END AS DOTDTL_ESTIMATEDCOT, CASE WHEN CHARINDEX('DW5', ACT_DOTDETAIL.EFFECTIVETIME_TXT, 0)     
> 0 THEN 1 ELSE 0 END AS DOTDTL_FRIDAY, CASE WHEN CHARINDEX('DW1', ACT_DOTDETAIL.EFFECTIVETIME_TXT, 0)     
> 0 THEN 1 ELSE 0 END AS DOTDTL_MONDAY, CASE WHEN CHARINDEX('DW4', ACT_DOTDETAIL.EFFECTIVETIME_TXT, 0)     
> 0 THEN 1 ELSE 0 END AS DOTDTL_THURSDAY, CASE WHEN CHARINDEX('DW2', ACT_DOTDETAIL.EFFECTIVETIME_TXT, 0)     
> 0 THEN 1 ELSE 0 END AS DOTDTL_TUESDAY, CASE WHEN CHARINDEX('DW3', ACT_DOTDETAIL.EFFECTIVETIME_TXT, 0)     
> 0 THEN 1 ELSE 0 END AS DOTDTL_WEDNESDAY, ACT_DOTDETAIL.EFFECTIVETIME_DUR AS DOTDTL_WEEKS,     
ACUITYBOTH.VALUECODE_ID AS DOTDTL_BEGINACUITYBOTH_FK,     
UCS_ACUITYBOTH.FULLNAME AS DOTDTL_BEGINACUITYBOTH,     
ACUITYLEFT.VALUECODE_ID AS DOTDTL_BEGINACUITYLEFT_FK, UCS_ACUITYLEFT.FULLNAME AS DOTDTL_ACUITYLEFT,     
ACUITYRIGHT.VALUECODE_ID AS DOTDTL_BEGINACUITYRIGHT_FK,     
UCS_ACUITYRIGHT.FULLNAME AS DOTDTL_ACUITYRIGHT,     
ACUITYBALANCE.VALUECODE_ID AS DOTDTL_BEGINBALANCE_FK,     
UCS_ACUITYBALANCE.FULLNAME AS DOTDTL_ACUITYBALANCE,     
COLORVISION.VALUECODE_ID AS DOTDTL_BEGINCOLORVISION_FK,     
UCS_COLORVISION.FULLNAME AS DOTDTL_COLORVISION,     
HEARINGLEFT.VALUECODE_ID AS DOTDTL_BEGINHEARINGLEFT_FK,     
UCS_HEARINGLEFT.FULLNAME AS DOTDTL_HEARINGLEFT,     
HEARINGRIGHT.VALUECODE_ID AS DOTDTL_BEGINHEARINGRIGHT_FK,     
UCS_HEARINGRIGHT.FULLNAME AS DOTDTL_HEARINGRIGHT,     
LIVERFUNCTION.VALUECODE_ID AS DOTDTL_BEGINLIVERFUNCTION_FK,     
UCS_LIVERFUNCTION.FULLNAME AS DOTDTL_LIVERFUNCTION,  BEGINWEIGHT.VALUENUMERATOR AS DOTDTL_BEGINWEIGHT    
FROM DBO.A_PATIENTENCOUNTER A_PATIENTENCOUNTER_1 (NOLOCK)    
INNER JOIN DBO.A_ACT ACT_DOTDETAIL (NOLOCK) ON A_PATIENTENCOUNTER_1.ID = ACT_DOTDETAIL.ID AND ACT_DOTDETAIL.METACODE = 'DOTDTL_ID' AND ACT_DOTDETAIL.MOODCODE = 'INT'     
INNER JOIN DBO.A_ACT ACTREL_FORMDOC (NOLOCK) ON ACTREL_FORMDOC.ID = ACT_DOTDETAIL.ACT_PARENT_ID AND ACTREL_FORMDOC.ACT_PARENT_TYPECODE = 'COMP'     
INNER JOIN DBO.A_ACT ACTREL_SERVICEFORM (NOLOCK) ON ACTREL_SERVICEFORM.ID = ACTREL_FORMDOC.ACT_PARENT_ID AND ACTREL_SERVICEFORM.ACT_PARENT_TYPECODE = 'COMP'     
LEFT OUTER JOIN DBO.P_PARTICIPATION PART_CASEMGR (NOLOCK) ON PART_CASEMGR.ACT_ID = ACT_DOTDETAIL.ID AND PART_CASEMGR.TYPECODE = 'PPRF'     
LEFT OUTER JOIN DBO.R_ROLE ROLE_CASEMGR (NOLOCK) ON PART_CASEMGR.ROLE_ID = ROLE_CASEMGR.ID AND ROLE_CASEMGR.CLASSCODE = 'AGNT'     
LEFT OUTER JOIN DBO.T_ENTITYNAME T_ENTITYNAME_1 (NOLOCK) ON T_ENTITYNAME_1.ENTITY_ID = ROLE_CASEMGR.PLAYER_ID AND T_ENTITYNAME_1.USECODE = 'L'     
LEFT OUTER JOIN DBO.T_ATTRIBUTE ATTR_INITIALS (NOLOCK) ON ATTR_INITIALS.ROLE_ID = ROLE_CASEMGR.ID AND ATTR_INITIALS.NAME = 'USER_INITIALS'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_LICENSE (NOLOCK) ON UCS_LICENSE.ID = ROLE_CASEMGR.CODE_ID     
LEFT OUTER JOIN DBO.T_ATTRIBUTE ATTR_DATEENDED (NOLOCK) ON ATTR_DATEENDED.ACT_ID = ACT_DOTDETAIL.ID AND ATTR_DATEENDED.NAME = 'DOTDTL_DATEENDED' AND ATTR_DATEENDED.TYPE = 'IVL'     
LEFT JOIN DBO.A_ACT ACUITYBOTH (NOLOCK) ON ACUITYBOTH.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND ACUITYBOTH.CLASSCODE = 'OBS' AND ACUITYBOTH.METACODE = 'DOTDTL_BEGINACUITYBOTH_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_ACUITYBOTH (NOLOCK) ON UCS_ACUITYBOTH.ID =  ACUITYBOTH.VALUECODE_ID    
LEFT JOIN DBO.A_ACT ACUITYLEFT (NOLOCK) ON ACUITYLEFT.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND ACUITYLEFT.CLASSCODE = 'OBS' AND ACUITYLEFT.METACODE = 'DOTDTL_BEGINACUITYLEFT_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_ACUITYLEFT (NOLOCK) ON UCS_ACUITYLEFT.ID =  ACUITYLEFT.VALUECODE_ID     
LEFT JOIN DBO.A_ACT ACUITYRIGHT (NOLOCK) ON ACUITYRIGHT.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND ACUITYRIGHT.CLASSCODE = 'OBS' AND ACUITYRIGHT.METACODE = 'DOTDTL_BEGINACUITYRIGHT_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_ACUITYRIGHT (NOLOCK) ON UCS_ACUITYRIGHT.ID = ACUITYRIGHT.VALUECODE_ID     
LEFT JOIN DBO.A_ACT ACUITYBALANCE (NOLOCK) ON ACUITYBALANCE.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND ACUITYBALANCE.CLASSCODE = 'OBS' AND ACUITYBALANCE.METACODE = 'DOTDTL_BEGINBALANCE_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_ACUITYBALANCE (NOLOCK) ON UCS_ACUITYBALANCE.ID = ACUITYBALANCE.VALUECODE_ID     
LEFT JOIN DBO.A_ACT COLORVISION (NOLOCK) ON COLORVISION.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND COLORVISION.CLASSCODE = 'OBS' AND COLORVISION.METACODE = 'DOTDTL_BEGINCOLORVISION_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_COLORVISION (NOLOCK) ON UCS_COLORVISION.ID = COLORVISION.VALUECODE_ID    
LEFT JOIN DBO.A_ACT HEARINGLEFT (NOLOCK) ON HEARINGLEFT.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND HEARINGLEFT.CLASSCODE = 'OBS' AND HEARINGLEFT.METACODE = 'DOTDTL_BEGINHEARINGLEFT_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_HEARINGLEFT (NOLOCK) ON UCS_HEARINGLEFT.ID =  HEARINGLEFT.VALUECODE_ID     
LEFT JOIN DBO.A_ACT HEARINGRIGHT (NOLOCK) ON HEARINGRIGHT.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND HEARINGRIGHT.CLASSCODE = 'OBS' AND HEARINGRIGHT.METACODE = 'DOTDTL_BEGINHEARINGRIGHT_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_HEARINGRIGHT (NOLOCK) ON UCS_HEARINGRIGHT.ID = HEARINGRIGHT.VALUECODE_ID     
LEFT JOIN DBO.A_ACT LIVERFUNCTION (NOLOCK) ON LIVERFUNCTION.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND LIVERFUNCTION.CLASSCODE = 'OBS' AND LIVERFUNCTION.METACODE = 'DOTDTL_BEGINLIVERFUNCTION_FK'     
LEFT OUTER JOIN DBO.V_UNIFIEDCODESET UCS_LIVERFUNCTION (NOLOCK) ON UCS_LIVERFUNCTION.ID = LIVERFUNCTION.VALUECODE_ID     
LEFT JOIN DBO.A_ACT BEGINWEIGHT (NOLOCK) ON BEGINWEIGHT.ACT_PARENT_ID = ACT_DOTDETAIL.ID AND BEGINWEIGHT.CLASSCODE = 'OBS' AND BEGINWEIGHT.METACODE = 'DOTDTL_BEGINWEIGHT' 


