
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_CONCERN_LIST]
AS 
SELECT  
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_CONCERNALL.ID AS CONCERNALL_ID,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CONCERNALL.VALUECODE_ID) AS CONCERNALL_CONCERN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_ASSOCIATEDDOMAIN_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_ASSOCIATEDDOMAIN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_ASSOCSERVICE_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_ASSOCSERVICE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_SCOPE_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_SCOPE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_CLASSIFICATION_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_CLASSIFICATION,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_PRIORITY_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_PRIORITY,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_INTERVENTIONNEEDED_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_INTERVENTIONNEEDED,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_NOINTERVENTIONREASON_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_NOINTERVENTIONREASON,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_EVALUATEDBY_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_EVALUATEDBY,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_HASPLAN_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_HASPLAN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_USESRESOURCES_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_USESRESOURCE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_CONDITIONCONTROL_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_CONDITIONCONTROL,
	ACT_CONCERNALL.EFFECTIVETIME_BEG AS CONCERNALL_EVALUATIONDATE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_TIMEOFRATING_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_TIMEOFRATING,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_KNOWLEDGERATING_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_KNOWLEDGERATING,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_BEHAVIORRATING_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_BEHAVIORRATING,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_SIGNSSYMPTOMS_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_SIGNSSYMPTOMS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CONCALL_DISPOSITIONS_FK',ACT_CONCERNALL.ID,'VALUECODE_ID') AS CONCERNALL_DISPOSITIONS
FROM 
	A_ACT ACT_CONCERNALL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_CONCERNALL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_CONCERNALL.METACODE='CONCALL_ID'
