
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_EPIDEMIOLOGY_TBSITE]
AS
SELECT DV_PHCASE.DVSVC_ROWID AS TBSITE_SERVICE_FK, DV_PHCASE.DVSVC_PATIENT_FK AS TBSITE_PATIENT_FK,ACT_TBSITE.ID AS TBSITE_ID,
DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISPULMONARY',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISPULMONARY,
DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISEXTRAPULMONARY',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISEXTRAPULMONARY,
DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISINFECTIOUS',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISINFECTIOUS,
DBO.[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](DV_PHCASE.DVSVC_PATIENT_FK,'VALUECODE_ID','TBIMMIGRANTSTATUS_FK') AS TBSITE_TBIMMIGRANTSTATUS,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODBEGINMONTH_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODBEGINMONTH,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODBEGINYEAR_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODBEGINYEAR,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODENDMONTH_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODENDMONTH,
DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODENDYEAR_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODENDYEAR

FROM A_ACT ACT_TBSITE (NOLOCK) 
INNER JOIN A_ACT ACT_DOCBODY (NOLOCK) ON ACT_TBSITE.ACT_PARENT_ID=ACT_DOCBODY.ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
INNER JOIN DV_SERVICE DV_PHCASE (NOLOCK) ON DV_PHCASE.DVSVC_ROWID=ACT_DOCBODY.ACT_PARENT_ID

WHERE ACT_TBSITE.CLASSCODE='DOCSECT' AND ACT_TBSITE.METACODE='TBSITE_ID' AND ACT_TBSITE.STATUSCODE = 'ACTIVE'

