
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_PATIENTDATA_PROGRAMS]
AS
SELECT  
	ACT_PROG.[ID] AS PROG_PROGRAMID, 
	VPATIENTFOLDER.PATIENT_ID AS PROG_PATIENTID, 
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](ACT_PROG.CODE_ID) AS PROG_PROGRAM,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PROG_ISELIGIBLE', ACT_PROG.ID, 'VALUEBOOL') AS PROG_ISELIGIBLE, 
	ACT_PROG.EFFECTIVETIME_BEG AS PROG_ENROLLEDDATE,
	ACT_PROG.[VALUEBOOL] AS PROG_ISCURRENT
FROM 
	DBO.A_ACT ACT_PROG (NOLOCK) 
	INNER JOIN [VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER  (NOLOCK) ON ACT_PROG.ACT_PARENT_ID = VPATIENTFOLDER.ACT_FOLDER_ID
WHERE 
	ACT_PROG.METACODE='PROG_ID' AND ACT_PROG.STATUSCODE = 'ACTIVE'
