
CREATE VIEW [AtlasInternal].[VIEW_NCM_VISIT_SMOKING]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_SMOKING.ID AS SMOK_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('SMOK_SMOKING', ACT_SMOKING.ID, 'VALUEBOOL') AS SMOK_SMOKING,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('SMOK_SMOKES', ACT_SMOKING.ID, 'VALUEBOOL') AS SMOK_SMOKES,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('SMOK_FREQUENCY', ACT_SMOKING.ID, 'VALUENUMERATOR') AS SMOK_FREQUENCY
FROM 
	A_ACT ACT_SMOKING (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_SMOKING.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_SMOKING.METACODE='SMOK_ID' AND ACT_SMOKING.STATUSCODE = 'ACTIVE'

