
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_PPD]
AS
SELECT 
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	ACT_PPD.ID AS PPD_ID,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](OBSPPD.METHODCODE_ID) AS PPD_PPDTYPE_TEXT,
	ACT_PPD.EFFECTIVETIME_BEG AS PPD_DATE,
	ACT_PPD.ACTIVITYTIME_BEG AS PPD_INTERPRETED,
	(CASE WHEN [DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](OBSPPD.INTERPRETATIONCODE_ID)='ABNORMAL' THEN 1 ELSE 0 END) AS PPD_ISPOSITIVE,
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID](ACT_PPD.ID , 'VALUESTRING' , 'PPD_WHERE') AS PPD_WHERE,
	(CASE WHEN DATEDIFF(HOUR, ACT_PPD.EFFECTIVETIME_BEG, ACT_PPD.ACTIVITYTIME_BEG) <= 48 THEN 1 ELSE 0 END) AS PPD_CLEARANCEMET,
	ACT_PPD.VALUENUMERATOR AS PPD_RESULT,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](ACT_PPD.ID, 'PPD_NEXTDUEDATE', 'SEQL', 'EFFECTIVETIME_BEG') AS PPD_NEXTDUEDATE,
	ACT_PPD.TEXT AS PPD_COMMENTS 
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_PPD (NOLOCK) ON ACT_PPD.ACT_PARENT_ID=DOCBODY.ID AND ACT_PPD.METACODE='PPD_ID' AND ACT_PPD.STATUSCODE <> 'NULLIFIED'
	INNER JOIN A_OBSERVATION OBSPPD (NOLOCK) ON OBSPPD.ID = ACT_PPD.ID
