
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_IMMUNIZATIONSLIST]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_CDIMMUNIZATION.ID AS CASEIMMUN_ID,
	ACT_CDIMMUNIZATION.EFFECTIVETIME_BEG AS CASEIMMUN_DATE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](ACT_CDIMMUNIZATION.CODE_ID) AS CASEIMMUN_IMMUNIZATION,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYACTID] (ACT_CDIMMUNIZATION.ID,'VALUECODE_ID','CASEIMMUN_IMMUNIZATIONTYPE_FK') AS CASEIMMUN_IMMUNIZATIONTYPE,
	ACT_CDIMMUNIZATION.TEXT AS CASEIMMUN_COMMENTS
FROM 
	A_ACT ACT_CDIMMUNIZATION (NOLOCK)
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_CDIMMUNIZATION.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_CDIMMUNIZATION.METACODE='CASEIMMUN_ID' AND ACT_CDIMMUNIZATION.STATUSCODE='ACTIVE'
