
CREATE VIEW [ATLASINTERNAL].[VIEW_CMR_ANIMALREPORT_CONTACT_DATA] AS 

SELECT     DIID, CONTACTID, INSTANCEID AS ANIMALID, RLENT_FIRSTNAME, RLENT_LASTNAME, RLENT_MIDDLEINITIAL, RLENT_NAMESUFFIX, RLENT_AGE, RLENT_DOB, RLENT_SEX, 
                      RLENT_CONTACTTYPE, RLENT_DATESOFCONTACT, RLENT_STREETADDRESS, RLENT_APARTMENT, RLENT_CITY, RLENT_ZIP, RLENT_PHONE, RLENT_DISTRICT, 
                      RLENT_PROPHYLAXISMEDICATION, RLENT_INVESTIGATORDR, RLENT_EXPEVENTDR, RLENT_EXPEVENT, RLENT_PRIORITYDR, RLENT_CLUSTERID, 
                      RLENT_STATUSDR, FOLDERID, RLENT_ELECTRONICCONTACT, RLENT_EMAIL
FROM         [ATLASINTERNAL].VIEWSYSTEMCONTACTDATA
WHERE     (RECORDTYPE = 'AR')


