
CREATE VIEW [AtlasInternal].[VIEW_NCM_CASEFLOW_TBMEDICATION]
AS
SELECT 
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	ACT_TBMED.ID AS TBMED_ID,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_TBMED.ID ,'CODE_ID') AS TBMED_MEDICATION_TEXT,
	SUBSTANCEADMINISTRATION.DOSEQUANTITY_LO AS TBMED_DOSAGE,
	ACT_TBMED.EFFECTIVETIME_BEG AS TBMED_DATEBEGUN,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](SUBSTANCEADMINISTRATION.DOSEQUANTITY_ALT_UNIT_ID) AS TBMED_UNIT_TEXT,
	--SugannyaB 08/09/2011 Issue#110408 Function to get boolean value needs to be called
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](ACT_TBMED.ID,'TBMED_ISPERBODYWEIGHT') AS TBMED_ISPERBODYWEIGHT,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](SUBSTANCEADMINISTRATION.ROUTECODE_ID) AS TBMED_ROUTE_TEXT,
	[DBO].[MDF_UCS_FULLNAME_ACTUCS_BYACTID]( ACT_TBMED.ID, 'EFFECTIVETIME_FRQ_ID') AS TBMED_FREQUENCY_TEXT,
	ACT_TBMED.EFFECTIVETIME_DUR AS TBMED_DURATION,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID]( ACT_TBMED.EFFECTIVETIME_DUR_UNIT) AS TBMED_TIMEUNIT_TEXT,
	SUBSTANCEADMINISTRATION.MAXDOSEQUANTITY_NMR AS TBMED_TOTALDOSES,
	ACT_TBMED.EFFECTIVETIME_END AS TBMED_DATESTOPPED,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](REASON.REASONCODE_ID) AS TBMED_REASONSTOPPED_TEXT,
	---SBAIN HTTPS://DEVELOPMENT.ATLASDEV.COM/ISSUE_VIEW.ASP?ISSUENBR=69200 5/12/2010 --ACTIVE COLUMN REMOVED.
	ACT_TBMED.TEXT AS TBMED_COMMENTS 
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_TBMED (NOLOCK) ON ACT_TBMED.ACT_PARENT_ID=DOCBODY.ID AND ACT_TBMED.CLASSCODE='SBADM' AND ACT_TBMED.MOODCODE='RQO' AND ACT_TBMED.METACODE='TBMED_ID' AND ACT_TBMED.STATUSCODE <> 'NULLIFIED'
	INNER JOIN A_SUBSTANCEADMINISTRATION SUBSTANCEADMINISTRATION (NOLOCK) ON SUBSTANCEADMINISTRATION.ID = ACT_TBMED.ID
	LEFT JOIN T_ACTREASON REASON (NOLOCK) ON REASON.ACT_ID = ACT_TBMED.ID AND REASON.STATUSCHANGE = 'STOP'

