
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_PATIENTDATA_MULTIPLEIDENTITIES]
AS
SELECT
	DVPER.DVPER_ROWID AS [IDE_PATIENTID],
	ATTRIBUTE_PSNTRY.VALUETS [IDE_ENTRYDATE],
	ATTRIBUTE_PSNTRY.VALUETSEND AS [IDE_LASTUPDATE],
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](ENTITY_PSN.ID, 'VALUECODE_ID', 'PSNID_TYPE_FK') AS [IDE_TYPE] ,
	CASE WHEN ENTITY_PSN.ID = S_LINK.ENTITY2_ID THEN 'TRUE' ELSE 'FALSE' END AS [IDE_ISPRIMARY],
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYENTITYID](ENTITY_PSN.ID, 'PSNID_INACTIVE') AS [IDE_INACTIVE],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](INSTANCEIDENT_SOURCE.SOURCECODE_ID) AS [IDE_SOURCE],
	INSTANCEIDENT_SOURCE.SOURCE_ORTX AS [IDE_SOURCEDESCRIPTION],
	INSTANCEIDENT_SOURCE.EXTENSION AS [IDE_SOURCEIDENTIFIER], 
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](ENTITY_PSN.ID, 'VALUESTRING_TXT', 'PSNID_ACCOUNTNUM') AS [IDE_ACCOUNTNUMBER],
	ENTITYNAME_PSN.PARTGIV AS [IDE_FIRSTNAME],	
	ENTITYNAME_PSN.PARTFAM AS [IDE_LASTNAME],
	ENTITYNAME_PSN.PARTMID AS [IDE_MIDDLENAME],
	ENTITYNAME_PSN.PARTSFX AS [IDE_NAMESUFFIX],
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](ENTITY_PSN.ID, 'H', 'TEL') AS [IDE_HOMEPHONE],
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](ENTITY_PSN.ID, 'A', 'TEL') AS [IDE_CELLPHONE],
	DVIDEN.DVIDEN_SSN AS [IDE_SSN],
	DVIDEN.DVIDEN_DOB AS [IDE_DOB],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](DVIDEN.DVIDEN_SEXCODE_ID) AS [IDE_GENDER],
	ENTITYNAME_PSN.VALIDTIME_BEG AS [IDE_FROMDATE],
	ENTITYNAME_PSN.VALIDTIME_END AS [IDE_TODATE]
FROM
	DV_IDENTITY DVIDEN (NOLOCK) 
	INNER JOIN DBO.DV_PERSON DVPER (NOLOCK) ON DVIDEN.DVIDEN_ROOTID = DVPER.DVPER_ROWID
	INNER JOIN DBO.E_ENTITY ENTITY_PSN (NOLOCK) ON ENTITY_PSN.ID = DVIDEN.DVIDEN_ROWID AND ENTITY_PSN.CLASSCODE = 'PSN'
	INNER JOIN DBO.T_ATTRIBUTE ATTRIBUTE_PSNTRY (NOLOCK) ON ATTRIBUTE_PSNTRY.ENTITY_ID = ENTITY_PSN.ID AND ATTRIBUTE_PSNTRY.[NAME] = 'PSNID_ENTRYDATE'
	LEFT JOIN DBO.S_LINK (NOLOCK) ON S_LINK.ENTITY1_ID = ENTITY_PSN.ID AND S_LINK.[NAME] = 'PERSON-PRIMARY'
	LEFT JOIN DBO.T_ENTITYNAME ENTITYNAME_PSN (NOLOCK) ON ENTITYNAME_PSN.ENTITY_ID = ENTITY_PSN.ID AND ENTITYNAME_PSN.USECODE = 'L'
	LEFT JOIN DBO.T_INSTANCEIDENTIFIER INSTANCEIDENT_SOURCE (NOLOCK) ON INSTANCEIDENT_SOURCE.ENTITY_ID = ENTITY_PSN.ID AND INSTANCEIDENT_SOURCE.[NAME] = 'PSN_SOURCE'
