
CREATE VIEW [ATLASINTERNAL].[VIEW_SUB_NCM_TBHISTORY_PSNLINK]
AS
SELECT 
LINK.ENTITY2_ID AS TBHIST_PATIENTID,
	ACT_PHCASE.ID AS TBHIST_SERVICEID,
	ACT_DOCBODY.ID AS DOCBODY_ID
FROM
	DBO.A_ACT ACT_DOCBODY (NOLOCK) 
	INNER JOIN V_UNIFIEDCODESET UCS_TBH (NOLOCK) ON UCS_TBH.ID=ACT_DOCBODY.CODE_ID AND UCS_TBH.CONCEPTCODE  = 'TBH'
	INNER JOIN DBO.A_ACT ACT_PHCASE (NOLOCK) ON  ACT_PHCASE.ID = ACT_DOCBODY.ACT_PARENT_ID AND ACT_PHCASE.CLASSCODE = 'CASE' AND ACT_PHCASE.METACODE = 'SVC_ID'
	INNER JOIN DBO.S_LINK LINK (NOLOCK) ON  LINK.ACT1_ID = ACT_PHCASE.ID AND LINK.[NAME] = 'PATIENT-CASE'
	INNER JOIN DBO.E_ENTITY ENTITY_PSN (NOLOCK) ON  ENTITY_PSN.ID = LINK.ENTITY2_ID AND ENTITY_PSN.CLASSCODE = 'PSN'
WHERE 
	ACT_DOCBODY.CLASSCODE = 'DOCBODY' AND ACT_DOCBODY.STATUSCODE = 'ACTIVE'
