CREATE VIEW [AtlasInternal].[View_UODS_UDSection] 
AS  
SELECT  
	AREL.SOURCE_ID AS ACT_ID,    
	VUCS_SECTION.ID AS UDSECID, 
	VUCS_SECTION.FULLNAME AS UDSECNAME,
	VUCS_FIELD.FULLNAME AS UDFIELDNAME,
	VUCS_FIELD.ID AS UDFIELDID,  
	--+CMG IssueNbr:-123369
	Ax_UDFValues.valueDateTime AS UDField_valueDateTime,
	Ax_UDFValues.valueString  AS UDField_valueString,
	Ax_UDFValues.VALUE_ENTITYID  AS UDField_valueENTITYID,
	Ax_UDFValues.value_UCSID  AS UDField_valueUCSID,
	Ax_UDFValues.metaCode_UCSID  AS UDField_metaCodeUCSID,
	---CMG IssueNbr:-123369 
	ACT_SECTION.CODE_ID as SectionID,    
	VCP_Field.Field_ID AS Field_ID,    
	VCP_Section.SEC_ID AS  Sec_ID,
	VUCS_SECTION.shortName AS UDSecType,
	ACT_SECTION.ID AS UDSectionActID,
	AX_UDFVALUES.ID AS UDFieldActID,
	VCP_Section.SEC_IsListSection AS SEC_IsListSection,
	ISNull(VCP_Field.FIELD_IsRequired, 0) AS UDFieldIsRequired,
	VCP_Field.FIELD_TypeCode_ID,
	ACT_SECTION.effectiveTime_Beg AS UDSectionCreateDate
FROM 
	A_ACT AS ACT_SECTION (NOLOCK)
	INNER JOIN A_ACTRELATIONSHIP AREL (NOLOCK) ON AREL.TARGET_ID=ACT_SECTION.ID
	INNER JOIN AX_UDFVALUES (NOLOCK) ON ACT_SECTION.ID = AX_UDFVALUES.ACT_PARENT_ID
	INNER JOIN V_UNIFIEDCODESET VUCS_FIELD (NOLOCK) ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID    
	INNER JOIN V_UNIFIEDCODESET VUCS_SECTION (NOLOCK) ON  VUCS_SECTION.ID=ACT_SECTION.CODE_ID    
	LEFT JOIN VCP_UDField VCP_Field (NOLOCK) ON VCP_Field.SubjCode_Id = VUCS_FIELD.ID    
	LEFT JOIN VCP_UDSection VCP_Section (NOLOCK) ON VCP_Section.subjCode_Id = VUCS_SECTION.ID    

