
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_WOMENSHEALTHFAMILYPLANNING]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,ACT_WMNHLTH.ID AS WMNHLTH_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('WMNHLTH_WOMENSHEALTH',ACT_WMNHLTH.ID,'VALUEBOOL') AS WMNHLTH_WOMENSHEALTH,
	ACT_ENC.EFFECTIVETIME_BEG AS WMNHLTH_PAPSMEARAPPT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('WMNHLTH_MONTHLYBREASTEXAM',ACT_WMNHLTH.ID,'VALUEBOOL') AS WMNHLTH_MONTHLYBREASTEXAM,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('WMNHLTH_FOLICACID',ACT_WMNHLTH.ID,'VALUEBOOL') AS WMNHLTH_FOLICACID,
	ACT_LASTMAMMOGRAMAPPT.EFFECTIVETIME_BEG AS WMNHLTH_LASTMAMMOGRAMAPPT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('WMNHLTH_FAMILYPLANNING',ACT_WMNHLTH.ID,'VALUEBOOL') AS WMNHLTH_FAMILYPLANNING,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('WMNHLTH_FAMILYPLANNINGMETHOD_FK',ACT_WMNHLTH.ID,'VALUECODE_ID') AS WMNHLTH_FAMILYPLANNINGMETHOD,
	ACT_FAMILYPLANNINGNEXTAPPT.EFFECTIVETIME_BEG AS WMNHLTH_FAMILYPLANNINGNEXTAPPT
FROM 
	A_ACT ACT_WMNHLTH (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_WMNHLTH.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
	LEFT OUTER JOIN A_ACTRELATIONSHIP AREL (NOLOCK) 
	INNER JOIN A_ACT ACT_ENC (NOLOCK) ON ACT_ENC.ID=AREL.TARGET_ID AND ACT_ENC.METACODE='WMNHLTH_PAPSMEARAPPT'
	ON AREL.SOURCE_ID=ACT_WMNHLTH.ID AND AREL.TYPECODE='COMP'
	LEFT OUTER JOIN A_ACTRELATIONSHIP AREL_LASTMAMMOGRAMAPPT  (NOLOCK)
	INNER JOIN A_ACT ACT_LASTMAMMOGRAMAPPT (NOLOCK) ON ACT_LASTMAMMOGRAMAPPT.ID=AREL_LASTMAMMOGRAMAPPT.TARGET_ID AND ACT_LASTMAMMOGRAMAPPT.METACODE='WMNHLTH_LASTMAMMOGRAMAPPT' 
	ON AREL_LASTMAMMOGRAMAPPT.SOURCE_ID=ACT_WMNHLTH.ID AND AREL_LASTMAMMOGRAMAPPT.TYPECODE='COMP'
	LEFT OUTER JOIN A_ACTRELATIONSHIP AREL_FAMILYPLANNINGNEXTAPPT (NOLOCK)
	INNER JOIN A_ACT ACT_FAMILYPLANNINGNEXTAPPT (NOLOCK) ON ACT_FAMILYPLANNINGNEXTAPPT.ID=AREL_FAMILYPLANNINGNEXTAPPT.TARGET_ID AND ACT_FAMILYPLANNINGNEXTAPPT.METACODE='WMNHLTH_FAMILYPLANNINGNEXTAPPT' 
	ON AREL_FAMILYPLANNINGNEXTAPPT.SOURCE_ID=ACT_WMNHLTH.ID AND AREL_FAMILYPLANNINGNEXTAPPT.TYPECODE='COMP'
WHERE 
	ACT_WMNHLTH.METACODE='WMNHLTH_ID' AND ACT_WMNHLTH.STATUSCODE='ACTIVE'
