
CREATE VIEW [AtlasInternal].[View_UODS_UDForm]
AS
SELECT AREL.SOURCE_ID AS Act_ID,
ACT_FORM.ID AS UDFormID,
ACT_FORM.CODE_ID AS UDFormDefID,
ACT_FORM.VALUECODE_ID AS DISEASE_ID, 
VUCS_SECTION.FULLNAME AS UDSecName,
VUCS_SECTION.SHORTNAME AS UDSecType,
VUCS_FIELD.FULLNAME AS UDFieldName,
VUCS_FIELD.ID AS UDFieldID,
VUCS_SECTION.ID AS UDSectionDefID,
ACT_SECTION.ID AS UDSectionActID,
AX_UDFVALUES.ID AS UDFieldActID,
--+CMG IssueNbr:-123369
Ax_UDFValues.valueDateTime AS UDField_valueDateTime,
Ax_UDFValues.valueString  AS UDField_valueString,
Ax_UDFValues.VALUE_ENTITYID  AS UDField_valueENTITYID,
Ax_UDFValues.value_UCSID  AS UDField_valueUCSID,
Ax_UDFValues.metaCode_UCSID  AS UDField_metaCodeUCSID,
---CMG IssueNbr:-123369
VCP_Field.Field_ID AS Field_ID,
VCP_Section.SEC_ID AS  Sec_ID,
VCP_Section.SEC_IsListSection,
ISNull(VCP_Field.FIELD_IsRequired, 0) AS UDFieldIsRequired,
VCP_Field.FIELD_TypeCode_ID,
--+SKUMAR IssueNbr:89539 Added UDForm Fullname, Description and CreateDate
VUCS_FORM.FULLNAME AS UDFormName,
(CASE WHEN ISNULL(T_ATTRIBUTE.valueString, '') = '' THEN VCP_UDForm.FRM_DESC ELSE T_ATTRIBUTE.valueString END) AS UDFormDesc,
ACT_FORM.EFFECTIVETIME_BEG AS UDFormCreateDate
---SKUMAR IssueNbr:89539
FROM A_ACT AS ACT_FORM (NOLOCK)
INNER JOIN A_ActRelationship AREL (NOLOCK) ON AREL.TARGET_ID=ACT_FORM.ID AND AREL.TYPECODE='COMP'
INNER JOIN A_ACT AS ACT_SECTION (NOLOCK) ON ACT_SECTION.ACT_PARENT_ID =ACT_FORM.ID AND ACT_SECTION.CLASSCODE='DOCSECT' 
INNER JOIN AX_UDFVALUES (NOLOCK) ON ACT_SECTION.ID = AX_UDFVALUES.ACT_PARENT_ID
LEFT JOIN V_UNIFIEDCODESET VUCS_FORM (NOLOCK) ON VUCS_FORM.ID = ACT_FORM.CODE_ID	---SKUMAR IssueNbr:89539
LEFT JOIN V_UNIFIEDCODESET VUCS_FIELD (NOLOCK) ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID
LEFT JOIN V_UNIFIEDCODESET VUCS_SECTION (NOLOCK) ON  VUCS_SECTION.ID=ACT_SECTION.CODE_ID
LEFT JOIN VCP_UDForm (NOLOCK) ON VCP_UDForm.SubjCode_Id = ACT_FORM.CODE_ID	---SKUMAR IssueNbr:89539
LEFT JOIN T_ATTRIBUTE (NOLOCK) ON ACT_FORM.ID = T_ATTRIBUTE.ACT_ID AND T_ATTRIBUTE.NAME = 'UDFORM_Description' ---SKUMAR IssueNbr:89539
LEFT JOIN VCP_UDField VCP_Field (NOLOCK) ON VCP_Field.SubjCode_Id = AX_UDFVALUES.METACODE_UCSID
LEFT JOIN VCP_UDSection VCP_Section (NOLOCK) ON VCP_Section.subjCode_Id = ACT_SECTION.CODE_ID
--+abhattacharya : Issue#86657 - Added active filter on docbody act
WHERE ACT_FORM.CLASSCODE='DOCBODY' AND ACT_FORM.STATUSCODE='active'
---abhattacharya : Issue#86657 - Added active filter on docbody act

