
CREATE VIEW [AtlasInternal].[VIEW_NCM_CD_CONTACT_SPECIMEN]
AS

SELECT 
CONTACTINFOVIEW.PATIENT_ID AS PATIENT_ID,
CONTACTINFOVIEW.SERVICE_ID AS SERVICE_ID,     --Saravanakumar Issue #110413 08/16/2011
CONTACTINFOVIEW.CONTDEMO_CONTACT_ID AS CONTDEMO_ID,
ACT_CONTACTSPECIMEN.ID AS CDCONTSPEC_ID,
ACT_CONTACTSPECIMEN.EFFECTIVETIME_BEG AS CDCONTSPEC_DATECOLLECTED,
ACT_CONTACTSPECIMEN.ACTIVITYTIME_BEG AS CDCONTSPEC_DATETESTED,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ENTITY_SPECTYPE.CODE_ID) AS CDCONTSPEC_SPECIMENTYPE_TEXT,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(OBSERVATION_CONTACTSPECIMEN.INTERPRETATIONCODE_ID) AS CDCONTSPEC_RESULT_TEXT,
DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCONTSPEC_ANTIBIOTICPRIORTOTEST',ACT_CONTACTSPECIMEN.ID,'VALUEBOOL') AS      CDCONTSPEC_ANTIBIOTICPRIORTOTEST

FROM   A_OBSERVATION OBSERVATION_CONTACTSPECIMEN (NOLOCK) 
INNER JOIN A_ACT ACT_CONTACTSPECIMEN (NOLOCK) ON OBSERVATION_CONTACTSPECIMEN.ID=ACT_CONTACTSPECIMEN.ID AND ACT_CONTACTSPECIMEN.METACODE='CDCONTSPEC_ID' AND ACT_CONTACTSPECIMEN.STATUSCODE<>'NULLIFIED'      
INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_CONTACT_INFORMATION] CONTACTINFOVIEW (NOLOCK) ON ACT_CONTACTSPECIMEN.ACT_PARENT_ID=CONTACTINFOVIEW.CONTACT_FOLDER_ID AND CONTACTINFOVIEW.CONTACT_FORMLINK='CDI'
LEFT JOIN P_PARTICIPATION PARTICIPATION_SPECTYPE (NOLOCK) ON ACT_CONTACTSPECIMEN.ID=PARTICIPATION_SPECTYPE.ACT_ID 
AND PARTICIPATION_SPECTYPE.TYPECODE='SPC'
LEFT JOIN R_ROLE ROLE_SPECTYPE (NOLOCK) ON PARTICIPATION_SPECTYPE.ROLE_ID=ROLE_SPECTYPE.ID AND ROLE_SPECTYPE.CLASSCODE='SPEC' AND 
ROLE_SPECTYPE.CODE_ID=DBO.MDF_UCS_GETID_UCSVDOMAIN_BYDOMAINOIDCONCEPTCODE('2.16.840.1.113883.5.111','P')
LEFT JOIN E_ENTITY ENTITY_SPECTYPE (NOLOCK) ON ROLE_SPECTYPE.PLAYER_ID=ENTITY_SPECTYPE.ID AND ENTITY_SPECTYPE.CLASSCODE='MAT'    

