
CREATE VIEW [AtlasInternal].[VIEW_NCM_CASEFLOW_CXR]
AS
SELECT 
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	ACT_CXR.ID AS CXR_ID, 
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](OBSRESULT.INTERPRETATIONCODE_ID) AS CXR_CXRRESULT_TEXT, 
	ACT_CXR.EFFECTIVETIME_BEG AS CXR_DATE,
	DBO.[MDF_UCS_FULLNAME_UCS_BYUCSID](ACT_CXR.VALUECODE_ID) AS CXR_CXRTYPE_TEXT,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](TVALUE.VALUECODE_ID) AS CXR_CXRCONDITION_TEXT,
	DBO.[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID] (ACT_CXR.ID,'VALUESTRING','CXR_WHERE') AS CXR_WHERE,
	[DBO].[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE] (ACT_CXR.ID, 'CXR_NEXTDUEDATE', 'SEQL', 'EFFECTIVETIME_BEG') AS CXR_NEXTDUEDATE,
	ACT_CXR.TEXT AS CXR_COMMENTS 
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_CXR (NOLOCK) ON ACT_CXR.ACT_PARENT_ID=DOCBODY.ID AND ACT_CXR.METACODE='CXR_ID' AND ACT_CXR.STATUSCODE <> 'NULLIFIED'
	INNER JOIN A_OBSERVATION OBSRESULT (NOLOCK) ON OBSRESULT.ID = ACT_CXR.ID
	--SugannyaB 08/09/2011 Issue#110408 Sections not having results as abnormal should also be fetched
	LEFT JOIN T_VALUE TVALUE(NOLOCK) ON ACT_CXR.ID = TVALUE.ACT_ID AND TVALUE.METACODE = 'CXR_CXRCONDITION_FK'

