CREATE  VIEW [AtlasInternal].[VIEW_CMR_EXPOSURE_LOCATION]
AS
SELECT INSTANCEIDENTIFIER.EXTENSION AS DIID,
    OBSERVATION.[ID] AS [DEE_ROWID],
    R_ROLE.[SCOPER_ID] AS [DEE_LOCATIONDR], 
    T_ENTITYNAME.[TRIVIALNAME] AS [DEE_LOCATION_NAME], 
    E_Entity.[CODE_ID] AS [DEE_LOCATIONTYPEDR],
    UCSLocType.[FullName] AS [DEE_LOCATIONTYPE],
    ACT.[EFFECTIVETIME_BEG] AS [DEE_EXPOSURETIMEBEGIN], 
    ACT.[EFFECTIVETIME_END] AS [DEE_EXPOSURETIMEEND], 
    ACT.[CODE_ID] AS [DEE_EXPOSURETYPEDR], 
    UCS.[FULLNAME] AS [DEE_EXPOSURETYPE] ,
    LOCCONTACT.ValueString AS LOCATIONCONTACT,
    ACT.STATUSCODE AS LOCATIONISACTIVE,
    TELECOM.ADDRESS AS LOCATIONPHONE,
    CASE WHEN cast(isnull(ADDRESS.[partSal],'') as varchar(400)) = '' THEN '' ELSE cast(ADDRESS.[partSal] as varchar(400)) END + 
 CASE WHEN ISNULL(ADDRESS.[partAptNum],'') = '' THEN '' ELSE 
    CASE WHEN ISNULL(ADDRESS.[partSal],'') <> '' THEN ', ' + ADDRESS.[partAptNum] ELSE  ADDRESS.[partAptNum] END END +  
 CASE WHEN ISNULL(ADDRESS.[partCty],'') = '' THEN '' ELSE 
    CASE WHEN ISNULL(ADDRESS.[partSal],'') <> '' OR ISNULL(ADDRESS.[partAptNum],'') <> '' THEN ', ' + ADDRESS.[partCty] ELSE  ADDRESS.[partCty] END END +
 CASE WHEN ISNULL(ADDRESS.[partSta],'') = '' THEN '' ELSE 
    CASE WHEN ISNULL(ADDRESS.[partSal],'') <> '' OR ISNULL(ADDRESS.[partAptNum],'') <> '' OR ISNULL(ADDRESS.[partCty],'') <> '' THEN ', ' + ADDRESS.[partSta] ELSE  ADDRESS.[partSta] END END +  
 CASE WHEN ISNULL(ADDRESS.[partZip],'') = '' THEN '' ELSE 
    CASE WHEN (ISNULL(ADDRESS.[partSal],'') <> '' OR ISNULL(ADDRESS.[partAptNum],'') <> '' OR ISNULL(ADDRESS.[partCty],'') <> '' OR ISNULL(ADDRESS.[partSta],'') <> '') THEN ', ' + ADDRESS.[partZip] ELSE  ADDRESS.[partZip] END END AS LOCATION_ADDRESS
FROM [A_Act] ACT (nolock) 
    INNER JOIN [A_Observation] OBSERVATION (nolock) ON  ACT.[ID]=OBSERVATION.[ID] 
    LEFT JOIN [P_Participation] Participation (nolock) ON  ACT.[ID]=Participation.[Act_ID] AND Participation.[metaCode] = 'DEE_LaboratoryDR'
    LEFT JOIN [R_Role] R_Role (nolock) ON  R_Role.[ID]=Participation.[Role_ID] AND R_Role.CLASSCODE='LOCE'
    LEFT JOIN [E_Entity] E_Entity (nolock) ON  E_Entity.[ID]=R_Role.[scoper_ID] AND E_Entity.CLASSCODE='PLC'
    LEFT JOIN [V_UnifiedCodeSet] AS UCSLocType (nolock) ON UCSLocType.[ID]=E_Entity.[CODE_ID]
    LEFT JOIN [T_EntityName] T_EntityName (nolock) ON  E_Entity.[ID]=T_EntityName.[Entity_ID] AND T_EntityName.[metaCode] = 'LOC_Name' AND T_EntityName.[useCode] = 'SRCH'
    LEFT JOIN [T_Attribute] LOCCONTACT (nolock) ON  [E_Entity].[ID]=LOCCONTACT.[Entity_ID] AND LOCCONTACT.[name] = 'LOC_PrimaryContact' AND LOCCONTACT.[type] = 'ST'
    LEFT JOIN [V_UnifiedCodeSet] AS UCS (nolock) ON  UCS.[ID]=ACT.[code_ID] 
    INNER JOIN A_ACT CASEACT (nolock) ON CASEACT.ID = ACT.ACT_PARENT_ID AND CASEACT.METACODE IN ( 'PR_ROWID','AI_RowId') AND CASEACT.CLASSCODE = 'CASE' AND CASEACT.MOODCODE = 'EVN'
    INNER JOIN T_INSTANCEIDENTIFIER INSTANCEIDENTIFIER (nolock) ON CASEACT.ID = INSTANCEIDENTIFIER.ACT_ID AND (INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.1%' OR INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.8%')
    LEFT OUTER JOIN DBO.E_PLACE PLACE (nolock) ON R_ROLE.SCOPER_ID = PLACE.ID 
    LEFT OUTER JOIN DBO.T_ENTITYTELECOM TELECOM (nolock) ON PLACE.ID = TELECOM.ENTITY_ID AND TELECOM.[SCHEME] = 'TEL' AND TELECOM.[USECODE] = 'PHYS'
    LEFT OUTER JOIN DBO.T_ENTITYADDRESS ADDRESS (nolock) ON PLACE.ID = ADDRESS.ENTITY_ID AND ADDRESS.USECODE = 'PHYS'
    WHERE ACT.[metaCode] = 'DEE_RowID' AND ACT.STATUSCODE <> 'NULLIFIED'

