CREATE VIEW [AtlasInternal].[VIEW_NCM_ENCOUNTER_ENCOUNTERWORKERS_LIST]
AS
SELECT DISTINCT
	ACT_ENCOUNTERWORKERS.ID AS ENCOUNTERWORKERS_ID,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_ID,
	ENCWRKLUSER.NAMECOMBINED AS ENCWRKL_USER,
	ACT_ENCOUNTERWORKERS.EFFECTIVETIME_BEG AS ENCWRKL_DATEBEGUN, 
	CONVERT(VARCHAR(8),ACT_ENCOUNTERWORKERS.ACTIVITYTIME_BEG,108) AS ENCWRKL_VISITTIME, 
	CASE WHEN CHARINDEX('DW1',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_MONDAY], 
	CASE WHEN CHARINDEX('DW2',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_TUESDAY], 
	CASE WHEN CHARINDEX('DW3',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_WEDNESDAY], 
	CASE WHEN CHARINDEX('DW4',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_THURSDAY], 
	CASE WHEN CHARINDEX('DW5',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_FRIDAY], 
	CASE WHEN CHARINDEX('DW6',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_SATURDAY], 
	CASE WHEN CHARINDEX('DW7',[ACT_ENCOUNTERWORKERS].[EFFECTIVETIME_TXT])=0 THEN 'False' ELSE 'True' END AS [ENCWRKL_SUNDAY], 
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(MANAGERROLE.CODE_ID) AS ENCWRKL_USER_LICENSE
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT SVC(NOLOCK) ON SVC.ID=DVSVC.DVSVC_RowID
	INNER JOIN A_ACT FOLDER(NOLOCK) ON FOLDER.ID=SVC.ACT_PARENT_ID
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=FOLDER.ID AND DOCBODY.CLASSCODE='DOCBODY' 
	AND DOCBODY.CODE_ID = (SELECT ID FROM V_UNIFIEDCODESET (NOLOCK) WHERE CONCEPTCODE='ENC' AND SHORTNAME='ENCOUNTER') 
	INNER JOIN DBO.A_ACT ACT_ENCOUNTERWORKERS (NOLOCK) ON ACT_ENCOUNTERWORKERS.ACT_PARENT_ID=DOCBODY.ID AND ACT_ENCOUNTERWORKERS.METACODE = 'ENCWRKL_ID'  AND ACT_ENCOUNTERWORKERS.STATUSCODE = 'ACTIVE'
	LEFT JOIN [ATLASINTERNAL].[VIEW_CMN_PARTICIPATION_ROLE_ENTITY]  ENCWRKLUSER (NOLOCK) ON ACT_ENCOUNTERWORKERS.ID=ENCWRKLUSER.ACT_ID AND ENCWRKLUSER.TYPECODE='PRF' AND ENCWRKLUSER.USECODE = 'L'
	LEFT JOIN DBO.R_ROLE MANAGERROLE (NOLOCK) ON MANAGERROLE.ID = ENCWRKLUSER.ROLEID AND MANAGERROLE.CLASSCODE='AGNT'
