
Create  VIEW [AtlasInternal].[VIEW_NCM_RVCT_MAIN]
AS
SELECT 
	 DBO.MDF_ROLE_GETVALUE_ACTPARTICIPATIONROLE_BYACTID([CASE].ACT_PARENT_ID, 'PLAYER_ID') AS PATIENT_ID
	,ACT_DOCBODY.Act_CaseNcm_ID  AS SERVICE_ID 
	,ACT_RVCTPG.ID AS RVCTPG_ID
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_CASEVERIFICATION_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_CASEVERIFICATION_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_COUNTINGCOUNTY_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_COUNTINGCOUNTY_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_STATEREPORTING_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_STATEREPORTING_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_RACEASIAN', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_RACEASIANSPECIFY_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_RACENATIVEHAWAIIAN', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_NATIVESPECIFY_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_NOTUS', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_ORIGINCOUNTRY_FK
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_MAJORSITEOTHER', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_MAJOROTHERCODE_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_TISSUECULTURECODE1_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_TISSUECULTURECODE1_TEXT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_STATEREPORTING_FK',ACT_RVCTPG.ID,'TITLE') AS RVCTPG_STATECASENUMBER
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CITYCOUNTYCASESTATE_FK',ACT_RVCTPG.ID,'TITLE') AS RVCTPG_CITYCOUNTYCASENUMBER
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DATESUBMITTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_DATESUBMITTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DATEREPORTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_DATEREPORTED
	,DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DATECOUNTED',ACT_RVCTPG.ID,'EFFECTIVETIME_BEG') AS RVCTPG_DATECOUNTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_COUNTINGCITY_TEXT',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_COUNTINGCITY_TEXT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_WITHINCITYLIMITSYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_WITHINCITYLIMITSYES
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_COUNTINGZIPCODE_TEXT',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_COUNTINGZIPCODE_TEXT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DOB',ACT_RVCTPG.ID,'EffectiveTime_Txt') AS RVCTPG_DOB 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_GENDERMALE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_GENDERMALE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_GENDERFEMALE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_GENDERFEMALE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACEAMERICANINDIAN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACEAMERICANINDIAN 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACEASIAN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACEASIAN 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACEBLACK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACEBLACK 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACENATIVEHAWAIIAN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACENATIVEHAWAIIAN 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACEWHITE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACEWHITE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RACEUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RACEUNKNOWN	
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHNICITYHISPANIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHNICITYHISPANIC	
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHNICITYNOTHISPANIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHNICITYNOTHISPANIC	
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_US',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_US	
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NOTUS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NOTUS	
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_COUNTRYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_COUNTRYUNKNOWN	
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ORIGINCOUNTRY_TEXT',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_ORIGINCOUNTRY_TEXT 
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_NOTUS',ACT_RVCTPG.ID, 1) AS RVCTPG_MONTHARRIVED
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_NOTUS',ACT_RVCTPG.ID, 0) AS RVCTPG_YEARARRIVED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ALIVE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ALIVE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DEAD',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_DEAD 
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_PREVIOUSTBYES',ACT_RVCTPG.ID, 0) AS RVCTPG_PREVIOUSTBYEAR
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEPULMONARY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEPULMONARY 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEPLEURAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEPLEURAL 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITECERVICAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITECERVICAL 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEINTRATHORACIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEINTRATHORACIC 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITELYMPHOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITELYMPHOTHER 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITELYMPHUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITELYMPHUNKNOWN 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEBONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEBONE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEGENITOURINARY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEGENITOURINARY 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEMENINGEAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEMENINGEAL 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEPERITONEAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEPERITONEAL 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEOTHER 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITENOTSTATED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITENOTSTATED 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_SMEARPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_SMEARPOS 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_SMEARNEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_SMEARNEG 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_SMEARNOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_SMEARNOTDONE 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_SMEARUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_SMEARUNKNOWN 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTUREPOS 
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTURENEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTURENEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTURENOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTURENOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTUREUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICPOS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICNEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICNEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICNOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICNOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICUNKNOWN
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_MICROSCOPICCODE1_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_MICROSCOPICCODE1_TEXT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTUREPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTUREPOS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTURENEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTURENEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTURENOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTURENOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTUREUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTUREUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRNORMAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRNORMAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRNOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRNOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRTYPECAVITARY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRTYPECAVITARY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PPDPOS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDNEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PPDNEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDNOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PPDNOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PPDUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HOMELESSNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HOMELESSNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HOMELESSYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HOMELESSYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HOMELESSUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HOMELESSUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CORRECTIONALNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CORRECTIONALNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CORRECTIONALYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CORRECTIONALYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CORRECTIONALUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CORRECTIONALUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_FEDERALPRISON',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_FEDERALPRISON
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LOCALJAIL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LOCALJAIL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OTHERCORRECTIONAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OTHERCORRECTIONAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_STATEPRISON',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_STATEPRISON
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_JUVENILECORRECTIONAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_JUVENILECORRECTIONAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_UNKNOWNCORRFACILITY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_UNKNOWNCORRFACILITY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LONGTERMFACILITYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LONGTERMFACILITYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LONGTERMFACILITYYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LONGTERMFACILITYYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LONGTERMFACILITYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LONGTERMFACILITYUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NURSINGHOME',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NURSINGHOME
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HOSPITALBASED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HOSPITALBASED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RESIDENTIAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RESIDENTIAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MENTALHEALTH',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MENTALHEALTH
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AODTREATMENT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AODTREATMENT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OTHERLONGTERM',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OTHERLONGTERM
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_UNKNOWNLONGTERMFACILITY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_UNKNOWNLONGTERMFACILITY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ISONIAZIDNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ISONIAZIDNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAMPINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAMPINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PYRAZINAMIDENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PYRAZINAMIDENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHAMBUTOLNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHAMBUTOLNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_STREPTOMYCINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_STREPTOMYCINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHIONAMIDENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHIONAMIDENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_KANAMYCINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_KANAMYCINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CYCLOSERINENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CYCLOSERINENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CAPREOMYCINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CAPREOMYCINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PARAAMINONO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PARAAMINONO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFABUTINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFABUTINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CIPROFLOXACINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CIPROFLOXACINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OFLOXACINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OFLOXACINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHERNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHERNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_INJECTINGDRUGUSENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_INJECTINGDRUGUSENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_INJECTINGDRUGUSEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_INJECTINGDRUGUSEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_INJECTINGDRUGUSEUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_INJECTINGDRUGUSEUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NONINJECTINGDRUGUSENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NONINJECTINGDRUGUSENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NONINJECTINGDRUGUSEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NONINJECTINGDRUGUSEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NONINJECTINGDRUGUSEUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NONINJECTINGDRUGUSEUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_EXCESSALCOHOLUSENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_EXCESSALCOHOLUSENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_EXCESSALCOHOLUSEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_EXCESSALCOHOLUSEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_EXCESSALCOHOLUSEUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_EXCESSALCOHOLUSEUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCHEALTHCARE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCHEALTHCARE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCCORRECTIONAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCCORRECTIONAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCMIGRATORYAGRICULTURAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCMIGRATORYAGRICULTURAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCNOTEMPLOYED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCNOTEMPLOYED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVTESTOFFEREDNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVTESTOFFEREDNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVTESTOFFEREDYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVTESTOFFEREDYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVTESTOFFEREDUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVTESTOFFEREDUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHNUMBERFOUND',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AIDSMATCHNUMBERFOUND
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHNUMBERNOTFOUND',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AIDSMATCHNUMBERNOTFOUND
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHPENDING',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AIDSMATCHPENDING
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHNOTPERFORMED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AIDSMATCHNOTPERFORMED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AIDSMATCHUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ISONIAZIDYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ISONIAZIDYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAMPINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAMPINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PYRAZINAMIDEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PYRAZINAMIDEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHAMBUTOLYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHAMBUTOLYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_KANAMYCINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_KANAMYCINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CYCLOSERINEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CYCLOSERINEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CAPREOMYCINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CAPREOMYCINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PARAAMINOYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PARAAMINOYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFABUTINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFABUTINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CIPROFLOXACINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CIPROFLOXACINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OFLOXACINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OFLOXACINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHERYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHERYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ISONIAZIDUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ISONIAZIDUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAMPINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAMPINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PYRAZINAMIDEUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PYRAZINAMIDEUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHAMBUTOLUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHAMBUTOLUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_KANAMYCINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_KANAMYCINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CYCLOSERINEUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CYCLOSERINEUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CAPREOMYCINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CAPREOMYCINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PARAAMINOUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PARAAMINOUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFABUTINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFABUTINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CIPROFLOXACINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CIPROFLOXACINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OFLOXACINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OFLOXACINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHERUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHERUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_STREPTOMYCINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_STREPTOMYCINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_STREPTOMYCINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_STREPTOMYCINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHIONAMIDEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHIONAMIDEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ETHIONAMIDEUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ETHIONAMIDEUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PREVIOUSTBYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PREVIOUSTBYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PREVIOUSTBNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_PREVIOUSTBNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_WITHINCITYLIMITSNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_WITHINCITYLIMITSNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AMIKACINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AMIKACINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AMIKACINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AMIKACINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AMIKACINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_AMIKACINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSNEGATIVE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSNEGATIVE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSNOTOFFERED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSNOTOFFERED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSPOSITIVE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSPOSITIVE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSREFUSED',ACT_RVCTPG.ID,'VALUEBOOL') AS		RVCTPG_HIVSTATUSREFUSED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSTESTDONERESULTUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSTESTDONERESULTUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSINDETERMINATE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_HIVSTATUSINDETERMINATE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_COUNTABLETBCASE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_COUNTABLETBCASE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NCTBANOTHERAREA',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NCTBANOTHERAREA
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NCTBANOTHERCOUNTRY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NCTBANOTHERCOUNTRY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NCTBRECURRENTTB',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NCTBRECURRENTTB
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TWOMONTHSOUTSIDEUSYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TWOMONTHSOUTSIDEUSYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TWOMONTHSOUTSIDEUSNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TWOMONTHSOUTSIDEUSNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TWOMONTHSOUTSIDEUSUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TWOMONTHSOUTSIDEUSUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREREPORTLABCOMMERCIAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTUREREPORTLABCOMMERCIAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREREPORTLABPUBLIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTUREREPORTLABPUBLIC
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREREPORTLABOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CULTUREREPORTLABOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICEXAMSMEAR',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICEXAMSMEAR
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICEXAMPATHOLOGY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MICROSCOPICEXAMPATHOLOGY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTURELABPUBLIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTURELABPUBLIC
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTURELABCOMMERCIAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTURELABCOMMERCIAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTURELABOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TISSUECULTURELABOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAAPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAAPOS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAANEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAANEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAANOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAANOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAAUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAAUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAAINDETERMINATE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAAINDETERMINATE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAASPECIMENTTYPESPUTUM',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAASPECIMENTTYPESPUTUM
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAALABPUBLIC',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAALABPUBLIC
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAALABCOMMERCIAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAALABCOMMERCIAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAALABOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_NAALABOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALCAVITY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALCAVITY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALCAVITYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALCAVITYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALCAVITYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALCAVITYUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALMILIARYYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALMILIARYYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALMILIARYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALMILIARYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CXRABNORMALMILIARYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CXRABNORMALMILIARYUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSNORMAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSNORMAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSNOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSNOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALCAVITYYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALCAVITYYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALCAVITYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALCAVITYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALCAVITYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALCAVITYUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALMILIARYYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALMILIARYYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALMILIARYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALMILIARYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CTSABNORMALMILIARYUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_CTSABNORMALMILIARYUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRAPOS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IGRAPOS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRANEG',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IGRANEG
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRAINDETERMINATE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IGRAINDETERMINATE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRANOTDONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IGRANOTDONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRAUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IGRAUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONSYMPTOMS',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONSYMPTOMS
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONABNORMALCXR',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONABNORMALCXR
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONCONTACTINVESTIGATION',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONCONTACTINVESTIGATION
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONTARGETEDTESTING',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONTARGETEDTESTING
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONHCWORKER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONHCWORKER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONEMPTESTING',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONEMPTESTING
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONIMMIEXAM',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONIMMIEXAM
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONINCIDENTALLAB',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONINCIDENTALLAB
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBREASONUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBREASONUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONCUSTODYNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONCUSTODYNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONCUSTODYYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONCUSTODYYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCNOTSEEKING',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCNOTSEEKING
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_OCCRETIRED',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_OCCRETIRED
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKMDRCONTACT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKMDRCONTACT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKINFECTIOUSCONTACT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKINFECTIOUSCONTACT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKMISSEDCONTACT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKMISSEDCONTACT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKLTBIINCOMPLETERX',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKLTBIINCOMPLETERX
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKTNFANTAGONISTRX',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKTNFANTAGONISTRX
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKPOSTORGANTRANSPLANT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKPOSTORGANTRANSPLANT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKDIABETES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKDIABETES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKENDSTAGERENAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKENDSTAGERENAL
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKIMMUNOSUPP',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKIMMUNOSUPP
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKNONE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_ADDRISKNONE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSNA',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSNA
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSIMMIGRANT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSIMMIGRANT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSSTUDENT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSSTUDENT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSEMPLOYMENT',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSEMPLOYMENT
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSTOURIST',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSTOURIST
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSFAMILY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSFAMILY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSREFUGEE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSREFUGEE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSASYLEE',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSASYLEE
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSOTHER',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSOTHER
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IMMIGRATIONSTATUSUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_IMMIGRATIONSTATUSUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_USARRIVEDWITHTBNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_USARRIVEDWITHTBNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_USARRIVEDWITHTBYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_USARRIVEDWITHTBYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_USARRIVEDWITHTBUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_USARRIVEDWITHTBUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAPENTINENO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAPENTINENO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAPENTINEYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAPENTINEYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_RIFAPENTINEUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_RIFAPENTINEUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LEVOFLOXACINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LEVOFLOXACINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LEVOFLOXACINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LEVOFLOXACINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LEVOFLOXACINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_LEVOFLOXACINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MOXIFLOXACINNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MOXIFLOXACINNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MOXIFLOXACINYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MOXIFLOXACINYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MOXIFLOXACINUNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MOXIFLOXACINUNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHER2NO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHER2NO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHER2YES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHER2YES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHER2UNK',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MEDOTHER2UNK
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBCAUSEOFDEATHYES',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBCAUSEOFDEATHYES
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBCAUSEOFDEATHNO',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBCAUSEOFDEATHNO
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TBCAUSEOFDEATHUNKNOWN',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_TBCAUSEOFDEATHUNKNOWN
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITEAXILLARY',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITEAXILLARY
	,DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MAJORSITELARYNGEAL',ACT_RVCTPG.ID,'VALUEBOOL') AS RVCTPG_MAJORSITELARYNGEAL
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DATETHERAPYSTARTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_DATETHERAPYSTARTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_AIDSMATCHNUMBERNOTFOUND',ACT_RVCTPG.ID,'TEXT') AS RVCTPG_AIDSMATCHPATIENTNUMBER
	
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_STATEREPORTING_FK',ACT_RVCTPG.ID, 0) AS RVCTPG_STATEREPORTINGYEAR
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_CITYCOUNTYCASESTATE_FK',ACT_RVCTPG.ID, 0) AS RVCTPG_CITYCOUNTYCASEYEAR
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSIFPOSITIVELISTCITYPATNO',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_HIVSTATUSIFPOSITIVELISTCITYPATNO
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_HIVSTATUSIFPOSITIVELISTSTATEPATNO',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_HIVSTATUSIFPOSITIVELISTSTATEPATNO
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_CITYCOUNTYCASESTATE_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_CITYCOUNTYCASESTATE_TEXT
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_LINKINGSTATE1STATE_FK',ACT_RVCTPG.ID, 0) AS RVCTPG_LINKINGSTATE1YEAR
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LINKINGSTATE1STATE_FK',ACT_RVCTPG.ID,'TITLE') AS RVCTPG_LINKINGSTATE1CASENUMBER
	,DBO.MDF_ACT_GET_MONTH_YEAR_ACT_DATETYPE('RVCTPG_LINKINGSTATE2STATE_FK',ACT_RVCTPG.ID, 0) AS RVCTPG_LINKINGSTATE2YEAR
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_LINKINGSTATE2STATE_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_LINKINGSTATE2STATE_TEXT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_LINKINGSTATE2STATE_FK',ACT_RVCTPG.ID,'TITLE') AS RVCTPG_LINKINGSTATE2CASENUMBER
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_NCTBANOTHERCOUNTRYSPECIFY_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_NCTBANOTHERCOUNTRYSPECIFY_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDVALUESTRING_BYPARENTACTID('RVCTPG_TWOMONTHSOUTSIDEUSYES',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_COUNTRIESLIVEDIN	
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_BIRTHCOUNTYGUARDIAN1_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_BIRTHCOUNTYGUARDIAN1_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_BIRTHCOUNTYGUARDIAN2_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_BIRTHCOUNTYGUARDIAN2_TEXT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_DEAD',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_DATEOFDEATH
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_MAJOROTHERCODE2_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_MAJOROTHERCODE2_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_MAJOROTHERCODE3_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_MAJOROTHERCODE3_TEXT
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_LINKINGSTATE1STATE_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_LINKINGSTATE1STATE_TEXT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_SMEARDATECOLLECTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_SMEARDATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREDATECOLLECTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_CULTUREDATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_CULTUREDATERESULTREPORTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_CULTUREDATERESULTREPORTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MICROSCOPICDATECOLLECTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_MICROSCOPICDATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTUREDATECOLLECTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_TISSUECULTUREDATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_TISSUECULTUREDATERESULT',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_TISSUECULTUREDATERESULT
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAADATECOLLECTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_NAADATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_NAADATERESULTREPORTED',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_NAADATERESULTREPORTED
	,DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'RVCTPG_NAACODE1_FK', ACT_RVCTPG.ID, 'VALUECODE_ID') AS RVCTPG_NAACODE1_TEXT
	,DBO.MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDMILLIMETERS',ACT_RVCTPG.ID,'VALUENUMERATOR') AS RVCTPG_PPDMILLIMETERS
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_PPDMILLIMETERS',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_PPDDATEPLACED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRATESTTYPE',ACT_RVCTPG.ID,'EFFECTIVETIME_TXT') AS RVCTPG_IGRADATECOLLECTED
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_IGRATESTTYPE',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_IGRATESTTYPE
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_ADDRISKOTHER',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_ADDRISKOTHERSPECIFY
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_USARRIVEDWITHTBYES',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_USARRIVEDWITHTBALIENNUMBER
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHERYES',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_MEDOTHERSPECIFY
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_MEDOTHER2YES',ACT_RVCTPG.ID,'VALUESTRING') AS RVCTPG_MEDOTHER2SPECIFY
	,DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('RVCTPG_COMMENTS',ACT_RVCTPG.ID,'TEXT') AS RVCTPG_COMMENTS
	,ACT_CDCMESSAGE.ACTIVITYTIME_END AS RVCTPG_DATECDCMESSAGEUPDATE
	,ACT_CDCMESSAGE.ACTIVITYTIME_BEG AS RVCTPG_DATECDCMESSAGETRANSMIT
	,DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(T_ACTREASON.REASONCODE_ID) AS RVCTPG_LINKINGSTATE2REASON_TEXT
	,DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(T_ACTREASON_1.REASONCODE_ID) AS RVCTPG_LINKINGSTATE1REASON_TEXT
	,II1.EXTENSION AS RVCTPG_LOCALRECORDID
FROM 
	A_ACT ACT_RVCTPG (NOLOCK) 
	INNER JOIN DBO.A_ACT ACT_DOCBODY (NOLOCK) ON ACT_DOCBODY.ID=ACT_RVCTPG.ACT_PARENT_ID AND ACT_DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN DBO.A_ACT [CASE] (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=[CASE].ID
	LEFT JOIN DBO.A_ACT ACT_CDCMESSAGE (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=ACT_CDCMESSAGE.ACT_CASENCM_ID AND ACT_CDCMESSAGE.METACODE='DI_DATESENT'
	--NO NEED TO CONVERT INTO FUNCTION BECAUSE BELOW JOINS ARE USED ONLY IN THIS VIEW.
	LEFT JOIN DBO.A_ACT ACT_OBS  (NOLOCK) ON ACT_OBS.ACT_PARENT_ID = ACT_RVCTPG.ID AND ACT_OBS.METACODE = 'RVCTPG_LINKINGSTATE2STATE_FK'
	LEFT JOIN DBO.T_ACTREASON T_ACTREASON  (NOLOCK) ON T_ACTREASON.ACT_ID = ACT_OBS.ID
	LEFT JOIN DBO.A_ACT ACT_OBS_1  (NOLOCK) ON ACT_OBS_1.ACT_PARENT_ID = ACT_RVCTPG.ID AND ACT_OBS_1.METACODE = 'RVCTPG_LINKINGSTATE1STATE_FK'
	LEFT JOIN DBO.T_ACTREASON T_ACTREASON_1  (NOLOCK) ON T_ACTREASON_1.ACT_ID = ACT_OBS_1.ID
	LEFT JOIN DBO.T_INSTANCEIDENTIFIER II1 (NOLOCK) ON II1.ACT_ID = ACT_RVCTPG.ID AND II1.METACODE='RVCTPG_LocalRecordID'
WHERE	
	ACT_RVCTPG.CLASSCODE = 'DOCSECT' AND ACT_RVCTPG.METACODE = 'RVCTPG_ID'	


