
CREATE VIEW [AtlasInternal].[VIEW_SUB_REFERRAL_TUBERCULOSIS]
AS
SELECT 
	S_LINK.ENTITY2_ID AS PATIENT_FK,
	ACT_SVC.ID AS SERVICE_FK,
	ACT_REFCHILD.ID AS ACT_ID,	
	ACT_REFCHILD.CODE_ID AS ACT_CODE_ID,
	ACT_REFCHILD.VALUECODE_ID AS ACT_VALUECODE_ID,
	ACT_REFCHILD.EFFECTIVETIME_BEG AS ACT_EFFECTIVETIME_BEG,
	ACT_REFCHILD.EFFECTIVETIME_END AS ACT_EFFECTIVETIME_END,
	ACT_REFCHILD.ACTIVITYTIME_BEG AS ACT_ACTIVITYTIME_BEG,
	ACT_REFCHILD.[TEXT] AS ACT_TEXT,
	ACT_REFCHILD.VALUENUMERATOR AS ACT_VALUENUMERATOR,
	ACT_REFCHILD.EFFECTIVETIME_FRQ_ID AS ACT_EFFECTIVETIME_FRQ_ID,
	ACT_REFCHILD.EFFECTIVETIME_DUR_UNIT AS ACT_EFFECTIVETIME_DUR_UNIT,
	ACT_REFCHILD.EFFECTIVETIME_DUR AS ACT_EFFECTIVETIME_DUR,	
	ACT_REFCHILD.METACODE AS ACT_METACODE,
	ACT_REFCHILD.CLASSCODE AS ACT_CLASSCODE
FROM
	DBO.A_ACT ACT_REFCHILD (NOLOCK)
	INNER JOIN DBO.A_ACT ACT_DOCBODY (NOLOCK) ON  ACT_REFCHILD.ACT_PARENT_ID = ACT_DOCBODY.ID AND ACT_DOCBODY.CLASSCODE = 'DOCBODY' 
	INNER JOIN DBO.V_UNIFIEDCODESET UCS_DOCBODY (NOLOCK) ON  ACT_DOCBODY.CODE_ID = UCS_DOCBODY.ID AND UCS_DOCBODY.CONCEPTCODE = 'REF'
	INNER JOIN A_ACTRELATIONSHIP (NOLOCK) ON A_ACTRELATIONSHIP.TARGET_ID=ACT_DOCBODY.ID
	INNER JOIN DBO.A_ACT ACT_SVC (NOLOCK) ON  A_ACTRELATIONSHIP.SOURCE_ID = ACT_SVC.ID AND ACT_SVC.CLASSCODE = 'CASE' AND ACT_SVC.METACODE = 'SVC_ID'
	INNER JOIN DBO.S_LINK (NOLOCK) ON  S_LINK.ACT1_ID = ACT_SVC.ID AND S_LINK.[NAME] = 'PATIENT-CASE'
WHERE
	ACT_REFCHILD.STATUSCODE = 'ACTIVE'

