CREATE VIEW [AtlasInternal].[VIEW_ClientRecord_MultipleAddresses_CMMode]
AS  
SELECT   
	DVPER.DVPER_ROWID AS [ADR_PATIENTID],   
	DVPER.DVPER_NCMID AS [ADR_CLIENTID],
	[PATIENTDATA_ADDRESS].[ADR_ENTRYDATE],  
	CASE WHEN SLINK_PERSON.TADDRESS1_ID = PATIENTDATA_ADDRESS.ADR_ID THEN 'TRUE' ELSE 'FALSE' END AS [ADR_ISPRIMARY],  
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYENTITYADDRESSID](PATIENTDATA_ADDRESS.ADR_ID, 'PSNAD_INACTIVE') AS [ADR_INACTIVE],  
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](INSTANCEIDENT_SOURCE.SOURCECODE_ID) AS [ADR_SOURCE],  
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ATTRUCS_BYENTITYADDRESSID](PATIENTDATA_ADDRESS.ADR_ID, 'PSNAD_TYPE_FK') AS [ADR_TYPE],  
	[PATIENTDATA_ADDRESS].[ADR_APARTMENT],  
	[PATIENTDATA_ADDRESS].[ADR_ADDRESS],  
	[PATIENTDATA_ADDRESS].[ADR_CITY],  
	[PATIENTDATA_ADDRESS].[ADR_STATE],  
	[PATIENTDATA_ADDRESS].[ADR_ZIP],  
	[PATIENTDATA_ADDRESS].[ADR_CENSUSTRACT],  
	[DBO].[MDF_ATTR_GETDATETIMEVALUE_ENTATTR_BYENTITYADDRESSID](PATIENTDATA_ADDRESS.ADR_ID, 'VALUETS', 'PSNAD_VALIDDATE') AS [ADR_FROMDATE],  
	[DBO].[MDF_ATTR_GETDATETIMEVALUE_ENTATTR_BYENTITYADDRESSID](PATIENTDATA_ADDRESS.ADR_ID, 'VALUETSEND', 'PSNAD_VALIDDATE') AS [ADR_TODATE]
FROM  
	DBO.DV_PERSON DVPER (NOLOCK)  
	INNER JOIN [ATLASINTERNAL].[VIEW_CMN_PATIENTDATA_ADDRESS] PATIENTDATA_ADDRESS (NOLOCK) ON PATIENTDATA_ADDRESS.[ADR_PATIENTID] = DVPER.DVPER_ROWID
	INNER JOIN [DBO].E_ENTITY ENTPARENT (NOLOCK) ON ENTPARENT.ID = PATIENTDATA_ADDRESS.ENTITYHX_ID  
	LEFT JOIN [DBO].S_LINK SLINK_PERSON (NOLOCK) ON SLINK_PERSON.ENTITY1_ID = ENTPARENT.ID AND SLINK_PERSON.[NAME] = 'PERSON-PRIMARY'  
	LEFT JOIN [DBO].T_INSTANCEIDENTIFIER INSTANCEIDENT_SOURCE (NOLOCK) ON INSTANCEIDENT_SOURCE.ENTITYADDRESS_ID = PATIENTDATA_ADDRESS.ADR_ID AND INSTANCEIDENT_SOURCE.[NAME] = 'PSN_SOURCE'  
  
	
