
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_TUBERCULOSIS_MAIN]
AS

SELECT 
	VIEW_SUB_REFTUB.PATIENT_FK AS TBHIST_PATIENT_FK,
	VIEW_SUB_REFTUB.SERVICE_FK AS TBHIST_SERVICE_FK,
	VIEW_SUB_REFTUB.ACT_ID AS TBHIST_ID,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBHIST_PREVIOUSTB', VIEW_SUB_REFTUB.ACT_ID, 'VALUEBOOL') AS TBHIST_PREVIOUSTB,
	VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_BEG AS TBHIST_DATEGIVEN, 
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBHIST_RX', VIEW_SUB_REFTUB.ACT_ID, 'TEXT') AS TBHIST_RX,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(T_ATTRIBUTE.VALUECODE_ID) AS TBHIST_TBIMMIGRANTSTATUS

FROM 
	[ATLASINTERNAL].[VIEW_SUB_REFERRAL_TUBERCULOSIS] VIEW_SUB_REFTUB
	LEFT JOIN E_ENTITY (NOLOCK) ON E_ENTITY.ID = VIEW_SUB_REFTUB.PATIENT_FK
	LEFT JOIN T_ATTRIBUTE (NOLOCK) ON T_ATTRIBUTE.ENTITY_ID = E_ENTITY.ID AND T_ATTRIBUTE.[NAME] = 'TBIMMIGRANTSTATUS_FK'

WHERE 
	VIEW_SUB_REFTUB.ACT_METACODE = 'TBHIST_ID' AND VIEW_SUB_REFTUB.ACT_CLASSCODE ='DOCSECT'

