
CREATE VIEW [ATLASINTERNAL].[VIEW_SUB_NCM_EPICONTACT]
AS
SELECT 
	ROLE_EXPR.SCOPER_ID AS PATIENT_FK,
	PART_IND.ACT_ID AS SERVICE_FK,
	ACT_EPICONTCHILD.ID AS ACT_ID,
	ACT_FOLDER.ID AS CONTACT_FK,
	ACT_EPICONTCHILD.CODE_ID AS ACT_CODE_ID,
	ACT_EPICONTCHILD.VALUECODE_ID AS ACT_VALUECODE_ID,
	ACT_EPICONTCHILD.EFFECTIVETIME_BEG AS ACT_EFFECTIVETIME_BEG,
	ACT_EPICONTCHILD.EFFECTIVETIME_END AS ACT_EFFECTIVETIME_END,
	ACT_EPICONTCHILD.ACTIVITYTIME_BEG AS ACT_ACTIVITYTIME_BEG,
	ACT_EPICONTCHILD.[TEXT] AS ACT_TEXT,
	ACT_EPICONTCHILD.VALUENUMERATOR AS ACT_VALUENUMERATOR,
	ACT_EPICONTCHILD.EFFECTIVETIME_DUR AS ACT_EFFECTIVETIME_DUR,	
	ACT_EPICONTCHILD.METACODE AS ACT_METACODE,
	ACT_EPICONTCHILD.CLASSCODE AS ACT_CLASSCODE,
	ACT_EPICONTCHILD.STATUSCODE AS ACT_STATUSCODE,	
	ACT_EPICONTCHILD.MOODCODE AS ACT_MOODCODE
FROM
	DBO.A_ACT ACT_EPICONTCHILD (NOLOCK)
	INNER JOIN DBO.A_ACT ACT_FOLDER (NOLOCK) ON  ACT_EPICONTCHILD.ACT_PARENT_ID = ACT_FOLDER.ID AND ACT_FOLDER.CLASSCODE = 'FOLDER' 
	INNER JOIN P_PARTICIPATION PART (NOLOCK) ON PART.ACT_ID=ACT_FOLDER.[ID] AND PART.TYPECODE='SBJ'
	INNER JOIN R_ROLE (NOLOCK) ON R_ROLE.ID=PART.ROLE_ID AND R_ROLE.CLASSCODE='MBR'
	INNER JOIN E_ENTITY ENT_GRP (NOLOCK) ON ENT_GRP.ID=R_ROLE.SCOPER_ID AND ENT_GRP.CLASSCODE='ENT' AND ENT_GRP.DETERMINERCODE='QUANTIFIED_KIND'
	INNER JOIN R_ROLE ROLE_EXPR (NOLOCK) ON ROLE_EXPR.PLAYER_ID=ENT_GRP.ID AND ROLE_EXPR.CLASSCODE='EXPR'
	INNER JOIN P_PARTICIPATION PART_IND (NOLOCK) ON PART_IND.ROLE_ID=ROLE_EXPR.ID AND PART_IND.TYPECODE='IND'
WHERE
	ACT_EPICONTCHILD.STATUSCODE <> 'NULLIFIED'
