
CREATE VIEW [AtlasInternal].[VIEW_CMR_LIPCROSSREFERENCE_DATA]
AS
SELECT  
    LIPX.subjCode_ID AS ID, 
    LAB.TRIVIALNAME AS LaboratoryName,
    RESULT.FULLNAME AS ResultName, 
    POSDIAG.FULLNAME AS PositiveDiagnosis,
    NONPOSDIAG.FULLNAME AS NonPositiveDiagnosis,
    LIPX.LABR_LOINCREFERENCECODE AS LOINCReferenceCode, 
    LIPX.LABR_LOCALREFERENCECODE AS LocalReferenceCode, 
    HEPA.FULLNAME AS HepTest,
    CAST(LIPX.LABR_DONOTIMPORT AS VARCHAR(1)) AS DoNotImport, 
    LIPX.LABR_SNOMEDCONCEPTID AS SNOMEDConceptID, 
    LIPX.LABR_SNOMEDLEGACYCODE AS SNOMEDLegacyCode,
    LIPX.LABR_LOCALORGANISMCODE AS LocalOrganismCode,
    CAST(isnull(LIPX.LABR_TESTORGANISMCOMBINED,0) AS VARCHAR(1)) AS TestOrganismCombinedFlag,
    CAST(isnull(LIPX.LABR_OutbreakManualEntry ,0) AS VARCHAR(1)) AS OutbreakManualEntryFlag,
    CASE WHEN isnull([V_TermDictionary].[active],1) = 1 THEN 0 ELSE 1 END AS InactiveFlag,
    dbo.FN_ConcateManualSusceptibilityResult(LIPX.subjCode_ID) as ManualSusceptibilityEntries,
    LIPX.LABR_ReinfectionInDays ReinfectionInDays,
    LAB.ENTITY_ID AS LabID
FROM [VCP_LIPLABCROSSREFERENCE] LIPX (NOLOCK)
INNER JOIN [T_ENTITYNAME] LAB (NOLOCK) ON LAB.ENTITY_ID = LIPX.LABR_LABORATORYDR
LEFT JOIN [V_UNIFIEDCODESET] RESULT (NOLOCK) ON RESULT.ID=LIPX.SUBJCODE_ID
LEFT JOIN [V_UNIFIEDCODESET] POSDIAG (NOLOCK) ON POSDIAG.ID=LIPX.LABR_POSITIVEDISEASEDR
LEFT JOIN [V_UNIFIEDCODESET] NONPOSDIAG (NOLOCK) ON NONPOSDIAG.ID=LIPX.LABR_NONPOSITIVEDISEASEDR
LEFT JOIN [V_UNIFIEDCODESET] HEPA (NOLOCK) ON HEPA.ID=LIPX.LABR_HEPATITISTESTDR
LEFT JOIN [V_TERMDICTIONARY] (NOLOCK) ON LIPX.subjCode_ID = V_TERMDICTIONARY.TERMCODE_ID AND [V_TermDictionary].[name] = 'LIPLABCROSSREF'


