
CREATE VIEW [AtlasInternal].[VIEW_SUB_NCM_CONTACT_INFORMATION]
AS
WITH CTE_SSNOID(SSNOID)
AS
(
	SELECT dbo.FN_GetSSNOIDBasedOnSiteID(CAST((CASE WHEN VAL.value='' THEN CONFIG.defaultvalue ELSE VAL.value END) AS VARCHAR(20))) 
	FROM S_CONFIGDEFINITION (nolock)CONFIG
	INNER JOIN S_CONFIGVALUE(nolock) VAL ON VAL.configdefinition_id = CONFIG.id
	WHERE CONFIG.[KEY]='SITEID'
)
SELECT 
PARTFOLDER.ACT_ID AS CONTACT_FOLDER_ID,
PART.ACT_ID AS SERVICE_ID,                      --Saravanakumar Issue #110413 08/16/2011
ROLE_CONTACT.ID AS MEMBER_ROLE_ID,
UNIFIEDCODESETCONCEPTCODE.CONCEPTCODE AS CONTACT_FORMLINK,
ROLEEXPR.SCOPER_ID AS PATIENT_ID,
ENTITY_CONTACT.ID AS CONTDEMO_CONTACT_ID,
ATTR.VALUECODE_ID AS CONTACT_JURISDICTION_ID,	-- SKUMAR IssueNbr:110410 08/09/2011 
DV_PERSON.DVPER_LASTNAME AS CONTDEMO_LASTNAME,
DV_PERSON.DVPER_FIRSTNAME AS CONTDEMO_FIRSTNAME,
ENTNAME.PARTMID AS CONTDEMO_MIDDLENAME,
ENTNAME.PARTSFX AS CONTDEMO_NAMESUFFIX,     
DV_PERSON.DVPER_SSN AS CONTDEMO_SSN,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(INST.STATUSCODE_ID) AS CONTDEMO_SSNSTATUS,
DV_PERSON.DVPER_STREETADDRESS AS CONTDEMO_ADDRESS,
DV_PERSON.DVPER_CITY AS CONTDEMO_CITY,
DV_PERSON.DVPER_STATE AS CONTDEMO_STATE,
DV_PERSON.DVPER_ZIP AS CONTDEMO_ZIP,      
DV_PERSON.DVPER_CENSUSTRACT AS CONTDEMO_CENSUSTRACT,	-- SKUMAR IssueNbr:110410 08/09/2011 
DV_PERSON.DVPER_HOMEPHONE AS CONTDEMO_HOMEPHONE,
-- +SKUMAR IssueNbr:110410 08/12/2011 
DBO.[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](DV_PERSON.DVPER_ROWID, 'valueString', 'PSNID_EmailID') AS CONTDEMO_EMAILID,
DBO.[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](DV_PERSON.DVPER_ROWID, 'valueString', 'PSNID_ElectronicContact') AS CONTDEMO_ELECTRONICCONTACT,
CASE  
WHEN DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(DV_PERSON.DVPER_ROWID, 'PER_Age') IS NOT NULL THEN DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(DV_PERSON.DVPER_ROWID, 'PER_Age') ELSE
				CASE 
				WHEN DV_PERSON.DVPER_DOB IS NULL THEN NULL
				ELSE [DBO].[CALCULATEAGE](DV_PERSON.DVPER_DOB,default)
				END	
END AS CONTDEMO_AGE,
-- -SKUMAR IssueNbr:110410 08/12/2011 
-- +Saravanakumar Issue #110413 08/16/2011
CASE 
WHEN DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(ENTITY_CONTACT.ID,'PER_AgeInMonths') IS NOT NULL THEN DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(ENTITY_CONTACT.ID,'PER_AgeInMonths') ELSE
				CASE 
				WHEN DV_PERSON.DVPER_DOB IS NULL THEN NULL
				ELSE [DBO].[CALCULATEAGE](DV_PERSON.DVPER_DOB,'MONTHS')
				END	
END  AS CONTDEMO_AGEMONTHS,
CASE 
WHEN DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(ENTITY_CONTACT.ID,'PER_AgeInDays') IS NOT NULL THEN  DBO.MDF_ATTR_GETINTEGERVALUE_ENTATTR_BYENTITYID(ENTITY_CONTACT.ID,'PER_AgeInDays') ELSE
				CASE 
				WHEN DV_PERSON.DVPER_DOB IS NULL THEN NULL
				ELSE [DBO].[CALCULATEAGE](DV_PERSON.DVPER_DOB,'DAYS')
				END	
END AS CONTDEMO_AGEDAYS,
-- -Saravanakumar Issue #110413 08/16/2011
DBO.MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID(ENTITY_CONTACT.ID,'A','TEL')AS CONTDEMO_ALTERNATEPHONE,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(DV_PERSON.DVPER_SEXCODE_ID) AS CONTDEMO_GENDER,
DV_PERSON.DVPER_DOB AS CONTDEMO_DOB,  
-- +MPatra Issue#112455 09/07/2011-
DBO.MDF_ENTLOCNAME_ENTITY_BYPSNENTITYID(DV_PERSON.DVPER_ROWID,'PER_WORKSCHOOLLOCATIONDR','SRCH')AS CONTDEMO_COMPANYSCHOOL,
DBO.MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID(ENTITY_CONTACT.ID,'WP','TEL')AS CONTDEMO_COMPANYSCHOOLTEPHONE,
-- +SKUMAR IssueNbr:110410 08/09/2011 
DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('PER_WORKSCHOOLCONTACT',PARTFOLDER.ACT_ID,'VALUESTRING') AS CONTDEMO_SUPERVISORTEACHER,	
DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('PAT_LASTWORKEDATTENDED',PARTFOLDER.ACT_ID,'VALUETS') AS CONTDEMO_LASTWORKED,
-- +MPatra Issue#112455 09/07/2011
DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(DV_PERSON.DVPER_ROWID,'PER_WORKSCHOOLLOCATIONDR','PARTSAL','PHYS')AS CONTDEMO_COMPANYSCHOOLADDRESS,
DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(DV_PERSON.DVPER_ROWID,'PER_WORKSCHOOLLOCATIONDR','PARTCTY','PHYS')AS CONTDEMO_COMPANYSCHOOLCITY,
DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(DV_PERSON.DVPER_ROWID,'PER_WORKSCHOOLLOCATIONDR','PARTSTA','PHYS')AS CONTDEMO_COMPANYSCHOOLSTATE,
DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(DV_PERSON.DVPER_ROWID,'PER_WORKSCHOOLLOCATIONDR','PARTZIP','PHYS')AS CONTDEMO_COMPANYSCHOOLZIPCODE,
-- -MPatra Issue#112455 09/07/2011
-- -SKUMAR IssueNbr:110410 08/09/2011 
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID( LANG.LANGUAGECODE_ID) AS CONTDEMO_PRIMARYLANGUAGE,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(DV_PERSON.DVPER_OCCUPATIONCODE_ID) AS CONTDEMO_OCCUPATION,
DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(DV_PERSON.DVPER_ETHNICITYCODE_ID) AS CONTDEMO_ETHNICITY,
--SKUMAR IssueNbr:110410 08/09/2011 
CASE UNIFIEDCODESETCONCEPTCODE.CONCEPTCODE
	WHEN 'EPI' THEN 
					DBO.MDF_Attr_GetStringValue_ActAttr_ByActId(PARTFOLDER.ACT_ID, 'valueString', 'CONTDESC_ClusterID')
	WHEn 'CDI' THEN 
					DBO.MDF_Attr_GetStringValue_ActAttr_ByActId(PARTFOLDER.ACT_ID, 'valueString', 'CDCONTDESC_ClusterID')
END  AS CONTACT_CLUSTERID,
ROLE_CONTACT.EFFECTIVETIME_BEG AS CONTDESC_DATEIDENTIFIED
FROM
E_ENTITY ENTITY_CONTACT (NOLOCK) 
INNER JOIN DV_PERSON DV_PERSON (NOLOCK) ON ENTITY_CONTACT.ID=DV_PERSON.DVPER_ROWID AND DVPER_ISCONTACT=1
INNER JOIN S_LINK LINK (NOLOCK) ON  LINK.ENTITY1_ID = ENTITY_CONTACT.ID AND LINK.NAME = 'PERSON-PRIMARY'
INNER JOIN R_ROLE ROLE_CONTACT (NOLOCK)ON  ROLE_CONTACT.PLAYER_ID = ENTITY_CONTACT.ID  AND ROLE_CONTACT.CLASSCODE = 'MBR' AND ROLE_CONTACT.STATUSCODE<>'NULLIFIED'
INNER JOIN P_PARTICIPATION PARTFOLDER (NOLOCK) ON  PARTFOLDER.ROLE_ID = ROLE_CONTACT.ID AND PARTFOLDER.TYPECODE = 'SBJ'
INNER JOIN A_ACTRELATIONSHIP ACTRELATIONSHIP (NOLOCK) ON PARTFOLDER.ACT_ID=ACTRELATIONSHIP.TARGET_ID AND ACTRELATIONSHIP.TYPECODE='REFR'
INNER JOIN A_ACT ACTDOCBODY (NOLOCK) ON ACTRELATIONSHIP.SOURCE_ID=ACTDOCBODY.ID AND ACTDOCBODY.CLASSCODE='DOCBODY' 
INNER JOIN V_UNIFIEDCODESET UNIFIEDCODESETCONCEPTCODE(NOLOCK) ON ACTDOCBODY.CODE_ID=UNIFIEDCODESETCONCEPTCODE.ID
INNER JOIN E_ENTITY ENTITY_GRP (NOLOCK) ON  ENTITY_GRP.ID = ROLE_CONTACT.SCOPER_ID AND ENTITY_GRP.CLASSCODE = 'ENT'
INNER JOIN R_ROLE ROLEEXPR (NOLOCK) ON  ROLEEXPR.PLAYER_ID = ENTITY_GRP.ID AND ROLEEXPR.CLASSCODE = 'EXPR'
INNER JOIN P_PARTICIPATION PART (NOLOCK) ON  PART.ROLE_ID = ROLEEXPR.ID AND PART.TYPECODE = 'IND' 
INNER JOIN T_ENTITYNAME ENTNAME (NOLOCK) ON  ENTNAME.ENTITY_ID = ENTITY_CONTACT.ID
INNER JOIN CTE_SSNOID ON 1=1
LEFT JOIN T_INSTANCEIDENTIFIER INST (NOLOCK) ON  ENTITY_CONTACT.ID=INST.ENTITY_ID  AND INST.ROOT = CTE_SSNOID.SSNOID 
LEFT JOIN T_LANGUAGECOMMUNICATION LANG (NOLOCK) ON  ENTITY_CONTACT.ID=LANG.ENTITY_ID  
-- +SKUMAR IssueNbr:110410 08/09/2011 
LEFT JOIN T_Attribute ATTR (NOLOCK) ON PARTFOLDER.ACT_ID = ATTR.ACT_ID AND ATTR.[TYPE] = 'CV' AND ATTR.NAME LIKE '%CONTDESC_Jurisdiction_FK'
WHERE
ENTITY_CONTACT.CLASSCODE = 'PSN'


