
CREATE VIEW [AtlasInternal].[VIEWEXPOSUREEVENTS]      
AS      
SELECT TOP 100 PERCENT INCIDENT.ID AS PHRECORDID,
EXPOSUREEVENT.ID as EXPOSUREEVENTID,
DBO.T_INSTANCEIDENTIFIER.EXTENSION AS PHRECORD_INSTANCE_ID,       
EXPOSUREEVENT.EFFECTIVETIME_BEG AS DEE_EXPOSUREDATETIME,       
EXPOSUREEVENT.EFFECTIVETIME_END AS DEE_EXPOSUREENDDATETIME,  
EXPOSUREEVENT.CODE_ID AS DEE_ExposureTypeDR,   
DBO.V_UNIFIEDCODESET.FULLNAME AS DEE_EXPOSURETYPE,       
DBO.R_ROLE.SCOPER_ID AS DEE_LOCATIONDR,       
TNAME.TRIVIALNAME AS DEE_LOCATION_NAME,
EXPOSUREEVENT.statuscode as DEE_StatusCode ,
INCIDENT.METACODE as PR_RecordType       
FROM DBO.A_ACT INCIDENT (NOLOCK)   
INNER JOIN DBO.A_ACT EXPOSUREEVENT (NOLOCK) ON EXPOSUREEVENT.ACT_PARENT_ID = INCIDENT.ID     
INNER JOIN DBO.T_INSTANCEIDENTIFIER (NOLOCK) ON INCIDENT.ID = DBO.T_INSTANCEIDENTIFIER.ACT_ID     
INNER JOIN DBO.V_UNIFIEDCODESET (NOLOCK) ON EXPOSUREEVENT.CODE_ID = DBO.V_UNIFIEDCODESET.ID     
INNER JOIN DBO.P_PARTICIPATION (NOLOCK) ON EXPOSUREEVENT.ID = DBO.P_PARTICIPATION.ACT_ID     
INNER JOIN DBO.R_ROLE (NOLOCK) ON DBO.P_PARTICIPATION.ROLE_ID = DBO.R_ROLE.ID     
LEFT OUTER JOIN DBO.E_PLACE PLACE (NOLOCK) ON DBO.R_ROLE.SCOPER_ID = PLACE.ID     
LEFT OUTER JOIN DBO.T_ENTITYNAME TNAME (NOLOCK) ON TNAME.ENTITY_ID = PLACE.ID      
WHERE (INCIDENT.METACODE IN('PR_ROWID','OB_RowID','AI_RowID') )AND (EXPOSUREEVENT.METACODE = 'DEE_ROWID') and (EXPOSUREEVENT.STATUSCODE = 'active')    
AND   (DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.1%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.7%' OR DBO.T_INSTANCEIDENTIFIER.ROOT LIKE '2.16.840.1.113883.3.33.4.2.2.11.8%') AND (DBO.R_ROLE.CLASSCODE = 'LOCE')   
ORDER BY DBO.T_INSTANCEIDENTIFIER.EXTENSION DESC  

