
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_SUSCEPTIBILITY]
AS
SELECT 
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	ACT_SUSC.ID AS SUSC_ID,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_SUSC.ID ,'CODE_ID') AS SUSC_MEDICATION_TEXT,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](OBSSUSC.INTERPRETATIONCODE_ID) AS SUSC_RESULT_TEXT,
	ACT_SUSC.EFFECTIVETIME_BEG AS SUSC_DATECOLLECTED,
	ACT_SUSC.AVAILABILITYTIME AS SUSC_DATEREPORTED,
	ACT_SUSC.TEXT AS SUSC_COMMENTS 
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY' 
	INNER JOIN A_ACT ACT_SUSC (NOLOCK) ON ACT_SUSC.ACT_PARENT_ID=DOCBODY.ID AND ACT_SUSC.METACODE='SUSC_ID' AND ACT_SUSC.STATUSCODE <> 'NULLIFIED'
	INNER JOIN A_OBSERVATION OBSSUSC (NOLOCK) ON OBSSUSC.ID = ACT_SUSC.ID
