
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_MENTALHEALTH]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_MENT.ID AS MENT_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('MENT_MENTALHEALTH', ACT_MENT.ID, 'VALUEBOOL') AS MENT_MENTALHEALTH,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('MENT_CONSCIOUSLEVEL_FK',ACT_MENT.ID,'VALUECODE_ID') AS MENT_CONSCIOUSLEVEL,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('MENT_AFFECT_FK',ACT_MENT.ID,'VALUECODE_ID') AS MENT_AFFECT,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('MENT_MOOD_FK',ACT_MENT.ID,'VALUECODE_ID') AS MENT_MOOD,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('MENT_CONCENTRATION_FK',ACT_MENT.ID,'VALUECODE_ID') AS MENT_CONCENTRATION,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('MENT_COPING_FK',ACT_MENT.ID,'VALUECODE_ID') AS MENT_COPING,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('MENT_STRESSCONFLICT', ACT_MENT.ID, 'VALUESTRING') AS MENT_STRESSCONFLICT
FROM 
	A_ACT ACT_MENT (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_MENT.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_MENT.METACODE='MENT_ID' AND ACT_MENT.STATUSCODE='ACTIVE'
