
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_DOT_DAYSUMMARY]
AS
SELECT 
	ACT_DOT.[ID] AS DOTDAY_ID,
	-- MED SECTION 1
	SUB_MED1DATA.DOTDAY_MED AS DOTDAY_MED1,SUB_MED1DATA.EFFECTIVETIME_END AS DOTDAY_MED1DATESTOPPED,
	SUB_MED1DATA.DOSEQUANTITY_LO AS DOTDAY_MED1DOSAGE, SUB_MED1DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED1PERBWDOSE,
	SUB_MED1DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED1DOSENUMBER,SUB_MED1DATA.DOTDAY_MEDFREQ AS DOTDAY_MED1FREQ,
	SUB_MED1DATA.VALUEBOOL AS DOTDAY_MED1PERBW,SUB_MED1DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED1REASONSTOPPED,
	SUB_MED1DATA.DOTDAY_MEDROUTE AS DOTDAY_MED1ROUTE,SUB_MED1DATA.DOTDAY_MEDUNIT AS DOTDAY_MED1UNIT,
	SUB_MED1DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED1WASTAKEN,
	-- MED SECTION 2
	SUB_MED2DATA.DOTDAY_MED AS DOTDAY_MED2,SUB_MED2DATA.EFFECTIVETIME_END AS DOTDAY_MED2DATESTOPPED,
	SUB_MED2DATA.DOSEQUANTITY_LO AS DOTDAY_MED2DOSAGE, SUB_MED2DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED2PERBWDOSE,
	SUB_MED2DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED2DOSENUMBER,SUB_MED2DATA.DOTDAY_MEDFREQ AS DOTDAY_MED2FREQ,
	SUB_MED2DATA.VALUEBOOL AS DOTDAY_MED2PERBW,SUB_MED2DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED2REASONSTOPPED,
	SUB_MED2DATA.DOTDAY_MEDROUTE AS DOTDAY_MED2ROUTE,SUB_MED2DATA.DOTDAY_MEDUNIT AS DOTDAY_MED2UNIT,
	SUB_MED2DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED2WASTAKEN,
	-- MED SECTION 3
	SUB_MED3DATA.DOTDAY_MED AS DOTDAY_MED3,SUB_MED3DATA.EFFECTIVETIME_END AS DOTDAY_MED3DATESTOPPED,
	SUB_MED3DATA.DOSEQUANTITY_LO AS DOTDAY_MED3DOSAGE, SUB_MED3DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED3PERBWDOSE,
	SUB_MED3DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED3DOSENUMBER,SUB_MED3DATA.DOTDAY_MEDFREQ AS DOTDAY_MED3FREQ,
	SUB_MED3DATA.VALUEBOOL AS DOTDAY_MED3PERBW,SUB_MED3DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED3REASONSTOPPED,
	SUB_MED3DATA.DOTDAY_MEDROUTE AS DOTDAY_MED3ROUTE,SUB_MED3DATA.DOTDAY_MEDUNIT AS DOTDAY_MED3UNIT,
	SUB_MED3DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED3WASTAKEN,
	-- MED SECTION 4
	SUB_MED4DATA.DOTDAY_MED AS DOTDAY_MED4,SUB_MED4DATA.EFFECTIVETIME_END AS DOTDAY_MED4DATESTOPPED,
	SUB_MED4DATA.DOSEQUANTITY_LO AS DOTDAY_MED4DOSAGE, SUB_MED4DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED4PERBWDOSE,
	SUB_MED4DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED4DOSENUMBER,SUB_MED4DATA.DOTDAY_MEDFREQ AS DOTDAY_MED4FREQ,
	SUB_MED4DATA.VALUEBOOL AS DOTDAY_MED4PERBW,SUB_MED4DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED4REASONSTOPPED,
	SUB_MED4DATA.DOTDAY_MEDROUTE AS DOTDAY_MED4ROUTE,SUB_MED4DATA.DOTDAY_MEDUNIT AS DOTDAY_MED4UNIT,
	SUB_MED4DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED4WASTAKEN,
	-- MED SECTION 5
	SUB_MED5DATA.DOTDAY_MED AS DOTDAY_MED5,SUB_MED5DATA.EFFECTIVETIME_END AS DOTDAY_MED5DATESTOPPED,
	SUB_MED5DATA.DOSEQUANTITY_LO AS DOTDAY_MED5DOSAGE, SUB_MED5DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED5PERBWDOSE,
	SUB_MED5DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED5DOSENUMBER,SUB_MED5DATA.DOTDAY_MEDFREQ AS DOTDAY_MED5FREQ,
	SUB_MED5DATA.VALUEBOOL AS DOTDAY_MED5PERBW,SUB_MED5DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED5REASONSTOPPED,
	SUB_MED5DATA.DOTDAY_MEDROUTE AS DOTDAY_MED5ROUTE,SUB_MED5DATA.DOTDAY_MEDUNIT AS DOTDAY_MED5UNIT,
	SUB_MED5DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED5WASTAKEN,
	-- MED SECTION 6
	SUB_MED6DATA.DOTDAY_MED AS DOTDAY_MED6,SUB_MED6DATA.EFFECTIVETIME_END AS DOTDAY_MED6DATESTOPPED,
	SUB_MED6DATA.DOSEQUANTITY_LO AS DOTDAY_MED6DOSAGE, SUB_MED6DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED6PERBWDOSE,
	SUB_MED6DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED6DOSENUMBER,SUB_MED6DATA.DOTDAY_MEDFREQ AS DOTDAY_MED6FREQ,
	SUB_MED6DATA.VALUEBOOL AS DOTDAY_MED6PERBW,SUB_MED6DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED6REASONSTOPPED,
	SUB_MED6DATA.DOTDAY_MEDROUTE AS DOTDAY_MED6ROUTE,SUB_MED6DATA.DOTDAY_MEDUNIT AS DOTDAY_MED6UNIT,
	SUB_MED6DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED6WASTAKEN,
	-- MED SECTION 7
	SUB_MED7DATA.DOTDAY_MED AS DOTDAY_MED7,SUB_MED7DATA.EFFECTIVETIME_END AS DOTDAY_MED7DATESTOPPED,
	SUB_MED7DATA.DOSEQUANTITY_LO AS DOTDAY_MED7DOSAGE, SUB_MED7DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED7PERBWDOSE,
	SUB_MED7DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED7DOSENUMBER,SUB_MED7DATA.DOTDAY_MEDFREQ AS DOTDAY_MED7FREQ,
	SUB_MED7DATA.VALUEBOOL AS DOTDAY_MED7PERBW,SUB_MED7DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED7REASONSTOPPED,
	SUB_MED7DATA.DOTDAY_MEDROUTE AS DOTDAY_MED7ROUTE,SUB_MED7DATA.DOTDAY_MEDUNIT AS DOTDAY_MED7UNIT,
	SUB_MED7DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED7WASTAKEN,
	-- MED SECTION 8
	SUB_MED8DATA.DOTDAY_MED AS DOTDAY_MED8,SUB_MED8DATA.EFFECTIVETIME_END AS DOTDAY_MED8DATESTOPPED,
	SUB_MED8DATA.DOSEQUANTITY_LO AS DOTDAY_MED8DOSAGE, SUB_MED8DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED8PERBWDOSE,
	SUB_MED8DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED8DOSENUMBER,SUB_MED8DATA.DOTDAY_MEDFREQ AS DOTDAY_MED8FREQ,
	SUB_MED8DATA.VALUEBOOL AS DOTDAY_MED8PERBW,SUB_MED8DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED8REASONSTOPPED,
	SUB_MED8DATA.DOTDAY_MEDROUTE AS DOTDAY_MED8ROUTE,SUB_MED8DATA.DOTDAY_MEDUNIT AS DOTDAY_MED8UNIT,
	SUB_MED8DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED8WASTAKEN,
	-- MED SECTION 9
	SUB_MED9DATA.DOTDAY_MED AS DOTDAY_MED9,SUB_MED9DATA.EFFECTIVETIME_END AS DOTDAY_MED9DATESTOPPED,
	SUB_MED9DATA.DOSEQUANTITY_LO AS DOTDAY_MED9DOSAGE, SUB_MED9DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED9PERBWDOSE,
	SUB_MED9DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED9DOSENUMBER,SUB_MED9DATA.DOTDAY_MEDFREQ AS DOTDAY_MED9FREQ,
	SUB_MED9DATA.VALUEBOOL AS DOTDAY_MED9PERBW,SUB_MED9DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED9REASONSTOPPED,
	SUB_MED9DATA.DOTDAY_MEDROUTE AS DOTDAY_MED9ROUTE,SUB_MED9DATA.DOTDAY_MEDUNIT AS DOTDAY_MED9UNIT,
	SUB_MED9DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED9WASTAKEN,
	-- MED SECTION 10
	SUB_MED10DATA.DOTDAY_MED AS DOTDAY_MED10,SUB_MED10DATA.EFFECTIVETIME_END AS DOTDAY_MED10DATESTOPPED,
	SUB_MED10DATA.DOSEQUANTITY_LO AS DOTDAY_MED10DOSAGE, SUB_MED10DATA.DOSEQUANTITY_ALT_HI AS DOTDAY_MED10PERBWDOSE,
	SUB_MED10DATA.DOSECHECKQUANTITY_NMR AS DOTDAY_MED10DOSENUMBER,SUB_MED10DATA.DOTDAY_MEDFREQ AS DOTDAY_MED10FREQ,
	SUB_MED10DATA.VALUEBOOL AS DOTDAY_MED10PERBW,SUB_MED10DATA.DOTDAY_MEDREASONSTOPPED AS DOTDAY_MED10REASONSTOPPED,
	SUB_MED10DATA.DOTDAY_MEDROUTE AS DOTDAY_MED10ROUTE,SUB_MED10DATA.DOTDAY_MEDUNIT AS DOTDAY_MED10UNIT,
	SUB_MED10DATA.DOTDAY_MEDWASTAKEN AS DOTDAY_MED10WASTAKEN,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DOTDAY_SUBMITTED',ACT_DOT.ID,'VALUEBOOL') AS DOTDAY_SUBMITTED
FROM
	A_ACT ACT_DOT (NOLOCK) 
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED1DATA (NOLOCK) ON SUB_MED1DATA.ID=ACT_DOT.[ID] AND SUB_MED1DATA.METACODE='DOTDAY_MED1DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED2DATA (NOLOCK) ON SUB_MED2DATA.ID=ACT_DOT.[ID] AND SUB_MED2DATA.METACODE='DOTDAY_MED2DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED3DATA (NOLOCK) ON SUB_MED3DATA.ID=ACT_DOT.[ID] AND SUB_MED3DATA.METACODE='DOTDAY_MED3DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED4DATA (NOLOCK) ON SUB_MED4DATA.ID=ACT_DOT.[ID] AND SUB_MED4DATA.METACODE='DOTDAY_MED4DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED5DATA (NOLOCK) ON SUB_MED5DATA.ID=ACT_DOT.[ID] AND SUB_MED5DATA.METACODE='DOTDAY_MED5DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED6DATA (NOLOCK) ON SUB_MED6DATA.ID=ACT_DOT.[ID] AND SUB_MED6DATA.METACODE='DOTDAY_MED6DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED7DATA (NOLOCK) ON SUB_MED7DATA.ID=ACT_DOT.[ID] AND SUB_MED7DATA.METACODE='DOTDAY_MED7DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED8DATA (NOLOCK) ON SUB_MED8DATA.ID=ACT_DOT.[ID] AND SUB_MED8DATA.METACODE='DOTDAY_MED8DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED9DATA (NOLOCK) ON SUB_MED9DATA.ID=ACT_DOT.[ID] AND SUB_MED9DATA.METACODE='DOTDAY_MED9DOSENUMBER'
	LEFT JOIN [ATLASINTERNAL].VIEW_SUB_NCM_DOTDAY_MEDICATION SUB_MED10DATA (NOLOCK) ON SUB_MED10DATA.ID=ACT_DOT.[ID] AND SUB_MED10DATA.METACODE='DOTDAY_MED10DOSENUMBER'
WHERE 
	ACT_DOT.CLASSCODE='ENC' AND ACT_DOT.METACODE='DOTDAY_ID'
