
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CDCASE_SPECIMEN] AS
SELECT 
	ACTSPEC.ID AS CDSPEC_ID,
	ACT_BODY.ACT_PARENT_ID AS CDSPEC_NCMCASE_ID,
	ENTPAT.ID AS CDSPEC_PERSON_ID,
	ACTSPEC.EFFECTIVETIME_BEG AS CDSPEC_DATECOLLECTED,
	ACTSPEC.ACTIVITYTIME_BEG AS CDSPEC_DATETESTED,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ENTMAT.CODE_ID) AS CDSPEC_SPECIMENTYPE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(AOBS.INTERPRETATIONCODE_ID) AS CDSPEC_RESULT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDSPEC_PRIORANTIBIOTIC',ACTSPEC.ID,'VALUEBOOL') AS CDSPEC_PRIORANTIBIOTIC
FROM   DBO.A_ACT AS ACTSPEC (NOLOCK) 
	INNER JOIN A_ACT ACT_BODY  (NOLOCK) ON ACT_BODY.ID=ACTSPEC.ACT_PARENT_ID AND ACT_BODY.CLASSCODE='DOCBODY'
	INNER JOIN P_PARTICIPATION PART (NOLOCK) ON  PART.ACT_ID = ACTSPEC.ID AND PART.TYPECODE = 'SPC'
	INNER JOIN DBO.R_ROLE ROLE (NOLOCK) ON  ROLE.ID = PART.ROLE_ID AND ROLE.CLASSCODE = 'SPEC'
	INNER JOIN DBO.E_ENTITY ENTMAT (NOLOCK) ON  ENTMAT.ID = ROLE.PLAYER_ID AND ENTMAT.CLASSCODE = 'MAT' AND ENTMAT.DETERMINERCODE = 'QUANTIFIED_KIND'
	INNER JOIN E_ENTITY ENTPAT (NOLOCK) ON  ENTPAT.ID = ROLE.SCOPER_ID
	INNER JOIN A_OBSERVATION AOBS (NOLOCK) ON  AOBS.ID = ACTSPEC.ID
	WHERE  ACTSPEC.METACODE = 'CDSPEC_ID'
