
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_DENTAL]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,  
ACT_DENTAL.ID AS DENTAL_ID,  
CASE WHEN ISNULL([DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_REGULARORHYGIENE',ACT_DENTAL.ID,'ISVALUENULL'),0) = 1
		THEN NULL 
		ELSE [DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_REGULARORHYGIENE',ACT_DENTAL.ID,'VALUEBOOL') END AS DENT_REGULARORHYGIENE,    
CASE WHEN ISNULL([DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_CAVITIES',ACT_DENTAL.ID,'ISVALUENULL'),0) = 1
		THEN NULL 
		ELSE[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_CAVITIES',ACT_DENTAL.ID,'VALUEBOOL') END AS DENT_CAVITIES,  
ACT_DENTAL.EFFECTIVETIME_BEG AS DENT_LASTAPPOINTMENT,  
CASE WHEN ISNULL([DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_THRUSH',ACT_DENTAL.ID,'ISVALUENULL'),0) = 1
		THEN NULL 
		ELSE[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_THRUSH',ACT_DENTAL.ID,'VALUEBOOL') END AS DENT_THRUSH,   
CASE WHEN ISNULL([DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_UPPERDENTURE',ACT_DENTAL.ID,'ISVALUENULL'),0) = 1
		THEN NULL 
		ELSE[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_UPPERDENTURE',ACT_DENTAL.ID,'VALUEBOOL') END AS DENT_UPPERDENTURE,   
CASE WHEN ISNULL([DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_LOWERDENTURE',ACT_DENTAL.ID,'ISVALUENULL'),0) = 1
		THEN NULL 
		ELSE[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('DENT_LOWERDENTURE',ACT_DENTAL.ID,'VALUEBOOL') END AS DENT_LOWERDENTURE  
FROM 
	A_ACT ACT_DENTAL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_DENTAL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_DENTAL.METACODE='DENT_ID'
