
CREATE VIEW [AtlasInternal].[VIEW_NCM_PATIENTDATA_PATIENTDATA]
AS
SELECT 
	Sub_ViewPatData.[PAT_ID] AS [PAT_ID],
	Sub_ViewPatData.[PAT_NCMID] AS [PAT_NCMID],
	Sub_ViewPatData.[PAT_FIRSTNAME] AS [PAT_FIRSTNAME],
	Sub_ViewPatData.[PAT_LASTNAME] AS [PAT_LASTNAME],
	Sub_ViewPatData.[PAT_SS] AS [PAT_SS],
	Sub_ViewPatData.[PAT_ADDRESS] AS [PAT_ADDRESS],
	Sub_ViewPatData.[PAT_CITY] AS [PAT_CITY],
	Sub_ViewPatData.[PAT_STATE] AS [PAT_STATE],
	Sub_ViewPatData.[PAT_ZIP] AS [PAT_ZIP],
	Sub_ViewPatData.[PAT_DOB] AS [PAT_DOB],
	Sub_ViewPatData.[PAT_HOMEPHONE] AS [PAT_HOMEPHONE],
	Sub_ViewPatData.[PAT_MIDDLENAME] AS [PAT_MIDDLENAME],
	Sub_ViewPatData.[PAT_NAMESUFFIX] AS [PAT_NAMESUFFIX],
	PATADDR.PARTAPTNUM AS [PAT_APARTMENT],
	PATADDR.PARTCEN AS [PAT_CENSUSTRACT],
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'A', 'TEL')	AS [PAT_ALTERNATEPHONE],
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'WP', 'TEL') AS [PAT_COMPANYSCHOOLPHONE],
	-- +SKUMAR IssueNbr:110418 08/09/2011
	-- +MPatra Issue#112455 09/07/2011-
	DBO.MDF_ENTLOCNAME_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','SRCH') AS [PAT_COMPANYSCHOOL],	
	DBO.MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID(Sub_ViewPatData.[PAT_ID],'VALUESTRING', 'PER_WORKSCHOOLCONTACT') AS [PAT_SUPERVISORTEACHER],	
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('PAT_LASTWORKEDATTENDED', ACT_DOCBODY.ID,'VALUETS') AS [PAT_LASTWORKEDATTENDED],	
-- +MPatra Issue#112455 09/07/2011	
	DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','PARTSAL','PHYS') AS [PAT_COMPANYSCHOOLADDRESS],
	DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','PARTCTY','PHYS') AS [PAT_COMPANYSCHOOLCITY],
	DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','PARTSTA','PHYS') AS [PAT_COMPANYSCHOOLSTATE],
	DBO.MDF_ENTLOCADDRESSPART_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','PARTZIP','PHYS') AS [PAT_COMPANYSCHOOLZIP],
-- -MPatra Issue#112455 09/07/2011	
	-- -SKUMAR IssueNbr:110418 08/09/2011
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID],'PAT_SPEAKSENGLISH') AS [PAT_SPEAKSENGLISH],
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID],'PAT_READSENGLISH') AS [PAT_READSENGLISH],
	Sub_ViewPatData.[PAT_SSSTAT] as [PAT_SSSTAT],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](Sub_ViewPatData.DVPER_SEXCODE_ID) AS [PAT_GENDER],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](LANG.LANGUAGECODE_ID) AS [PAT_PRIMARYLANGUAGE],
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](Sub_ViewPatData.DVPER_ETHNICITYCODE_ID) AS [PAT_ETHNICITY],
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYROLEID](R_ROLE.ID, 'VALUECODE_ID', 'PAT_EDUCATION_FK')AS [PAT_EDUCATION],
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](Sub_ViewPatData.[PAT_ID] ,'VALUECODE_ID', 'PER_OCCUPATIONSETTINGTYPEDR') AS [PAT_OCCUPATIONSETTINGTYPE],
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](Sub_ViewPatData.[PAT_ID] ,'VALUECODE_ID', 'PER_OCCUPATIONDR') AS [PAT_OCCUPATION],
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'VALUECODE_ORTX', 'PER_OCCUPATIONSETTINGTYPEDR') AS [PAT_OCCUPATIONSETTINGTYPESPECIFY],
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'VALUECODE_ORTX', 'PER_OCCUPATIONDR') AS [PAT_OCCUPATIONSPECIFY],
	VIEW_HLTHCOV.HLTHCOV_MEDICAL AS [HLTHCOV_MEDICAL], 
	VIEW_HLTHCOV.HLTHCOV_MEDICALNUMBER AS [HLTHCOV_MEDICALNUMBER], 
	VIEW_HLTHCOV.HLTHCOV_EMERMEDICAL AS [HLTHCOV_EMERMEDICAL], 
	VIEW_HLTHCOV.HLTHCOV_EMERMEDICALNUMBER AS [HLTHCOV_EMERMEDICALNUMBER], 
	VIEW_HLTHCOV.HLTHCOV_TBMEDICAL AS [HLTHCOV_TBMEDICAL], 
	VIEW_HLTHCOV.HLTHCOV_TBMEDICALNUMBER AS [HLTHCOV_TBMEDICALNUMBER], 
	VIEW_HLTHCOV.HLTHCOV_MEDICARE AS [HLTHCOV_MEDICARE], 
	VIEW_HLTHCOV.HLTHCOV_MEDICARENUMBER AS [HLTHCOV_MEDICARENUMBER], 
	VIEW_HLTHCOV.HLTHCOV_MEDICAREEXCESS AS [HLTHCOV_MEDICAREEXCESS], 
	VIEW_HLTHCOV.HLTHCOV_PRIVATEINSURANCE AS [HLTHCOV_PRIVATEINSURANCE], 
	VIEW_HLTHCOV.HLTHCOV_PRIVATEINSURANCENUMBER AS [HLTHCOV_PRIVATEINSURANCENUMBER], 
	VIEW_HLTHCOV.HLTHCOV_PRIVATEINSURANCECOMPANY AS [HLTHCOV_PRIVATEINSURANCECOMPANY], 
	VIEW_HLTHCOV.HLTHCOV_PRIVATEINSURANCEEXCESS AS [HLTHCOV_PRIVATEINSURANCEEXCESS], 
	VIEW_HLTHCOV.HLTHCOV_UNINSURED AS [HLTHCOV_UNINSURED], 
	VIEW_HLTHCOV.HLTHCOV_INSURANCEELIGIBILITY AS [HLTHCOV_INSURANCEELIGIBILITY],
	VW_PATNOTES.[PAT_NOTES], --Saravanakumar Issue #110413 08/16/2011
	ECONTACT.VALUESTRING AS  [PAT_ELECTRONICCONTACT],
	EMAIL.VALUESTRING AS  [PAT_EMAIL]
FROM 
	
	[AtlasInternal].[VIEW_NCM_Sub_PatientData_PatientData] Sub_ViewPatData
	INNER JOIN DBO.E_ENTITY ENTITY_PSN (NOLOCK) ON ENTITY_PSN.ID = Sub_ViewPatData.[PAT_ID] 
	INNER JOIN DBO.S_LINK SL (NOLOCK) ON SL.ENTITY1_ID = ENTITY_PSN.ID AND SL.[NAME] = 'PERSON-PRIMARY'
	INNER JOIN DBO.R_ROLE (NOLOCK) ON R_ROLE.PLAYER_ID=Sub_ViewPatData.[PAT_ID]  and R_ROLE.classcode = 'PAT'
	INNER JOIN DBO.P_PARTICIPATION PART (NOLOCK) ON PART.ROLE_ID=R_ROLE.ID AND PART.TYPECODE='SBJ'
	INNER JOIN DBO.A_ACT ACT_FOLDER (NOLOCK) ON ACT_FOLDER.ID=PART.ACT_ID AND ACT_FOLDER.CLASSCODE='FOLDER' 
	LEFT JOIN ATLASINTERNAL.VIEW_SUB_NCM_PATIENTDATA_HEALTHCOVERAGE VIEW_HLTHCOV (NOLOCK) ON VIEW_HLTHCOV.ActFolder_ID=ACT_FOLDER.ID

	--SKUMAR IssueNbr:110418 08/11/2011 
	--BadhriNK Issue#137036 Added V_DOmain join in subquery
	LEFT JOIN DBO.A_ACT ACT_DOCBODY(NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=ACT_FOLDER.ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
				AND ACT_DOCBODY.CODE_ID=(SELECT V_Unifiedcodeset.ID FROM V_Unifiedcodeset (NOLOCK)
											INNER JOIN V_Domain (NOLOCK) on  V_Domain.id=V_Unifiedcodeset.domain_id
											WHERE V_Unifiedcodeset.ConceptCode='PTD' and V_Domain.domainName='AppForm')
	
	LEFT join [AtlasInternal].[VIEW_SUB_NCM_PATIENTDATA_NOTE] VW_PATNOTES (NOLOCK) on VW_PATNOTES.ACTDOCBODY_ID = ACT_DOCBODY.ID

	LEFT JOIN DBO.T_LANGUAGECOMMUNICATION LANG (NOLOCK) ON LANG.ENTITY_ID=Sub_ViewPatData.[PAT_ID] 
	LEFT JOIN DBO.T_ENTITYADDRESS PATADDR (NOLOCK) ON PATADDR.ID=SL.TADDRESS1_ID AND PATADDR.USECODE = 'H'
	-- +SKUMAR IssueNbr:110418 08/09/2011
	
	LEFT JOIN T_ATTRIBUTE EMAIL (NOLOCK) ON EMAIL.ENTITY_ID=Sub_ViewPatData.[PAT_ID] AND EMAIL.NAME='PSNID_EmailID' AND EMAIL.TYPE='ST'
	LEFT JOIN T_ATTRIBUTE ECONTACT (NOLOCK) ON ECONTACT.ENTITY_ID=Sub_ViewPatData.[PAT_ID] AND ECONTACT.NAME='PSNID_ElectronicContact' AND ECONTACT.TYPE='ST'	
	-- -SKUMAR IssueNbr:110418 08/09/2011




