
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_TBSITE]
AS
SELECT   
	DVSVC.DVSVC_ROWID AS SERVICE_FK,  
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,  
	ACT_TBSITE.ID AS TBSITE_ID,   
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISPULMONARY',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISPULMONARY,   
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISEXTRAPULMONARY',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISEXTRAPULMONARY,  
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('TBSITE_ISINFECTIOUS',ACT_TBSITE.ID,'VALUEBOOL') AS TBSITE_ISINFECTIOUS,   
	DBO.MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID(  DVSVC.DVSVC_PATIENT_FK,'VALUECODE_ID','TBIMMIGRANTSTATUS_FK') AS TBSITE_TBIMMIGRANTSTATUS_TEXT,   
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODBEGINMONTH_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODBEGINMONTH_TEXT,   
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODBEGINYEAR_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODBEGINYEAR_TEXT,   
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODENDMONTH_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODENDMONTH_TEXT,   
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('TBSITE_INFECTIOUSPERIODENDYEAR_FK',ACT_TBSITE.ID,'VALUECODE_ID') AS TBSITE_INFECTIOUSPERIODENDYEAR_TEXT
FROM   
	DV_SERVICE DVSVC (NOLOCK)  
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=DVSVC.DVSVC_ROWID AND DOCBODY.CLASSCODE='DOCBODY'   
	INNER JOIN A_ACT ACT_TBSITE (NOLOCK) ON ACT_TBSITE.ACT_PARENT_ID=DOCBODY.ID AND ACT_TBSITE.METACODE='TBSITE_ID'  
