

CREATE VIEW [AtlasInternal].[VIEW_CLIENTRECORD_DEMOGRAPHICS_CMMODE]
AS
SELECT 
		Sub_ViewPatData.[PAT_ID] AS [PAT_ID],
		Sub_ViewPatData.[PAT_NCMID] AS [PAT_CLIENTID],
		Sub_ViewPatData.[PAT_FIRSTNAME] AS [PAT_FIRSTNAME],
		Sub_ViewPatData.[PAT_LASTNAME] AS [PAT_LASTNAME],
		Sub_ViewPatData.[PAT_SS] AS [PAT_SSN],
		Sub_ViewPatData.[PAT_ADDRESS] AS [PAT_ADDRESS],
		Sub_ViewPatData.[PAT_CITY] AS [PAT_CITY],
		Sub_ViewPatData.[PAT_STATE] AS [PAT_STATE],
		Sub_ViewPatData.[PAT_ZIP] AS [PAT_ZIP],
		Sub_ViewPatData.[PAT_DOB] AS [PAT_DOB],
		Sub_ViewPatData.[PAT_HOMEPHONE] AS [PAT_HOMEPHONE],
		DBO.[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'MC', 'TEL')  AS [PAT_CELLPHONE],
		Sub_ViewPatData.[PAT_MIDDLENAME] AS [PAT_MIDDLENAME],
		Sub_ViewPatData.[PAT_NAMESUFFIX] AS [PAT_NAMESUFFIX],
		PATADDR.PARTAPTNUM AS [PAT_APARTMENT],
		PATADDR.PARTCEN AS [PAT_CENSUSTRACT],
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](COUNTY.valueCode_ID) AS [PAT_COUNTYOFRESIDENCE],
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](PATADDR.partCountry) AS [PAT_COUNTRYOFRESIDENCE],	
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](COUNTRY_BIR.partCountry) AS [PAT_COUNTRYOFBIRTH],
		DateOfArrival.valueTS as PAT_DATEOFUSARRIVAL,
		[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'WP', 'TEL') AS [PAT_WORKSCHOOLPHONE],
		WORKSCHOOLCONTACT.valueString AS [PAT_WORKSCHOOLCONTACT],
		DBO.MDF_ENTLOCNAME_ENTITY_BYPSNENTITYID(Sub_ViewPatData.[PAT_ID],'PER_WORKSCHOOLLOCATIONDR','SRCH') AS [PAT_WORKSCHOOL],                             
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](Sub_ViewPatData.DVPER_SEXCODE_ID) AS [PAT_GENDER],
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](LANG.LANGUAGECODE_ID) AS [PAT_PRIMARYLANGUAGE],
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](Sub_ViewPatData.DVPER_ETHNICITYCODE_ID) AS [PAT_ETHNICITY],
		[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](Sub_ViewPatData.[PAT_ID] ,'VALUECODE_ID', 'PER_OCCUPATIONSETTINGTYPEDR') AS [PAT_OCCUPATIONSETTINGTYPE],
		[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](Sub_ViewPatData.[PAT_ID] ,'VALUECODE_ID', 'PER_OCCUPATIONDR') AS [PAT_OCCUPATION],
		[DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'VALUECODE_ORTX', 'PER_OCCUPATIONSETTINGTYPEDR') AS [PAT_OCCUPATIONSETTINGTYPESPECIFY],
		[DBO].[MDF_ATTR_GETSTRINGVALUE_ENTATTR_BYENTITYID](Sub_ViewPatData.[PAT_ID], 'VALUECODE_ORTX', 'PER_OCCUPATIONDR') AS [PAT_OCCUPATIONSPECIFY],              
		VW_PATNOTES.[PAT_NOTES], 
		ECONTACT.VALUESTRING AS  [PAT_ELECTRONICCONTACT],
		[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](Sub_ViewPatData.DVPER_MaritalStatusCode_ID) AS PAT_MARITALSTATUS,
		EMAIL.VALUESTRING AS  [PAT_EMAIL],
		Sub_ViewPatData.[DVPER_CREATE_DATE] AS [PAT_CreateDate],
		GUARDIANNAME.VALUESTRING AS PAT_GUARDIANNAME,
		TEX.extension AS PAT_MEDICALRECORDNUMBER
FROM 
		[AtlasInternal].[VIEW_Sub_ClientRecord_Demographics_CMMode] Sub_ViewPatData
		INNER JOIN DBO.E_ENTITY ENTITY_PSN (NOLOCK) ON ENTITY_PSN.ID = Sub_ViewPatData.[PAT_ID] 
		INNER JOIN DBO.S_LINK SL (NOLOCK) ON SL.ENTITY1_ID = ENTITY_PSN.ID AND SL.[NAME] = 'PERSON-PRIMARY'
		INNER JOIN DBO.R_ROLE (NOLOCK) ON R_ROLE.PLAYER_ID=Sub_ViewPatData.[PAT_ID]  and R_ROLE.classcode = 'PAT'
		INNER JOIN DBO.P_PARTICIPATION PART (NOLOCK) ON PART.ROLE_ID=R_ROLE.ID AND PART.TYPECODE='SBJ'
		INNER JOIN DBO.A_ACT ACT_FOLDER (NOLOCK) ON ACT_FOLDER.ID=PART.ACT_ID AND ACT_FOLDER.CLASSCODE='FOLDER' 
		                                
		LEFT join [AtlasInternal].[VIEW_ClientRecord_Notes_CMMode] VW_PATNOTES (NOLOCK) on VW_PATNOTES.ACTFOLDER_ID = ACT_FOLDER.ID
		LEFT JOIN DBO.T_LANGUAGECOMMUNICATION LANG (NOLOCK) ON LANG.ENTITY_ID=Sub_ViewPatData.[PAT_ID] 
		LEFT JOIN DBO.T_ENTITYADDRESS PATADDR (NOLOCK) ON PATADDR.ID=SL.TADDRESS1_ID AND PATADDR.USECODE = 'H'
		LEFT JOIN T_ATTRIBUTE EMAIL (NOLOCK) ON EMAIL.ENTITY_ID=Sub_ViewPatData.[PAT_ID] AND EMAIL.NAME='PSNID_EmailID' AND EMAIL.TYPE='ST'
		LEFT JOIN T_ATTRIBUTE ECONTACT (NOLOCK) ON ECONTACT.ENTITY_ID=Sub_ViewPatData.[PAT_ID] AND ECONTACT.NAME='PSNID_ElectronicContact' AND ECONTACT.TYPE='ST'               
		LEFT JOIN T_Attribute GUARDIANNAME (nolock) ON GUARDIANNAME.Entity_ID=Sub_ViewPatData.[PAT_ID] AND GUARDIANNAME.Name='PER_GuardianName' AND GUARDIANNAME.Type='ST'   
		LEFT JOIN T_Attribute WORKSCHOOLCONTACT (nolock) ON WORKSCHOOLCONTACT.Entity_ID=Sub_ViewPatData.[PAT_ID] 
														AND WORKSCHOOLCONTACT.Name='PER_WorkSchoolContacT'AND WORKSCHOOLCONTACT.Type='ST'
		LEFT JOIN R_Role ROL ON ROL.player_ID=Sub_ViewPatData.[PAT_ID] AND ROL.classCode='PAT'
		LEFT JOIN T_InstanceIdentifier TEX ON TEX.Role_ID=ROL.ID AND TEX.metaCode='PER_MedRecNum'
		LEFT JOIN T_ENTITYADDRESS COUNTRY_BIR (NOLOCK) ON Sub_ViewPatData.[PAT_ID] = COUNTRY_BIR.Entity_ID AND COUNTRY_BIR.USECODE = 'BIR'
		LEFT JOIN T_ATTRIBUTE COUNTY (NOLOCK) ON Sub_ViewPatData.[PAT_ID] = COUNTY.ENTITY_ID AND COUNTY.NAME='PER_ResidenceCountyDR' AND COUNTY.[TYPE]='CV'
		LEFT OUTER JOIN dbo.T_Attribute AS DateOfArrival WITH (NOLOCK) ON Sub_ViewPatData.PAT_ID = DateOfArrival.Entity_ID AND DateOfArrival.name = 'PER_DateOfUSArrival'
               


