
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_DEVELOPMENTALSCREENINGTOOLS]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_DEVSCRN.ID AS DEVSCRN_ID,
	ACT_DEVSCRN.EFFECTIVETIME_BEG AS DEVSCRN_DATE,
	DBO.MDF_UCS_FULLNAME_ACTUCS_BYACTID(ACT_DEVSCRN.ID,'CODE_ID') AS DEVSCRN_SCREENTOOL,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('DEVSCRN_SCREENRESULT_FK',ACT_DEVSCRN.ID,'VALUECODE_ID') AS DEVSCRN_SCREENRESULT,
	ACT_DEVSCRN.TEXT AS DEVSCRN_COMMENTS
FROM 
	A_ACT ACT_DEVSCRN (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_DEVSCRN.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_DEVSCRN.METACODE='DEVSCRN_ID'
