
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CASEFLOW_DOTWORKER]
AS
SELECT 
	DVSVC.DVSVC_ROWID AS SERVICE_FK,
	DVSVC.DVSVC_PATIENT_FK AS PATIENT_FK,
	([DBO].[MDF_ENTITYNAME_GETVALUE_BYENTITYID](R_ROLE.PLAYER_ID,'L','PARTFAM') + ', ' + [DBO].[MDF_ENTITYNAME_GETVALUE_BYENTITYID](R_ROLE.PLAYER_ID,'L','PARTGIV')) AS [DOTWRKL_NAME],
	[ACT_DOTWRKL].[ID] AS [DOTWRKL_ID],
	[R_ROLE].[ID] AS [DOTWRKL_USER_FK],
	[T_ATTRIBUTE].[VALUESTRING] AS [DOTWRKL_USER_INITIALS], 
	[ACT_DOTWRKL].[EFFECTIVETIME_BEG] AS [DOTWRKL_DATEBEGUN],
	CONVERT(VARCHAR(5),[ACT_DOTWRKL].[ACTIVITYTIME_BEG], 108)AS [DOTWRKL_VISITTIME],
	CASE WHEN CHARINDEX('DW1',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_MONDAY], 
	CASE WHEN CHARINDEX('DW2',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_TUESDAY], 
	CASE WHEN CHARINDEX('DW3',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_WEDNESDAY], 
	CASE WHEN CHARINDEX('DW4',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_THURSDAY], 
	CASE WHEN CHARINDEX('DW5',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_FRIDAY], 
	CASE WHEN CHARINDEX('DW6',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_SATURDAY], 
	CASE WHEN CHARINDEX('DW7',[ACT_DOTWRKL].[EFFECTIVETIME_TXT])=0 THEN 0 ELSE 1 END AS [DOTWRKL_SUNDAY] 
FROM 
	DV_SERVICE DVSVC (NOLOCK)
	INNER JOIN A_ACT SVC (NOLOCK) ON SVC.ID=DVSVC.DVSVC_ROWID AND SVC.CLASSCODE='CASE'  AND SVC.STATUSCODE <> 'NULLIFIED' AND SVC.METACODE='SVC_ID'
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID=SVC.ID AND DOCBODY.CLASSCODE='DOCBODY' AND DOCBODY.ACT_PARENT_TYPECODE='COMP'
	INNER JOIN A_ACT ACT_DOTWRKL (NOLOCK) ON ACT_DOTWRKL.ACT_PARENT_ID=DOCBODY.ID AND ACT_DOTWRKL.CLASSCODE='ENC' AND ACT_DOTWRKL.MOODCODE='INT' AND ACT_DOTWRKL.METACODE='DOTWRKL_ID' AND ACT_DOTWRKL.STATUSCODE <> 'NULLIFIED'
	INNER JOIN [A_PATIENTENCOUNTER] (NOLOCK) ON  [ACT_DOTWRKL].[ID]=[A_PATIENTENCOUNTER].[ID] 
	INNER JOIN [P_PARTICIPATION] (NOLOCK) ON  [ACT_DOTWRKL].[ID]=[P_PARTICIPATION].[ACT_ID] AND ( ( [P_PARTICIPATION].[TYPECODE] = 'PRF'))
	INNER JOIN [R_ROLE] (NOLOCK) ON  [R_ROLE].[ID]=[P_PARTICIPATION].[ROLE_ID] AND ( ( [R_ROLE].[CLASSCODE] = 'AGNT')) 
	LEFT JOIN [T_ATTRIBUTE] (NOLOCK) ON  [R_ROLE].[ID]=[T_ATTRIBUTE].[ROLE_ID] AND ( ( [T_ATTRIBUTE].[NAME] = 'USER_INITIALS' AND [T_ATTRIBUTE].[TYPE] = 'ST')) 

