
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_NEUROLOGICAL]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_NEUROLOGICAL.ID AS NEUROLOGICAL_ID, 
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('NEUR_NEUROLOGICAL',ACT_NEUROLOGICAL.ID,'VALUEBOOL') AS NEUR_NEUROLOGICAL, 
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('NEUR_HEADACHE',ACT_NEUROLOGICAL.ID,'VALUEBOOL') AS NEUR_HEADACHE,
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('NEUR_DIZZINESS',ACT_NEUROLOGICAL.ID,'VALUEBOOL') AS NEUR_DIZZINESS, 
	DBO.[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('NEUR_BLURREDVISION',ACT_NEUROLOGICAL.ID,'VALUEBOOL') AS NEUR_BLURREDVISION, 
	ACT_NEUROLOGICAL.TEXT AS NEUR_COMMENTS
FROM 
	A_ACT ACT_NEUROLOGICAL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_NEUROLOGICAL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_NEUROLOGICAL.METACODE='NEUR_ID'
