
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_CHILDNUTRITION] 
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_CHLDNUTR.ID AS CHLDNUTR_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_CHILDNUTRITION',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_CHILDNUTRITION,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_EVERBREASTFEED',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_EVERBREASTFEED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_EVERINCLUDEFORMULA',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_EVERINCLUDEFORMULA,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHLDNUTR_STILLBREASTFEEDING_FK',ACT_CHLDNUTR.ID,'VALUECODE_ID') AS CHLDNUTR_STILLBREASTFEEDING,
	DBO.MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_AGESTOPPEDBREASTFEEDING',ACT_CHLDNUTR.ID,'VALUENUMERATOR') AS
	CHLDNUTR_AGESTOPPEDBREASTFEEDING,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_BREASTFEEDINGPAIN',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_BREASTFEEDINGPAIN,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_STILLBREASTFEEDING_FK',ACT_CHLDNUTR.ID,'EFFECKTIVETIME_TXT') AS CHLDNUTR_BREASTFEEDINGQ_HR,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_LATCHONEFFECTIVE',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_LATCHONEFFECTIVE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_NUTRITIVESUCKING',ACT_CHLDNUTR.ID,'VALUEBOOL') AS CHLDNUTR_NUTRITIVESUCKING,
	ACT_AGESTOPPEDBREASTFEEDING.TEXT AS CHLDNUTR_REASONSTOPPEDBF,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHLDNUTR_FLUIDSTYPE_FK',ACT_CHLDNUTR.ID,'CODE_ID') AS CHLDNUTR_FLUIDSTYPE,
	DBO.MDF_UCS_FULLNAME_ATTRUCS_BYACTID(ACT_FLUIDSTYPE.ID,'VALUECODE_ID','CHLDNUTR_FLUIDSFROM_FK') AS CHLDNUTR_FLUIDSFROM,
	ASUB.DOSEQUANTITY_LO AS CHLDNUTR_FLUIDSOZ,
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHLDNUTR_FLUIDSTYPE_FK',ACT_CHLDNUTR.ID,'EFFECKTIVETIME_TXT') AS CHLDNUTR_FLUIDSQ_HR,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHLDNUTR_SOLIDS_FK',ACT_CHLDNUTR.ID,'VALUECODE_ID') AS CHLDNUTR_SOLIDS,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHLDNUTR_FLUIDSINTAKE_FK',ACT_CHLDNUTR.ID,'VALUECODE_ID') AS CHLDNUTR_FLUIDSINTAKE,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYFRUIT',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYFRUIT,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYVEGETABLE',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYVEGETABLE,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYCEREAL',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYCEREAL,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYEGG',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYEGG,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYMEALS',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYMEALS,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYSNACKS',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYSNACKS,
	ACT_FOODPREFERENCE.TEXT AS CHLDNUTR_FOODPREFERENCE,ACT_SPECIALDIET.TEXT AS CHLDNUTR_SPECIALDIET,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYMEAT',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYMEAT,
	DBO.[MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE]('CHLDNUTR_DAILYDAIRY',ACT_CHLDNUTR.ID,'VALUEREAL') AS CHLDNUTR_DAILYDAIRY,
	ACT_CHILDNUTRITION.TEXT AS CHLDNUTR_COMMENTS
FROM 
	A_ACT ACT_CHLDNUTR (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_CHLDNUTR.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
	LEFT JOIN A_ACT ACT_CHILDNUTRITION (NOLOCK) ON ACT_CHILDNUTRITION.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_CHILDNUTRITION.METACODE='CHLDNUTR_CHILDNUTRITION'
	LEFT JOIN A_ACT ACT_STILLBREASTFEEDING (NOLOCK) ON ACT_STILLBREASTFEEDING.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_STILLBREASTFEEDING.METACODE='CHLDNUTR_STILLBREASTFEEDING_FK'
	LEFT JOIN A_ACT ACT_AGESTOPPEDBREASTFEEDING (NOLOCK) ON ACT_AGESTOPPEDBREASTFEEDING.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_AGESTOPPEDBREASTFEEDING.METACODE='CHLDNUTR_AGESTOPPEDBREASTFEEDING'
	LEFT JOIN A_ACT ACT_FLUIDSTYPE (NOLOCK) ON ACT_FLUIDSTYPE.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_FLUIDSTYPE.METACODE='CHLDNUTR_FLUIDSTYPE_FK'
	LEFT JOIN A_SUBSTANCEADMINISTRATION ASUB (NOLOCK) ON ASUB.ID=ACT_FLUIDSTYPE.ID
	LEFT JOIN A_ACT ACT_FOODPREFERENCE (NOLOCK) ON ACT_FOODPREFERENCE.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_FOODPREFERENCE.METACODE='CHLDNUTR_FOODPREFERENCE'
	LEFT JOIN A_ACT ACT_SPECIALDIET (NOLOCK) ON ACT_SPECIALDIET.ACT_PARENT_ID=ACT_CHLDNUTR.ID AND ACT_SPECIALDIET.METACODE='CHLDNUTR_SPECIALDIET' 
WHERE 
	ACT_CHLDNUTR.METACODE='CHLDNUTR_ID' AND ACT_CHLDNUTR.STATUSCODE='ACTIVE'
