
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_TUBERCULOSIS_PPD]
AS
SELECT 
	VIEW_SUB_REFTUB.PATIENT_FK AS PPDHIST_PATIENT_FK,
	VIEW_SUB_REFTUB.SERVICE_FK AS PPDHIST_SERVICE_FK,
	VIEW_SUB_REFTUB.ACT_ID AS PPDHIST_ID,
	(SELECT CONCEPTCODE FROM V_UNIFIEDCODESET (NOLOCK) WHERE ID = A_OBSERVATION.INTERPRETATIONCODE_ID) AS PPDHIST_ISPOSITIVE,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](A_OBSERVATION.METHODCODE_ID) AS PPDHIST_PPDTYPE,
	VIEW_SUB_REFTUB.ACT_EFFECTIVETIME_BEG AS PPDHIST_DATE,
	VIEW_SUB_REFTUB.ACT_ACTIVITYTIME_BEG AS PPDHIST_INTERPRETED,
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID](VIEW_SUB_REFTUB.ACT_ID, 'VALUESTRING', 'PPDHIST_WHERE') AS PPDHIST_WHERE,
	VIEW_SUB_REFTUB.ACT_VALUENUMERATOR AS PPDHIST_RESULT,
	DBO.[MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE](VIEW_SUB_REFTUB.ACT_ID, 'PPDHIST_NEXTDUEDATE', 'SEQL', 'EFFECTIVETIME_BEG') AS PPDHIST_NEXTDUEDATE,
	VIEW_SUB_REFTUB.ACT_TEXT AS PPDHIST_COMMENTS
FROM   
	DBO.A_OBSERVATION (NOLOCK)
	INNER JOIN [ATLASINTERNAL].[VIEW_SUB_REFERRAL_TUBERCULOSIS] VIEW_SUB_REFTUB ON VIEW_SUB_REFTUB.ACT_ID = A_OBSERVATION.ID 
				AND VIEW_SUB_REFTUB.ACT_CLASSCODE = 'OBS' AND VIEW_SUB_REFTUB.ACT_METACODE = 'PPDHIST_ID' 
	
