
CREATE VIEW [AtlasInternal].[VIEW_NCM_VISIT_ELIGIBILITY]      
AS     
  
SELECT       
 ACT_VISITDETAIL.ID AS VISITDTL_ID,
 ACT_VISITGROUP.ID AS VISITGRP_ID,      
 
 --TARGET GROUP
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('CUA21', ACT_VISITGROUP.ID, 0) AS VISITGRP_AGETO21,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('IARI', ACT_VISITGROUP.ID, 0) AS VISITGRP_INDIRISKINSTITUTIONALIZATION,  
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('IJNHPSO', ACT_VISITGROUP.ID, 0) AS VISITGRP_INDJEOPPSYCHOSOCIALOUTCOMES,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('ICD', ACT_VISITGROUP.ID, 0) AS VISITGRP_INDWITHCD,  
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('MFI', ACT_VISITGROUP.ID, 0) AS VISITGRP_MEDFRAGILEINDIVIDUALS,  
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('NECM', ACT_VISITGROUP.ID, 0) AS VISITGRP_NEEDSMGMT,  
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('NONE', ACT_VISITGROUP.ID, 0) AS VISITGRP_NONE,   
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('PTD', ACT_VISITGROUP.ID, 0) AS VISITGRP_TECHDEPENDENT,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('PHA', ACT_VISITGROUP.ID, 0) AS VISITGRP_HIV,  
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('PMD', ACT_VISITGROUP.ID, 0) AS VISITGRP_MULTIPLEDIAGNOSES,   
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('PW', ACT_VISITGROUP.ID, 0) AS VISITGRP_PREGNANT,     

 --RISK GROUP
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('ALCSSAAFCH', ACT_VISITGROUP.ID, 1) AS VISITGRP_LACKOFCOMMUNITYSUPPORT,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('AVANV', ACT_VISITGROUP.ID, 1) AS VISITGRP_ABUSENEGLECTVIOLENCE,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('AICMMSOSDEUMCNS', ACT_VISITGROUP.ID, 1) AS VISITGRP_UNSTABLECONDITION,    
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('AIUMDBCB', ACT_VISITGROUP.ID, 1) AS VISITGRP_COMPREHENSIONBARRIERS,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('ESH', ACT_VISITGROUP.ID, 1) AS VISITGRP_SUBSTANDARDHOUSING,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('FTUHS', ACT_VISITGROUP.ID, 1) AS VISITGRP_FAILSTOUSESERVICES,
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('FTANHCS', ACT_VISITGROUP.ID, 1) AS VISITGRP_FAILSTOTAKEADVSERVICES,
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('FITANHCS', ACT_VISITGROUP.ID, 1) AS VISITGRP_FAILSORINABILITYTOTAKEADVSERVICES,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('HDPSEA', ACT_VISITGROUP.ID, 1) AS VISITGRP_PHYSICALSEXUALEMOTIONALABUSE,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('HDD', ACT_VISITGROUP.ID, 1) AS VISITGRP_HISTORYOFDELINQUENCY,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('HDFV', ACT_VISITGROUP.ID, 1) AS VISITGRP_HISTORYOFFAMILYVIOLENCE,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('ILTR', ACT_VISITGROUP.ID, 1) AS VISITGRP_ILLITERACY,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('NPMR', ACT_VISITGROUP.ID, 1) AS VISITGRP_NONCOMPLIANT,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('NONE', ACT_VISITGROUP.ID, 1) AS VISITGRP_RISKNONE,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('SA', ACT_VISITGROUP.ID, 1) AS VISITGRP_SUBSTANCEABUSE,     
 DBO.[MDF_ACT_GETVALUEBOOL_ACT_BYPARACTIDCODEUCSTYPE]('SAIIE', ACT_VISITGROUP.ID, 1) AS VISITGRP_SUBSTANCEABUSEENVIRONMENT      

FROM       
 A_ACT ACT_VISITGROUP (NOLOCK)       
 INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_VISITGROUP.ACT_PARENT_ID AND ACT_VISITDETAIL.METACODE='VISITDTL_ID'   
 AND ACT_VISITDETAIL.CLASSCODE='ENC'      
WHERE       
 ACT_VISITGROUP.METACODE='VISITGRP_ID' AND ACT_VISITGROUP.CLASSCODE='DOCSECT' AND ACT_VISITGROUP.STATUSCODE='ACTIVE' 
 

