
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_TBHISTORY_DOCTOR]
AS

SELECT 
	VPSNLINK.TBHIST_SERVICEID AS TBHISTDOC_SERVICE_FK,
VPSNLINK.TBHIST_PATIENTID AS TBHISTDOC_PATIENT_FK,
	ENTITY_PROV.ID AS TBHISTDOC_ID,
	[DBO].[MDF_ENTITYNAME_GETVALUE_BYENTITYID](ENTITY_PROV.ID, 'L', 'TRIVIALNAME') AS TBHISTDOC_DOCTORCLINICNAME,
	[DBO].[MDF_ADDRPART_ADDRESS_ENTADDRADDRPART_BYADDRIDUSECODE](ENTITY_PROV.ID, 'CTY', 'WP') AS TBHISTDOC_DOCTORCLINICCITY,
	[DBO].[MDF_ENTTELECOM_ADDRESS_ENTITY_BYENTITYID](ENTITY_PROV.ID, 'WP', 'TEL') AS TBHISTDOC_DOCTORCLINICPHONE 

FROM
	E_ENTITY ENTITY_PROV (NOLOCK) 
	INNER JOIN R_ROLE ROLE_PLAYER  (NOLOCK) ON ROLE_PLAYER.PLAYER_ID = ENTITY_PROV.ID AND ROLE_PLAYER.CLASSCODE = 'PROV'
	INNER JOIN P_PARTICIPATION PART_PROV  (NOLOCK) ON PART_PROV.ROLE_ID = ROLE_PLAYER.ID AND PART_PROV.TYPECODE = 'PROV'
	INNER JOIN A_ACT ACT_OBSCLIN  (NOLOCK) ON ACT_OBSCLIN.ID = PART_PROV.ACT_ID AND ACT_OBSCLIN.CLASSCODE = 'OBS'
	INNER JOIN A_ACT  (NOLOCK) ON A_ACT.ID =  ACT_OBSCLIN.ACT_PARENT_ID 
	INNER JOIN VIEW_SUB_NCM_TBHISTORY_PSNLINK VPSNLINK  (NOLOCK) ON A_ACT.ACT_PARENT_ID = VPSNLINK.DOCBODY_ID

WHERE 
	ENTITY_PROV.CLASSCODE = 'ENT' AND
	ENTITY_PROV.STATUSCODE <> 'NULLIFIED'
