
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_CHRONICDISEASELIST]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_CHDISLIST.ID AS CHDISLIST_ID,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('CHDISLIST_DISEASE_FK',ACT_CHDISLIST.ID ,'VALUECODE_ID') AS CHDISLIST_DISEASE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHDISLIST_CONTROLLED', ACT_CHDISLIST.ID  , 'VALUEBOOL') AS CHDISLIST_CONTROLLED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHDISLIST_UNCONTROLLED', ACT_CHDISLIST.ID  , 'VALUEBOOL') AS CHDISLIST_UNCONTROLLED,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHDISLIST_SEEKMEDICALTREAT', ACT_CHDISLIST.ID  , 'VALUEBOOL') AS CHDISLIST_SEEKMEDICALTREAT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CHDISLIST_EMERROOMVISITS', ACT_CHDISLIST.ID  , 'VALUEBOOL') AS CHDISLIST_EMERROOMVISITS
FROM 
	A_ACT ACT_CHDISLIST (NOLOCK) 
	INNER JOIN A_ACT ACT_CHDIS (NOLOCK) ON ACT_CHDIS.ID=ACT_CHDISLIST.ACT_PARENT_ID AND ACT_CHDIS.METACODE='CHDIS_ID' 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_CHDIS.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_CHDISLIST.METACODE='CHDISLIST_ID' AND ACT_CHDISLIST.STATUSCODE='ACTIVE'
