
CREATE VIEW [AtlasInternal].[VIEW_NCM_TBHISTORY]
AS 

SELECT 
	VPSNLINK.TBHIST_SERVICEID AS TBHIST_SERVICEID,
VPSNLINK.TBHIST_PATIENTID AS TBHIST_PATIENTID,
	ACT_HIST.ID TBHISTPG_ID,

	[DBO].[MDF_ADDRPART_ADDRESS_ENTADDRADDRPART_BYADDRIDUSECODE](VPSNLINK.TBHIST_PATIENTID, 'CNT', 'BIR') AS IMGR_COUNTRYOFBIRTH,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](VPSNLINK.TBHIST_PATIENTID, 'VALUECODE_ID', 'IMGR_MONTHARRIVEDUSA_FK') AS IMGR_MONTHARRIVEDUSA,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYENTITYID](VPSNLINK.TBHIST_PATIENTID, 'VALUECODE_ID', 'IMGR_YEARARRIVEDUSA_FK') AS IMGR_YEARARRIVEDUSA,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](LANG_PSN.LANGUAGECODE_ID) AS IMGR_PRIMARYLANGUAGE,
	
	----  1. WHY DO YOU NEED TB TESTING?  
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ISTESTINGREQUIRED', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_ISTESTINGREQUIRED,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_REFERREDBYMD', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_REFERREDBYMD,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ISCONTACTTOCASE', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_ISCONTACTTOCASE,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_OTHERREASON', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_OTHERREASON,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_OTHERREASON', ACT_HIST.ID, 'TEXT') AS TBHISTPG_OTHERREASONSPECIFY,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FORJOB', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FORJOB,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FORSCHOOL', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FORSCHOOL,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FORVOLUNTEERPROGRAM', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FORVOLUNTEERPROGRAM,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FORIMMIGRATION', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FORIMMIGRATION,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FORDRUGSALCOHOL', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FORDRUGSALCOHOL,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FOROTHERREASON', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FOROTHERREASON,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FOROTHERREASON', ACT_HIST.ID, 'TEXT') AS TBHISTPG_FOROTHERREASONSPECIFIED,

	----- 1A. CHOOSE ONE 
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_CURRENTLYATTENDING', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_CURRENTLYATTENDING,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_CLEARANCENEEDED', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_CLEARANCENEEDED,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_NA', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_NA,
	
	------ 1B. NAME OF THE ABOVE ESTABLISHMENT 
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ESTABLISHMENT', ACT_HIST.ID, 'VALUESTRING') AS TBHISTPG_ESTABLISHMENT,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ESTABLISHMENTADDRESS', ACT_HIST.ID, 'VALUESTRING') AS TBHISTPG_ESTABLISHMENTADDRESS,
	
	------ 2. CURRENT TB SKIN TEST: CLINIC 
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_CURRENTSKINTESTCLINIC', ACT_HIST.ID, 'VALUESTRING') AS TBHISTPG_CURRENTSKINTESTCLINIC,
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('TBHISTPG_CURRENTSKINTESTRESULT', ACT_HIST.ID, 'VALUENUMERATOR') AS TBHISTPG_CURRENTSKINTESTRESULT,
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_CURRENTSKINTESTRESULT', ACT_HIST.ID, 'EFFECTIVETIME_BEG') AS TBHISTPG_CURRENTSKINTESTDATE,

	------ 3. PREVIOUS TB SKIN TEST: CLINIC 
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PREVIOUSSKINTESTCLINIC', ACT_HIST.ID, 'VALUESTRING') AS TBHISTPG_PREVIOUSSKINTESTCLINIC,
	[DBO].MDF_ACT_GETREALVALUE_ACT_BYPARACTIDMETACLASSVALUETYPE('TBHISTPG_PREVIOUSSKINTESTRESULT', ACT_HIST.ID, 'VALUENUMERATOR') AS TBHISTPG_PREVIOUSSKINTESTRESULT,
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PREVIOUSSKINTESTRESULT', ACT_HIST.ID, 'EFFECTIVETIME_BEG') AS TBHISTPG_PREVIOUSSKINTESTDATE,

	------ 4. PREVIOUS CHEST X-RAY: CLINIC 
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PREVIOUSCXRCLINIC', ACT_HIST.ID, 'VALUESTRING') AS TBHISTPG_PREVIOUSCXRCLINIC,
	[DBO].[MDF_UCS_FULLNAME_ACTOBSERVATION_BYPARENTACTID](ACT_HIST.ID, 'INTERPRETATIONCODE_ID', 'TBHISTPG_PREVIOUSCXRRESULT_FK') AS TBHISTPG_PREVIOUSCXRRESULT,
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PREVIOUSCXRRESULT_FK', ACT_HIST.ID, 'EFFECTIVETIME_BEG') AS TBHISTPG_PREVIOUSCXRDATE,
	
	------ 5. VACCINATION AGAINST TB
	[DBO].MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'TBHISTPG_RECEIVEDVACCINE_FK', ACT_HIST.ID, 'VALUECODE_ID') AS TBHISTPG_RECEIVEDVACCINE,	
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_RECEIVEDVACCINE_FK', ACT_HIST.ID, 'EFFECTIVETIME_BEG') AS TBHISTPG_RECEIVEDVACCINE_DATE,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_RECEIVEDVACCINEBLADDERCA', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_RECEIVEDVACCINEBLADDERCA,	
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_RECEIVEDVACCINEIMMUNIZATION', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_RECEIVEDVACCINEIMMUNIZATION,

	------ 7 A. TREATMENT FOR TB
	[DBO].MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID( 'TBHISTPG_RECEIVEDTREATMENT_FK', ACT_HIST.ID, 'VALUECODE_ID') AS TBHISTPG_RECEIVEDTREATMENT,
	ACT_TREATMENT.EFFECTIVETIME_BEG AS TBHISTPG_TREATMENTYEAR,
	ACT_TREATMENT.[TEXT] AS TBHISTPG_TREATMENTTBMEDS,
	ACT_TREATMENT.EFFECTIVETIME_DUR AS TBHISTPG_TREATMENTMONTHS,
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_TREATMENT.ID, 'VALUESTRING', 'TBHISTPG_TREATMENTPLACE') AS TBHISTPG_TREATMENTPLACE,

	------ 7 B. LTBI TREATMENT
	ACT_LTBITREATMENT.VALUEBOOL AS TBHISTPG_LTBITREATED,
	ACT_LTBITREATMENT.EFFECTIVETIME_BEG AS TBHISTPG_LTBITREATEDYEAR,
	ACT_LTBITREATMENT.[TEXT] AS TBHISTPG_LTBITREATEDTBMEDS,
	ACT_LTBITREATMENT.EFFECTIVETIME_DUR AS TBHISTPG_LTBITREATEDDURATION,
	-- SKUMAR IssueNbr:110421 08/10/2011
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_LTBITREATMENT.ID, 'VALUESTRING', 'TBHISTPG_LTBITREATEDLOCATION') AS TBHISTPG_LTBITREATEDLOCATION,
		
	------ 6. CONTACT TO ACTIVE CASE.
	ACT_CONTACTTOACTIVECASE.VALUEBOOL AS TBHISTPG_CONTACTTOACTIVECASE,
	-- +SKUMAR IssueNbr:110421 08/10/2011
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_CONTACTTOACTIVECASE.ID, 'VALUESTRING', 'TBHISTPG_ACTIVECASELASTNAME') AS TBHISTPG_ACTIVECASELASTNAME,
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_CONTACTTOACTIVECASE.ID, 'VALUESTRING', 'TBHISTPG_ACTIVECASEFIRSTNAME') AS TBHISTPG_ACTIVECASEFIRSTNAME,
	-- -SKUMAR IssueNbr:110421 08/10/2011	
	ACT_CONTACTTOACTIVECASE.EFFECTIVETIME_BEG AS TBHISTPG_ACTIVECASEEXPOSEDFROM,
	ACT_CONTACTTOACTIVECASE.EFFECTIVETIME_END AS TBHISTPG_ACTIVECASEEXPOSEDTO,

	------ 8. ACTIVE CASES IN FAMILY.
	ACT_ACTIVECASEINFAMILY.VALUEBOOL AS TBHISTPG_ACTIVECASEINFAMILY,
	-- +SKUMAR IssueNbr:110421 08/10/2011
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_ACTIVECASEINFAMILY.ID, 'VALUESTRING', 'TBHISTPG_FAMILYCASELASTNAME') AS TBHISTPG_FAMILYCASELASTNAME,
	[DBO].MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(ACT_ACTIVECASEINFAMILY.ID, 'VALUESTRING', 'TBHISTPG_FAMILYCASEFIRSTNAME') AS TBHISTPG_FAMILYCASEFIRSTNAME,
	-- -SKUMAR IssueNbr:110421 08/10/2011		
	ACT_ACTIVECASEINFAMILY.EFFECTIVETIME_BEG AS TBHISTPG_FAMILYCASEEXPOSEDFROM,
	ACT_ACTIVECASEINFAMILY.EFFECTIVETIME_END AS TBHISTPG_FAMILYCASEEXPOSEDTO,

	----- 9.A TB SYMPTOMS 
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PRODUCTIVECOUGH', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_PRODUCTIVECOUGH,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_COUGHINGBLOOD', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_COUGHINGBLOOD,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_UNEXPLAINEDCHILLS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_UNEXPLAINEDCHILLS,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_DRENCHINGSWEATING', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_DRENCHINGSWEATING,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_WEIGHTLOSS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_WEIGHTLOSS,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_CHESTPAIN', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_CHESTPAIN,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_FEVER', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_FEVER,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_APPETITELOSS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_APPETITELOSS,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_TIRED', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_TIRED,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_SHORTBREATH', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_SHORTBREATH,
	
	---- SMOKES
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_SMOKES', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_SMOKES,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_SMOKES', ACT_HIST.ID, 'TEXT') AS TBHISTPG_SMOKESHOWMUCH,

	---- DRINKS
	ACT_DRINKS.VALUEBOOL AS TBHISTPG_DRINKS,
	ACT_DRINKS.TEXT AS TBHISTPG_DRINKSWHAT,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_DRINKSHOWMUCH', ACT_DRINKS.ID, 'VALUESTRING') AS TBHISTPG_DRINKSHOWMUCH,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_DRINKSHOWOFTEN', ACT_DRINKS.ID, 'VALUESTRING') AS TBHISTPG_DRINKSHOWOFTEN,

	---- DRUGS
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_USESDRUGS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_USESDRUGS,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_USESDRUGS', ACT_HIST.ID, 'TEXT') AS TBHISTPG_USESWHATDRUG,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_USESDRUGSHOWOFTEN', ACT_DRINKS.ID, 'VALUESTRING') AS TBHISTPG_USESDRUGSHOWOFTEN,

	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_DOCTORCLINIC', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_DOCTORCLINIC,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_MEDICALCONDITIONS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_MEDICALCONDITIONS,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_MEDICALCONDITIONS', ACT_HIST.ID, 'TEXT') AS TBHISTPG_CONDITIONSCOMMENTS,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_TAKINGMEDICATION', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_TAKINGMEDICATION,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ALLERGIESTOMEDICATION', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_ALLERGIESTOMEDICATION,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_ALLERGIESTOMEDICATION', ACT_HIST.ID, 'TEXT') AS TBHISTPG_MEDICATIONALLERGICTO,

	------ 16. RISK OF DEVELOPING ACTIVE TB
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_SEXWITHHIVINFECTED', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_SEXWITHHIVINFECTED,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_INJECTEDDRUGS', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_INJECTEDDRUGS,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_HEMOPHILIA', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_HEMOPHILIA,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_BLOODTRANSFUSION', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_BLOODTRANSFUSION,

	--- HIV AND BIRTH CONTROL
	[DBO].[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]( 'TBHISTPG_HIVTEST_FK', ACT_HIST.ID, 'VALUECODE_ID') AS TBHISTPG_HIVTEST,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_HIVTEST_FK', ACT_HIST.ID, 'TEXT') AS  TBHISTPG_HIVTESTRESULT,
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_HIVTEST_FK', ACT_HIST.ID, 'EFFECTIVETIME_BEG') AS  TBHISTPG_HIVTESTDATE,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_BIRTHCONTROL', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_BIRTHCONTROL,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_BIRTHCONTROL', ACT_HIST.ID, 'TEXT') AS TBHISTPG_BIRTHCONTROLTYPE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_PREGNANT.VALUECODE_ID) AS TBHISTPG_PREGNANT,
	[DBO].MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_PREGNANT_FK', ACT_PREGNANT.ID, 'VALUETS') AS TBHISTPG_EDD,

	ACT_HIST.EFFECTIVETIME_BEG AS TBHISTPG_INTERVIEWDATE,
	[DBO].MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTPG_INCARCERATED', ACT_HIST.ID, 'VALUEBOOL') AS TBHISTPG_INCARCERATED,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE( 'TBHISTPG_COMMENTS', ACT_HIST.ID, 'TEXT') AS TBHISTPG_COMMENTS

FROM 
	A_ACT ACT_HIST (NOLOCK) 
	INNER JOIN [ATLASINTERNAL].VIEW_SUB_NCM_TBHISTORY_PSNLINK AS VPSNLINK  (NOLOCK) ON VPSNLINK.DOCBODY_ID = ACT_HIST.ACT_PARENT_ID
	
	LEFT JOIN T_LANGUAGECOMMUNICATION LANG_PSN  (NOLOCK) ON LANG_PSN.ENTITY_ID = VPSNLINK.TBHIST_PATIENTID
	LEFT JOIN A_ACT ACT_CONTACTTOACTIVECASE (NOLOCK) ON ACT_CONTACTTOACTIVECASE.ACT_PARENT_ID = ACT_HIST.ID AND ACT_CONTACTTOACTIVECASE.CLASSCODE = 'OBS' AND ACT_CONTACTTOACTIVECASE.METACODE = 'TBHISTPG_CONTACTTOACTIVECASE'
	LEFT JOIN A_ACT ACT_ACTIVECASEINFAMILY (NOLOCK) ON ACT_ACTIVECASEINFAMILY.ACT_PARENT_ID = ACT_HIST.ID AND ACT_ACTIVECASEINFAMILY.CLASSCODE = 'OBS' AND ACT_ACTIVECASEINFAMILY.METACODE = 'TBHISTPG_ACTIVECASEINFAMILY'
	LEFT JOIN A_ACT ACT_TREATMENT (NOLOCK) ON ACT_TREATMENT.ACT_PARENT_ID = ACT_HIST.ID AND ACT_TREATMENT.CLASSCODE = 'OBS' AND ACT_TREATMENT.METACODE = 'TBHISTPG_RECEIVEDTREATMENT_FK'
	LEFT JOIN A_ACT ACT_LTBITREATMENT (NOLOCK) ON ACT_LTBITREATMENT.ACT_PARENT_ID = ACT_HIST.ID AND ACT_LTBITREATMENT.CLASSCODE = 'OBS' AND ACT_LTBITREATMENT.METACODE = 'TBHISTPG_LTBITREATED'
	LEFT JOIN A_ACT ACT_DRINKS (NOLOCK) ON ACT_DRINKS.ACT_PARENT_ID = ACT_HIST.ID AND ACT_DRINKS.CLASSCODE = 'OBS' AND ACT_DRINKS.METACODE = 'TBHISTPG_DRINKS'
	LEFT JOIN A_ACT ACT_PREGNANT (NOLOCK) ON ACT_PREGNANT.ACT_PARENT_ID = ACT_HIST.ID AND ACT_PREGNANT.CLASSCODE = 'OBS' AND ACT_PREGNANT.METACODE = 'TBHISTPG_PREGNANT_FK'

WHERE  
	ACT_HIST.CLASSCODE = 'DOCSECT' AND 
	ACT_HIST.METACODE = 'TBHISTPG_ID' AND
	ACT_HIST.STATUSCODE <> 'NULLIFIED'

