
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_EPICONTACTS_CXR]
AS

SELECT  
	VIEW_SUB_EPICONT.PATIENT_FK AS CONTCXR_PATIENT_FK,
	VIEW_SUB_EPICONT.SERVICE_FK AS CONTCXR_CASE_FK,
	VIEW_SUB_EPICONT.ACT_ID AS CONTCXR_ID,
	
	VIEW_SUB_EPICONT.ACT_EFFECTIVETIME_BEG AS CXR_DATE,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(A_OBSERVATION.INTERPRETATIONCODE_ID) AS CONTCXR_CXRRESULT,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(T_VALUE.VALUECODE_ID) AS CONTCXR_CXRTYPE,
	[DBO].MDF_UCS_FULLNAME_UCS_BYUCSID(VIEW_SUB_EPICONT.ACT_VALUECODE_ID) AS CONTCXR_CXRCONDITION,
	DBO.MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID(VIEW_SUB_EPICONT.ACT_ID, 'VALUESTRING', 'CONTCXR_WHERE') AS CONTCXR_WHERE,
	DBO.MDF_ACT_GETDATEVALUE_ACTRELSRCACT_BYTRGACTIDMETACLASSMOODTYPEVALUETYPE(VIEW_SUB_EPICONT.ACT_ID, 'CONTCXR_NEXTDUEDATE', 'SEQL', 'EFFECTIVETIME_BEG') AS CONTCXR_NEXTDUEDATE,
	VIEW_SUB_EPICONT.ACT_TEXT AS CONTCXR_COMMENTS
FROM 
DBO.A_OBSERVATION (NOLOCK) 
	INNER JOIN [ATLASINTERNAL].[VIEW_SUB_NCM_EPICONTACT] VIEW_SUB_EPICONT  (NOLOCK) ON VIEW_SUB_EPICONT.ACT_ID = A_OBSERVATION.ID 
				AND VIEW_SUB_EPICONT.ACT_CLASSCODE = 'OBS' AND VIEW_SUB_EPICONT.ACT_METACODE = 'CONTCXR_ID' 
	LEFT JOIN T_VALUE (NOLOCK) ON T_VALUE.ACT_ID = VIEW_SUB_EPICONT.ACT_ID AND T_VALUE.METACODE = 'CONTCXR_CXRTYPE_FK'

