
CREATE VIEW [AtlasInternal].[VIEW_SUB_NCM_PATIENTDATA_HEALTHCOVERAGE]
AS
SELECT 
	ACT_FOLDER.ID as ActFolder_ID, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_MEDICAL', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_MEDICAL,  
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_MEDICALNUMBER', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_MEDICALNUMBER, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_EMERMEDICAL', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_EMERMEDICAL,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_EMERMEDICALNUMBER', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_EMERMEDICALNUMBER,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_TBMEDICAL', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_TBMEDICAL,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_TBMEDICALNUMBER', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_TBMEDICALNUMBER,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_MEDICARE', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_MEDICARE,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_MEDICARENUMBER', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_MEDICARENUMBER,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_MEDICAREEXCESS', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_MEDICAREEXCESS,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_PRIVATEINSURANCE', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_PRIVATEINSURANCE,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_PRIVATEINSURANCENUMBER', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_PRIVATEINSURANCENUMBER,
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_PRIVATEINSURANCECOMPANY', HLTHCOV.ID, 'VALUESTRING') AS HLTHCOV_PRIVATEINSURANCECOMPANY,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_PRIVATEINSURANCEEXCESS', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_PRIVATEINSURANCEEXCESS,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('HLTHCOV_UNINSURED', HLTHCOV.ID, 'VALUEBOOL') AS HLTHCOV_UNINSURED,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](HLTHCOV_INSURANCEELIGIBILITY_FK.VALUECODE_ID) AS HLTHCOV_INSURANCEELIGIBILITY 
FROM 
	DBO.A_ACT ACT_FOLDER (NOLOCK) 
	inner join (SELECT MIN(ID) AS ID, ACT_PARENT_ID FROM A_ACT (NOLOCK) WHERE METACODE = 'HLTHCOV_ID' GROUP BY ACT_PARENT_ID) HLTHCOV  on HLTHCOV.ACT_PARENT_ID = ACT_FOLDER.ID AND ACT_FOLDER.CLASSCODE='FOLDER' 
	LEFT JOIN A_ACT HLTHCOV_INSURANCEELIGIBILITY_FK (NOLOCK) ON HLTHCOV_INSURANCEELIGIBILITY_FK.ACT_PARENT_ID=HLTHCOV.ID AND HLTHCOV_INSURANCEELIGIBILITY_FK.METACODE='HLTHCOV_INSURANCEELIGIBILITY_FK' 

