
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_TBHISTORY_MEDICATION]
AS
SELECT 
	VPSNLINK.TBHIST_SERVICEID AS TBHISTMED_SERVICE_FK,
VPSNLINK.TBHIST_PATIENTID AS TBHISTMED_PATIENT_FK,
	ACT_MED.ID AS TBHISTMED_ID,
	ACT_MED.[TEXT] AS TBHISTMED_MEDICATION,
	[DBO].MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('TBHISTMED_PRESCRIBINGPHYSICIAN', ACT_MED.ID, 'VALUESTRING') AS TBHISTMED_PRESCRIBINGPHYSICIAN
FROM 
	A_ACT ACT_MED  (NOLOCK) 
	INNER JOIN A_ACT ACT_OBS  (NOLOCK) ON ACT_MED.ACT_PARENT_ID = ACT_OBS.ID AND ACT_OBS.CLASSCODE = 'OBS' AND ACT_OBS.METACODE = 'TBHISTPG_TAKINGMEDICATION' 
	INNER JOIN A_ACT ACT_TBHIST  (NOLOCK) ON ACT_TBHIST.ID = ACT_OBS.ACT_PARENT_ID AND ACT_TBHIST.CLASSCODE = 'DOCSECT' AND ACT_TBHIST.METACODE = 'TBHISTPG_ID'
	INNER JOIN VIEW_SUB_NCM_TBHISTORY_PSNLINK VPSNLINK  (NOLOCK) ON ACT_TBHIST.ACT_PARENT_ID = VPSNLINK.DOCBODY_ID
WHERE 
	ACT_MED.CLASSCODE = 'SBADM' AND 
	ACT_MED.METACODE = 'TBMEDHIST_ID'AND    
	ACT_MED.STATUSCODE <> 'NULLIFIED'

