
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_ENCOUNTER_DIAGNOSISHISTORY_LIST]
AS
SELECT 
	VPATIENTFOLDER.PATIENT_ID AS DIAGHIST_PATIENT_ID,
	ACT_MEDICALHISTORY.ID AS DIAGHIST_ID,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('DIAGHIST_DIAGNOSIS_FK',ACT_MEDICALHISTORY.ID,'VALUECODE_ID') AS DIAGHIST_DIAGNOSIS_TEXT,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('DIAGHIST_DIAGNOSISTYPE_FK',ACT_MEDICALHISTORY.ID,'VALUECODE_ID') AS DIAGHIST_DIAGNOSISTYPE_TEXT,
	ACT_MEDICALHISTORY.EFFECTIVETIME_BEG AS DIAGHIST_ONSETMONTHYEAR,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('DIAGHIST_CONTROLLED',ACT_MEDICALHISTORY.ID,'VALUEBOOL') AS DIAGHIST_CONTROLLED,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('DIAGHIST_CONTROLLED',ACT_MEDICALHISTORY.ID,'EFFECTIVETIME_BEG') AS DIAGHIST_WHENCONTROLLED
FROM 
	[ATLASINTERNAL].[VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER  (NOLOCK)
	INNER JOIN DBO.A_ACT ACT_DOCBODY (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=VPATIENTFOLDER.ACT_FOLDER_ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
	INNER JOIN A_ACT ACT_MEDICALHISTORY (NOLOCK) ON ACT_DOCBODY.ID=ACT_MEDICALHISTORY.ACT_PARENT_ID AND ACT_MEDICALHISTORY.METACODE='DIAGHIST_ID' AND ACT_MEDICALHISTORY.STATUSCODE='ACTIVE'
