
CREATE VIEW [AtlasInternal].[VIEW_NCM_VISIT_SUPPLEMENTAL]
AS
SELECT
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_VISITSUPPLEMENTAL.ID AS VISITSUP_ID,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_PARTICIPANT.ID,'VALUECODE_ID') AS VISITSUP_PARTICIPANT,
	ACT_PARTICIPANT.TEXT AS VISITSUP_SPECIFYPARTICIPANT,
	ENTITYNAME_SPECIFICLOCATION.TRIVIALNAME AS VISITSUP_SPECIFICLOCATION,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_TRANSLATORSERVICE.ID,'VALUECODE_ID') AS VISITSUP_TRANSLATORSERVICEOFFERED,
	ACT_TRANSLATORSERVICETYPE.VALUEBOOL AS VISITSUP_TRANSLATORSERVICEUSED,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_TRANSLATORSERVICETYPE.ID,'VALUECODE_ID') AS VISITSUP_TRANSLATORSERVICETYPE,
	ACT_FOLLOWUP.VALUEBOOL AS VISITSUP_FOLLOWUPREQUIRED,
	ACT_FOLLOWUP.EFFECTIVETIME_BEG AS VISITSUP_FOLLOWUPDATE,
	DBO.[MDF_UCS_FULLNAME_ACTUCS_BYACTID](ACT_FOLLOWUP.ID,'VALUECODE_ID')AS VISITSUP_FOLLOWUPREASON
FROM 
	A_ACT ACT_VISITSUPPLEMENTAL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL  (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_VISITSUPPLEMENTAL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
	LEFT JOIN A_ACT ACT_PARTICIPANT  (NOLOCK) ON ACT_PARTICIPANT.ACT_PARENT_ID=ACT_VISITSUPPLEMENTAL.ID AND ACT_PARTICIPANT.METACODE='VISITSUP_PARTICIPANT_FK'
	LEFT JOIN A_ACT ACT_SPECIFICLOCATION  (NOLOCK) ON ACT_SPECIFICLOCATION.ACT_PARENT_ID=ACT_VISITSUPPLEMENTAL.ID AND ACT_SPECIFICLOCATION.METACODE='VISITSUP_SPECIFICLOCATION_FK'
	LEFT JOIN T_ENTITYNAME ENTITYNAME_SPECIFICLOCATION (NOLOCK) ON ENTITYNAME_SPECIFICLOCATION.ENTITY_ID=ACT_SPECIFICLOCATION.VALUESTRING_TXT
	LEFT JOIN A_ACT ACT_TRANSLATORSERVICE  (NOLOCK) ON ACT_TRANSLATORSERVICE.ACT_PARENT_ID=ACT_VISITSUPPLEMENTAL.ID AND ACT_TRANSLATORSERVICE.METACODE='VISITSUP_TRANSLATORSERVICEOFFERED'
	LEFT JOIN A_ACT ACT_TRANSLATORSERVICETYPE  (NOLOCK) ON ACT_TRANSLATORSERVICETYPE.ACT_PARENT_ID=ACT_VISITSUPPLEMENTAL.ID AND ACT_TRANSLATORSERVICETYPE.METACODE='VISITSUP_TRANSLATORSERVICETYPE_FK'
	LEFT JOIN A_ACT ACT_FOLLOWUP  (NOLOCK) ON ACT_FOLLOWUP.ACT_PARENT_ID=ACT_VISITSUPPLEMENTAL.ID AND ACT_FOLLOWUP.METACODE='VISITSUP_FOLLOWUPREASON_FK'
WHERE 
	ACT_VISITSUPPLEMENTAL.METACODE='VISITSUP_ID' AND ACT_VISITSUPPLEMENTAL.STATUSCODE='ACTIVE'

