
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_INJURYVIOLENCE]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_INJURYVIOLENCE.ID AS INJ_ID,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_INJURYVIOLENCE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_INJURYVIOLENCE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_DOMESTICVIOLENCE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_DOMESTICVIOLENCE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_DVSAFEUNSAFE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_DVSAFEUNSAFE,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_DVSAFEUNSAFE', ACT_INJURYVIOLENCE.ID, 'EFFECTIVETIME_BEG') AS   INJ_DVONSET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_DVHASPLAN', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL')AS INJ_DVHASPLAN,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_CHILDABUSE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_CHILDABUSE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_ELDERABUSE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_ELDERABUSE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_ELDERABUSE',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_ELDERABUSETYPE,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_ELDERABUSE', ACT_INJURYVIOLENCE.ID, 'EFFECTIVETIME_BEG') AS INJ_EAONSET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_EAHASPLAN', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_EAHASPLAN,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_EATIMEFRAME_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_EATIMEFRAME,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_CATIMEFRAME_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_CATIMEFRAME,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_DVTIMEFRAME_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_DVTIMEFRAME,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_EALASTREPORT', ACT_INJURYVIOLENCE.ID, 'VALUETS') AS INJ_EALASTREPORT,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_DVLASTREPORT', ACT_INJURYVIOLENCE.ID, 'VALUETS') AS INJ_DVLASTREPORT,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_CALASTREPORT', ACT_INJURYVIOLENCE.ID, 'VALUETS') AS INJ_CALASTREPORT,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_EAPERPETRATORTYPE_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_EAPERPETRATORTYPE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_DVPERPETRATORTYPE_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_DVPERPETRATORTYPE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_CAPERPETRATORTYPE_FK',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_CAPERPETRATORTYPE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('INJ_CHILDABUSE',ACT_INJURYVIOLENCE.ID,'VALUECODE_ID') AS INJ_CHILDABUSETYPE,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_CHILDABUSE', ACT_INJURYVIOLENCE.ID, 'EFFECTIVETIME_BEG') AS INJ_CAONSET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_CAHASPLAN', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_CAHASPLAN,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_USESCARSEAT', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_USESCARSEAT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_USESSEATBELTS', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_USESSEATBELTS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_USESHELMET', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_USESHELMET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_GANGINVOLVEMENT', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_GANGINVOLVEMENT,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_SLEEPSONBACK', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_SLEEPSONBACK,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_CRIBSAFE', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_CRIBSAFE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('INJ_USESWALKER', ACT_INJURYVIOLENCE.ID, 'VALUEBOOL') AS INJ_USESWALKER
FROM 
	A_ACT ACT_INJURYVIOLENCE (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_INJURYVIOLENCE.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_INJURYVIOLENCE.METACODE='INJ_ID' AND ACT_INJURYVIOLENCE.STATUSCODE='ACTIVE'
