
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_ENCOUNTER_MEDICALHISTORY_LIST]
AS
SELECT 
	VPATIENTFOLDER.PATIENT_ID AS MEDHIST_PATIENT_ID,
	ACT_MEDICALHISTORY.ID AS MEDHIST_ID,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_MEDICALHISTORY.CODE_ID) AS MEDHIST_MEDICATION_TEXT,
	ACT_MEDICALHISTORY.EFFECTIVETIME_BEG AS MEDHIST_DATEBEGUN,
	ACT_MEDICALHISTORY.EFFECTIVETIME_END AS MEDHIST_DATEENDED,
	ACT_MEDICALHISTORY.TEXT AS MEDHIST_COMMENTS
FROM 
	[VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER  (NOLOCK)
	INNER JOIN DBO.A_ACT ACT_DOCBODY (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=VPATIENTFOLDER.ACT_FOLDER_ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
	INNER JOIN A_ACT ACT_MEDICALHISTORY (NOLOCK) ON ACT_MEDICALHISTORY.ACT_PARENT_ID=ACT_DOCBODY.ID AND ACT_MEDICALHISTORY.METACODE='MEDHIST_ID' AND 	ACT_MEDICALHISTORY.STATUSCODE='ACTIVE' 
