
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_BASICNEED]
AS
SELECT 
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_BASICNEED.ID AS BASNEED_ID,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_BASICNEEDS',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_BASICNEEDS,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_FOOD_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_FOOD_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_FOOD_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_FOOD_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_FOODCHOICE_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_FOODCHOICE_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_FOODCHOICE_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_FOODCHOICE_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_COOKING_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_COOKING_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_COOKING_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_COOKING_TEXT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_REFRIG',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_REFRIG,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_STOVE',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_STOVE,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_FOODSTAMPS',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_FOODSTAMPS,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_WIC',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_WIC,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_UTILITIES_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_UTILITIES_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_UTILITIES_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_UTILITIES_TEXT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_WATER',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_WATER,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HEAT',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_HEAT,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_AIRCOND',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_AIRCOND,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_PHONE',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_PHONE,
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_GAS',ACT_BASICNEED.ID,'VALUEBOOL') AS BASNEED_GAS,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HOUSING_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_HOUSING_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_HOUSING_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_HOUSING_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HOUSINGSTATUS_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_HOUSINGSTATUS_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_HOUSINGSTATUS_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_HOUSINGSTATUS_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HOUSINGTYPE_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_HOUSINGTYPE_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_HOUSINGTYPE_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_HOUSINGTYPE_TEXT,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HOMEMAINT_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_HOMEMAINT_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_HOMEMAINT_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_HOMEMAINT_TEXT,	
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_HOMESANITATION_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_HOMESANITATION_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_HOMESANITATION_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_HOMESANITATION_TEXT,	
	[DBO].[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_NUMINHOUSEHOLD',ACT_BASICNEED.ID,'VALUEINTEGER') AS BASNEED_NUMINHOUSEHOLD,
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_TRANSPORTATION_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_TRANSPORTATION_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_TRANSPORTATION_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_TRANSPORTATION_TEXT,	
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_TRANSPORTTYPE_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_TRANSPORTTYPE_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_TRANSPORTTYPE_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_TRANSPORTTYPE_TEXT,	
	DBO.[MDF_ACT_GETINTEGERVALUE_ACT_BYPARACTIDMETAVALUETYPE]('BASNEED_CLOTHING_FK',ACT_BASICNEED.ID,'VALUECODE_ID') AS BASNEED_CLOTHING_FK,
	DBO.[MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID]('BASNEED_CLOTHING_FK',ACT_BASICNEED.ID,'VALUECODE_ID')AS BASNEED_CLOTHING_TEXT,	
	ACT_BASICNEED.TEXT AS BASNEED_OTHER
FROM 
	A_ACT ACT_BASICNEED (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_BASICNEED.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC'
WHERE 
	ACT_BASICNEED.METACODE='BASNEED_ID'
