
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_CDCASE_CASEINFORMATION]
AS
SELECT  
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDCASE_ILLNES_FK.VALUECODE_ID) AS  CDCASE_ILLNESS,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDCASE_ILLNESGROUP_FK.VALUECODE_ID) AS CDCASE_ILLNESSGROUP,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDCASE_ILLNESSITE_FK.VALUECODE_ID) AS CDCASE_ILLNESSSITE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDCASE_ILLNESSTAGE_FK.VALUECODE_ID) AS CDCASE_ILLNESSSTAGE,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_CDCASE_ILLNESCLASS_FK.VALUECODE_ID) AS CDCASE_ILLNESSCLASS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASE_SOS',DOCSECT_CDCASE.ID,'VALUEBOOL') AS CDCASE_SOS,
	DOCSECT_CDCASESYMP.EFFECTIVETIME_BEG AS CDCASE_DATEOFONSET,
	ACT_CDCASE_ILLNESCLASS_FK.EFFECTIVETIME_BEG AS CDCASE_DATEOFDIAGNOSIS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_SYMPTOMSDETAIL',DOCSECT_CDCASESYMP.ID,'VALUEBOOL') AS CDCASESYMP_SYMPTOMS,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_SYMPTOMSAT1STINTERVIEW',DOCSECT_CDCASESYMP.ID,'VALUEBOOL') AS CDCASESYMP_SYMPTOMSAT1STINTERVIEW,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_SYMPTOMSAT1STINTERVIEW',DOCSECT_CDCASESYMP.ID,'EFFECTIVETIME_BEG') AS CDCASESYMP_DATEOF1STINTERVIEW,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_CURRENTSYMPTOMS',DOCSECT_CDCASESYMP.ID,'VALUEBOOL') AS CDCASESYMP_CURRENTSYMPTOMS,
	DBO.MDF_ACT_GETDATEVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_CURRENTSYMPTOMS',DOCSECT_CDCASESYMP.ID,'EFFECTIVETIME_BEG') AS CDCASESYMP_CURRENTSYMPTOMSDATE,	
	DBO.MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASESYMP_SYMPTOMSDETAIL',DOCSECT_CDCASESYMP.ID,'TEXT') AS CDCASESYMP_SYMPTOMSDETAIL,
	DOCSECT_CDCASESYMP.EFFECTIVETIME_DUR AS CDCASESYMP_HOURSSPENTONCASE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_HANDLESFOOD',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_HANDLESFOOD,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_CARESFORELDERLY',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_CARESFORELDERLY,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_CARESFORCHILDREN',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_CARESFORCHILDREN,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_HEALTHCAREWORKER',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_HEALTHCAREWORKER,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_ATTENDSDAYCARE',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_ATTENDSDAYCARE,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_WEARSGLOVES',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_WEARSGLOVES,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_PRACTICESHANDWASHING',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_PRACTICESHANDWASHING,	
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_ASSISTSWITHTOILET',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS 
	CDCASERISK_ASSISTSWITHTOILET,
	DBO.MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE('CDCASERISK_WEARSDIAPERS',DOCSECT_CDCASERISK.ID,'VALUEBOOL') AS CDCASERISK_WEARSDIAPERS,
	ACT_CASE.ID AS [SVC_ID],
	DBO.MDF_ROLE_GETVALUE_ACTPARTICIPATIONROLE_BYACTID(ACT_CASE.ACT_PARENT_ID,'PLAYER_ID') AS [PAT_ID]

FROM  A_ACT AS ACT_CASE (NOLOCK) 
	INNER JOIN A_ACT DOCBODY (NOLOCK) ON DOCBODY.ACT_PARENT_ID = ACT_CASE.ID AND DOCBODY.CLASSCODE = 'DOCBODY'
	INNER JOIN V_UNIFIEDCODESET UCSCODE (NOLOCK) ON UCSCODE.ID = DOCBODY.CODE_ID AND UCSCODE.CONCEPTCODE = 'CDI'
	LEFT JOIN A_ACT DOCSECT_CDCASE (NOLOCK) ON DOCSECT_CDCASE.ACT_PARENT_ID = DOCBODY.ID AND DOCSECT_CDCASE.CLASSCODE = 'DOCSECT' AND DOCSECT_CDCASE.METACODE ='CDCASE_ID'
	LEFT JOIN A_ACT DOCSECT_CDCASESYMP (NOLOCK) ON DOCSECT_CDCASESYMP.ACT_PARENT_ID = DOCBODY.ID  AND DOCSECT_CDCASESYMP.METACODE = 'CDCASESYMP_ID'
	LEFT JOIN A_ACT DOCSECT_CDCASERISK (NOLOCK) ON DOCSECT_CDCASERISK.ACT_PARENT_ID = DOCBODY.ID  AND DOCSECT_CDCASERISK.METACODE = 'CDCASERISK_ID'
	LEFT JOIN A_ACT ACT_CDCASE_ILLNES_FK (NOLOCK) ON ACT_CDCASE_ILLNES_FK.ACT_PARENT_ID = DOCSECT_CDCASE.ID  AND  ACT_CDCASE_ILLNES_FK.METACODE ='CDCASE_ILLNES_FK'
	LEFT JOIN A_ACT ACT_CDCASE_ILLNESGROUP_FK (NOLOCK) ON ACT_CDCASE_ILLNESGROUP_FK.ACT_PARENT_ID = DOCSECT_CDCASE.ID AND ACT_CDCASE_ILLNESGROUP_FK.METACODE ='CDCASE_ILLNESGROUP_FK'
	LEFT JOIN A_ACT ACT_CDCASE_ILLNESSITE_FK (NOLOCK) ON ACT_CDCASE_ILLNESSITE_FK.ACT_PARENT_ID = DOCSECT_CDCASE.ID AND  ACT_CDCASE_ILLNESSITE_FK.METACODE ='CDCASE_ILLNESSITE_FK'
	LEFT JOIN A_ACT ACT_CDCASE_ILLNESSTAGE_FK (NOLOCK) ON ACT_CDCASE_ILLNESSTAGE_FK.ACT_PARENT_ID = DOCSECT_CDCASE.ID  AND  ACT_CDCASE_ILLNESSTAGE_FK.METACODE ='CDCASE_ILLNESSTAGE_FK'
	LEFT JOIN A_ACT ACT_CDCASE_ILLNESCLASS_FK (NOLOCK) ON ACT_CDCASE_ILLNESCLASS_FK.ACT_PARENT_ID = DOCSECT_CDCASE.ID AND  ACT_CDCASE_ILLNESCLASS_FK.METACODE ='CDCASE_ILLNESCLASS_FK' 
WHERE 
	ACT_CASE.CLASSCODE = 'CASE'
