
CREATE VIEW [AtlasInternal].[VIEW_NCM_ENCOUNTER_PERIODICREVIEW_LIST]
AS
SELECT 
	VPATIENTFOLDER.PATIENT_ID AS PERREV_PATIENT_ID,
	ACT_PERIODICREVIEW.ID AS PERREV_ID,
	ACT_PERIODICREVIEW.EFFECTIVETIME_BEG AS PERREV_DATEREVIEWED,
	PERIODICREVIEW_CASEMANAGER.NAMECOMBINED AS PERREV_CASEMANAGER_TEXT,
	PERIODIC_SUPERVISOR.NAMECOMBINED AS PERREV_SUPERVISOR_TEXT,
	VALUE_PLANUPDATED.VALUEBOOL AS PERREV_PLANUPDATED,
	ACT_PERIODICREVIEW.TEXT AS PERREV_COMMENTS
FROM 
	[VIEW_CMN_PATIENTFOLDER] VPATIENTFOLDER  (NOLOCK)
	INNER JOIN DBO.A_ACT ACT_DOCBODY (NOLOCK) ON ACT_DOCBODY.ACT_PARENT_ID=VPATIENTFOLDER.ACT_FOLDER_ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
	INNER JOIN A_ACT ACT_PERIODICREVIEW (NOLOCK) ON ACT_DOCBODY.ID=ACT_PERIODICREVIEW.ACT_PARENT_ID AND ACT_PERIODICREVIEW.METACODE='PERREV_ID' AND ACT_PERIODICREVIEW.STATUSCODE='ACTIVE'
	LEFT JOIN VIEW_CMN_PARTICIPATION_ROLE_ENTITY PERIODICREVIEW_CASEMANAGER ON ACT_PERIODICREVIEW.ID=PERIODICREVIEW_CASEMANAGER.ACT_ID AND PERIODICREVIEW_CASEMANAGER.TYPECODE='PPRF' AND PERIODICREVIEW_CASEMANAGER.USECODE = 'L'
	LEFT JOIN VIEW_CMN_PARTICIPATION_ROLE_ENTITY PERIODIC_SUPERVISOR ON ACT_PERIODICREVIEW.ID=PERIODIC_SUPERVISOR.ACT_ID AND PERIODIC_SUPERVISOR.TYPECODE='SPRF' AND PERIODIC_SUPERVISOR.USECODE = 'L'
	LEFT JOIN A_ACT ACT_PLANUPDATED (NOLOCK) ON ACT_PERIODICREVIEW.ID=ACT_PLANUPDATED.ACT_PARENT_ID AND ACT_PLANUPDATED.METACODE='PERREV_PLANUPDATED'
	LEFT JOIN T_VALUE VALUE_PLANUPDATED (NOLOCK) ON ACT_PLANUPDATED.ID=VALUE_PLANUPDATED.ACT_ID

