CREATE VIEW [ATLASINTERNAL].[VIEW_SUB_NCM_PATIENTDATA_NOTE]
AS
SELECT 
ACT_DOCBODY.ID AS ACTDOCBODY_ID, 
CAST(PATNOTE.[TEXT] AS VARCHAR(MAX)) AS [PAT_NOTES]
FROM 
DBO.A_ACT ACT_DOCBODY (NOLOCK) 
INNER JOIN (SELECT MIN(ID) AS ID, ACT_PARENT_ID FROM DBO.A_ACT (NOLOCK) WHERE METACODE='PATNOTE_ID' GROUP BY ACT_PARENT_ID) PATNOTEMIN ON PATNOTEMIN.ACT_PARENT_ID=ACT_DOCBODY.ID AND ACT_DOCBODY.CLASSCODE='DOCBODY'
INNER JOIN DBO.A_ACT PATNOTE (NOLOCK) ON PATNOTE.ID=PATNOTEMIN.ID AND PATNOTE.METACODE='PATNOTE_ID' 
