CREATE VIEW [AtlasInternal].[VIEW_CMN_PATIENTFOLDER]  
AS  
SELECT   
 E_ENTITY.ID AS PATIENT_ID,  
 A_ACT.ID AS ACT_FOLDER_ID,  
 R_ROLE.ID AS ROLE_ID,
 E_ENTITY.statusCode AS PATIENT_STATUSCODE
FROM   
 E_ENTITY (NOLOCK)   
 INNER JOIN R_ROLE (NOLOCK) ON E_ENTITY.ID = R_ROLE.PLAYER_ID AND R_ROLE.CLASSCODE='PAT' AND R_ROLE.statusCode <> 'nullified' AND R_ROLE.statusCode <> 'terminated'  
 INNER JOIN P_PARTICIPATION (NOLOCK) ON P_PARTICIPATION.ROLE_ID = R_ROLE.ID AND P_PARTICIPATION.TYPECODE='SBJ'  
 INNER JOIN A_ACT (NOLOCK) ON A_ACT.ID = P_PARTICIPATION.ACT_ID AND A_ACT.CLASSCODE='FOLDER'   
WHERE   
 E_ENTITY.CLASSCODE='PSN' 
