
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_REFERRAL_PROGRAM]            
AS            
SELECT             
	DV_SERVICE.DVSVC_ROWID AS [SVC_ID],            
	DV_SERVICE.DVSVC_PATIENT_FK AS [PAT_ID],            
	DBO.MDF_UCS_FULLNAME_ACTUCS_BYACTID(PROG.ID,'CODE_ID') AS PROGRAM,            
	PROG.EFFECTIVETIME_BEG AS [ENROLLED DATE],            
	CASE WHEN PROG.VALUEBOOL =1 THEN 'TRUE' ELSE 'FALSE' END AS [CURRENT]            
FROM 
	A_ACT PROG (NOLOCK)  
	INNER JOIN A_ACT (NOLOCK) SVC ON PROG.ACT_PARENT_ID=SVC.ACT_PARENT_ID 
	INNER JOIN DV_SERVICE (NOLOCK) ON DV_SERVICE.DVSVC_ROWID=SVC.ID 
WHERE 
	PROG.METACODE='PROG_ID' AND PROG.STATUSCODE NOT IN ('NULLIFIED','TERMINATED') 
