
CREATE VIEW [ATLASINTERNAL].[VIEW_NCM_VISIT_GOAL_LIST]
AS
SELECT  
	ACT_VISITDETAIL.ID AS VISITDTL_ID,
	ACT_GOALALL.ID AS GOALALL_ID,
	DBO.MDF_UCS_FULLNAME_UCS_BYUCSID(ACT_GOALALL.VALUECODE_ID) AS GOALALL_GOAL,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('GOALALL_OUTCOMECATEGORY_FK',ACT_GOALALL.ID,'VALUECODE_ID') AS GOALALL_OUTCOMECATEGORY,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('GOALALL_ASSOCSERVICE_FK',ACT_GOALALL.ID,'VALUECODE_ID') AS GOALALL_ASSOCIATEDSERVICE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('GOALALL_ASSOCCONCERN_FK',ACT_GOALALL.ID,'VALUECODE_ID') AS GOALALL_ASSOCIATEDCONCERN,
	ACT_GOALALL.EFFECTIVETIME_BEG AS GOALALL_EVALUATIONDATE,
	DBO.MDF_UCS_FULLNAME_ACTCHILDUCS_BYPARENTACTID('GOALALL_OUTCOME_FK',ACT_GOALALL.ID,'VALUECODE_ID') AS GOALALL_OUTCOME
FROM 
	A_ACT ACT_GOALALL (NOLOCK) 
	INNER JOIN A_ACT ACT_VISITDETAIL (NOLOCK) ON ACT_VISITDETAIL.ID=ACT_GOALALL.ACT_PARENT_ID AND ACT_VISITDETAIL.CLASSCODE='ENC' 
WHERE 
	ACT_GOALALL.METACODE='GOALALL_ID'
