CREATE TABLE [LAC].[vph_dashboard] (
    [processStatus]      VARCHAR (255) NULL,
    [enteredBy]          VARCHAR (MAX) NOT NULL,
    [species]            VARCHAR (MAX) NULL,
    [shelterName]        VARCHAR (MAX) NULL,
    [bitingAnimalStatus] VARCHAR (MAX) NOT NULL,
    [HasSpecimen]        VARCHAR (MAX) NOT NULL,
    [caseType]           VARCHAR (MAX) NOT NULL,
    [inspector]          VARCHAR (255) NOT NULL,
    [isHotHead]          VARCHAR (MAX) NOT NULL,
    [animalCity]         VARCHAR (MAX) NOT NULL,
    [exposureType]       VARCHAR (MAX) NOT NULL,
    [expQTReleaseDate]   VARCHAR (30)  NOT NULL,
    [impountNumber]      VARCHAR (MAX) NOT NULL,
    [labRow]             BIGINT        NULL,
    [labResult]          VARCHAR (MAX) NOT NULL,
    [reportingPartyType] VARCHAR (MAX) NOT NULL,
    [reportingFacility]  VARCHAR (MAX) NOT NULL,
    [specimenSubmitDate] VARCHAR (MAX) NOT NULL,
    [wasVictimContacted] VARCHAR (MAX) NOT NULL,
    [victimContactDate]  VARCHAR (MAX) NOT NULL,
    [supplementalNotes]  VARCHAR (MAX) NOT NULL,
    [date_created]       DATE          NULL,
    [userid]             VARCHAR (MAX) NULL,
    [ai_iden_animalid]   INT           NOT NULL,
    [AIID]               INT           NOT NULL,
    [biteDate]           VARCHAR (MAX) NULL,
    [incCity]            VARCHAR (MAX) NOT NULL,
    [bvCity]             VARCHAR (MAX) NOT NULL
);

