CREATE TABLE dbo.COVID_INCIDENT
(
	PR_ROWID int NOT NULL,
	PR_PHTYPE varchar(255) NULL,
	PR_LEGACY_ROWID varchar(50) NULL,
	PR_PERSONDR int NULL,
	PR_USERDR int NULL,
	PR_OUTBREAKDRSTEXT varchar(max) NULL,
	PR_INCIDENTID int NOT NULL,
	PR_CMRRECORD varchar(50) NOT NULL,
	PR_NAMESPACE varchar(4) NOT NULL,
	PR_CREATEDATE datetime NOT NULL,
	PR_ONSETDATE datetime NULL,
	PR_CLOSEDDATE datetime NULL,
	PR_EPISODEDATE datetime NULL,
	PR_STANDARDAGE real NULL,
	PR_DATESUBMITTED datetime NULL,
	PR_DATEREPORTEDBY datetime NULL,
	PR_REPORTSOURCEDR int NULL,
	PR_MRN varchar(50) NULL,
	PR_CLUSTERID varchar(max) NULL,
	PR_ISINDEXCASE bit NULL,
	PR_DISEASE varchar(255) NULL,
	PR_DISEASESHORTNAME varchar(100) NULL,
	PR_OTHERDISEASE varchar(200) NULL,
	PR_DISTRICT varchar(255) NULL,
	PR_PROCESSSTATUS varchar(255) NULL,
	PR_SPA varchar(255) NULL,
	PR_RESOLUTIONSTATUS varchar(255) NULL,
	PR_NURSEINVESTIGATOR varchar(202) NOT NULL,
	PR_REPORTEDBYWEB bit NULL,
	PR_REPORTEDBYLAB bit NULL,
	PR_REPORTEDBYEHR bit NULL,
	PR_TRANSMISSIONSTATUS varchar(255) NULL,
	PR_DISEASECODE_DR int NULL,
	PR_DISTRICTCODE_DR int NULL,
	PR_PROCESSSTATUSCODE_DR int NULL,
	PR_SPACODE_DR int NULL,
	PR_RESOLUTIONSTATUSCODE_DR int NULL,
	PR_NURSEINVESTIGATORDR int NULL,
	PR_SPECIMENTYPE nvarchar(max) NULL,
	PR_SPECIMENDATECOLLECTED nvarchar(max) NULL,
	PR_SPECIMENDATERECEIVED nvarchar(max) NULL,
	PR_SPECIMENRESULT nvarchar(max) NULL,
	PR_SPECIMENNOTE nvarchar(max) NULL,
	PR_DIAGSPECIMENTYPES varchar(max) NULL,
	PR_EXPEXPOSURETYPES varchar(max) NULL,
	PR_HEPATITISDRS varchar(max) NULL,
	PR_DISEASEGROUPS varchar(max) NULL,
	PR_RESULTVALUE nvarchar(max) NULL,
	PR_LIPTESTORDERED varchar(max) NULL,
	PR_ISPREGNANT bit NULL,
	PR_EXPECTEDDELIVERYDATE datetime NULL,
	PR_LIPRESULTNOTES nvarchar(max) NULL,
	PR_LIPRESULTNAME varchar(max) NULL,
	PR_HEALTHCAREPROVIDERLOCATIONDR int NULL,
	PR_NOTES varchar(max) NULL,
	PR_DATEOFDIAGNOSIS datetime NULL,
	PR_DATEOFDEATH datetime NULL,
	PR_DATEOFLABREPORT datetime NULL,
	PR_DATEINVESTIGATORRECEIVED datetime NULL,
	PR_ISSYMPTOMATIC bit NULL,
	PR_ISPATIENTDIEDOFTHEILLNESS bit NULL,
	PR_ISPATIENTHOSPITALIZED bit NULL,
	PR_LABSPECIMENCOLLECTEDDATE datetime NULL,
	PR_LABSPECIMENRESULTDATE datetime NULL,
	PR_DATEADMITTED datetime NULL,
	PR_DATEDISCHARGED datetime NULL,
	PR_LABORATORY varchar(250) NULL,
	PR_HOSPITALDR int NULL,
	PR_HOSPITAL varchar(250) NULL,
	PR_OUTPATIENT bit NULL,
	PR_INPATIENT bit NULL,
	PR_DATESENT datetime NULL,
	PR_LASTCDCUPDATE datetime NULL,
	PR_NAMEOFSUBMITTER varchar(max) NULL,
	PR_OUTBREAKNUMBERS varchar(max) NULL,
	PR_OUTBREAKTYPES varchar(max) NULL,
	PR_ANIMALREPORTID int NULL,
	PR_FBIDR int NULL,
	PR_FBINumber varchar(50) NULL,
	PR_CENSUSTRACT varchar(100) NULL,
	Additional_Provider varchar(max) NULL,
	Additional_Laboratory varchar(max) NULL,
	Age real NULL,
	American_Indian_or_Alaska_Native nvarchar(max) NULL,
	Asian___Specify nvarchar(max) NULL,
	Black_or_African_American___Spec nvarchar(max) NULL,
	CMR_ID varchar(50) NULL,
	Country_of_Birth varchar(255) NULL,
	Created_By varchar(14) NULL,
	Date_Last_Edited datetime NULL,
	Final_Disposition varchar(255) NULL,
	Diagnostic_Specimen_Types nvarchar(max) NULL,
	Health_District_Number varchar(255) NULL,
	ImportedBy varchar(202) NULL,
	Imported_Status varchar(30) NULL,
	Lab_Report varchar(5) NULL,
	Lab_Report_Notes varchar(max) NULL,
	Lab_Report_Test_Name varchar(255) NULL,
	Marital_Status varchar(255) NULL,
	Medical_Record_Number varchar(50) NULL,
	Most_Recent_Lab_Result varchar(1100) NULL,
	Most_Recent_Lab_Result_Value varchar(max) NULL,
	Native_Hawaiian_or_Other_Pacific nvarchar(max) NULL,
	Occupation_Setting_Type varchar(255) NULL,
	Other___Specify nvarchar(max) NULL,
	Outbreak_IDs varchar(4000) NULL,
	Parent_or_Guardian_Name varchar(50) NULL,
	Priority varchar(255) NULL,
	Provider_Name varchar(255) NULL,
	Report_Source varchar(250) NULL,
	Secondary_District varchar(255) NULL,
	Suspected_Exposure_Types nvarchar(max) NULL,
	Type_of_Contact varchar(255) NULL,
	Unknown___Specify nvarchar(max) NULL,
	White___Specify nvarchar(max) NULL
)
go
create clustered index [COVID_INCIDENT.PR_ROWID.Fake.PrimaryKey]
on dbo.COVID_INCIDENT(PR_ROWID);
go
create index [COVID_INCIDENT.PR_PERSONDR.Index]
on dbo.COVID_INCIDENT(PR_PERSONDR);
