-- [dc].FN_122417_CMR_GetMinSpecimenCollectedDate - Will be used to calculate the episode date
CREATE FUNCTION [dc].FN_122417_CMR_GetEpisodeDate(@pr_rowid int, @SpecimenCollectedDate datetime)
RETURNS DATETIME 
AS

BEGIN
	DECLARE @EpisodeDate datetime
	
	SELECT @EpisodeDate=MIN(PR_EpisodeDate) from
	 (
		SELECT DXDATE AS PR_EPISODEDATE FROM A_PUBLICHEALTHCASE WHERE ID=@PR_ROWID -- PR_DATEOFDIAGNOSIS
		UNION 
		SELECT ACTDTH.EFFECTIVETIME_BEG AS PR_EPISODEDATE FROM A_ACT ACTDTH (NOLOCK) INNER JOIN A_ACT CASEACT (NOLOCK) ON CASEACT.ID=ACTDTH.ACT_PARENT_ID WHERE CASEACT.ID=@PR_ROWID AND ACTDTH.METACODE='APR_DATEOFDEATH' AND ACTDTH.CLASSCODE='OBX' AND ACTDTH.MOODCODE='EVN' -- PR_DATEOFDEATH
		UNION
		SELECT CASEACT.AVAILABILITYTIME AS PR_EPISODEDATE FROM A_ACT CASEACT (NOLOCK) WHERE CASEACT.ID=@PR_ROWID --PR_DATEINVESTIGATORRECEIVED
		UNION
		SELECT CASEACT.ACTIVITYTIME_BEG AS PR_EPISODEDATE FROM A_ACT CASEACT (NOLOCK) WHERE CASEACT.ID=@PR_ROWID -- PR_DATEREPORTEDBY
		UNION
		SELECT @SpecimenCollectedDate AS PR_EpisodeDate
	) RST
	
	return @EpisodeDate
END
 
