CREATE TABLE [covid].[SARS2_INCIDENT_SNAPSHOT_BAD] (
    [PR_ROWID]                         INT            NOT NULL,
    [PR_PHTYPE]                        VARCHAR (255)  NULL,
    [PR_LEGACY_ROWID]                  VARCHAR (50)   NULL,
    [PR_PERSONDR]                      INT            NULL,
    [PR_USERDR]                        INT            NULL,
    [PR_OUTBREAKDRSTEXT]               VARCHAR (MAX)  NULL,
    [PR_INCIDENTID]                    INT            NOT NULL,
    [PR_CMRRECORD]                     VARCHAR (50)   NOT NULL,
    [PR_NAMESPACE]                     VARCHAR (4)    NOT NULL,
    [PR_CREATEDATE]                    DATETIME       NOT NULL,
    [PR_ONSETDATE]                     DATETIME       NULL,
    [PR_CLOSEDDATE]                    DATETIME       NULL,
    [PR_EPISODEDATE]                   DATETIME       NULL,
    [PR_STANDARDAGE]                   REAL           NULL,
    [PR_DATESUBMITTED]                 DATETIME       NULL,
    [PR_DATEREPORTEDBY]                DATETIME       NULL,
    [PR_REPORTSOURCEDR]                INT            NULL,
    [PR_MRN]                           VARCHAR (50)   NULL,
    [PR_CLUSTERID]                     VARCHAR (8000) NULL,
    [PR_ISINDEXCASE]                   BIT            NULL,
    [PR_DISEASE]                       VARCHAR (255)  NULL,
    [PR_DISEASESHORTNAME]              VARCHAR (100)  NULL,
    [PR_OTHERDISEASE]                  VARCHAR (200)  NULL,
    [PR_DISTRICT]                      VARCHAR (255)  NULL,
    [PR_PROCESSSTATUS]                 VARCHAR (255)  NULL,
    [PR_SPA]                           VARCHAR (255)  NULL,
    [PR_RESOLUTIONSTATUS]              VARCHAR (255)  NULL,
    [PR_NURSEINVESTIGATOR]             VARCHAR (202)  NOT NULL,
    [PR_REPORTEDBYWEB]                 BIT            NULL,
    [PR_REPORTEDBYLAB]                 BIT            NULL,
    [PR_REPORTEDBYEHR]                 BIT            NULL,
    [PR_TRANSMISSIONSTATUS]            VARCHAR (255)  NULL,
    [PR_DISEASECODE_DR]                INT            NULL,
    [PR_DISTRICTCODE_DR]               INT            NULL,
    [PR_PROCESSSTATUSCODE_DR]          INT            NULL,
    [PR_SPACODE_DR]                    INT            NULL,
    [PR_RESOLUTIONSTATUSCODE_DR]       INT            NULL,
    [PR_NURSEINVESTIGATORDR]           INT            NULL,
    [PR_SPECIMENTYPE]                  NVARCHAR (MAX) NULL,
    [PR_SPECIMENDATECOLLECTED]         NVARCHAR (MAX) NULL,
    [PR_SPECIMENDATERECEIVED]          NVARCHAR (MAX) NULL,
    [PR_SPECIMENRESULT]                NVARCHAR (MAX) NULL,
    [PR_SPECIMENNOTE]                  NVARCHAR (MAX) NULL,
    [PR_DIAGSPECIMENTYPES]             VARCHAR (8000) NULL,
    [PR_EXPEXPOSURETYPES]              VARCHAR (8000) NULL,
    [PR_HEPATITISDRS]                  VARCHAR (8000) NULL,
    [PR_DISEASEGROUPS]                 VARCHAR (8000) NULL,
    [PR_RESULTVALUE]                   NVARCHAR (MAX) NULL,
    [PR_LIPTESTORDERED]                VARCHAR (8000) NULL,
    [PR_ISPREGNANT]                    BIT            NULL,
    [PR_EXPECTEDDELIVERYDATE]          DATETIME       NULL,
    [PR_LIPRESULTNOTES]                NVARCHAR (MAX) NULL,
    [PR_LIPRESULTNAME]                 VARCHAR (8000) NULL,
    [PR_HEALTHCAREPROVIDERLOCATIONDR]  INT            NULL,
    [PR_NOTES]                         VARCHAR (MAX)  NULL,
    [PR_DATEOFDIAGNOSIS]               DATETIME       NULL,
    [PR_DATEOFDEATH]                   DATETIME       NULL,
    [PR_DATEOFLABREPORT]               DATETIME       NULL,
    [PR_DATEINVESTIGATORRECEIVED]      DATETIME       NULL,
    [PR_ISSYMPTOMATIC]                 BIT            NULL,
    [PR_ISPATIENTDIEDOFTHEILLNESS]     BIT            NULL,
    [PR_ISPATIENTHOSPITALIZED]         BIT            NULL,
    [PR_LABSPECIMENCOLLECTEDDATE]      DATETIME       NULL,
    [PR_LABSPECIMENRESULTDATE]         DATETIME       NULL,
    [PR_DATEADMITTED]                  DATETIME       NULL,
    [PR_DATEDISCHARGED]                DATETIME       NULL,
    [PR_LABORATORY]                    VARCHAR (250)  NULL,
    [PR_HOSPITALDR]                    INT            NULL,
    [PR_HOSPITAL]                      VARCHAR (250)  NULL,
    [PR_OUTPATIENT]                    BIT            NULL,
    [PR_INPATIENT]                     BIT            NULL,
    [PR_DATESENT]                      DATETIME       NULL,
    [PR_LASTCDCUPDATE]                 DATETIME       NULL,
    [PR_NAMEOFSUBMITTER]               VARCHAR (8000) NULL,
    [PR_OUTBREAKNUMBERS]               VARCHAR (MAX)  NULL,
    [PR_OUTBREAKTYPES]                 VARCHAR (MAX)  NULL,
    [PR_ANIMALREPORTID]                INT            NULL,
    [PR_FBIDR]                         INT            NULL,
    [PR_FBINumber]                     VARCHAR (50)   NULL,
    [PR_CENSUSTRACT]                   VARCHAR (100)  NULL,
    [Additional_Provider]              VARCHAR (8000) NULL,
    [Additional_Laboratory]            VARCHAR (8000) NULL,
    [Age]                              REAL           NULL,
    [American_Indian_or_Alaska_Native] NVARCHAR (MAX) NOT NULL,
    [Asian___Specify]                  NVARCHAR (MAX) NOT NULL,
    [Black_or_African_American___Spec] NVARCHAR (MAX) NOT NULL,
    [CMR_ID]                           VARCHAR (50)   NOT NULL,
    [Country_of_Birth]                 VARCHAR (255)  NOT NULL,
    [Created_By]                       VARCHAR (14)   NOT NULL,
    [Date_Last_Edited]                 DATETIME       NULL,
    [Final_Disposition]                VARCHAR (255)  NOT NULL,
    [Diagnostic_Specimen_Types]        NVARCHAR (MAX) NOT NULL,
    [Health_District_Number]           VARCHAR (255)  NOT NULL,
    [ImportedBy]                       VARCHAR (202)  NULL,
    [Imported_Status]                  VARCHAR (30)   NULL,
    [Lab_Report]                       VARCHAR (5)    NOT NULL,
    [Lab_Report_Notes]                 VARCHAR (8000) NOT NULL,
    [Lab_Report_Test_Name]             VARCHAR (255)  NOT NULL,
    [Marital_Status]                   VARCHAR (255)  NOT NULL,
    [Medical_Record_Number]            VARCHAR (50)   NOT NULL,
    [Most_Recent_Lab_Result]           VARCHAR (1100) NOT NULL,
    [Most_Recent_Lab_Result_Value]     VARCHAR (8000) NOT NULL,
    [Native_Hawaiian_or_Other_Pacific] NVARCHAR (MAX) NOT NULL,
    [Occupation_Setting_Type]          VARCHAR (255)  NOT NULL,
    [Other___Specify]                  NVARCHAR (MAX) NOT NULL,
    [Outbreak_IDs]                     VARCHAR (MAX)  NOT NULL,
    [Parent_or_Guardian_Name]          VARCHAR (50)   NOT NULL,
    [Priority]                         VARCHAR (255)  NOT NULL,
    [Provider_Name]                    VARCHAR (255)  NOT NULL,
    [Report_Source]                    VARCHAR (250)  NOT NULL,
    [Secondary_District]               VARCHAR (255)  NOT NULL,
    [Suspected_Exposure_Types]         NVARCHAR (MAX) NOT NULL,
    [Type_of_Contact]                  VARCHAR (255)  NOT NULL,
    [Unknown___Specify]                NVARCHAR (MAX) NOT NULL,
    [White___Specify]                  NVARCHAR (MAX) NOT NULL
);

