CREATE TABLE [covid].[SARS2_PERSON] (
    [PER_ROWID]                        INT           NOT NULL,
    [PER_LEGACY_ROWID]                 VARCHAR (50)  NULL,
    [PER_COUNTRYOFBIRTHDR]             VARCHAR (100) NULL,
    [PER_CELLPHONE]                    VARCHAR (100) NULL,
    [PER_DATEOFUSARRIVAL]              DATETIME      NULL,
    [PER_OCCUPATIONLOCATION]           VARCHAR (MAX) NULL,
    [PER_OCCUPATIONSPECIFY]            VARCHAR (MAX) NULL,
    [PER_OCCUPATIONSETTINGTYPEDR]      INT           NULL,
    [PER_OCCUPATIONSETTINGTYPESPECIFY] VARCHAR (50)  NULL,
    [PER_ROOTID]                       INT           NULL,
    [PER_LASTNAME]                     VARCHAR (100) NULL,
    [PER_FIRSTNAME]                    VARCHAR (100) NULL,
    [PER_MIDDLENAME]                   VARCHAR (100) NULL,
    [PER_SSN]                          VARCHAR (50)  NULL,
    [PER_HOMEPHONE]                    VARCHAR (100) NULL,
    [PER_WORKPHONE]                    VARCHAR (100) NULL,
    [PER_STREETADDRESS]                VARCHAR (100) NULL,
    [PER_APARTMENT]                    VARCHAR (100) NULL,
    [PER_CITY]                         VARCHAR (100) NULL,
    [PER_STATE]                        VARCHAR (100) NULL,
    [PER_STATENUMBER]                  VARCHAR (MAX) NULL,
    [PER_ZIP]                          VARCHAR (100) NULL,
    [PER_ClientID]                     INT           NULL,
    [PER_COUNTYOFRESIDENCE]            VARCHAR (255) NULL,
    [PER_CENSUSTRACT]                  VARCHAR (100) NULL,
    [PER_LATITUDE]                     VARCHAR (100) NULL,
    [PER_LONGITUDE]                    VARCHAR (100) NULL,
    [PER_ADDRESSSTANDARDIZED]          VARCHAR (50)  NULL,
    [PER_COUNTYFIPS]                   VARCHAR (100) NULL,
    [PER_COUNTY]                       VARCHAR (100) NULL,
    [PER_CENSUSBLOCK]                  VARCHAR (100) NULL,
    [PER_ZIPPLUS4]                     VARCHAR (100) NULL,
    [PER_COUNTRY]                      VARCHAR (100) NULL,
    [PER_COUNTRY_NAME]                 VARCHAR (255) NULL,
    [PER_DOB]                          DATETIME      NULL,
    [PER_SEX]                          VARCHAR (255) NULL,
    [PER_RACE]                         VARCHAR (255) NULL,
    [PER_ETHNICITY]                    VARCHAR (255) NULL,
    [PER_OCCUPATION]                   VARCHAR (255) NULL,
    [PER_SEXCODE_DR]                   INT           NULL,
    [PER_RACECODE_DR]                  INT           NULL,
    [PER_ETHNICITYCODE_DR]             INT           NULL,
    [PER_OCCUPATIONCODE_DR]            INT           NULL,
    [PER_NAMESUFFIX]                   VARCHAR (50)  NULL,
    [PER_RECORDCREATEDBY]              VARCHAR (14)  NOT NULL,
    [PER_WORKSCHOOLLOCATION]           VARCHAR (250) NULL,
    [PER_WORKSCHOOLCONTACT]            VARCHAR (MAX) NULL,
    [PER_PRIMARYLANGUAGE_DR]           INT           NULL,
    [PER_PRIMARYLANGUAGE]              VARCHAR (255) NULL,
    [PER_EMAIL]                        VARCHAR (MAX) NULL,
    [PER_ELECTRONICCONTACT]            VARCHAR (MAX) NULL,
    [PER_CURRENTVERSION]               VARCHAR (1)   NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200731-171215]
    ON [covid].[SARS2_PERSON]([PER_ROWID] ASC);

