create table dbo.COVID_OUTBREAK
(
	OUTB_RowID int not null,
	OUTB_Legacy_RowID varchar(50) null,
	OUTB_Disease varchar(255) null,
	OUTB_OutbreakNumber varchar(50) not null,
	OUTB_IsHealthFacilityOutbreak varchar(255) null,
	OUTB_OutbreakLocation varchar(250) null,
	OUTB_District varchar(255) null,
	OUTB_DateofOnset datetime null,
	OUTB_DateCreated datetime not null,
	OUTB_DateClosed datetime null,
	OUTB_ProcessStatus varchar(255) null,
	OUTB_ResolutionStatus varchar(255) null,
	OUTB_Notes varchar(max) null,
	OUTB_OutbreakType varchar(255) null,
	OUTB_OUTBREAKID int not null,
	OUTB_COUNT int null,
	OUTB_USERDR int null,
	OUTB_HEALTHFACILITYCODE_DR int null,
	OUTB_DISEASECODE_DR int null,
	OUTB_DISSHORTNAME varchar(100) null,
	OUTB_LOCATIONDR int null,
	OUTB_DISTRICTCODE_DR int null,
	OUTB_SPACODE_DR int null,
	OUTB_OUTBREAKTYPECODE_DR int null,
	OUTB_PROCESSSTATUSCODE_DR int null,
	OUTB_RESOLUTIONSTATUSCODE_DR int null,
	OUTB_DATESUBMITTED datetime null,
	OUTB_DGRPDR varchar(max) null,
	OUTB_USERNAME varchar(202) not null,
	OUTB_ISHEALTHFACILITY varchar(5) not null,
	OUTB_LOCATIONTYPE varchar(255) null,
	OUTB_LOCATIONADDRESS varchar(202) null,
	OUTB_LOCATIONPHONE varchar(100) null,
	OUTB_NURSEINVESTIGATOR varchar(202) not null,
	OUTB_NURSEINVESTIGATORDR int null,
	OUTB_LOCATIONEMAIL varchar(max) null,
	OUTB_LOCATIONPRIMARYCONTACT varchar(max) null,
	OUTB_LOCCOUNTY varchar(255) null,
	OUTB_LOCJURISDICTION varchar(255) null,
	OUTB_LOCATIONTYPEDR int null,
	OUTB_PRIORITY varchar(255) null,
	OUTB_DISTRICTNUMBER varchar(255) null,
	OUTB_LOCATIONCENSUSTRACT varchar(100) null,
	OUTB_LOCATIONCENSUSBLOCK varchar(100) null,
	OUTB_LOCATIONCOUNTYFIPS varchar(100) null,
	OUTB_LOCATIONLATITUDE varchar(100) null,
	OUTB_LOCATIONLONGITUDE varchar(100) null,
	OUTB_LOCATIONDISTRICTNUMBER varchar(255) null,
	OUTB_LOCATIONADDRESS_PLUS varchar(507) null,
	Patients_Linked_to_Outbreak nvarchar(max) null,
	All_Contacts_Linked_to_Outbreak nvarchar(max) null,
	Incident_Contacts_Linked_to_Outbreak nvarchar(max) null,
	Contact_Investigations_Linked_to_Outbreak nvarchar(max) null
)
go
create clustered index [COVID_OUTBREAK.OUTB_RowID.Fake.PrimaryKey]
on dbo.COVID_OUTBREAK(OUTB_RowID);
