
CREATE VIEW [AtlasPublic].[View_CMMode_SharedAcrossRecordSection]
AS
SELECT 
    AREL.SOURCE_ID AS Act_ID,
    NULL AS UDFormID,
    NULL AS UDFormDefID,
    AX_SERVICES.SVC_INITIALSERVICEDR AS Service_DR, 
    VUCS_SECTION.FULLNAME AS UDSecName,
    VUCS_SECTION.SHORTNAME AS UDSecType,
    VUCS_FIELD.FULLNAME AS UDFieldName,
    VUCS_FIELD.ID AS UDFieldID,
    VUCS_SECTION.ID AS UDSectionDefID,
    ACT_SECTION.ID AS UDSectionActID,
    AX_UDFVALUES.ID AS UDFieldActID,
    --+CMG IssueNbr:-123369
    Ax_UDFValues.valueDateTime AS UDField_valueDateTime,
    Ax_UDFValues.valueString  AS UDField_valueString,
    ([dbo].[UDF_GetEntityRoot](Ax_UDFValues.VALUE_ENTITYID)) AS UDField_valueENTITYID, 
    Ax_UDFValues.value_UCSID  AS UDField_valueUCSID,
    Ax_UDFValues.metaCode_UCSID  AS UDField_metaCodeUCSID,
    ---CMG IssueNbr:-123369
    VCP_Field.Field_ID AS Field_ID,
    VCP_Section.SEC_ID AS  Sec_ID,
    VCP_Section.SEC_IsListSection,
    ISNull(VCP_Field.FIELD_IsRequired, 0) AS UDFieldIsRequired,
    VCP_Field.FIELD_TypeCode_ID,
    '' AS UDFormName,
    '' AS UDFormDesc,
    ACT_SECTION.EFFECTIVETIME_BEG AS UDFormCreateDate
FROM 
    A_ACT AS ACT_SECTION (NOLOCK)
    INNER JOIN A_ActRelationship AREL (NOLOCK) ON AREL.TARGET_ID=ACT_SECTION.ID AND AREL.TYPECODE='COMP'  AND ACT_SECTION.CLASSCODE='DOCSECT'
    INNER JOIN AX_UDFVALUES (NOLOCK) ON ACT_SECTION.ID = AX_UDFVALUES.ACT_PARENT_ID
    LEFT JOIN AX_SERVICES (NOLOCK) ON AREL.SOURCE_ID = AX_SERVICES.SVC_ID
    INNER JOIN V_UNIFIEDCODESET VUCS_FIELD (NOLOCK) ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID
    INNER JOIN V_UNIFIEDCODESET VUCS_SECTION (NOLOCK) ON  VUCS_SECTION.ID=ACT_SECTION.CODE_ID
    INNER JOIN VCP_UDField VCP_Field (NOLOCK) ON VCP_Field.SubjCode_Id = AX_UDFVALUES.METACODE_UCSID
    INNER JOIN VCP_UDSection VCP_Section (NOLOCK) ON VCP_Section.subjCode_Id = ACT_SECTION.CODE_ID
        --added the ShareAcrossRecord check
        AND VCP_Section.SEC_ShareAcrossRecord = 1
WHERE 
    ACT_SECTION.STATUSCODE='active'
