

CREATE  VIEW [AtlasPublic].[VIEW_UODS_PERSONALRECORD_LEGACY_DVLOCKS]   
AS
	SELECT A.ID AS PR_ROWID,
	dbo.FN_GetUCSFullName(DVPR_TypeDR) PR_PHTYPE,
	A.LOCALID AS PR_LEGACY_ROWID,
	PR.DVPR_PERSONDR AS PR_PERSONDR, 
	PR.DVPR_USERDR AS PR_USERDR, 
	PR.DVPR_OUTBREAKDRSTEXT AS PR_OUTBREAKDRSTEXT, 
	PR.DVPR_INCIDENTID AS PR_INCIDENTID, 
	PR.DVPR_CMRID AS PR_CMRRECORD, 
	--SunilV Issue #135736 Adding [Namespace] column to differentiate LIVE,ELR,MLR and WEB records
	CASE 
		 WHEN UCSNamespace.ConceptCode='WEB' THEN 'WEB' 
		 WHEN UCSNamespace.ConceptCode='MLR' THEN 'MLR'
		 WHEN ((UCSNamespace.ID IS NULL) OR ((UCSNamespace.ID IS NOT NULL) AND (UCSImportOptions.ID IS NOT NULL) AND (UCSImportOptions.ConceptCode NOT IN ('ALR', 'UDL')))) THEN 'LIVE' 
		 ELSE 'ELR' 
	END AS PR_NAMESPACE,
	PR.DVPR_CREATEDATE AS PR_CREATEDATE, 
	PR.DVPR_ONSETDATE AS PR_ONSETDATE, 
	PR.DVPR_CLOSEDDATE AS PR_CLOSEDDATE, 
	PR.DVPR_EPISODEDATE AS PR_EPISODEDATE, 
	PR.DVPR_STANDARDAGE AS PR_STANDARDAGE, 
	PR.DVPR_DATESUBMITTED AS PR_DATESUBMITTED, 
	PR.DVPR_DATEREPORTEDBY AS PR_DATEREPORTEDBY, 
	PR.DVPR_REPORTSOURCEDR AS PR_REPORTSOURCEDR, 
	PR.DVPR_MRN AS PR_MRN, 
	PR.DVPR_CLUSTERID AS PR_CLUSTERID, 
	PR.DVPR_ISINDEXCASE AS PR_ISINDEXCASE, 
	UCS1.FULLNAME AS PR_DISEASE, 
	UCS1.SHORTNAME AS PR_DISEASESHORTNAME, 
	ACT_OTHERDISEASE.VALUESTRING_TXT AS PR_OTHERDISEASE, --CMG ISSUENBR:-50796    
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](PR.DVPR_DISTRICTCODE_ID) AS PR_DISTRICT,     
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](PR.DVPR_PROCESSSTATUSCODE_ID) AS PR_PROCESSSTATUS,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](REGION.SPACODE_ID) AS PR_SPA,
	[DBO].[MDF_UCS_FULLNAME_UCS_BYUCSID](PR.DVPR_RESOLUTIONSTATUSCODE_ID) AS PR_RESOLUTIONSTATUS, 
	case when ISNULL(TENTN.PARTFAM,'') + ', ' + ISNULL(TENTN.PARTGIV,'') = ', ' then '' else ISNULL(TENTN.PARTFAM,'') + ', ' + ISNULL(TENTN.PARTGIV,'') end  AS PR_NURSEINVESTIGATOR, 
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](A.ID,'PR_REPORTEDBYWEB') AS PR_REPORTEDBYWEB, 
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](A.ID,'PR_REPORTEDBYLAB') AS PR_REPORTEDBYLAB,  
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](A.ID,'PR_REPORTEDBYEHR') AS PR_REPORTEDBYEHR,
	[DBO].[MDF_UCS_FULLNAME_ATTRUCS_BYACTID](A.ID,'VALUECODE_ID','PR_TRANSMISSIONSTATUS') AS PR_TRANSMISSIONSTATUS,
	PR.DVPR_DISEASECODE_ID AS PR_DISEASECODE_DR, 
	PR.DVPR_DISTRICTCODE_ID AS PR_DISTRICTCODE_DR, 
	PR.DVPR_PROCESSSTATUSCODE_ID AS PR_PROCESSSTATUSCODE_DR, 
	REGION.SPACODE_ID AS PR_SPACODE_DR,			 --SugannyaB 07/23/2012 Issue#127694
	PR.DVPR_RESOLUTIONSTATUSCODE_ID AS PR_RESOLUTIONSTATUSCODE_DR, 
	PR.DVPR_NURSEINVESTIGATORDR AS PR_NURSEINVESTIGATORDR, 
	--+DNS*06232008*GET THE SPECIMEN DATA FROM DENORMALIZE SPECIMEN TABLE.          
	STDSPECIMENS.DVIS_SPECIMENTYPES AS PR_SPECIMENTYPE, 
	STDSPECIMENS.DVIS_COLLECTIONDATES AS PR_SPECIMENDATECOLLECTED, 
	STDSPECIMENS.DVIS_RECEIVEDDATES PR_SPECIMENDATERECEIVED, 
	[dbo].FN_ConcateDILRResultValueText(STDSPECIMENS.DVIS_INCIDENTDR) AS PR_SPECIMENRESULT, 
	[dbo].FN_ConcateDILRNoteText(STDSPECIMENS.DVIS_INCIDENTDR) AS PR_SPECIMENNOTE,
	---DNS*06232008*GET THE SPECIMEN DATA FROM DENORMALIZE SPECIMEN TABLE.      
	---MD - HTTPS://DEVELOPMENT.ATLASDEV.COM/ISSUE_VIEW.ASP?ISSUENBR=40727          
	[dbo].FN_CumulativeTypes(A.ID, 'DIST_ROWID') AS PR_DIAGSPECIMENTYPES, 
	[dbo].FN_CumulativeTypes(A.ID, 'DIET_ROWID') AS PR_EXPEXPOSURETYPES, 
	[dbo].FN_CumulativeTypes(A.ID, 'DIHT_HEPATITISTESTDR') AS PR_HEPATITISDRS, 
	[dbo].FN_DiseaseGroups(A.CODE_ID) AS PR_DISEASEGROUPS, 
	---MD - HTTPS://DEVELOPMENT.ATLASDEV.COM/ISSUE_VIEW.ASP?ISSUENBR=40727       
	[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_LIPRESULTVALUE', A.ID, 'VALUESTRING_TXT') AS PR_RESULTVALUE,  
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID](A.ID, 'VALUESTRING_TXT','PR_LIPTESTORDERED') AS PR_LIPTESTORDERED, --Suroy Issue#165190 02/19/14
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_ISPREGNANT', A.ID, 'VALUEBOOL') AS PR_ISPREGNANT, 
	[DBO].[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_EXPECTEDDELIVERYDATE', A.ID, 'VALUETS') AS PR_EXPECTEDDELIVERYDATE, 
	--[DBO].[MDF_ACT_GETSTRINGVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_LIPRESULTNOTES', A.ID, 'VALUESTRING') AS PR_LIPRESULTNOTES, 
	cast(lipnotes.valueString as nvarchar(max)) as PR_LIPRESULTNOTES,
	ISNULL(A8.VALUESTRING, A5.VALUESTRING) AS PR_LIPRESULTNAME, 
	HCP.TRIVIALNAME AS PR_HEALTHCAREPROVIDER, 
	LOCLINK.ENTITY2_ID AS PR_HEALTHCAREPROVIDERLOCATIONDR, 
	A.[text] AS PR_NOTES,
	PR.DVPR_DIAGNOSISDATE AS PR_DATEOFDIAGNOSIS, 
	[DBO].[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_DATEOFDEATH',A.ID,'EFFECTIVETIME_BEG') AS PR_DATEOFDEATH, 
	A8.AVAILABILITYTIME AS PR_DATEOFLABREPORT, 
	A.AVAILABILITYTIME AS PR_DATEINVESTIGATORRECEIVED, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_ISASYMPTOMATIC', A.ID, 'VALUEBOOL') AS PR_ISSYMPTOMATIC, 
	[DBO].[MDF_ACT_GETBOOLEANVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_ISPATIENTDIEDOFTHEILLNESS', A.ID, 'VALUEBOOL') AS PR_ISPATIENTDIEDOFTHEILLNESS,
	PH.HOSPITALIZEDIND AS PR_ISPATIENTHOSPITALIZED, 
	[DBO].[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_LABSPECIMENCOLLECTEDDATE',A.ID,'EFFECTIVETIME_BEG') AS PR_LABSPECIMENCOLLECTEDDATE,
	[DBO].[MDF_ACT_GETDATETIMEVALUE_ACT_BYPARACTIDMETAVALUETYPE]('PR_LABSPECIMENRESULTDATE',A.ID,'EFFECTIVETIME_BEG') AS PR_LABSPECIMENRESULTDATE,
	-- +MLG ISSUE - 45920          
	A.VALUETS AS PR_DATEADMITTED, 
	A.VALUETSEND AS PR_DATEDISCHARGED, 
	LAB.TRIVIALNAME AS PR_LABORATORY,
	R_HOSPITAL.PLAYER_ID AS PR_HOSPITALDR, 
	TEN_HOSPITAL.TRIVIALNAME AS PR_HOSPITAL, 
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](A.ID,'PR_OUTPATIENT') AS PR_OUTPATIENT, 
	[DBO].[MDF_ATTR_GETBOOLEANVALUE_ACTATTR_BYACTID](A.ID,'PR_INPATIENT') AS PR_INPATIENT,
	DATESENT.ACTIVITYTIME_BEG AS PR_DATESENT, 
	DATESENT.ACTIVITYTIME_END AS PR_LASTCDCUPDATE,  
	--+ SHREERAM SRIDHARAN - ISSUE # 46516 - TTD SECTION 5.3.2    
	[DBO].[MDF_ATTR_GETSTRINGVALUE_ACTATTR_BYACTID](A.ID,'VALUESTRING','PR_NAMEOFSUBMITTER') AS PR_NAMEOFSUBMITTER,  
	--* SHREERAM SRIDHARAN - ISSUE # 46516 - TTD SECTION 5.3.2      
	-- -MLG ISSUE - 45920      
	PR.DVPR_OUTBREAKNUMBERS AS PR_OUTBREAKNUMBERS,
	-- +SKUMAR ISSUENBR:110616
	PR.DVPR_OUTBREAKTYPES AS PR_OUTBREAKTYPES,
	AI.DVAI_ANIMALREPORTID AS PR_ANIMALREPORTID,
	-- -SKUMAR ISSUENBR:110616
	-- +Suroy Issue#135926 10/01/2012
	FBIInc.SOURCE_ID AS PR_FBIDR,
	FBIComp.extension AS PR_FBINumber,
	-- -Suroy Issue#135926 10/01/2012
	PER.DVPER_CensusTract as PR_CENSUSTRACT
	
	FROM [dbo].DV_PHPERSONALRECORD PR 
	INNER JOIN dbo.DV_Person PER  ON PER.DVPER_RowID=PR.DVPR_PersonDR 
    LEFT OUTER JOIN [dbo].V_UNIFIEDCODESET UCSNamespace(NOLOCK) ON PER.DVPER_NamespaceCode_ID=UCSNamespace.ID
    LEFT OUTER JOIN [dbo].V_UNIFIEDCODESET UCSImportOptions(NOLOCK) ON PER.DVPER_ImportOptionsCode_ID=UCSImportOptions.ID
	INNER JOIN [dbo].A_ACT A(NOLOCK) ON  A.ID = PR.DVPR_ROWID AND A.METACODE = 'PR_ROWID'
	INNER JOIN [dbo].A_PUBLICHEALTHCASE PH(NOLOCK) ON PH.ID = A.ID 
	left join a_act lipnotes (nolock) on lipnotes.Act_Parent_ID = a.id and lipnotes.metaCode = 'PR_LIPRESULTNOTES'         
	--+CMG ISSUENBR:-50796
	LEFT JOIN [dbo].A_ACT ACT_OTHERDISEASE(NOLOCK) ON  ACT_OTHERDISEASE.ACT_PARENT_ID = A.ID AND ACT_OTHERDISEASE.METACODE = 'PR_OTHERDISEASENAME'       
	---CMG ISSUENBR:-50796      
	LEFT JOIN VCP_DISTRICT REGION (NOLOCK) ON PR.DVPR_DISTRICTCODE_ID = REGION.SUBJCODE_ID
	LEFT JOIN [dbo].V_UNIFIEDCODESET UCS1(NOLOCK) ON  PR.DVPR_DISEASECODE_ID = UCS1.ID   
	LEFT JOIN [dbo].T_ENTITYNAME TENTN (NOLOCK) ON PR.DVPR_NURSEINVESTIGATORDR=TENTN.ENTITY_ID AND TENTN.USECODE = 'L'        
	LEFT JOIN [dbo].A_ACT A5(NOLOCK) ON  A5.ACT_PARENT_ID = A.ID AND A5.METACODE = 'PR_LIPRESULTNAME'          
	LEFT JOIN [dbo].A_ACT A8(NOLOCK) ON  A8.ACT_PARENT_ID = A.ID AND A8.METACODE = 'DILR_ID' AND A8.ID = [dbo].FN_LAB_ACTID(A.ID) 
	--SUGANNYAB 09/20/2010 ISSUENBR=89578    
	LEFT JOIN [dbo].T_ENTITYNAME HCP(NOLOCK) ON  HCP.ENTITY_ID = PR.DVPR_REPORTSOURCEDR AND HCP.USECODE = 'SRCH' AND HCP.METACODE = 'RS_HEALTHCAREPROVIDER'       
	--+DNS*06232008*REORDERED THE CLASSCODE & METACODE FILTER          
	LEFT JOIN [dbo].S_LINK LOCLINK(NOLOCK) ON LOCLINK.NAME='RSLOCATION-PRIMARY' AND LOCLINK.ENTITY1_ID=PR.DVPR_REPORTSOURCEDR      
	---DNS*06232008*REORDERED THE CLASSCODE & METACODE FILTER      
	--+DNS*06232008*QUERY TO GET THE SPECIMEN DATA FROM DENORMALIZE SPECIMEN TABLE.
	LEFT JOIN 
	(
		SELECT [dbo].STRCONCAT(DVIS_CollectionDate) AS DVIS_COLLECTIONDATES,   
		[dbo].STRCONCAT(DVIS_RECEIVEDDATE) AS DVIS_RECEIVEDDATES,   
		[dbo].STRCONCAT(ISNULL(UCS1.FULLNAME,'')) AS DVIS_SPECIMENTYPES,   
		[dbo].STRCONCAT(DVIS_SPECIMENRESULTS) AS DVIS_SPECIMENRESULTS, 
		DVIS_INCIDENTDR 
		FROM [dbo].DV_INCIDENTSPECIMEN 
		LEFT JOIN [dbo].V_UNIFIEDCODESET UCS1(NOLOCK) ON  UCS1.ID = DVIS_SPECIMENTYPECODE_ID
		GROUP BY DVIS_INCIDENTDR
	) STDSPECIMENS ON STDSPECIMENS.DVIS_INCIDENTDR=PR.DVPR_ROWID      
	---DNS*06232008*QUERY TO GET THE SPECIMEN DATA FROM DENORMALIZE SPECIMEN TABLE.      
	-- +MLG ISSUE - 45920 
	LEFT JOIN [dbo].P_PARTICIPATION PART (NOLOCK) ON  PART.ACT_ID = PR.DVPR_ROWID AND PART.TYPECODE = 'ELOC' AND PART.METACODE = 'PR_LABORATORYDR'
	LEFT JOIN [dbo].R_ROLE RLAB (NOLOCK) ON  RLAB.ID = PART.ROLE_ID AND RLAB.CLASSCODE = 'QUAL' 
	LEFT JOIN [dbo].T_ENTITYNAME LAB (NOLOCK) ON  LAB.ENTITY_ID = RLAB.PLAYER_ID AND LAB.USECODE = 'SRCH' 
	LEFT JOIN [dbo].P_PARTICIPATION P_HOSPITAL (NOLOCK) ON  P_HOSPITAL.ACT_ID = A.ID AND P_HOSPITAL.METACODE = 'PR_HOSPITALDR'      
	LEFT JOIN [dbo].R_ROLE R_HOSPITAL (NOLOCK) ON  R_HOSPITAL.ID = P_HOSPITAL.ROLE_ID AND R_HOSPITAL.CLASSCODE = 'QUAL'      
	LEFT JOIN [dbo].A_ACT DATESENT (NOLOCK) ON PR.DVPR_ROWID=DATESENT.ACT_PARENT_ID AND DATESENT.CLASSCODE='OBS' AND DATESENT.METACODE='PR_DATESENT'       
	LEFT JOIN [dbo].T_ENTITYNAME TEN_HOSPITAL (NOLOCK) ON  TEN_HOSPITAL.ENTITY_ID = R_HOSPITAL.PLAYER_ID AND TEN_HOSPITAL.USECODE = 'SRCH' AND TEN_HOSPITAL.METACODE = 'LOC_NAME'       
	-- +SKUMAR ISSUENBR:110616
	LEFT JOIN [dbo].A_ACTRELATIONSHIP ACTREL_ANIMAL (NOLOCK) ON A.ID = ACTREL_ANIMAL.TARGET_ID AND ACTREL_ANIMAL.TYPECODE='COMP' AND ACTREL_ANIMAL.METACODE IN('AI_CONTACTINVESTIGATIONDR','AI_DISEASEINCIDENTDR')
	LEFT JOIN [dbo].DV_ANIMALREPORT AI  ON AI.DVAI_ROWID = ACTREL_ANIMAL.SOURCE_ID
	-- -SKUMAR ISSUENBR:110616
		---- +Suroy Issue#135926 10/01/2012
	LEFT JOIN A_ActRelationship(NOLOCK) FBIInc on PH.ID=FBIInc.Target_ID and FBIInc.TypeCode='COMP' and FBIInc.METACODE='PR_FBIDR'
	LEFT JOIN T_INSTANCEIDENTIFIER (NOLOCK) FBIComp on FBIInc.source_ID=FBIComp.ACT_ID
	---- -Suroy Issue#135926 10/01/2012



