
CREATE VIEW [AtlasPublic].[viewUDF_SharedAcrossPersonSection]
AS
SELECT 
	CASEACT.ID AS Act_ID,
	NULL AS UDFormID,
	NULL AS UDFormDefID,
	ACT_SECTION.VALUECODE_ID AS DISEASE_ID, 
	VUCS_SECTION.FULLNAME AS UDSecName,
	VUCS_SECTION.SHORTNAME AS UDSecType,
	VUCS_FIELD.FULLNAME AS UDFieldName,
	VUCS_FIELD.ID AS UDFieldID,
	VUCS_SECTION.ID AS UDSectionDefID,
	ACT_SECTION.ID AS UDSectionActID,
	AX_UDFVALUES.ID AS UDFieldActID,
	--+CMG IssueNbr:-123369
	Ax_UDFValues.valueDateTime AS UDField_valueDateTime,
	Ax_UDFValues.valueString  AS UDField_valueString,
	Ax_UDFValues.VALUE_ENTITYID  AS UDField_valueENTITYID,
	Ax_UDFValues.value_UCSID  AS UDField_valueUCSID,
	Ax_UDFValues.metaCode_UCSID  AS UDField_metaCodeUCSID,
	---CMG IssueNbr:-123369
	VCP_Field.Field_ID AS Field_ID,
	VCP_Section.SEC_ID AS  Sec_ID,
	VCP_Section.SEC_IsListSection,
	ISNull(VCP_Field.FIELD_IsRequired, 0) AS UDFieldIsRequired,
	VCP_Field.FIELD_TypeCode_ID,
	'' AS UDFormName,
	'' AS UDFormDesc,
	ACT_SECTION.EFFECTIVETIME_BEG AS UDFormCreateDate
FROM 
	A_ACT(NOLOCK) AS ACT_SECTION
	INNER JOIN A_ActRelationship(NOLOCK) AREL ON AREL.TARGET_ID=ACT_SECTION.ID AND AREL.TYPECODE='COMP'
	INNER JOIN A_ACT(NOLOCK) AS CASEACT ON CASEACT.ACT_PARENT_ID =AREL.source_ID AND CASEACT.CLASSCODE='CASE'
	INNER JOIN AX_UDFVALUES(NOLOCK) ON ACT_SECTION.ID = AX_UDFVALUES.ACT_PARENT_ID
	INNER JOIN VCP_UDSection(NOLOCK) VCP_Section ON VCP_Section.subjCode_Id = ACT_SECTION.CODE_ID		
	LEFT JOIN V_UNIFIEDCODESET(NOLOCK) VUCS_FIELD ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID
	LEFT JOIN V_UNIFIEDCODESET(NOLOCK) VUCS_SECTION ON  VUCS_SECTION.ID=ACT_SECTION.CODE_ID
	LEFT JOIN VCP_UDField(NOLOCK) VCP_Field ON VCP_Field.SubjCode_Id = AX_UDFVALUES.METACODE_UCSID	
	
WHERE 
	ACT_SECTION.CLASSCODE='DOCSECT' 
	AND ACT_SECTION.STATUSCODE='active'
	--added the ShareAcrossPerson check
	AND VCP_Section.SEC_ShareAcrossPerson = 1


