

CREATE VIEW [AtlasPublic].[VIEW_CMMode_FamilyMembers]
AS
SELECT 
    PER_CLIENTID,
    FAM_PERSONID,
    FAM_PATIENTID,
    FAM_LASTNAME,
    FAM_FIRSTNAME,
    FAM_MIDDLENAME,
    FAM_NAMESUFFIX,
    FAM_FAMILYMEMBER as FAM_CLIENTID,
    FAM_RELATION,
    FAM_ADDRESS,
    FAM_CITY,
    FAM_STATE,
    FAM_ZIP,
    FAM_CENSUSTRACT,
    FAM_HOMEPHONE,
    FAM_CELLPHONE,
    FAM_GENDER,
    FAM_DOB,
    FAM_PRIMARYLANGUAGE,
    FAM_ETHNICITY,
    FAM_RACE
    FROM [AtlasInternal].[VIEW_ClientRecord_FamilyMembers_CMMode]      

