
CREATE VIEW [AtlasPublic].[VIEW_CMR_AR_Vet_SignOfIllness] AS
SELECT 
AI_ROWID AS AI_SOI_AnimalRowId,
AI_AnimalReportID AS AI_SOI_AnimalID,
UCSSIGNILL.FULLNAME as AI_SOI_SignOfIllness 
FROM A_Act ACTSIGNILL (NOLOCK)
INNER JOIN [AtlasInternal].VIEW_CMR_AR_Vet_ChildActTopic ON AI_VET_ACTTOPIC=ACTSIGNILL.Act_Parent_ID
INNER JOIN V_UnifiedCodeSet UCSSIGNILL  (NOLOCK) ON UCSSIGNILL.ID=ACTSIGNILL.valueCode_ID WHERE ACTSIGNILL.metaCode='ARSOI_RowID'  AND ACTSIGNILL.statusCode='ACTIVE'

