CREATE VIEW [AtlasPublic].[View_CMR_ReportSource] 
AS  
SELECT 
	TOP 100 PERCENT DBO.E_ORGANIZATION.ID,
	DBO.T_ENTITYNAME.TRIVIALNAME AS RS_NAME,
	TYPE_UCS.FULLNAME AS RS_TYPE,  
	DBO.T_ENTITYADDRESS.PartAPTNUM AS RS_BUILDINGNUMBER,
	DBO.T_INSTANCEIDENTIFIER.EXTENSION  As RS_ProviderIdentifier,
	ISNULL(DBO.T_ATTRIBUTE.VALUEBOOL,0) AS RS_IsPreferredProviderIdentifier
FROM 
	DBO.V_UNIFIEDCODESET TYPE_UCS (NOLOCK)
	RIGHT OUTER JOIN DBO.E_ORGANIZATION (NOLOCK)
	INNER JOIN DBO.E_ENTITY (NOLOCK) ON DBO.E_ORGANIZATION.ID = DBO.E_ENTITY.ID ON TYPE_UCS.ID = DBO.E_ENTITY.CODE_ID 
	LEFT OUTER JOIN DBO.T_ENTITYNAME (NOLOCK) ON DBO.E_ENTITY.ID = DBO.T_ENTITYNAME.ENTITY_ID 
	LEFT OUTER JOIN  DBO.T_ENTITYADDRESS (NOLOCK) ON DBO.E_ENTITY.ID = DBO.T_ENTITYADDRESS.ENTITY_ID
	LEFT JOIN DBO.T_INSTANCEIDENTIFIER (NOLOCK) ON DBO.T_INSTANCEIDENTIFIER.Entity_ID =DBO.E_ORGANIZATION.ID 
	AND DBO.T_INSTANCEIDENTIFIER.ROOT = '2.16.840.1.113883.4.6' AND DBO.T_INSTANCEIDENTIFIER.METACODE = 'RS_NationalProviderIdentifier' 
	LEFT JOIN DBO.T_ATTRIBUTE (NOLOCK) ON DBO.T_ATTRIBUTE.Entity_ID=DBO.E_ORGANIZATION.ID  
	AND DBO.T_ATTRIBUTE.NAME='RS_NPI_IsNPI' AND DBO.T_ATTRIBUTE.TYPE='BL' 
	ORDER BY DBO.T_ENTITYNAME.TRIVIALNAME  

