
CREATE VIEW [AtlasPublic].[VIEW_ClientRecord_FamilyMembers]
AS
    SELECT 
        FAMVIEW.PER_CLIENTID AS FAM_CLIENTID,
        FAMVIEW.FAM_PERSONID AS FAM_ROWID,
        FAMVIEW.FAM_PATIENTID AS FAM_LINKEDPERSONID,
        FAMVIEW.FAM_LASTNAME AS FAM_LASTNAME,
        FAMVIEW.FAM_FIRSTNAME AS FAM_FIRSTNAME,
        FAMVIEW.FAM_MIDDLENAME AS FAM_MIDDLENAME,
        FAMVIEW.FAM_NAMESUFFIX AS FAM_NAMESUFFIX,
        FAMVIEW.FAM_HOMEPHONE AS FAM_HOMEPHONE,
        FAMVIEW.FAM_CELLPHONE AS FAM_CELLPHONE,
        FAMVIEW.FAM_GENDER AS FAM_GENDER,
        FAMVIEW.FAM_DOB AS FAM_DOB,
        FAMVIEW.FAM_RACE AS FAM_RACE,
        FAMVIEW.FAM_ETHNICITY AS FAM_ETHNICITY,
        FAMVIEW.FAM_RELATION AS FAM_RELATION,
        FAMVIEW.FAM_ADDRESS AS FAM_ADDRESS,
        FAMVIEW.FAM_APARTMENT AS FAM_APARTMENT,
        FAMVIEW.FAM_CITY AS FAM_CITY,
        FAMVIEW.FAM_STATE AS FAM_STATE,
        FAMVIEW.FAM_ZIP AS FAM_ZIP,
        FAMVIEW.FAM_CENSUSTRACT AS FAM_CENSUSTRACT,
        FAMVIEW.FAM_PRIMARYLANGUAGE AS FAM_PRIMARYLANGUAGE      
    FROM
        [AtlasInternal].[VIEW_ClientRecord_FamilyMembers_CMMode] FAMVIEW

