
CREATE VIEW [AtlasPublic].[View_UODS_UDFData]
AS 

WITH CTE_PHDATEFIELDFORMAT(DATEFIELDFORMAT)
AS
(
    SELECT 
    CASE 
        WHEN ISNULL(VAL.Value,'')='' THEN CAST(CONFIG.defaultValue AS VARCHAR)
        ELSE CAST(VAL.Value AS VARCHAR)
    END AS DATEFIELDFORMAT
    FROM S_CONFIGDEFINITION (nolock)CONFIG
    INNER JOIN S_CONFIGVALUE(nolock) VAL ON VAL.configdefinition_id = CONFIG.id
    WHERE CONFIG.[KEY]='PHDateFieldFormat'
)
--START - BLK Normal Sections
SELECT 
      PHCASE.ID AS [RECORD_ID],    
      UDFormID AS [FORM_INSTANCE_ID],
      VCPUDF.FRM_ID [FORM_DEF_DR],  
      VCPUDF.SUBJCODE_ID [Form_DEF_ID],
      UDFormName AS [FORM_NAME],  
      VCPUDF.FRM_InCMR [FORM_SHOW_IN_CMR],    
      VCPUDF.FRM_InNCM [FORM_SHOW_IN_NCM] , 
      UDFormDesc AS [FORM_DESCRIPTION],  
      UDFormCreateDate AS [FORM_CREATEDATE] , 
      (SELECT MultiInstanceFormNumber FROM dbo.[FN_CMR_GetMultiInstanceFormNumber](PHCASE.ID, VCPUDF.FRM_IsMultipleInstance)  WHERE SecActID = UDFormID) AS [FORM_NUMBER],
      VCPUDF.FRM_IsMultipleInstance AS FORM_IsMultipleInstance ,
      UDSectionActID AS [SECTION_INSTANCE_ID],  
      Sec_ID AS [SECTION_DEF_DR],   
      UDSecName AS [SECTION_NAME],    
      (CASE WHEN (SELECT VTD.ACTIVE FROM V_TERMDICTIONARY VTD (NOLOCK) WHERE UDSectionDefID=VTD.TERMCODE_ID) > 0 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS],    
      CASE WHEN (SELECT VCP.SEC_ISLISTSECTION FROM VCP_UDSECTION VCP (NOLOCK) WHERE UDSectionDefID=VCP.SubjCode_ID) > 0 THEN 'LIST' ELSE 'NON-LIST' END AS [SECTION_TYPE],  
      ( SELECT ListSectionNumber FROM [GetListSectionNumber] (UDFormID,0)  WHERE SecActID = UDSectionActID) AS [SECTION_NUMBER] ,   
      UDFieldActID AS [FIELD_INSTANCE_ID], 
      Field_ID AS [FIELD_DEF_DR],     
      UDFieldName AS [FIELD_NAME],    
      (CASE WHEN UDFieldIsRequired=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],
      (CASE WHEN VFORM.UDField_valueENTITYID > 1 
     THEN 
        (SELECT [dbo].[UDF_GetEntityNameAsText](VFORM.UDField_metaCodeUCSID,VFORM.UDField_valueENTITYID) AS Expr1)
     ELSE 
        (SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, VFORM.UDField_valueDateTime, VFORM.UDField_valueString, VFORM.UDField_valueENTITYID, - 1, VFORM.UDField_valueUCSID, VFORM.UDField_metaCodeUCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1)
     END) AS [FIELD_VALUE], 
    (CASE WHEN VFORM.UDField_valueENTITYID > 1
     THEN 
        CAST(VFORM.UDField_valueENTITYID AS varchar(100))
     ELSE 
        (SELECT dbo.UDF_GetFieldUCSValueAsConceptCode( VFORM.UDField_valueUCSID) AS Expr1)
     END) AS [FIELD_CONCEPT_CODE_VALUE], 
      (Case when VTDField.Active=1 then 'ACTIVE' else 'INACTIVE' END)  AS [FIELD_STATUS],  
      UCSFieldType.FullName AS [FIELD_TYPE]
FROM 
      CTE_PHDATEFIELDFORMAT,
      A_ACT PHCASE  (NOLOCK)  
      INNER JOIN [ATLASINTERNAL].[VIEW_UODS_UDFORM] VFORM (NOLOCK) ON VFORM.Act_ID =PHCASE.ID
      INNER JOIN VCP_UDFORM VCPUDF (NOLOCK) ON  VCPUDF.SUBJCODE_ID = UDFormDefID
      LEFT JOIN V_TERMDICTIONARY VTDFIELD (NOLOCK) ON VTDFIELD.TERMCODE_ID=VFORM.UDFIELDID 
      LEFT JOIN V_UNIFIEDCODESET UCSFIELDTYPE (NOLOCK) ON UCSFIELDTYPE.ID=VFORM.FIELD_TYPECODE_ID    
      LEFT JOIN AX_UDFVALUES AFIELD (NOLOCK) ON AFIELD.ID=VFORM.UDFIELDACTID
 WHERE  
      PHCASE.Classcode IN('Case','OUTB','TOPIC')
      AND PHCASE.METACODE IN('PR_RowID','OB_RowID','AI_ROWID','SVC_ID','GE_RowID')
      AND PHCASE.Statuscode NOT IN ('nullified','terminated')
--END -- BLK Normal Sections
--START -- BLK SHARED ACROSS RECORD SECTIONS
UNION ALL
(
    SELECT 
    PHCASE.ID AS [RECORD_ID],    
    UDFormID AS [FORM_INSTANCE_ID],  
    VCPUDF.FRM_ID [FORM_DEF_DR],    
    VCPUDF.SUBJCODE_ID [Form_DEF_ID],
    UDFormName AS [FORM_NAME], 
    VCPUDF.FRM_InCMR [FORM_SHOW_IN_CMR],    
    VCPUDF.FRM_InNCM [FORM_SHOW_IN_NCM] ,
    UDFormDesc AS [FORM_DESCRIPTION],  
    UDFormCreateDate AS [FORM_CREATEDATE] , 
    (SELECT MultiInstanceFormNumber FROM dbo.[FN_CMR_GetMultiInstanceFormNumber](PHCASE.ID, VCPUDF.FRM_IsMultipleInstance)  WHERE SecActID = UDFormID) AS [FORM_NUMBER],
     VCPUDF.FRM_IsMultipleInstance AS FORM_IsMultipleInstance ,
    UDSectionActID AS [SECTION_INSTANCE_ID], 
    Sec_ID AS [SECTION_DEF_DR],     
    UDSecName AS [SECTION_NAME],    
    (CASE WHEN (SELECT VTD.ACTIVE FROM V_TERMDICTIONARY VTD (NOLOCK) WHERE UDSectionDefID=VTD.TERMCODE_ID) > 0 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS], 
    CASE WHEN (SELECT VCP.SEC_ISLISTSECTION FROM VCP_UDSECTION VCP (NOLOCK) WHERE UDSectionDefID=VCP.SubjCode_ID) > 0 THEN 'LIST' ELSE 'NON-LIST' END AS [SECTION_TYPE],
    ( SELECT ListSectionNumber FROM [GetListSectionNumber] (PHCASE.ID,1)  WHERE SecActID = UDSectionActID) AS [SECTION_NUMBER] ,    
    UDFieldActID AS [FIELD_INSTANCE_ID],
    Field_ID AS [FIELD_DEF_DR],     
    UDFieldName AS [FIELD_NAME],    
    (CASE WHEN UDFieldIsRequired=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],  
     (CASE WHEN VFORM.UDField_valueENTITYID > 1 
     THEN 
        (SELECT [dbo].[UDF_GetEntityNameAsText](VFORM.UDField_metaCodeUCSID,VFORM.UDField_valueENTITYID) AS Expr1)
     ELSE 
        (SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, VFORM.UDField_valueDateTime, VFORM.UDField_valueString, VFORM.UDField_valueENTITYID, - 1, VFORM.UDField_valueUCSID, VFORM.UDField_metaCodeUCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1)
     END) AS [FIELD_VALUE], 
    (CASE WHEN VFORM.UDField_valueENTITYID > 1
     THEN 
        CAST(VFORM.UDField_valueENTITYID AS varchar(100))
     ELSE 
        (SELECT dbo.UDF_GetFieldUCSValueAsConceptCode( VFORM.UDField_valueUCSID) AS Expr1)
     END) AS [FIELD_CONCEPT_CODE_VALUE], 
    (Case when VTDField.Active=1 then 'ACTIVE' else 'INACTIVE' END)  AS [FIELD_STATUS],  
    UCSFieldType.FullName AS [FIELD_TYPE]
FROM CTE_PHDATEFIELDFORMAT,
    A_ACT PHCASE  (NOLOCK)   
    INNER JOIN [ATLASPUBLIC].[VIEWUDF_SHAREDACROSSCASESECTION] VFORM (NOLOCK) ON VFORM.ACT_ID=PHCASE.ID
    LEFT JOIN VCP_UDFORM VCPUDF (NOLOCK) ON  VCPUDF.SUBJCODE_ID = UDFORMDEFID
    LEFT JOIN V_TERMDICTIONARY VTDFIELD (NOLOCK) ON VTDFIELD.TERMCODE_ID=VFORM.UDFIELDID    
    LEFT JOIN V_UNIFIEDCODESET UCSFIELDTYPE (NOLOCK) ON UCSFIELDTYPE.ID=VFORM.FIELD_TYPECODE_ID    
WHERE  
      PHCASE.Classcode in('CASE','OUTB','TOPIC')
      AND PHCASE.METACODE in('PR_RowID','OB_RowID','AI_ROWID','SVC_ID','GE_RowID')
      AND PHCASE.Statuscode NOT IN ('nullified','terminated')
)
--END -- BLK SHARED ACROSS RECORD SECTIONS

--START -- BLK SHARED ACROSS PERSON SECTIONS
UNION ALL

(
SELECT 
    PHCASE.ID AS [RECORD_ID],    
    UDFormID AS [FORM_INSTANCE_ID],  
    VCPUDF.FRM_ID [FORM_DEF_DR],    
    VCPUDF.SUBJCODE_ID [Form_DEF_ID],
    UDFormName AS [FORM_NAME], 
    VCPUDF.FRM_InCMR [FORM_SHOW_IN_CMR],    
    VCPUDF.FRM_InNCM [FORM_SHOW_IN_NCM] ,
    UDFormDesc AS [FORM_DESCRIPTION],  
    UDFormCreateDate AS [FORM_CREATEDATE] , 
    (SELECT MultiInstanceFormNumber FROM dbo.[FN_CMR_GetMultiInstanceFormNumber](PHCASE.ID, VCPUDF.FRM_IsMultipleInstance)  WHERE SecActID = UDFormID) AS [FORM_NUMBER],
     VCPUDF.FRM_IsMultipleInstance AS FORM_IsMultipleInstance ,
    UDSectionActID AS [SECTION_INSTANCE_ID], 
    Sec_ID AS [SECTION_DEF_DR],     
    UDSecName AS [SECTION_NAME],    
    (CASE WHEN (SELECT VTD.ACTIVE FROM V_TERMDICTIONARY VTD (NOLOCK) WHERE UDSectionDefID=VTD.TERMCODE_ID) > 0 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS], 
    CASE WHEN (SELECT VCP.SEC_ISLISTSECTION FROM VCP_UDSECTION VCP (NOLOCK) WHERE UDSectionDefID=VCP.SubjCode_ID) > 0 THEN 'LIST' ELSE 'NON-LIST' END AS [SECTION_TYPE],
    ( SELECT ListSectionNumber FROM [GetListSectionNumber] (PHCASE.Act_Parent_ID,1)  WHERE SecActID = UDSectionActID) AS [SECTION_NUMBER] ,    
    UDFieldActID AS [FIELD_INSTANCE_ID],
    Field_ID AS [FIELD_DEF_DR],     
    UDFieldName AS [FIELD_NAME],    
    (CASE WHEN UDFieldIsRequired=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],  
     (CASE WHEN VFORM.UDField_valueENTITYID > 1 
     THEN 
        (SELECT [dbo].[UDF_GetEntityNameAsText](VFORM.UDField_metaCodeUCSID,VFORM.UDField_valueENTITYID) AS Expr1)
     ELSE 
        (SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, VFORM.UDField_valueDateTime, VFORM.UDField_valueString, VFORM.UDField_valueENTITYID, - 1, VFORM.UDField_valueUCSID, VFORM.UDField_metaCodeUCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1)
     END) AS [FIELD_VALUE], 
    (CASE WHEN VFORM.UDField_valueENTITYID > 1
     THEN 
        CAST(VFORM.UDField_valueENTITYID AS varchar(100))
     ELSE 
        (SELECT dbo.UDF_GetFieldUCSValueAsConceptCode( VFORM.UDField_valueUCSID) AS Expr1)
     END) AS [FIELD_CONCEPT_CODE_VALUE], 
    (Case when VTDField.Active=1 then 'ACTIVE' else 'INACTIVE' END)  AS [FIELD_STATUS],  
    UCSFieldType.FullName AS [FIELD_TYPE]
FROM CTE_PHDATEFIELDFORMAT,
    A_ACT PHCASE (NOLOCK)   
    INNER JOIN [ATLASPUBLIC].[VIEWUDF_SHAREDACROSSPERSONSECTION] VFORM (NOLOCK) ON VFORM.ACT_ID=PHCASE.ID
    LEFT JOIN VCP_UDFORM VCPUDF (NOLOCK) ON  VCPUDF.SUBJCODE_ID = UDFORMDEFID  
    LEFT JOIN V_TERMDICTIONARY VTDFIELD (NOLOCK) ON VTDFIELD.TERMCODE_ID=VFORM.UDFIELDID    
    LEFT JOIN V_UNIFIEDCODESET UCSFIELDTYPE (NOLOCK) ON UCSFIELDTYPE.ID=VFORM.FIELD_TYPECODE_ID    
    
WHERE  
      PHCASE.Classcode = 'Case' 
      AND PHCASE.METACODE IN('PR_RowID','SVC_ID')
      AND PHCASE.Statuscode NOT IN ('nullified','terminated')
)
--END -- BLK SHARED ACROSS PERSON SECTIONS

