
CREATE VIEW [AtlasPublic].[View_CMMode_UserAccessible_CaseReports]
AS
    SELECT 
    UACASEREPORT.[USR_RowID] AS [USR_ROWID], 
    UACASEREPORT.[USR_Login] AS [USR_LOGIN],
    UACASEREPORT.[USR_ACCESSIBLE_FORMDEF_ID] AS [USR_ACCESSIBLE_FORM_DEF_DR],
    UACASEREPORT.[USR_ACCESSIBLE_FORM_ID] AS [USR_ACCESSIBLE_FORM_ID],
    UACASEREPORT.[USR_Accessible_Form_Name] AS [USR_ACCESSIBLE_FORM_NAME]
    FROM [AtlasPublic].[View_CMR_UserAccessible_CaseReports] AS UACASEREPORT

