
CREATE VIEW [AtlasPublic].[VIEW_CMR_AR_IdentificationTab] AS
select 
ANIMAL.DVAI_ROWID AS AI_IDEN_ANIMALROWID,
ANIMAL.DVAI_ANIMALREPORTID AS AI_IDEN_ANIMALID,
UCSDISEASE.FULLNAME AS AI_IDEN_DISEASE,
UCSDISEASE.ID AS AI_IDEN_DISEASEDR,
ANIMAL.DVAI_HUMANFIRSTNAME AS AI_IDEN_FIRSTNAME,
ANIMAL.DVAI_HUMANLASTNAME AS AI_IDEN_LASTNAME,
ETPERSON.[ADDRESS] AS AI_IDEN_PHONE_NUMBER,
UCSRELATIONTOANIMAL.FULLNAME AS AI_IDEN_RELATIONSHIP_TO_ANIMAL,
EAPERSON.PARTSAL AS AI_IDEN_HC_ADDRESS,
EAPERSON.PARTAPTNUM AS AI_IDEN_HC_APARTMENT,
EAPERSON.PARTCTY AS AI_IDEN_HC_CITY,
EAPERSON.PARTSTA AS AI_IDEN_HC_STATE,
EAPERSON.PARTZIP AS AI_IDEN_HC_ZIP,
EAPERSON.PARTCEN AS AI_IDEN_HC_SUBDIVISION,
EAPERSON.PARTGEOLONG AS AI_IDEN_HC_LONGITUDE, 
EAPERSON.PARTGEOLAT AS AI_IDEN_HC_LATITUDE,
UCSREPORTTYPE.FULLNAME AS AI_IDEN_TYPE_OF_REPORT,
ENREPORTINGORG.TRIVIALNAME AS AI_IDEN_REPORTING_ORG,
ATTSUBMITTER.VALUESTRING AS AI_IDEN_SUBMITTER_NAME,
UCSANIMALTYPE.FULLNAME AS AI_IDEN_ANIMAL_TYPE,
UCSSPECIES.FULLNAME AS AI_IDEN_SPECIES,
UCSBREED.FULLNAME AS AI_IDEN_BREED,
AACT.AVAILABILITYTIME AS AI_IDEN_DATE_OF_REPORT,
EAANIMAL.PARTSAL AS AI_IDEN_AI_ADDRESS,
EAANIMAL.PARTAPTNUM AS AI_IDEN_AI_APARTMENT,
EAANIMAL.PARTCTY AS AI_IDEN_AI_CITY,
EAANIMAL.PARTSTA AS AI_IDEN_AI_STATE,
EAANIMAL.PARTZIP AS AI_IDEN_AI_ZIP,
EAANIMAL.PARTCEN AS AI_IDEN_AI_SUBDIVISION,
EAANIMAL.PARTGEOLONG AS AI_IDEN_AI_LONGITUDE, 
EAANIMAL.PARTGEOLAT AS AI_IDEN_AI_LATITUDE,
UCSJURISDICTION.FULLNAME AS AI_IDEN_JURISDICTION,
UCSJURISDICTION.ID AS AI_IDEN_JURISDICTIONDR,
AACT.effectiveTime_Beg AS AI_Iden_Date_Created,
UCSProcessStatus.fullname as AI_Iden_Process_Status,
(ENInvestigator.partfam+','+ENInvestigator.partgiv) as AI_Iden_Investigator,
AACT.effectiveTime_End as AI_Iden_Date_Closed,
UCSResolutionStatus.fullname as AI_Iden_Resolution_Status,
DI.DVPR_IncidentID as AI_Iden_Link_to_DI,
CI.DVPR_IncidentID as AI_Iden_Link_to_CI,
OB.DVOB_OutbreakID as AI_Iden_Link_to_OB,
AACT.[text] as AI_Iden_Notes
from
DV_AnimalReport ANIMAL (NOLOCK)
INNER JOIN V_UNIFIEDCODESET UCSDISEASE (NOLOCK) ON UCSDISEASE.ID=ANIMAL.DVAI_DISEASECODE_ID
INNER JOIN S_LINK SLANIMAL (NOLOCK) ON ANIMAL.DVAI_ROWID=SLANIMAL.ACT1_ID and SLANIMAL.name='Animal-Case'
LEFT JOIN T_ENTITYTELECOM ETPERSON (NOLOCK) ON SLANIMAL.ENTITY2_ID=ETPERSON.ENTITY_ID AND ETPERSON.USECODE='H' AND ETPERSON.SCHEME='TEL'
LEFT JOIN R_ROLE (NOLOCK) ON SLANIMAL.ENTITY2_ID=R_ROLE.PLAYER_ID AND R_ROLE.CLASSCODE='CON'
LEFT JOIN V_UNIFIEDCODESET UCSRELATIONTOANIMAL (NOLOCK) ON R_ROLE.CODE_ID=UCSRELATIONTOANIMAL.ID
LEFT JOIN T_ENTITYADDRESS EAPERSON (NOLOCK) ON R_ROLE.ID=EAPERSON.ROLE_ID
LEFT JOIN V_UNIFIEDCODESET UCSREPORTTYPE (NOLOCK) ON ANIMAL.DVAI_REPORTTYPECODE_ID=UCSREPORTTYPE.ID
LEFT JOIN T_ENTITYNAME ENREPORTINGORG (NOLOCK) ON ANIMAL.DVAI_ReportOrganizationDR=ENREPORTINGORG.ENTITY_ID
LEFT JOIN T_ATTRIBUTE ATTSUBMITTER (NOLOCK) ON ANIMAL.DVAI_ROWID=ATTSUBMITTER.ACT_ID AND ATTSUBMITTER.NAME='AI_NAMEOFSUBMITTER'
inner JOIN V_UNIFIEDCODESET UCSANIMALTYPE (NOLOCK) ON ANIMAL.DVAI_ANIMALTYPECODE_ID=UCSANIMALTYPE.ID
LEFT JOIN V_UNIFIEDCODESET UCSSPECIES (NOLOCK) ON ANIMAL.DVAI_SPECIESCODE_ID=UCSSPECIES.ID
LEFT JOIN E_NONPERSONLIVINGSUBJECT NPLSBREED (NOLOCK) ON SLANIMAL.ENTITY1_ID=NPLSBREED.ID
LEFT JOIN V_UNIFIEDCODESET UCSBREED (NOLOCK) ON NPLSBREED.STRAINCODE_ID=UCSBREED.ID
LEFT JOIN A_ACT AACT (NOLOCK) ON ANIMAL.DVAI_ROWID=AACT.ID
LEFT JOIN R_ROLE RANIMALADDRESS (NOLOCK) ON SLANIMAL.ENTITY1_ID=RANIMALADDRESS.PLAYER_ID AND RANIMALADDRESS.CLASSCODE='CASESBJ'
LEFT JOIN T_ENTITYADDRESS EAANIMAL (NOLOCK) ON RANIMALADDRESS.ID=EAANIMAL.ROLE_ID
LEFT JOIN V_UNIFIEDCODESET UCSJURISDICTION (NOLOCK) ON ANIMAL.DVAI_DistrictCode_ID=UCSJURISDICTION.ID
left join V_UNIFIEDCODESET UCSProcessStatus (NOLOCK) on ANIMAL.DVAI_ProcessStatusCode_ID=UCSProcessStatus.id
left join V_UNIFIEDCODESET UCSResolutionStatus (NOLOCK) on ANIMAL.DVAI_ResolutionStatusCode_ID=UCSResolutionStatus.id
left join T_ENTITYNAME ENInvestigator (NOLOCK) on ANIMAL.DVAI_NurseInvestigatorDR=ENInvestigator.entity_id
left join DV_PHPersonalRecord DI (NOLOCK) on ANIMAL.DVAI_DiseaseIncidentDR=DI.DVPR_RowID
left join DV_PHPersonalRecord CI (NOLOCK) on ANIMAL.DVAI_ContactInvestigationDR=CI.DVPR_RowID
left join DV_Outbreak OB (NOLOCK) on ANIMAL.DVAI_OutbreakDR=OB.DVOB_RowID

