
CREATE VIEW [AtlasPublic].[View_CMMode_ContactAddonData] 
AS
WITH CTE_PHDATEFIELDFORMAT(DATEFIELDFORMAT)
AS
(
  SELECT 
  CASE 
    WHEN ISNULL(VAL.Value,'')='' THEN CAST(CONFIG.defaultValue AS VARCHAR)
    ELSE CAST(VAL.Value AS VARCHAR)
  END AS DATEFIELDFORMAT
  FROM S_CONFIGDEFINITION (nolock)CONFIG
  INNER JOIN S_CONFIGVALUE(nolock) VAL ON VAL.configdefinition_id = CONFIG.id
  WHERE CONFIG.[KEY]='PHDateFieldFormat'
)
(
SELECT
PHCASE.SVC_ID AS [RECORD_ID],
NULL AS [FORM_INSTANCE_ID], 
NULL [FORM_DEF_DR],
NULL AS [FORM_NAME],
NULL [FORM_SHOW_IN_CMR],
NULL [FORM_SHOW_IN_CMM],
NULL AS [FORM_DESCRIPTION],
NULL AS [FORM_CREATEDATE] ,
UDSECTIONACTID AS [SECTION_INSTANCE_ID],
SEC_ID AS [SECTION_DEF_DR],
UDSECNAME AS [SECTION_NAME],
(CASE WHEN (SELECT VTD.ACTIVE FROM V_TERMDICTIONARY VTD (NOLOCK) WHERE SECTIONID=VTD.TERMCODE_ID) > 0 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS],
(CASE WHEN (SELECT VCP.SEC_ISLISTSECTION FROM VCP_UDSECTION VCP (NOLOCK) WHERE SECTIONID=VCP.SUBJCODE_ID) > 0 THEN 'LIST' ELSE 'NON-LIST' END) AS [SECTION_TYPE],
(SELECT LISTSECTIONNUMBER FROM [GETLISTSECTIONNUMBER] (FOLDERACT.ID, 1) WHERE SECACTID = UDSECTIONACTID) AS [SECTION_NUMBER],
UDFIELDACTID AS [FIELD_INSTANCE_ID],
FIELD_ID AS [FIELD_DEF_DR],
UDFIELDNAME AS [FIELD_NAME],
(CASE WHEN UDFIELDISREQUIRED=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],
(CASE WHEN VSEC.UDField_valueENTITYID > 1 Then 
(SELECT [dbo].[UDF_GetEntityNameAsText](VSEC.UDField_metaCodeUCSID,VSEC.UDField_valueENTITYID) AS Expr1)
ELSE
(SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, VSEC.UDField_valueDateTime, VSEC.UDField_valueString, VSEC.UDField_valueENTITYID, - 1, VSEC.UDField_valueUCSID, VSEC.UDField_metaCodeUCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1) END) As [FIELD_VALUE],
(CASE WHEN VSEC.UDField_valueENTITYID > 0 Then 
    CAST(VSEC.UDField_valueENTITYID AS varchar(100))
ELSE
(SELECT DBO.UDF_GETFIELDUCSVALUEASCONCEPTCODE( VSEC.UDFIELD_VALUEUCSID) AS EXPR1) END) AS [FIELD_CONCEPT_CODE_VALUE],
(CASE WHEN VTDFIELD.ACTIVE=1 THEN 'ACTIVE' ELSE 'INACTIVE' END)  AS [FIELD_STATUS],    
UCSFIELDTYPE.FULLNAME AS [FIELD_TYPE]  
FROM CTE_PHDATEFIELDFORMAT,
 AX_SERVICES PHCASE (NOLOCK)
 INNER JOIN P_PARTICIPATION INDPART (NOLOCK) ON INDPART.ACT_ID = PHCASE.SVC_ID AND INDPART.TYPECODE = 'IND'  
 INNER JOIN R_ROLE EXPROLE (NOLOCK) ON EXPROLE.ID = INDPART.ROLE_ID AND EXPROLE.CLASSCODE = 'EXPR' AND EXPROLE.STATUSCODE <> 'NULLIFIED'  
 INNER JOIN R_ROLE MBRROLE (NOLOCK) ON MBRROLE.SCOPER_ID = EXPROLE.PLAYER_ID AND MBRROLE.CLASSCODE = 'MBR'  
 INNER JOIN P_PARTICIPATION SBJPART(NOLOCK) ON SBJPART.ROLE_ID = MBRROLE.ID AND SBJPART.TYPECODE = 'SBJ'  
 INNER JOIN A_ACT AS FOLDERACT (NOLOCK) ON FOLDERACT.ID =SBJPART.ACT_ID AND FOLDERACT.CLASSCODE='FOLDER'  
 INNER JOIN [ATLASINTERNAL].[VIEW_UODS_UDSECTION] VSEC (NOLOCK) ON VSEC.ACT_ID=FOLDERACT.ID  
 INNER JOIN V_CODEPROPERTY VCPSVC(NOLOCK) ON VCPSVC.SUBJCODE_ID = PHCASE.SVC_INITIALSERVICEDR AND VCPSVC.VALUECODE_ID=VSEC.UDSECID AND VCPSVC.PROPERTY='vocSVCCAT_UDSection_FK'   
 INNER JOIN V_UNIFIEDCODESET UCSFIELDTYPE (NOLOCK)ON UCSFIELDTYPE.ID=VSEC.FIELD_TYPECODE_ID   
 INNER JOIN V_TERMDICTIONARY VTDFIELD (NOLOCK) ON VTDFIELD.TERMCODE_ID=VSEC.UDFIELDID 
 )

