
CREATE VIEW [AtlasPublic].[View_CMMode_ClientRecordAddonData]
AS
WITH CTE_PHDATEFIELDFORMAT(DATEFIELDFORMAT)
AS
(
  SELECT 
  CASE 
    WHEN ISNULL(VAL.Value,'')='' THEN CAST(CONFIG.defaultValue AS VARCHAR)
    ELSE CAST(VAL.Value AS VARCHAR)
  END AS DATEFIELDFORMAT
  FROM S_CONFIGDEFINITION (nolock)CONFIG
  INNER JOIN S_CONFIGVALUE(nolock) VAL ON VAL.configdefinition_id = CONFIG.id
  WHERE CONFIG.[KEY]='PHDateFieldFormat'
)
SELECT 
PER.DVPER_NCMID AS [PER_CLIENTID],
SEC.id AS [SECTION_INSTANCE_ID],
SEC.code_ID AS [SECTION_DEF_ID],
VUCS_SECTION.Fullname AS [SECTION_NAME],        
(CASE WHEN ( VTD.ACTIVE >0 ) THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [SECTION_STATUS],
(CASE WHEN SEC_ISLISTSECTION> 0 THEN 'LIST' ELSE 'NON-LIST' END) AS [SECTION_TYPE], 
(CASE WHEN SEC_ISLISTSECTION=1 THEN ROW_NUMBER () OVER (PARTITION BY AX_UDFValues.METACODE_UCSID,SEC.Code_ID ORDER BY AX_UDFValues.METACODE_UCSID,SEC.Code_ID) ELSE 1 END) [SECTION_NUMBER],                    
AX_UDFValues.id AS [FIELD_INSTANCE_ID], 
AX_UDFValues.METACODE_UCSID AS [FIELD_DEF_ID],
VUCS_FIELD.FullName [FIELD_NAME],
(CASE WHEN FIELD_IsRequired=1 THEN 'TRUE' ELSE 'FALSE' END) AS [FIELD_IS_REQUIRED],
(CASE WHEN ax_UDFvalues.VALUE_ENTITYID > 1 Then 
(SELECT [dbo].[UDF_GetEntityNameAsText](Ax_UDFValues.metaCode_UCSID,ax_UDFvalues.VALUE_ENTITYID) AS Expr1)
ELSE
(SELECT dbo.UDF_GetFieldValueAsText(NULL, NULL, NULL, Ax_UDFValues.valueDateTime, Ax_UDFValues.valueString, ax_UDFvalues.VALUE_ENTITYID, - 1, Ax_UDFValues.value_UCSID, Ax_UDFValues.metaCode_UCSID, NULL, CTE_PHDATEFIELDFORMAT.DATEFIELDFORMAT) AS Expr1) END) As [FIELD_VALUE],
(CASE WHEN ax_UDFvalues.VALUE_ENTITYID > 0 Then 
    CAST(ax_UDFvalues.VALUE_ENTITYID AS varchar(100))
ELSE
(SELECT DBO.UDF_GETFIELDUCSVALUEASCONCEPTCODE(Ax_UDFValues.value_UCSID) AS EXPR1) END) AS [FIELD_CONCEPT_CODE_VALUE],
(CASE WHEN VTDField.Active=1 THEN 'ACTIVE' ELSE 'INACTIVE' END) AS [FIELD_STATUS],
UCSFieldType.FullName AS [FIELD_TYPE]
FROM CTE_PHDATEFIELDFORMAT, A_Act SEC (NOLOCK) 
INNER JOIN ax_UDFvalues (NOLOCK) on SEC.ID=AX_UDFVALUES.Act_Parent_ID and SEC.classCode='DOCSECT' 
INNER JOIN A_ActRelationship frm (NOLOCK) on target_ID=SEC.ID and typeCode='COMP'
INNER JOIN V_UNIFIEDCODESET VUCS_FIELD (NOLOCK) ON VUCS_FIELD.ID=AX_UDFVALUES.METACODE_UCSID
INNER JOIN V_UNIFIEDCODESET VUCS_SECTION (NOLOCK) ON VUCS_SECTION.ID=SEC.CODE_ID
INNER JOIN VCP_UDField (NOLOCK) ON VCP_UDField.SubjCode_Id = VUCS_FIELD.ID
INNER JOIN VCP_UDSection (NOLOCK) ON VCP_UDSection.subjCode_Id = VUCS_SECTION.ID
INNER Join V_TermDictionary VTDField (NOLOCK) on VTDField.termCode_ID=VUCS_FIELD.ID
INNER JOIN V_TERMDICTIONARY VTD (NOLOCK) ON SEC.code_ID=VTD.TERMCODE_ID
INNER JOIN V_UnifiedCodeSet UCSFieldType (NOLOCK) on UCSFieldType.ID=VCP_UDField.FIELD_TypeCode_ID
LEFT JOIN V_UnifiedCodeSet UCS (NOLOCK) on UCS.ID=Ax_UDFValues.value_UCSID
INNER JOIN A_ACT CASEACT (NOLOCK) ON CASEACT.ID = FRM.SOURCE_ID AND CASEACT.metaCode='PR_RowID' 
INNER JOIN A_PublicHealthCase PHCASE (NOLOCK) ON PHCASE.ID=CASEACT.ID
INNER JOIN V_UnifiedCodeSet UCSRecordType (NOLOCK) ON UCSRecordType.ID=PHCASE.phRecordTypeCode_ID AND UCSRecordType.conceptCode='CR'
INNER JOIN P_PARTICIPATION PART (NOLOCK) ON PART.ACT_ID = CASEACT.ACT_PARENT_ID AND PART.TYPECODE = 'SBJ'
INNER JOIN R_ROLE RLE (NOLOCK) ON RLE.ID = PART.ROLE_ID AND RLE.CLASSCODE='PAT'
INNER JOIN DV_PERSON PER (NOLOCK) ON PER.DVPER_ROWID = RLE.PLAYER_ID
WHERE SEC.CODE_ID = (
SELECT CAST(VALUE AS INT) 
FROM dbo.S_ConfigValue (NOLOCK)
WHERE configDefinition_ID =
    (SELECT ID FROM dbo.S_ConfigDefinition (NOLOCK) WHERE [key] = 'CNF_ClientUDSection')
)

