CREATE VIEW dbo.[uvw_suspect_pastweek]
AS
SELECT  P.[PER_ClientID]                                             AS 'Person_ID'
        , P.[PER_LASTNAME]                                           AS 'Last_Name'
        , P.[PER_FIRSTNAME]                                          AS 'First_Name'
        , P.[PER_MIDDLENAME]                                         AS 'Middle_Name'
        , P.[PER_NAMESUFFIX]                                         AS 'Name_Suffix'
        , P.[PER_PRIMARYLANGUAGE]                                    AS 'Primary_Language'
        , try_CONVERT(DATETIME, P.[PER_DOB])                         AS 'DOB'
        , P.[PER_STREETADDRESS]                                      AS 'Street_Address'
        , P.[PER_APARTMENT]                                          AS 'Apartment_Number'
        , P.[PER_CITY]                                               AS 'City'
        , P.[PER_STATE]                                              AS 'State'
        , P.[PER_ZIP]                                                AS 'Zip'
        , P.[PER_LATITUDE]                                           AS 'Latitude'
        , P.[PER_LONGITUDE]                                          AS 'Longitude'
        , P.[PER_ADDRESSSTANDARDIZED]                                AS 'Address_Standardized'
        , P.[PER_COUNTYFIPS]                                         AS 'County_FIPS'
        , P.[PER_COUNTY]                                             AS 'County'
        , P.[PER_CENSUSBLOCK]                                        AS 'Census_Block'
        , P.[PER_ZIPPLUS4]                                           AS 'Zip_Plus_4'
        , P.[PER_COUNTYOFRESIDENCE]                                  AS 'County_of_Residence'
        , P.[PER_COUNTRY_NAME]                                       AS 'Country_of_Residence'
        , P.[PER_SEX]                                                AS 'Sex'
        , I.[PR_INCIDENTID]                                          AS 'Incident_ID'
        , I.[Age]                                                    AS 'Age'
        , I.[PR_CENSUSTRACT]                                         AS 'Census_Tract'
        , I.[PR_DISTRICT]                                            AS 'District'
        , I.[Health_District_Number]                                 AS 'Health_District_Number'
        , try_CONVERT(datetime,I.[PR_ONSETDATE])                     AS 'Onset_Date_Date_of_Contact'
        , I.[PR_PROCESSSTATUS]                                       AS 'Process_Status'
        , I.[Secondary_District]                                     AS 'Secondary_District'
        , try_CONVERT(datetime,I.[PR_LABSPECIMENCOLLECTEDDATE])      AS 'Lab_Specimen_Collection_Date'
        , try_CONVERT(datetime,I.[PR_DATEREPORTEDBY])                AS 'Date_Reported_By'
        , try_CONVERT(datetime,I.[PR_DATEOFLABREPORT])               AS 'Date_of_Lab_Report'
        , I.[Diagnostic_Specimen_Types]                              AS 'Diagnostic_Specimen_Types'
        , I.[Priority]                                               AS 'Priority'
        , try_CONVERT(datetime,I.[PR_LABSPECIMENRESULTDATE])         AS 'Lab_Specimen_Result_Date'
        , try_CONVERT(datetime,I.[PR_DATEOFDIAGNOSIS])               AS 'Date_of_Diagnosis'
        , I.[Report_Source]                                          AS 'Report_Source'
        , try_CONVERT(datetime,I.[PR_DATEOFDEATH])                   AS 'Date_of_Death'  
        , I.[PR_LABORATORY]                                          AS 'Laboratory'
        , try_CONVERT(datetime,I.[PR_DATEINVESTIGATORRECEIVED])      AS 'Date_Received'
        , I.[PR_RESOLUTIONSTATUS]                                    AS 'Resolution_Status'
        , I.[Additional_Provider]                                    AS 'Additional_Provider'
        , I.[Final_Disposition]                                      AS 'Final_Disposition'
        , I.[Additional_Laboratory]                                  AS 'Additional_Laboratory'
        , I.[Created_By]                                             AS 'Created_By'
        , try_CONVERT(datetime,I.[PR_CREATEDATE])                    AS 'Date_Created'
        , try_CONVERT(datetime,I.[PR_DATESUBMITTED])                 AS 'Date_Submitted'
        , try_CONVERT(datetime,I.[PR_EPISODEDATE])                   AS 'Episode_Date' 
FROM    
  dbo.[COVID_PERSON] AS P with (nolock) 
	INNER JOIN 
  dbo.[COVID_INCIDENT] AS I with (nolock)
    ON P.[PER_RowID] = I.[PR_PersonDR] 
WHERE I.[PR_RESOLUTIONSTATUS] in ('Suspect','Probable') AND I.[PR_CREATEDATE] > DATEADD(DAY, -8, GETDATE())

GO
