create view dbo.uvw_COVID_OUTBREAK as
select
  OUTB_RowID as Row_ID, 
  OUTB_OUTBREAKID as Outbreak_ID, 
  OUTB_COUNT as Number_of_Cases, 
  OUTB_OutbreakNumber as Outbreak_Number, 
  OUTB_Disease as Disease, 
  OUTB_DISSHORTNAME as Disease_Short_Name, 
  OUTB_ISHEALTHFACILITY as Is_Health_Facility, 
  OUTB_OutbreakLocation as Location, 
  OUTB_LOCATIONTYPE as Location_Type, 
  OUTB_LOCATIONADDRESS_PLUS as Location_Address, 
  OUTB_LOCATIONPHONE as Location_Phone, 
  OUTB_LOCATIONEMAIL as [Location_E_mail], 
  OUTB_LOCATIONPRIMARYCONTACT as Location_Primary_Contact, 
  OUTB_LOCCOUNTY as Location_County, 
  OUTB_LOCJURISDICTION as Location_District, 
  try_convert(datetime,OUTB_DateofOnset) as Date_of_Onset, 
  try_convert(datetime,OUTB_DateCreated) as Date_Created, 
  left(try_convert(varchar(16),OUTB_DateCreated,14),8) as Time_Created, 
  try_convert(datetime,OUTB_DateClosed) as Date_Closed, 
  OUTB_District as District, 
  OUTB_NurseInvestigator as Investigator, 
  OUTB_PRIORITY as Priority, 
  OUTB_ProcessStatus as Process_Status, 
  OUTB_ResolutionStatus as Resolution_Status, 
  OUTB_OutbreakType as Outbreak_Type, 
  OUTB_Notes as Notes, 
  OUTB_IsHealthFacilityOutbreak as IsHealthFacilityOutbreak, 
  Patients_Linked_to_Outbreak as Patients_Linked_to_Outbreak, 
  All_Contacts_Linked_to_Outbreak as All_Contacts_Linked_to_Outbreak, 
  Incident_Contacts_Linked_to_Outbreak as Incident_Contacts_Linked_to_Outbreak, 
  Contact_Investigations_Linked_to_Outbreak as Contact_Investigations_Linked_to_Outbreak
from    
  dbo.COVID_OUTBREAK with (nolock)
