create view dbo.uvw_NCOVPUIISOCNT as
select
  try_cast(NCOVPUIISOCNTISODT AS datetime) NCOVPUIISOCNTISODT,
  try_cast(NCOVPUIISOCNTISORLSDT AS datetime) NCOVPUIISOCNTISORLSDT,
  NCOVPUIISOCNTDISPSPCFY,
  NCOVPUIISOCNTLOSPCFY,
  try_cast(NCOVPUIISOCNTPHCLRDT  AS datetime) NCOVPUIISOCNTPHCLRDT,
  try_cast(NCOVPUIISOCNTLABCLRDT  AS datetime) NCOVPUIISOCNTLABCLRDT,
  substring(NCOVPUIISOCNTPHCLR,1,1) NCOVPUIISOCNTPHCLR,
  substring(NCOVPUIISOCNTLABCLR,1,1) NCOVPUIISOCNTLABCLR,
  NCOVPUIISOCNTNUMCLOHW,
  NCOVPUIISOCNTNUMCLO,
  NCOVPUIISOCNTNUMOTH,
  NCOVPUIISOCNTNUMTOT,
  substring(NCOVPUIISOCNTORDERS,1,1) NCOVPUIISOCNTORDERS,
  NCOVPUIISOCNTLO,
  NCOVPUIISOCNTDISP,
  DIID = RECORD_ID,
  INSTANCEID = PR_INCIDENTID,
  Person_ID = PER_ClientID,
  UDSectionActID = SECTION_INSTANCE_ID,
  RecordType = PR_PHTYPE,
  Disease = PR_DISEASE,
  District = PR_DISTRICT,
  FormInstanceID = FORM_INSTANCE_ID,
  FormName = FORM_NAME,
  FormDescription = FORM_DESCRIPTION,
  FormCreateDateTime = try_convert(datetime,[FORM_CREATEDATE])
from
( SELECT  
    UDF.RECORD_ID,
    UDF.FORM_INSTANCE_ID,
    UDF.FORM_NAME,
    UDF.FORM_DESCRIPTION,
    UDF.FORM_CREATEDATE,
    UDF.SECTION_INSTANCE_ID,
    UDF.FIELD_DEF_DR,
    UDF.FIELD_VALUE,
    P.PER_ClientID,
    I.PR_PHTYPE,
    I.PR_DISEASE,
    I.PR_INCIDENTID,
    I.PR_DISTRICT
  from   
  dbo.COVID_UDF_DATA UDF with (nolock) 
    inner join 
    dbo.COVID_INCIDENT I with (nolock)
    on 
      UDF.RECORD_ID = I.PR_ROWID
    inner join 
    dbo.COVID_PERSON P with (nolock)
    on 
      P.PER_ROWID = I.PR_PersonDR
  where   
    UDF.SECTION_DEF_DR = 'NCOVPUIISOCNT'  and FORM_DEF_DR = 'NCOVPUI'
) PivotData
pivot 
( max(FIELD_VALUE)
  FOR FIELD_DEF_DR IN 
  ( NCOVPUIISOCNTISODT,
    NCOVPUIISOCNTISORLSDT,
    NCOVPUIISOCNTDISPSPCFY,
    NCOVPUIISOCNTLOSPCFY,
    NCOVPUIISOCNTPHCLRDT,
    NCOVPUIISOCNTLABCLRDT,
    NCOVPUIISOCNTPHCLR,
    NCOVPUIISOCNTLABCLR,
    NCOVPUIISOCNTNUMCLOHW,
    NCOVPUIISOCNTNUMCLO,
    NCOVPUIISOCNTNUMOTH,
    NCOVPUIISOCNTNUMTOT,
    NCOVPUIISOCNTORDERS,
    NCOVPUIISOCNTLO,
    NCOVPUIISOCNTDISP
  )
) PivotTable
